/**
 * Standardlisten unregelmäßiger Verben je Sprache und Lernjahr (30.09.2026).
 *
 * Für Lerngruppen ohne eingepflegte Lehrwerksliste. Das Lernjahr ist eine ORIENTIERUNG, kein
 * Lehrplanzitat: ab wann ein Verb in den gängigen Lehrwerken üblicherweise mit allen Formen gelernt
 * wird (Recherche: recherche/unregelmaessige-verben-2026-09-30.md). Die Lehrkraft wählt ohnehin
 * einzeln aus; eine eingepflegte Liste des eigenen Lehrwerks geht immer vor.
 *
 * Schreibweise je Zeile wie in den Schulbüchern, Zellen mit „|" getrennt in der Reihenfolge der
 * Spalten aus src/shared/verben.ts. „—" = diese Form gibt es nicht.
 */
import { VERB_SPALTEN, type VerbEintrag, type VerbSprache } from '@shared/verben'

type Roh = [lernjahr: number, zeile: string]

const EN: Roh[] = [
  [1, 'be|was/were|been|sein'],
  [1, 'have|had|had|haben'],
  [1, 'do|did|done|tun, machen'],
  [1, 'go|went|gone|gehen'],
  [1, 'come|came|come|kommen'],
  [1, 'get|got|got|bekommen'],
  [1, 'see|saw|seen|sehen'],
  [1, 'say|said|said|sagen'],
  [1, 'make|made|made|machen, herstellen'],
  [1, 'take|took|taken|nehmen'],
  [1, 'eat|ate|eaten|essen'],
  [1, 'give|gave|given|geben'],
  [1, 'buy|bought|bought|kaufen'],
  [1, 'find|found|found|finden'],
  [1, 'know|knew|known|wissen, kennen'],
  [2, 'begin|began|begun|beginnen'],
  [2, 'become|became|become|werden'],
  [2, 'bring|brought|brought|bringen'],
  [2, 'drink|drank|drunk|trinken'],
  [2, 'feel|felt|felt|fühlen'],
  [2, 'fly|flew|flown|fliegen'],
  [2, 'forget|forgot|forgotten|vergessen'],
  [2, 'hear|heard|heard|hören'],
  [2, 'leave|left|left|verlassen, abfahren'],
  [2, 'lose|lost|lost|verlieren'],
  [2, 'meet|met|met|treffen'],
  [2, 'put|put|put|legen, stellen'],
  [2, 'read|read|read|lesen'],
  [2, 'ride|rode|ridden|reiten, (Rad) fahren'],
  [2, 'run|ran|run|laufen, rennen'],
  [2, 'sell|sold|sold|verkaufen'],
  [2, 'send|sent|sent|schicken'],
  [2, 'sing|sang|sung|singen'],
  [2, 'sit|sat|sat|sitzen'],
  [2, 'sleep|slept|slept|schlafen'],
  [2, 'speak|spoke|spoken|sprechen'],
  [2, 'swim|swam|swum|schwimmen'],
  [2, 'tell|told|told|erzählen'],
  [2, 'think|thought|thought|denken'],
  [2, 'throw|threw|thrown|werfen'],
  [2, 'understand|understood|understood|verstehen'],
  [2, 'wake up|woke up|woken up|aufwachen'],
  [2, 'wear|wore|worn|tragen (Kleidung)'],
  [2, 'win|won|won|gewinnen'],
  [2, 'write|wrote|written|schreiben'],
  [3, 'blow|blew|blown|blasen, wehen'],
  [3, 'break|broke|broken|(zer)brechen'],
  [3, 'build|built|built|bauen'],
  [3, 'catch|caught|caught|fangen'],
  [3, 'choose|chose|chosen|wählen'],
  [3, 'cut|cut|cut|schneiden'],
  [3, 'draw|drew|drawn|zeichnen'],
  [3, 'drive|drove|driven|fahren'],
  [3, 'fall|fell|fallen|fallen'],
  [3, 'feed|fed|fed|füttern'],
  [3, 'fight|fought|fought|kämpfen'],
  [3, 'grow|grew|grown|wachsen'],
  [3, 'hide|hid|hidden|verstecken'],
  [3, 'hit|hit|hit|schlagen, treffen'],
  [3, 'hold|held|held|halten'],
  [3, 'hurt|hurt|hurt|verletzen, wehtun'],
  [3, 'keep|kept|kept|behalten'],
  [3, 'learn|learnt/learned|learnt/learned|lernen'],
  [3, 'lend|lent|lent|(ver)leihen'],
  [3, 'let|let|let|lassen'],
  [3, 'mean|meant|meant|bedeuten, meinen'],
  [3, 'pay|paid|paid|bezahlen'],
  [3, 'ring|rang|rung|klingeln, anrufen'],
  [3, 'show|showed|shown|zeigen'],
  [3, 'shut|shut|shut|schließen'],
  [3, 'spend|spent|spent|ausgeben, verbringen'],
  [3, 'stand|stood|stood|stehen'],
  [3, 'steal|stole|stolen|stehlen'],
  [3, 'teach|taught|taught|unterrichten'],
  [4, 'bend|bent|bent|biegen'],
  [4, 'bet|bet|bet|wetten'],
  [4, 'bite|bit|bitten|beißen'],
  [4, 'bleed|bled|bled|bluten'],
  [4, 'burn|burnt/burned|burnt/burned|brennen, verbrennen'],
  [4, 'deal|dealt|dealt|handeln (mit)'],
  [4, 'dig|dug|dug|graben'],
  [4, 'dream|dreamt/dreamed|dreamt/dreamed|träumen'],
  [4, 'forbid|forbade|forbidden|verbieten'],
  [4, 'forgive|forgave|forgiven|verzeihen'],
  [4, 'freeze|froze|frozen|frieren, gefrieren'],
  [4, 'hang|hung|hung|hängen'],
  [4, 'lay|laid|laid|legen'],
  [4, 'lead|led|led|führen'],
  [4, 'lie|lay|lain|liegen'],
  [4, 'light|lit|lit|anzünden'],
  [4, 'rise|rose|risen|steigen, aufgehen'],
  [4, 'seek|sought|sought|suchen'],
  [4, 'shake|shook|shaken|schütteln'],
  [4, 'shine|shone|shone|scheinen'],
  [4, 'shoot|shot|shot|schießen'],
  [4, 'sink|sank|sunk|sinken'],
  [4, 'smell|smelt/smelled|smelt/smelled|riechen'],
  [4, 'spell|spelt/spelled|spelt/spelled|buchstabieren'],
  [4, 'stick|stuck|stuck|kleben, stecken'],
  [4, 'sweep|swept|swept|fegen'],
  [4, 'swing|swung|swung|schwingen'],
  [4, 'tear|tore|torn|zerreißen']
]

const FR: Roh[] = [
  [1, "être|je suis|nous sommes|ils sont|j'ai été|je serai|sein"],
  [1, "avoir|j'ai|nous avons|ils ont|j'ai eu|j'aurai|haben"],
  [1, "aller|je vais|nous allons|ils vont|je suis allé(e)|j'irai|gehen"],
  [1, "faire|je fais|nous faisons|ils font|j'ai fait|je ferai|machen, tun"],
  [1, "prendre|je prends|nous prenons|ils prennent|j'ai pris|je prendrai|nehmen"],
  [2, "venir|je viens|nous venons|ils viennent|je suis venu(e)|je viendrai|kommen"],
  [2, "pouvoir|je peux|nous pouvons|ils peuvent|j'ai pu|je pourrai|können"],
  [2, "vouloir|je veux|nous voulons|ils veulent|j'ai voulu|je voudrai|wollen"],
  [2, "devoir|je dois|nous devons|ils doivent|j'ai dû|je devrai|müssen"],
  [2, "savoir|je sais|nous savons|ils savent|j'ai su|je saurai|wissen"],
  [2, "voir|je vois|nous voyons|ils voient|j'ai vu|je verrai|sehen"],
  [2, "dire|je dis|nous disons|ils disent|j'ai dit|je dirai|sagen"],
  [2, "mettre|je mets|nous mettons|ils mettent|j'ai mis|je mettrai|legen, stellen, setzen"],
  [2, "lire|je lis|nous lisons|ils lisent|j'ai lu|je lirai|lesen"],
  [2, "écrire|j'écris|nous écrivons|ils écrivent|j'ai écrit|j'écrirai|schreiben"],
  [2, "partir|je pars|nous partons|ils partent|je suis parti(e)|je partirai|abfahren, weggehen"],
  [2, "sortir|je sors|nous sortons|ils sortent|je suis sorti(e)|je sortirai|ausgehen"],
  [2, "dormir|je dors|nous dormons|ils dorment|j'ai dormi|je dormirai|schlafen"],
  [2, "boire|je bois|nous buvons|ils boivent|j'ai bu|je boirai|trinken"],
  [2, "comprendre|je comprends|nous comprenons|ils comprennent|j'ai compris|je comprendrai|verstehen"],
  [2, "apprendre|j'apprends|nous apprenons|ils apprennent|j'ai appris|j'apprendrai|lernen"],
  [3, "connaître|je connais|nous connaissons|ils connaissent|j'ai connu|je connaîtrai|kennen"],
  [3, "croire|je crois|nous croyons|ils croient|j'ai cru|je croirai|glauben"],
  [3, "courir|je cours|nous courons|ils courent|j'ai couru|je courrai|laufen, rennen"],
  [3, "ouvrir|j'ouvre|nous ouvrons|ils ouvrent|j'ai ouvert|j'ouvrirai|öffnen"],
  [3, "recevoir|je reçois|nous recevons|ils reçoivent|j'ai reçu|je recevrai|bekommen, erhalten"],
  [3, "vivre|je vis|nous vivons|ils vivent|j'ai vécu|je vivrai|leben"],
  [3, "suivre|je suis|nous suivons|ils suivent|j'ai suivi|je suivrai|folgen"],
  [3, "tenir|je tiens|nous tenons|ils tiennent|j'ai tenu|je tiendrai|halten"],
  [3, "devenir|je deviens|nous devenons|ils deviennent|je suis devenu(e)|je deviendrai|werden"],
  [3, "envoyer|j'envoie|nous envoyons|ils envoient|j'ai envoyé|j'enverrai|schicken"],
  [3, "conduire|je conduis|nous conduisons|ils conduisent|j'ai conduit|je conduirai|(Auto) fahren"],
  [3, "rire|je ris|nous rions|ils rient|j'ai ri|je rirai|lachen"],
  [3, "mourir|je meurs|nous mourons|ils meurent|je suis mort(e)|je mourrai|sterben"],
  [3, "naître|je nais|nous naissons|ils naissent|je suis né(e)|je naîtrai|geboren werden"],
  [4, "offrir|j'offre|nous offrons|ils offrent|j'ai offert|j'offrirai|schenken, anbieten"],
  [4, "battre|je bats|nous battons|ils battent|j'ai battu|je battrai|schlagen"],
  [4, "peindre|je peins|nous peignons|ils peignent|j'ai peint|je peindrai|malen"],
  [4, "craindre|je crains|nous craignons|ils craignent|j'ai craint|je craindrai|fürchten"],
  [4, "produire|je produis|nous produisons|ils produisent|j'ai produit|je produirai|herstellen"],
  [4, "résoudre|je résous|nous résolvons|ils résolvent|j'ai résolu|je résoudrai|lösen"],
  [4, "s'asseoir|je m'assieds|nous nous asseyons|ils s'asseyent|je me suis assis(e)|je m'assiérai|sich setzen"]
]

const ES: Roh[] = [
  [1, 'ser|soy|somos|fui|sido|sein'],
  [1, 'estar|estoy|estamos|estuve|estado|sein, sich befinden'],
  [1, 'tener|tengo|tenemos|tuve|tenido|haben'],
  [1, 'ir|voy|vamos|fui|ido|gehen, fahren'],
  [1, 'hacer|hago|hacemos|hice|hecho|machen, tun'],
  [1, 'querer|quiero|queremos|quise|querido|wollen, lieben'],
  [1, 'poder|puedo|podemos|pude|podido|können'],
  [2, 'decir|digo|decimos|dije|dicho|sagen'],
  [2, 'venir|vengo|venimos|vine|venido|kommen'],
  [2, 'poner|pongo|ponemos|puse|puesto|setzen, stellen, legen'],
  [2, 'salir|salgo|salimos|salí|salido|ausgehen, weggehen'],
  [2, 'saber|sé|sabemos|supe|sabido|wissen'],
  [2, 'dar|doy|damos|di|dado|geben'],
  [2, 'ver|veo|vemos|vi|visto|sehen'],
  [2, 'conocer|conozco|conocemos|conocí|conocido|kennen'],
  [2, 'dormir|duermo|dormimos|dormí|dormido|schlafen'],
  [2, 'jugar|juego|jugamos|jugué|jugado|spielen'],
  [2, 'pedir|pido|pedimos|pedí|pedido|bitten, bestellen'],
  [2, 'empezar|empiezo|empezamos|empecé|empezado|anfangen'],
  [2, 'volver|vuelvo|volvemos|volví|vuelto|zurückkehren'],
  [2, 'escribir|escribo|escribimos|escribí|escrito|schreiben'],
  [3, 'traer|traigo|traemos|traje|traído|bringen'],
  [3, 'oír|oigo|oímos|oí|oído|hören'],
  [3, 'leer|leo|leemos|leí|leído|lesen'],
  [3, 'pensar|pienso|pensamos|pensé|pensado|denken'],
  [3, 'encontrar|encuentro|encontramos|encontré|encontrado|finden, treffen'],
  [3, 'seguir|sigo|seguimos|seguí|seguido|folgen, weitermachen'],
  [3, 'sentir|siento|sentimos|sentí|sentido|fühlen'],
  [3, 'abrir|abro|abrimos|abrí|abierto|öffnen'],
  [3, 'romper|rompo|rompemos|rompí|roto|zerbrechen'],
  [3, 'morir|muero|morimos|morí|muerto|sterben'],
  [3, 'conducir|conduzco|conducimos|conduje|conducido|(Auto) fahren'],
  [3, 'andar|ando|andamos|anduve|andado|gehen, laufen'],
  [4, 'caber|quepo|cabemos|cupe|cabido|hineinpassen'],
  [4, 'cubrir|cubro|cubrimos|cubrí|cubierto|bedecken'],
  [4, 'descubrir|descubro|descubrimos|descubrí|descubierto|entdecken'],
  [4, 'elegir|elijo|elegimos|elegí|elegido|wählen'],
  [4, 'construir|construyo|construimos|construí|construido|bauen'],
  [4, 'producir|produzco|producimos|produje|producido|herstellen'],
  [4, 'resolver|resuelvo|resolvemos|resolví|resuelto|lösen']
]

const IT: Roh[] = [
  [1, 'essere|sono|sono|sono stato/a|sein'],
  [1, 'avere|ho|hanno|ho avuto|haben'],
  [1, 'andare|vado|vanno|sono andato/a|gehen'],
  [1, 'fare|faccio|fanno|ho fatto|machen'],
  [1, 'stare|sto|stanno|sono stato/a|sein, bleiben'],
  [2, 'venire|vengo|vengono|sono venuto/a|kommen'],
  [2, 'dire|dico|dicono|ho detto|sagen'],
  [2, 'dare|do|danno|ho dato|geben'],
  [2, 'potere|posso|possono|ho potuto|können'],
  [2, 'volere|voglio|vogliono|ho voluto|wollen'],
  [2, 'dovere|devo|devono|ho dovuto|müssen'],
  [2, 'sapere|so|sanno|ho saputo|wissen'],
  [2, 'uscire|esco|escono|sono uscito/a|ausgehen'],
  [2, 'bere|bevo|bevono|ho bevuto|trinken'],
  [2, 'prendere|prendo|prendono|ho preso|nehmen'],
  [2, 'mettere|metto|mettono|ho messo|legen, stellen'],
  [2, 'vedere|vedo|vedono|ho visto|sehen'],
  [2, 'leggere|leggo|leggono|ho letto|lesen'],
  [2, 'scrivere|scrivo|scrivono|ho scritto|schreiben'],
  [3, 'rimanere|rimango|rimangono|sono rimasto/a|bleiben'],
  [3, 'tenere|tengo|tengono|ho tenuto|halten'],
  [3, 'scegliere|scelgo|scelgono|ho scelto|wählen'],
  [3, 'chiudere|chiudo|chiudono|ho chiuso|schließen'],
  [3, 'aprire|apro|aprono|ho aperto|öffnen'],
  [3, 'chiedere|chiedo|chiedono|ho chiesto|fragen'],
  [3, 'rispondere|rispondo|rispondono|ho risposto|antworten'],
  [3, 'decidere|decido|decidono|ho deciso|entscheiden'],
  [3, 'perdere|perdo|perdono|ho perso|verlieren'],
  [3, 'correre|corro|corrono|ho corso|laufen'],
  [3, 'nascere|nasco|nascono|sono nato/a|geboren werden'],
  [3, 'morire|muoio|muoiono|sono morto/a|sterben'],
  [3, 'piacere|piaccio|piacciono|sono piaciuto/a|gefallen'],
  [4, 'conoscere|conosco|conoscono|ho conosciuto|kennen'],
  [4, 'tradurre|traduco|traducono|ho tradotto|übersetzen'],
  [4, 'vincere|vinco|vincono|ho vinto|gewinnen'],
  [4, 'spendere|spendo|spendono|ho speso|ausgeben'],
  [4, 'accendere|accendo|accendono|ho acceso|anzünden, einschalten'],
  [4, 'salire|salgo|salgono|sono salito/a|hinaufgehen, einsteigen'],
  [4, 'offrire|offro|offrono|ho offerto|anbieten, schenken']
]

const RU: Roh[] = [
  [1, 'хотеть|хочу|хочешь|хотят|хотел|wollen'],
  [1, 'мочь|могу|можешь|могут|мог|können'],
  [1, 'жить|живу|живёшь|живут|жил|leben, wohnen'],
  [1, 'писать|пишу|пишешь|пишут|писал|schreiben'],
  [1, 'идти|иду|идёшь|идут|шёл|gehen (zu Fuß, in eine Richtung)'],
  [1, 'ехать|еду|едешь|едут|ехал|fahren (in eine Richtung)'],
  [1, 'есть|ем|ешь|едят|ел|essen'],
  [2, 'пить|пью|пьёшь|пьют|пил|trinken'],
  [2, 'давать|даю|даёшь|дают|давал|geben'],
  [2, 'любить|люблю|любишь|любят|любил|lieben, mögen'],
  [2, 'спать|сплю|спишь|спят|спал|schlafen'],
  [2, 'видеть|вижу|видишь|видят|видел|sehen'],
  [2, 'сидеть|сижу|сидишь|сидят|сидел|sitzen'],
  [2, 'петь|пою|поёшь|поют|пел|singen'],
  [2, 'брать|беру|берёшь|берут|брал|nehmen'],
  [2, 'ждать|жду|ждёшь|ждут|ждал|warten'],
  [3, 'вставать|встаю|встаёшь|встают|вставал|aufstehen'],
  [3, 'нести|несу|несёшь|несут|нёс|tragen'],
  [3, 'вести|веду|ведёшь|ведут|вёл|führen'],
  [3, 'плакать|плачу|плачешь|плачут|плакал|weinen'],
  [3, 'искать|ищу|ищешь|ищут|искал|suchen'],
  [3, 'ходить|хожу|ходишь|ходят|ходил|gehen (mehrmals, hin und zurück)'],
  [3, 'ездить|езжу|ездишь|ездят|ездил|fahren (mehrmals, hin und zurück)'],
  [3, 'бежать|бегу|бежишь|бегут|бежал|laufen, rennen'],
  [3, 'дать|дам|дашь|дадут|дал|geben (vollendet)'],
  [3, 'сказать|скажу|скажешь|скажут|сказал|sagen (vollendet)'],
  [4, 'расти|расту|растёшь|растут|рос|wachsen'],
  [4, 'лечь|лягу|ляжешь|лягут|лёг|sich hinlegen'],
  [4, 'сесть|сяду|сядешь|сядут|сел|sich setzen'],
  [4, 'умереть|умру|умрёшь|умрут|умер|sterben'],
  [4, 'начать|начну|начнёшь|начнут|начал|anfangen (vollendet)'],
  [4, 'понять|пойму|поймёшь|поймут|понял|verstehen (vollendet)']
]

const LA: Roh[] = [
  [1, 'sum|esse|fui|—|sein'],
  [1, 'possum|posse|potui|—|können'],
  [1, 'eo|ire|ii|itum|gehen'],
  [1, 'do|dare|dedi|datum|geben'],
  [1, 'sto|stare|steti|statum|stehen'],
  [1, 'video|videre|vidi|visum|sehen'],
  [1, 'venio|venire|veni|ventum|kommen'],
  [1, 'facio|facere|feci|factum|machen, tun'],
  [1, 'capio|capere|cepi|captum|fassen, nehmen'],
  [1, 'dico|dicere|dixi|dictum|sagen'],
  [2, 'duco|ducere|duxi|ductum|führen'],
  [2, 'mitto|mittere|misi|missum|schicken, gehen lassen'],
  [2, 'ago|agere|egi|actum|handeln, tun'],
  [2, 'scribo|scribere|scripsi|scriptum|schreiben'],
  [2, 'lego|legere|legi|lectum|lesen'],
  [2, 'peto|petere|petivi|petitum|erstreben, bitten'],
  [2, 'quaero|quaerere|quaesivi|quaesitum|suchen, fragen'],
  [2, 'rego|regere|rexi|rectum|lenken, beherrschen'],
  [2, 'vinco|vincere|vici|victum|siegen, besiegen'],
  [2, 'relinquo|relinquere|reliqui|relictum|verlassen, zurücklassen'],
  [2, 'moveo|movere|movi|motum|bewegen'],
  [2, 'teneo|tenere|tenui|—|halten'],
  [2, 'timeo|timere|timui|—|fürchten'],
  [2, 'iubeo|iubere|iussi|iussum|befehlen'],
  [2, 'maneo|manere|mansi|mansum|bleiben'],
  [2, 'respondeo|respondere|respondi|responsum|antworten'],
  [3, 'fero|ferre|tuli|latum|tragen, bringen'],
  [3, 'volo|velle|volui|—|wollen'],
  [3, 'nolo|nolle|nolui|—|nicht wollen'],
  [3, 'malo|malle|malui|—|lieber wollen'],
  [3, 'fio|fieri|factus sum|—|werden, geschehen'],
  [3, 'cado|cadere|cecidi|casum|fallen'],
  [3, 'curro|currere|cucurri|cursum|laufen'],
  [3, 'pello|pellere|pepuli|pulsum|stoßen, vertreiben'],
  [3, 'tango|tangere|tetigi|tactum|berühren'],
  [3, 'credo|credere|credidi|creditum|glauben'],
  [3, 'trado|tradere|tradidi|traditum|übergeben, überliefern'],
  [3, 'vivo|vivere|vixi|victum|leben'],
  [3, 'cognosco|cognoscere|cognovi|cognitum|erkennen, kennenlernen'],
  [3, 'constituo|constituere|constitui|constitutum|beschließen, festsetzen'],
  [3, 'gero|gerere|gessi|gestum|ausführen, führen'],
  [4, 'fugio|fugere|fugi|—|fliehen'],
  [4, 'iacio|iacere|ieci|iactum|werfen'],
  [4, 'rapio|rapere|rapui|raptum|rauben, reißen'],
  [4, 'cupio|cupere|cupivi|cupitum|wünschen, begehren'],
  [4, 'pario|parere|peperi|partum|hervorbringen, gebären'],
  [4, 'frango|frangere|fregi|fractum|brechen'],
  [4, 'rumpo|rumpere|rupi|ruptum|brechen, zerreißen'],
  [4, 'sentio|sentire|sensi|sensum|fühlen, merken'],
  [4, 'aperio|aperire|aperui|apertum|öffnen, aufdecken']
]

const ROH: Record<VerbSprache, Roh[]> = { en: EN, fr: FR, es: ES, it: IT, ru: RU, la: LA }

export interface StandardVerb extends VerbEintrag {
  /** Lernjahr, ab dem das Verb üblicherweise mit allen Formen gelernt wird */
  lernjahr: number
}

const cache = new Map<VerbSprache, StandardVerb[]>()

/** Die Standardliste einer Sprache (alle Lernjahre) */
export function standardListe(sprache: VerbSprache): StandardVerb[] {
  const da = cache.get(sprache)
  if (da) return da
  const spalten = VERB_SPALTEN[sprache]
  const liste = ROH[sprache].map(([lernjahr, zeile], i) => {
    const zellen = zeile.split('|')
    const formen: Record<string, string> = {}
    spalten.forEach((s, j) => {
      if (zellen[j]?.trim()) formen[s.id] = zellen[j].trim()
    })
    return { id: `std-${sprache}-${i + 1}`, formen, lernjahr }
  })
  cache.set(sprache, liste)
  return liste
}

/** Verben bis einschließlich dieses Lernjahrs */
export const standardBis = (sprache: VerbSprache, lernjahr: number): StandardVerb[] => standardListe(sprache).filter((v) => v.lernjahr <= Math.max(1, lernjahr))
