/** Čeština – Spielnamen und Spieltexte in einfacher Sprache (09.10.2026) */
import type { SprachPaket } from './typ'
import { lexikonAus } from './lexikonAus'

export const cs: SprachPaket = {
  namen: {
    'mehr:teammatch': 'Týmový zápas',
    'mehr:satzbaustelle': 'Stavba vět',
    'mehr:fluchtraum': 'Útěk',
    'mehr:beschreiben': 'Popiš a hádej',
    'mehr:tauziehen': 'Přetahování lanem',
    'mehr:staffel': 'Štafeta tvarů',
    'mehr:bingo': 'Slovní bingo',
    'mehr:schiffe': 'Lodě',
    'mehr:wortkette': 'Slovní řetěz',
    'mehr:bildergeschichte': 'Obrázkový příběh',
    'mehr:teammemory': 'Týmové pexeso',
    'mehr:kreuzwort': 'Společná křížovka',
    'mehr:fehlerdetektive': 'Detektivové chyb',
    'mehr:uebersetzung': 'Puzzle překladu',
    'mehr:dialog': 'Divadlo rozhovorů',
    'mehr:woerterturm': 'Věž slov',
    'mehr:hoerkette': 'Řetěz poslechu',
    'mehr:zeitstrahl': 'Časová osa',
    'mehr:reiseplaner': 'Plánovač cest',
    'mehr:schnapp': 'Chyť!',
    'mehr:galgen': 'Souboj – šibenice',
    'mehr:buzzer': 'Týmové tlačítko',
    'mehr:konjugation': 'Souboj časování',
    'mehr:umbau': 'Závod přestavby',
    'mehr:kollokation': 'Souboj spojení',
    'mehr:auktion': 'Aukce slov',
    'mehr:domino': 'Slovní domino',
    'mehr:stadtland': 'Město, jméno, zvíře',
    'mehr:sniper': 'Odstřelovač chyb',
    'mehr:synonyme': 'Žebřík synonym',
    'vok:memory': 'Pexeso',
    'vok:zuordnen': 'Přiřazování na čas',
    'vok:blitz': 'Bleskové kolo',
    'vok:satz': 'Puzzle vět',
    'vok:wortraten': 'Hádej slovo',
    'vok:kreuzwort': 'Křížovka',
    'vok:fallend': 'Padající slova',
    'vok:suchsel': 'Osmisměrka',
    'vok:bildwort': 'Obrázková hádanka',
    'vok:hoeren': 'Poslechový kvíz',
    'vok:satzhoeren': 'Diktát vět',
    'vok:diktat': 'Poslouchej a piš',
    'vok:satzluecke': 'Doplň mezeru',
    'vok:duell': 'Souboj slov',
    'vok:hoermemory': 'Poslechové pexeso',
    'vok:richtiggehoert': 'Slyšíš dobře?',
    'vok:buchstaben': 'Puzzle z písmen',
    'vok:hoerbingo': 'Poslechové bingo',
    'vok:bildmemory': 'Obrázkové pexeso',
    'vok:wasfehlt': 'Co chybí?',
    'vok:aufdecken': 'Odkryj obrázek',
    'vok:wortbild': 'Slovo → obrázek',
    'vok:verbtrio': 'Trio tvarů',
    'vok:formenblitz': 'Blesk tvarů',
    'vok:bildverb': 'Sloveso z obrázku',
    'vok:muster': 'Třiď vzory',
    'gram:fehlerjagd': 'Najdi chybu',
    'gram:satzbaupuzzle': 'Postav větu',
    'gram:formenblitz': 'Blesk tvarů',
    'gram:regelzuordnen': 'Přiřaď pravidlo',
    'gram:verbtrio': 'Trio tvarů',
    'gram:verbblitz': 'Blesk tvarů',
    'gram:bildverb': 'Sloveso z obrázku',
    'gram:muster': 'Třiď vzory',
    'gram:richtigfalsch': 'Správně, nebo špatně?',
    'gram:formenmemory': 'Pexeso tvarů',
    'gram:tabellenpuzzle': 'Puzzle tabulky',
    'gram:signalwort': 'Signální slova'
  },
  beschreibung: {
    teammatch: 'Všichni vidí otázku. Správná odpověď je jen na jednom zařízení. Mluvte spolu!',
    satzbaustelle: 'Každý má pár slov věty. Seřaďte je spolu ve správném pořadí.',
    fluchtraum: 'Odpovídejte spolu. Za pár správných odpovědí dostanete písmeno tajného slova. Najděte slovo a utečte!',
    beschreiben: 'Jeden hráč vidí slovo a vybírá nápovědy. Ostatní hádají. Pak se vystřídáte.',
    tauziehen: 'Každá správná odpověď táhne lano k tobě. Těžké otázky táhnou silněji.',
    staffel: 'Týmy odpovídají střídavě. Kdo první vyplní deset polí, vyhrává.',
    bingo: 'Aplikace říká slova. Ťukni na správné pole na své kartě. Plná řada je bingo!',
    schiffe: 'Pár správných odpovědí a můžeš střílet. Najdi první všechny lodě!',
    wortkette: 'Střídavě jedno slovo. Každé slovo začíná posledním písmenem předchozího.',
    bildergeschichte: 'Příběh je napsaný slovy. Seřaďte obrázky správně.',
    teammemory: 'Střídavě otočte dvě karty. Zvládnete to s málo tahy?',
    kreuzwort: 'Každý má jiné nápovědy. Spolu doplníte všechna slova.',
    fehlerdetektive: 'Jeden najde chybu, další ji opraví.',
    uebersetzung: 'Postavte spolu překlad – pozor, ne každý dílek patří.',
    dialog: 'Dvě role, jeden rozhovor: doplň do své repliky chybějící slovo.',
    woerterturm: 'Každá správná odpověď je kostka. Postavte věž, než se zakývá!',
    hoerkette: 'Jeden slyší slovo a zopakuje ho. Ostatní na něj ťuknou.',
    zeitstrahl: 'Dejte věty na časovou osu a řekněte čas.',
    reiseplaner: 'Všichni vidí stejné cesty, každý má své nápovědy. Jen všechny nápovědy dohromady sedí na jednu cestu.',
    schnapp: 'Hodí se slovo a význam k sobě? Kdo první správně chytí, má bod.',
    galgen: 'Hádej svá slova písmeno po písmenu. Kdo má první tři?',
    buzzer: 'Kdo první zmáčkne, odpovídá. Špatně? Pak odpovídá druhý tým.',
    konjugation: 'Správný tvar slovesa – kdo má první osm?',
    umbau: 'Přestav větu – rychle a správně.',
    kollokation: 'Které slovo se hodí k sousedním slovům?',
    auktion: 'Vsaď mince na „pravda" nebo „nepravda".',
    domino: 'Polož kámen se slovem, které sedí k otevřenému významu.',
    stadtland: 'Slova z tvého kurzu na dané písmeno – server kontroluje.',
    sniper: 'Ťukni první na chybu a oprav ji. Vedle? Tři sekundy pauza.',
    synonyme: 'Slova se stejným významem tě vynesou nahoru po žebříku.'
  },
  einzel: {
    'vok:memory': 'Najdi slovo a překlad jako pár.',
    'vok:zuordnen': 'Ťukej na páry co nejrychleji.',
    'vok:blitz': '60 sekund – co nejvíc správných odpovědí.',
    'vok:satz': 'Seřaď příkladové věty správně.',
    'vok:wortraten': 'Uhádni písmena, než květina ztratí všechny lístky.',
    'vok:kreuzwort': 'Tvoje slova v křížovce, s německými nápovědami.',
    'vok:fallend': 'Napiš překlad, než slovo spadne dolů.',
    'vok:suchsel': 'Najdi slova v mřížce písmen.',
    'vok:bildwort': 'Najdi slovo k obrázku.',
    'vok:hoeren': 'Poslouchej a vyber správný pravopis.',
    'vok:satzhoeren': 'Poslechni si větu a seřaď slova.',
    'vok:diktat': 'Poslechni si slovo a napiš ho správně.',
    'vok:satzluecke': 'Doplň správné slovo do příkladové věty.',
    'vok:duell': 'Hodí se pár? 20 kol proti tvému rekordu.',
    'vok:hoermemory': 'Najdi slovo ke každému zvuku.',
    'vok:richtiggehoert': '60 sekund: hodí se obrázek ke slovu, které slyšíš?',
    'vok:buchstaben': 'Poslouchej a slož slovo z písmen.',
    'vok:hoerbingo': 'Ťukej na slova, která slyšíš – plná řada je bingo.',
    'vok:bildmemory': 'Najdi obrázek a slovo jako pár.',
    'vok:wasfehlt': 'Zapamatuj si obrázky – který zmizel?',
    'vok:aufdecken': 'Uhádni slovo, než je vidět celý obrázek.',
    'vok:wortbild': 'Ťukni na obrázek ke slovu.',
    'vok:verbtrio': 'Najdi spolu všechny tvary slovesa.',
    'vok:formenblitz': '60 sekund: jaký tvar jsi slyšel?',
    'vok:bildverb': 'Řekni tvary slovesa k obrázku.',
    'vok:muster': 'Roztřiď slovesa podle vzoru.',
    'gram:fehlerjagd': 'Ťukni na špatné slovo a oprav ho.',
    'gram:satzbaupuzzle': 'Seřaď slova správně.',
    'gram:formenblitz': '60 sekund – vyber správný tvar.',
    'gram:regelzuordnen': 'Najdi pravidlo k příkladu.',
    'gram:verbtrio': 'Najdi spolu všechny tvary slovesa.',
    'gram:verbblitz': '60 sekund: jaký tvar jsi slyšel?',
    'gram:bildverb': 'Řekni tvary slovesa k obrázku.',
    'gram:muster': 'Roztřiď slovesa podle vzoru.',
    'gram:richtigfalsch': '60 sekund: je věta správně?',
    'gram:formenmemory': 'Najdi základní a nový tvar jako pár.',
    'gram:tabellenpuzzle': 'Dej tvary do správných polí tabulky.',
    'gram:signalwort': 'Jaký čas ukazuje signální slovo?'
  },
  einheiten: {
    gelöst: 'vyřešeno',
    Fehler: 'chyb',
    s: 's',
    erraten: 'uhádnuto',
    Punkte: 'bodů',
    richtig: 'správně',
    Aufrufe: 'vyvolání',
    Treffer: 'zásahů',
    Glieder: 'článků',
    Züge: 'tahů',
    Steine: 'kostek',
    Wörter: 'slov',
    Sätze: 'vět',
    Münzen: 'mincí',
    Sprossen: 'příček'
  },
  texte: {
    wasBedeutet: 'Co to znamená?',
    wieHeisst: 'Jaké je to slovo?',
    welchesFehlt: 'Které slovo chybí?',
    richtigIst: 'Správně: {0}',
    jemand: 'Někdo',
    duBistDran: 'Jsi na řadě!',
    istDran: 'Na řadě je {0}.',
    daneben: 'vedle.',
    richtig: 'Správně!',
    unentschieden: 'Remíza!',
    gewonnenHat: 'Vyhrává: {0}',
    teilVon: 'Část {0} z {1}',
    frageVon: 'Otázka {0} z {1}',
    herzen: 'společná srdce',
    nurEinGeraet: 'Správná odpověď je jen na jednom zařízení. Kdo ji má?',
    passtNicht: '„{0}" nesedí.',
    keineHerzen: 'Už nejsou srdce – jdeme dál.',
    tmGeschafft: 'Cíl týmu splněn: {0} z {1} vyřešeno!',
    tmLeer: '{0} z {1} vyřešeno – jednou došla srdce.',
    satz: 'Věta',
    geschichte: 'Příběh',
    zeitstrahl: 'Časová osa',
    vonN: '{0} {1} z {2}',
    gemeinsameReihe: 'Vaše společná řada',
    deineTeile: 'Tvoje dílky – ťukni na další',
    keineTeile: 'Už nemáš dílky – pomáhej ostatním.',
    nichtJedesTeil: 'Pozor: ne každý dílek patří.',
    passtNochNicht: 'To sem ještě nepatří.',
    passt: 'Sedí!',
    fertig: 'Hotovo!',
    baut: 'Postavte větu.',
    frueherSpaeter: 'Seřaďte věty od dřív k později.',
    welcheZeitform: 'Jaký je to čas?',
    nenntZeitform: 'Teď {0} řekne čas věty: „{1}"',
    richtigDoppel: 'Správně: {0}.',
    nichtGanz: 'Ne úplně.',
    dieGeschichte: 'Příběh: {0}',
    uebersetzt: 'Německy: „{0}"',
    fehlerfreiGebaut: 'Postaveno bez chyby!',
    mitFehlern: 'Hotovo, chyb: {0}.',
    mitEinemFehler: 'Hotovo, 1 chyba.',
    codewort: 'Tajné slovo',
    codewortN: 'Tajné slovo – {0} písmen',
    buchstabenGefunden: 'Nalezená písmena (pořadí neznámé)',
    bisBuchstabe: 'Ještě {0} správných odpovědí do dalšího písmena.',
    alleBuchstaben: 'Máte všechna písmena – napište tajné slovo!',
    buchstabeFrei: 'odkryl(a) písmeno!',
    richtigWeiter: 'správně! ({0} z {1} pro další písmeno)',
    neueAufgabe: 'Ne úplně – tady je nový úkol.',
    falschesWort: 'To není tajné slovo. Přečtěte si znovu nápovědy!',
    entkommen: 'Dveře jsou otevřené! Tajné slovo bylo „{0}" ({1}).',
    zeitAus: 'Čas vypršel.',
    zeitAusWort: 'Čas vypršel. Tajné slovo bylo „{0}" ({1}).',
    gemeinsameZeit: 'Společný čas',
    hinweise: 'Nápovědy k tajnému slovu',
    tuerOeffnen: 'Otevřít dveře',
    wortEingeben: 'Napiš tajné slovo',
    fehlversuche: 'Špatné pokusy: {0}',
    entkommenIn: 'Útěk za {0} minut!',
    nichtGereicht: 'Tentokrát nestačil čas.',
    hLaenge: 'Slovo má {0} písmen.',
    hBild: 'Podívejte se na obrázek.',
    hNomen: 'Je to podstatné jméno.',
    hVerb: 'Je to sloveso.',
    hAdj: 'Je to přídavné jméno.',
    hAdv: 'Je to příslovce.',
    hLuecke: 'Hodí se do této mezery: {0}',
    hSynonym: 'Znamená skoro totéž co „{0}".',
    hDefinition: 'Definice: {0}, {1} písmen, podobné jako „{2}".',
    hGebrauch: 'Takhle se používá: {0}',
    hAufgabe: 'Je to odpověď na úkol: {0}',
    wortartNomen: 'podstatné jméno',
    wortartVerb: 'sloveso',
    wortartAdj: 'přídavné jméno',
    wortartAdv: 'příslovce',
    wortartWort: 'slovo',
    feldGefuellt: 'Pole vyplněno!',
    erstDieFrage: 'Jsi na řadě – nejdřív otázka!',
    schussLaden: 'Ještě {0} správných odpovědí do výstřelu.',
    geladen: 'správně – ještě {0} do výstřelu.',
    darfSchiessen: 'smí střílet!',
    danebenAnderes: 'vedle – na řadě je druhý tým.',
    tippeFeld: 'Ťukni na pole druhého týmu.',
    treffer: 'Zásah!',
    wasser: 'Voda.',
    feldVon: 'Pole: {0} ({1} z {2} zasaženo)',
    eureFlotte: 'Vaše flotila',
    ziehtMit: 'táhne silou {0}!',
    teilRichtig: 'Část {0} z {1} správně – dál!',
    duZiehstLinks: 'Táhneš doleva.',
    duZiehstRechts: 'Táhneš doprava.',
    aufrufVon: 'Vyvolání {0} z {1}',
    nichtGerufen: 'To nebylo vyvoláno.',
    bingo: 'BINGO!',
    auchBingo: 'má taky bingo (místo {0})!',
    bingoPlatz: 'Bingo – místo {0}!',
    deinFeld: 'Tvoje karta',
    warteAndere: 'Čekáme na ostatní …',
    nichtImFeld: 'Není na mé kartě – dál',
    bingoListe: 'Bingo: {0}',
    bingoErste: 'První bingo: {0}',
    keinBingo: 'Tentokrát žádné bingo.',
    welchesWortSatz: 'Které slovo se hodí?',
    rundeVon: 'Kolo {0} z {1}',
    rundeFertig: 'Kolo hotovo!',
    deinePunkte: 'Tvoje body: {0}',
    abgegebenWarte: 'Odesláno – počkej na ostatní.',
    ueberspringenLoesung: 'Přeskočit (ukázat odpověď)',
    gefunden: 'Nalezeno!',
    nichtGanzDoppel: 'Ne úplně:',
    richtigKlein: 'správně!',
    wortVon: 'Slovo {0} z {1}',
    satzVon: 'Věta {0} z {1}',
    karteVon: 'Karta {0} z {1}',
    reiseVon: 'Cesta {0} z {1}',
    aussageVon: 'Tvrzení {0} z {1}',
    faengtMit: 'Začíná na „{0}".',
    passtNichtKlein: 'nesedí.',
    wortPasst: '{0} sedí!',
    kette: 'Řetěz ({0} z {1})',
    neuesGlied: 'Nový článek!',
    ketteHaelt: 'Řetěz přesto drží – dál!',
    ketteErgebnis: 'Váš řetěz má {0} článků.',
    paarGefunden: 'Pár nalezen!',
    keinPaar: 'Není to pár.',
    memoryStand: 'Tahy: {0} · Páry: {1} z {2}',
    memoryDran: 'Jsi na řadě: otoč dvě karty.',
    memoryErgebnis: 'Všechny páry za {0} tahů.',
    gemeinsamesRaetsel: 'Společná křížovka',
    woerterGeloest: 'Tvoje slova jsou vyřešená – pomáhejte si!',
    kreuzErgebnis: 'Křížovka vyřešena, špatné pokusy: {0}.',
    wieRichtig: 'Jak je „{0}" správně?',
    fehlerGefunden: 'našel/našla chybu: „{0}".',
    istRichtigWort: '„{0}" je správně.',
    fallGeloest: 'Případ vyřešen!',
    hatUebersprungen: 'přeskočil(a).',
    satzRot: 'Věta – červené slovo je špatně',
    deinSatz: 'Tvoje věta: které slovo je špatně? Ťukni na něj.',
    duVerbesserst: '{0} našel/našla chybu – ty ji opravíš:',
    verbessertDeinen: 'Nalezeno! Teď {0} opraví tvou větu.',
    nochFaelle: 'V tomto kole ještě {0} případy.',
    nochEinFall: 'V tomto kole ještě 1 případ.',
    faelleErgebnis: 'Případy: {0}, špatné ťuknutí: {1}.',
    fehlerEntdeckt: 'objevil(a) chybu!',
    danebenPause: 'vedle – 3 sekundy pauza.',
    niemandGefunden: 'Nikdo ji nenašel.',
    verbesserungFalsch: 'Oprava je špatně.',
    uebersprungen: 'Přeskočeno.',
    pause: 'Pauza',
    tippeFalsches: 'Ťukni na špatné slovo!',
    verbessert: '{0} opravuje.',
    findeNicht: 'Nenajdu – přeskočit',
    naechsterSatz: 'Dál na další větu.',
    deineRolle: 'Tvoje role: {0}',
    bisherGespraech: 'Rozhovor zatím',
    rolleFehlt: 'Role {0}: které slovo chybí?',
    rolleSpricht: 'Role {0} říká: {1}',
    dialogErgebnis: '{0} z {1} replik správně.',
    richtigVerstanden: 'správně rozuměl(a)!',
    diesmalNicht: 'Tentokrát ne.',
    warEsNicht: '– to nebylo ono.',
    ketteGlieder: 'Řetěz: {0} článků',
    duHoerst: 'Slyšíš slovo. Řekni ho nahlas – ostatní na něj ťuknou.',
    sprichtVor: '{0} ti řekne slovo.',
    welchesGehoert: 'Jaké slovo jsi slyšel(a)?',
    hoerErgebnis: '{0} z {1} slov správně předáno.',
    eureReise: 'To je vaše cesta!',
    reisePasstNicht: 'Tahle cesta nesedí na všechny nápovědy.',
    deineHinweise: 'Tvoje nápovědy (vidíš jen ty)',
    welcheReise: 'Která je to cesta? Domluvte se!',
    reiseErgebnis: 'Cest: {0}, špatné pokusy: {1}.',
    rpReiseN: 'Cesta {0}',
    rpTippen: 'Ťukněte na cestu a navrhněte ji.',
    rpVorschlag: '{0} navrhuje cestu {1}.',
    rpZustimmen: 'Souhlasím!',
    rpWarteZustimmung: 'Počkej, až ostatní souhlasí …',
    rpZustimmungen: 'Souhlasí: {0} z {1}',
    rpPasstNichtWeil: 'Cesta {0} nesedí: „{1}" ({2})',
    rpZeitAus: 'Čas vypršel – správná cesta byla {0}.',
    rpZusammen: 'Jen všechny nápovědy dohromady sedí na jednu cestu. Přečtěte si je navzájem!',
    schnapp: 'Chyceno!',
    zuFrueh: 'chytil(a) moc brzy.',
    passteNicht: 'Správně, to k sobě nepatřilo.',
    schnappPasst: 'Chyť! Sedí!',
    passtNichtKnopf: 'Nesedí',
    wortGeschafft: 'uhádl(a) slovo!',
    neuesWort: 'Nové slovo.',
    gesucht: 'Hledej slovo: {0}',
    fehlerVonMax: 'Chyby: {0} z {1}',
    fuersTeam: '+{0} pro tým!',
    auchDaneben: 'taky vedle.',
    buzzer: 'Zmáčkni!',
    antwortet: '{0} odpovídá.',
    anderesTeamAntwortet: 'Odpovídá druhý tým.',
    aussageStimmte: 'Tvrzení byla pravda.',
    aussageStimmteNicht: 'Tvrzení nebyla pravda.',
    deineMuenzen: 'Tvoje mince: {0}',
    gebotAb: 'Sázka podána – počkej na ostatní.',
    aufStimmt: '{0} na „pravda"',
    aufStimmtNicht: '{0} na „nepravda"',
    steinDoch: 'přece měl(a) správný kámen.',
    steinPasstNicht: 'Ten kámen nesedí.',
    legtAn: 'přikládá!',
    offen: 'Otevřeno: {0}',
    dominoDran: 'Jsi na řadě: polož kámen se správným slovem – nebo pas.',
    deineSteine: 'Tvoje kameny ({0})',
    passen: 'Pas',
    slfWort: 'Slovo z tvého kurzu',
    slfLang: 'Slovo s aspoň 5 písmeny',
    slfNomen: 'Podstatné jméno',
    slfVerb: 'Sloveso',
    slfDeutsch: 'Německý význam slova z kurzu (slovo začíná tím písmenem)',
    zaehltNicht: '{0}: „{1}" neplatí',
    rundeAusgewertet: 'Kolo {0} vyhodnoceno.',
    rundeBuchstabe: 'Kolo {0}: písmeno {1}',
    gemeinsamVon: 'Spolu: {0} z {1} {2}',
    geschafftEinheit: 'Hotovo: {0} {1}!',
    vonEinheit: '{0} z {1} {2}.',
    welchesPasstDazu: 'Které slovo se k tomu hodí?',
    welchesDasselbe: 'Které slovo znamená totéž?',
    bWortart: 'Slovní druh: {0}',
    bAnfang: 'Začíná na „{0}"',
    bEnde: 'Končí na „{0}"',
    bLaenge: '{0} písmen',
    bLaengeWoerter: '{0} písmen ve {1} slovech',
    bGegenteil: 'Opak: {0}',
    bErraten: 'uhádl(a)!',
    bNichtErraten: 'Tentokrát neuhádnuto.',
    bWarNicht: 'Nebylo to „{0}".',
    bDuErklaerst: 'Vysvětluješ: {0} ({1})',
    bWaehle: 'Vyber 2 nebo 3 nápovědy a pošli je',
    bAndereRaten: 'Teď hádají ostatní.',
    bErklaert: '{0} vysvětluje.',
    bWarteHinweise: 'Čekáme na nápovědy …',
    bHinweise: 'Nápovědy',
    bWelchesGemeint: 'Které je to slovo?',
    bErgebnis: 'Uhádnuto {0} z {1} slov.',
    uiEinladungscode: 'Kód pozvánky',
    uiCodeHinweis: 'Ostatní ho zadají na úvodní stránce („Mit Code öffnen") nebo v seznamu her.',
    uiDabei: 'Hráči ({0} z {1})',
    uiGetrennt: 'Spojení přerušeno – místo čeká 60 sekund',
    uiHerausnehmen: 'Odebrat {0}',
    uiSpiel: 'Hra',
    uiSchwierigkeit: 'Úroveň',
    uiBerechnet: '{0} – podle toho, co všichni umíte.',
    uiGrammatik: 'Gramatika',
    uiStarten: 'Spustit hru',
    uiWarteMit: 'Čekáme na hráče (aspoň {0})',
    uiGleich: 'Hned začneme – {0} vybírá úroveň a spouští. Úroveň: {1}',
    uiDerHost: 'hostitel',
    uiTeamZiel: 'Cíl týmu splněn!',
    uiGutGespielt: 'Dobře zahráno!',
    uiGewonnen: 'Vyhrává: {0}',
    uiNurFuerDich: 'Jen pro tebe',
    uiRichtigN: 'správně: {0}',
    uiPlatz: 'Místo {0}',
    uiEinWortWieder: 'Brzy si znovu procvičíš 1 slovo.',
    uiWoerterWieder: 'Brzy si znovu procvičíš {0} slov.',
    uiZurueck: 'Zpět',
    uiNochmal: 'Ještě jednou',
    uiVerlassen: 'Odejít',
    uiKooperativ: 'Spolu',
    uiVersus: 'Proti sobě',
    uiAntwortSchreiben: 'Napiš odpověď',
    uiKeineAntwort: 'Na tvém zařízení teď není žádná odpověď.',
    uiNochmalHoeren: 'Poslechnout znovu',
    uiAbschicken: 'Odeslat',
    uiAbschickenN: 'Odeslat ({0})',
    sLeicht: 'Lehká',
    sMittel: 'Střední',
    sSchwer: 'Těžká',
    sUnmoeglich: 'Nemožná',
    sLeichtText: 'Slova, která všichni dobře znají',
    sMittelText: 'Občas se něco nepovedlo',
    sSchwerText: 'Často špatně – dobré na trénink',
    sUnmoeglichText: 'Nejtěžší slova všech',
    ruf0: 'Výborně!',
    ruf1: 'Pomoc?',
    ruf2: 'Jsem na řadě',
    ruf3: 'Super tým!',
    ruf4: 'Moment …',
    uiKoopText: 'Dosáhnout cíle spolu s ostatními z tvého kurzu',
    uiVersusText: 'Proti sobě – férově, s otázkami podle vaší úrovně',
    uiZiffern: '6 číslic',
    uiBeitreten: 'Připojit se',
    uiCodeSechs: 'Kód pozvánky má šest číslic.',
    uiNachUebung: 'Hrát spolu můžete po dnešním procvičování.',
    uiWirdEroeffnet: 'Hra se otevírá …',
    uiStartenPersonen: 'Spustit · {0}–{1} hráči',
    uiCodeTitel: 'Hrajte spolu – kód pozvánky',
    uiCodeBeschreibung: 'Pozval tě někdo? Napiš kód a stiskni Enter.',
    brauchtBeispielsatz: 'Potřebuje slova s příkladovou větou.',
    brauchtVier: 'Potřebuje aspoň čtyři slova.'
  },
  reise: lexikonAus(
    {
      ziel: [
        ['moře', 'Chceme jet k moři.', 'Nechceme jet k moři.', 'Tom nesnáší písek a slanou vodu.', 'moře'],
        ['hory', 'Chceme jet na hory.', 'Nechceme jet na hory.', 'Babička nemůže chodit do kopce.', 'hora'],
        ['velké město', 'Chceme navštívit velké město.', 'Nechceme jet do velkého města.', 'Mia nesnáší hluk a dopravu.', 'město'],
        ['jezero', 'Chceme jet k jezeru.', 'Nechceme jet k jezeru.', 'Táta říká, že jezera jsou nudná.', 'jezero'],
        ['ostrov', 'Chceme jet na ostrov.', 'Nechceme jet na ostrov.', 'Nikdo nechce být týden na malém ostrově.', 'ostrov'],
        ['statek', 'Chceme spát na statku.', 'Nechceme spát na statku.', 'Tom se bojí krav.', 'statek']
      ],
      verkehr: [
        ['vlak', 'Chceme jet vlakem.', 'Nechceme jet vlakem.', 'Tento týden stávkují vlaky.', 'vlak'],
        ['autobus', 'Chceme jet autobusem.', 'Nechceme jet autobusem.', 'Mie je v autobusu vždycky špatně.', 'autobus'],
        ['auto', 'Chceme jet autem.', 'Nechceme jet autem.', 'Naše auto je rozbité.', 'auto'],
        ['letadlo', 'Chceme letět letadlem.', 'Nechceme letět letadlem.', 'Táta se bojí létat.', 'letadlo'],
        ['kolo', 'Chceme jet na kole.', 'Nechceme jet na kole.', 'Babička neumí jezdit na kole.', 'kolo'],
        ['loď', 'Chceme plout lodí.', 'Nechceme plout lodí.', 'Babičce je na lodi špatně.', 'loď']
      ],
      wetter: [
        ['slunce', 'Chceme slunce.', 'Nechceme slunce.', 'Tom se velmi rychle spálí.', 'slunce', 'Když svítí slunce,'],
        ['déšť', null, 'Nemáme rádi déšť.', 'Mia zapomněla deštník.', 'déšť', 'Když prší,'],
        ['sníh', 'Chceme sníh.', 'Nechceme sníh.', 'Nemáme teplé oblečení.', 'sníh', 'Když sněží,'],
        ['vítr', 'Chceme trochu větru.', 'Nechceme vítr.', 'Mie vždycky uletí klobouk.', 'vítr', 'Když fouká vítr,']
      ],
      akt: [
        ['plavání', 'Chceme plavat.', 'Mia neumí plavat.', 'Mia se bojí hluboké vody.', 'plavat', 'chceme plavat.'],
        ['túry', 'Chceme chodit na túry.', 'Babička nemůže chodit daleko.', 'Babičku bolí koleno.', 'chodit', 'chceme jít na túru.'],
        ['lyže', 'Chceme lyžovat.', 'Tom neumí lyžovat.', 'Tom si loni v zimě zlomil nohu.', 'lyže', 'chceme lyžovat.'],
        ['muzea', 'Chceme jít do muzea.', 'Nechceme jít do muzea.', 'Tom si myslí, že muzea jsou nudná.', 'muzeum', 'chceme jít do muzea.'],
        ['nákupy', 'Chceme jít nakupovat.', 'Nechceme jít nakupovat.', 'Nemáme peníze na nákupy.', 'obchod', 'chceme jít nakupovat.'],
        ['plachtění', 'Chceme jezdit na plachetnici.', 'Nechceme jezdit na plachetnici.', 'Tátovi je na malých lodích špatně.', 'plachta', 'chceme jezdit na plachetnici.'],
        ['stan', 'Chceme spát ve stanu.', 'Nechceme spát ve stanu.', 'Mia se v noci bojí hmyzu.', 'stan', 'chceme spát ve stanu.']
      ]
    },
    {
      preisKarte: '{0} €',
      tageKarte: 'dní: {0}',
      preis5: 'Máme {0} eur.',
      preis7: 'Musí to stát méně než {0} eur.',
      preis9: 'Můžeme utratit nejvýš {0} eur.',
      tage5: 'Máme jen {0} dní.',
      tage7: 'Chceme zůstat aspoň {0} dní.',
      tage9: 'Nejpozději po {0} dnech musíme být doma.'
    }
  )
}
