/** Dansk – Spielnamen und Spieltexte in einfacher Sprache (09.10.2026) */
import type { SprachPaket } from './typ'
import { lexikonAus } from './lexikonAus'

export const da: SprachPaket = {
  namen: {
    'mehr:teammatch': 'Holdkamp',
    'mehr:satzbaustelle': 'Sætningsbyggeri',
    'mehr:fluchtraum': 'Escape room',
    'mehr:beschreiben': 'Forklar og gæt',
    'mehr:tauziehen': 'Tovtrækning',
    'mehr:staffel': 'Formstafet',
    'mehr:bingo': 'Ordbanko',
    'mehr:schiffe': 'Sænke slagskibe',
    'mehr:wortkette': 'Ordkæde',
    'mehr:bildergeschichte': 'Billedhistorie',
    'mehr:teammemory': 'Holdvendespil',
    'mehr:kreuzwort': 'Fælles krydsord',
    'mehr:fehlerdetektive': 'Fejldetektiver',
    'mehr:uebersetzung': 'Oversættelsespuslespil',
    'mehr:dialog': 'Dialogteater',
    'mehr:woerterturm': 'Ordtårn',
    'mehr:hoerkette': 'Lyttekæde',
    'mehr:zeitstrahl': 'Tidslinje',
    'mehr:reiseplaner': 'Rejseplanlægger',
    'mehr:schnapp': 'Snup!',
    'mehr:galgen': 'Galgeduel',
    'mehr:buzzer': 'Holdbuzzer',
    'mehr:konjugation': 'Bøjningsduel',
    'mehr:umbau': 'Ombygningsløb',
    'mehr:kollokation': 'Kollokationsduel',
    'mehr:auktion': 'Ordauktion',
    'mehr:domino': 'Orddomino',
    'mehr:stadtland': 'By, land, flod',
    'mehr:sniper': 'Fejlsniper',
    'mehr:synonyme': 'Synonymstige',
    'vok:memory': 'Vendespil',
    'vok:zuordnen': 'Par mod uret',
    'vok:blitz': 'Lynrunde',
    'vok:satz': 'Sætningspuslespil',
    'vok:wortraten': 'Gæt ordet',
    'vok:kreuzwort': 'Krydsord',
    'vok:fallend': 'Faldende ord',
    'vok:suchsel': 'Ordjagt',
    'vok:bildwort': 'Billedgåde',
    'vok:hoeren': 'Lyttequiz',
    'vok:satzhoeren': 'Sætningsdiktat',
    'vok:diktat': 'Lyt og skriv',
    'vok:satzluecke': 'Udfyld hullet',
    'vok:duell': 'Ordduel',
    'vok:hoermemory': 'Lyttevendespil',
    'vok:richtiggehoert': 'Hørt rigtigt?',
    'vok:buchstaben': 'Bogstavpuslespil',
    'vok:hoerbingo': 'Lyttebanko',
    'vok:bildmemory': 'Billedvendespil',
    'vok:wasfehlt': 'Hvad mangler?',
    'vok:aufdecken': 'Afdæk billedet',
    'vok:wortbild': 'Ord → billede',
    'vok:verbtrio': 'Formtrio',
    'vok:formenblitz': 'Formlyn',
    'vok:bildverb': 'Billedverbum',
    'vok:muster': 'Sortér mønstre',
    'gram:fehlerjagd': 'Find fejlen',
    'gram:satzbaupuzzle': 'Byg sætningen',
    'gram:formenblitz': 'Formlyn',
    'gram:regelzuordnen': 'Find reglen',
    'gram:verbtrio': 'Formtrio',
    'gram:verbblitz': 'Formlyn',
    'gram:bildverb': 'Billedverbum',
    'gram:muster': 'Sortér mønstre',
    'gram:richtigfalsch': 'Rigtigt eller forkert?',
    'gram:formenmemory': 'Formvendespil',
    'gram:tabellenpuzzle': 'Tabelpuslespil',
    'gram:signalwort': 'Signalord'
  },
  beschreibung: {
    teammatch: 'Alle ser spørgsmålet. Det rigtige svar står kun på én skærm. Tal sammen!',
    satzbaustelle: 'Alle har nogle ord fra sætningen. Sæt dem sammen i den rigtige rækkefølge.',
    fluchtraum: 'Svar sammen. Efter nogle rigtige svar får I et bogstav i det hemmelige ord. Find ordet og slip ud!',
    beschreiben: 'Én ser ordet og vælger ledetråde. De andre gætter. Så bytter I.',
    tauziehen: 'Hvert rigtigt svar trækker rebet over til dig. Svære spørgsmål trækker hårdere.',
    staffel: 'Holdene svarer på skift. Det hold, der først fylder ti felter, vinder.',
    bingo: 'Appen siger ord. Tryk på det rigtige felt på din plade. En fuld række er banko!',
    schiffe: 'Nogle rigtige svar, så må du skyde. Find alle skibene først!',
    wortkette: 'Et ord på skift. Hvert ord begynder med det sidste bogstav i ordet før.',
    bildergeschichte: 'Historien står med ord. Læg jeres billeder i den rigtige rækkefølge.',
    teammemory: 'Vend to kort på skift. Kan I klare det med få træk?',
    kreuzwort: 'Alle har forskellige ledetråde. Sammen udfylder I alle ordene.',
    fehlerdetektive: 'Én finder fejlen, den næste retter den.',
    uebersetzung: 'Byg oversættelsen sammen – pas på, ikke alle brikker hører med.',
    dialog: 'To roller, én samtale: sæt det manglende ord ind i din replik.',
    woerterturm: 'Hvert rigtigt svar er en klods. Byg tårnet, før det vakler!',
    hoerkette: 'Én hører ordet og siger det. De andre trykker på det.',
    zeitstrahl: 'Læg sætningerne på tidslinjen og sig tiden.',
    reiseplaner: 'Alle ser de samme rejser og har egne ledetråde. Kun alle ledetråde sammen passer til én rejse.',
    schnapp: 'Passer ord og betydning sammen? Den, der først snupper rigtigt, får et point.',
    galgen: 'Gæt dine ord bogstav for bogstav. Hvem har tre først?',
    buzzer: 'Den, der trykker først, svarer. Forkert? Så svarer det andet hold.',
    konjugation: 'Den rigtige form af verbet – hvem har otte først?',
    umbau: 'Byg sætningen om – hurtigt og rigtigt.',
    kollokation: 'Hvilket ord passer til ordene ved siden af?',
    auktion: 'Sæt mønter på „rigtigt" eller „forkert".',
    domino: 'Læg brikken, hvis ord passer til den åbne betydning.',
    stadtland: 'Ord fra dit forløb med forbogstavet – serveren tjekker.',
    sniper: 'Tryk først på fejlen og ret den. Forbi? Tre sekunders pause.',
    synonyme: 'Ord med samme betydning fører dig op ad stigen.'
  },
  einzel: {
    'vok:memory': 'Find ordet og oversættelsen som et par.',
    'vok:zuordnen': 'Tryk på parrene så hurtigt som muligt.',
    'vok:blitz': '60 sekunder – så mange rigtige svar som muligt.',
    'vok:satz': 'Sæt eksempelsætningerne i den rigtige rækkefølge.',
    'vok:wortraten': 'Gæt bogstaverne, før blomsten mister alle blade.',
    'vok:kreuzwort': 'Dine ord i et krydsord med tyske ledetråde.',
    'vok:fallend': 'Skriv oversættelsen, før ordet når bunden.',
    'vok:suchsel': 'Find ordene i bogstavgitteret.',
    'vok:bildwort': 'Find ordet til billedet.',
    'vok:hoeren': 'Lyt og vælg den rigtige stavemåde.',
    'vok:satzhoeren': 'Lyt til sætningen og sæt ordene i rækkefølge.',
    'vok:diktat': 'Lyt til ordet og skriv det rigtigt.',
    'vok:satzluecke': 'Sæt det rigtige ord ind i eksempelsætningen.',
    'vok:duell': 'Passer parret? 20 runder mod din bedste tid.',
    'vok:hoermemory': 'Find ordet til hver lyd.',
    'vok:richtiggehoert': '60 sekunder: passer billedet til ordet, du hører?',
    'vok:buchstaben': 'Lyt og byg ordet med bogstaver.',
    'vok:hoerbingo': 'Tryk på de ord, du hører – en fuld række er banko.',
    'vok:bildmemory': 'Find billede og ord som et par.',
    'vok:wasfehlt': 'Husk billederne – hvilket er væk?',
    'vok:aufdecken': 'Gæt ordet, før hele billedet ses.',
    'vok:wortbild': 'Tryk på billedet til ordet.',
    'vok:verbtrio': 'Find alle former af et verbum sammen.',
    'vok:formenblitz': '60 sekunder: hvilken form hørte du?',
    'vok:bildverb': 'Sig verbets former til billedet.',
    'vok:muster': 'Sortér verberne efter mønster.',
    'gram:fehlerjagd': 'Tryk på det forkerte ord og ret det.',
    'gram:satzbaupuzzle': 'Sæt ordene i den rigtige rækkefølge.',
    'gram:formenblitz': '60 sekunder – vælg den rigtige form.',
    'gram:regelzuordnen': 'Find reglen til eksempelsætningen.',
    'gram:verbtrio': 'Find alle former af et verbum sammen.',
    'gram:verbblitz': '60 sekunder: hvilken form hørte du?',
    'gram:bildverb': 'Sig verbets former til billedet.',
    'gram:muster': 'Sortér verberne efter mønster.',
    'gram:richtigfalsch': '60 sekunder: er sætningen rigtig?',
    'gram:formenmemory': 'Find grundform og ny form som et par.',
    'gram:tabellenpuzzle': 'Sæt formerne i de rigtige felter i tabellen.',
    'gram:signalwort': 'Hvilken tid viser signalordet?'
  },
  einheiten: {
    gelöst: 'løst',
    Fehler: 'fejl',
    s: 's',
    erraten: 'gættet',
    Punkte: 'point',
    richtig: 'rigtige',
    Aufrufe: 'opråb',
    Treffer: 'træffere',
    Glieder: 'led',
    Züge: 'træk',
    Steine: 'klodser',
    Wörter: 'ord',
    Sätze: 'sætninger',
    Münzen: 'mønter',
    Sprossen: 'trin'
  },
  texte: {
    wasBedeutet: 'Hvad betyder det?',
    wieHeisst: 'Hvad hedder ordet?',
    welchesFehlt: 'Hvilket ord mangler?',
    richtigIst: 'Rigtigt er: {0}',
    jemand: 'Nogen',
    duBistDran: 'Det er din tur!',
    istDran: 'Det er {0}s tur.',
    daneben: 'forbi.',
    richtig: 'Rigtigt!',
    unentschieden: 'Uafgjort!',
    gewonnenHat: 'Vinder: {0}',
    teilVon: 'Del {0} af {1}',
    frageVon: 'Spørgsmål {0} af {1}',
    herzen: 'fælles hjerter',
    nurEinGeraet: 'Det rigtige svar står kun på én skærm. Hvem har det?',
    passtNicht: '„{0}" er ikke rigtigt.',
    keineHerzen: 'Ingen hjerter tilbage – vi fortsætter.',
    tmGeschafft: 'Holdets mål er nået: {0} af {1} løst!',
    tmLeer: '{0} af {1} løst – én gang løb hjerterne tør.',
    satz: 'Sætning',
    geschichte: 'Historie',
    zeitstrahl: 'Tidslinje',
    vonN: '{0} {1} af {2}',
    gemeinsameReihe: 'Jeres fælles række',
    deineTeile: 'Dine brikker – tryk på den næste',
    keineTeile: 'Du har ikke flere brikker – hjælp de andre.',
    nichtJedesTeil: 'Pas på: ikke alle brikker hører med.',
    passtNochNicht: 'Det passer ikke her endnu.',
    passt: 'Passer!',
    fertig: 'Færdig!',
    baut: 'Byg sætningen.',
    frueherSpaeter: 'Læg sætningerne fra tidligere til senere.',
    welcheZeitform: 'Hvilken tid er det?',
    nenntZeitform: 'Nu siger {0} tiden for: „{1}"',
    richtigDoppel: 'Rigtigt: {0}.',
    nichtGanz: 'Ikke helt.',
    dieGeschichte: 'Historien: {0}',
    uebersetzt: 'På tysk: „{0}"',
    fehlerfreiGebaut: 'Bygget uden fejl!',
    mitFehlern: 'Klaret med {0} fejl.',
    mitEinemFehler: 'Klaret med 1 fejl.',
    codewort: 'Kodeord',
    codewortN: 'Kodeord – {0} bogstaver',
    buchstabenGefunden: 'Fundne bogstaver (rækkefølge ukendt)',
    bisBuchstabe: 'Endnu {0} rigtige svar til det næste bogstav.',
    alleBuchstaben: 'I har alle bogstaverne – skriv kodeordet!',
    buchstabeFrei: 'har låst et bogstav op!',
    richtigWeiter: 'rigtigt! ({0} af {1} til det næste bogstav)',
    neueAufgabe: 'Ikke helt – her er en ny opgave.',
    falschesWort: 'Det er ikke kodeordet. Læs ledetrådene igen!',
    entkommen: 'Døren er åben! Kodeordet var „{0}" ({1}).',
    zeitAus: 'Tiden er gået.',
    zeitAusWort: 'Tiden er gået. Kodeordet var „{0}" ({1}).',
    gemeinsameZeit: 'Holdets tid',
    hinweise: 'Ledetråde til kodeordet',
    tuerOeffnen: 'Åbn døren',
    wortEingeben: 'Skriv kodeordet',
    fehlversuche: 'Forkerte forsøg: {0}',
    entkommenIn: 'Sluppet ud på {0} minutter!',
    nichtGereicht: 'Denne gang var der ikke tid nok.',
    hLaenge: 'Ordet har {0} bogstaver.',
    hBild: 'Se på billedet.',
    hNomen: 'Det er et navneord.',
    hVerb: 'Det er et udsagnsord.',
    hAdj: 'Det er et tillægsord.',
    hAdv: 'Det er et biord.',
    hLuecke: 'Det passer i dette hul: {0}',
    hSynonym: 'Det betyder næsten det samme som „{0}".',
    hDefinition: 'Definition: {0} med {1} bogstaver, ligner „{2}".',
    hGebrauch: 'Sådan bruger man det: {0}',
    hAufgabe: 'Det er svaret på denne opgave: {0}',
    wortartNomen: 'et navneord',
    wortartVerb: 'et udsagnsord',
    wortartAdj: 'et tillægsord',
    wortartAdv: 'et biord',
    wortartWort: 'et ord',
    feldGefuellt: 'Felt fyldt!',
    erstDieFrage: 'Det er din tur – først spørgsmålet!',
    schussLaden: 'Endnu {0} rigtige svar til et skud.',
    geladen: 'rigtigt – endnu {0} til skuddet.',
    darfSchiessen: 'må skyde!',
    danebenAnderes: 'forbi – det er det andet holds tur.',
    tippeFeld: 'Tryk på et felt hos det andet hold.',
    treffer: 'Ramt!',
    wasser: 'Plask.',
    feldVon: '{0}s plade ({1} af {2} ramt)',
    eureFlotte: 'Jeres flåde',
    ziehtMit: 'trækker med {0}!',
    teilRichtig: 'Del {0} af {1} rigtig – fortsæt!',
    duZiehstLinks: 'Du trækker mod venstre.',
    duZiehstRechts: 'Du trækker mod højre.',
    aufrufVon: 'Opråb {0} af {1}',
    nichtGerufen: 'Det blev ikke råbt op.',
    bingo: 'BANKO!',
    auchBingo: 'har også banko (plads {0})!',
    bingoPlatz: 'Banko – plads {0}!',
    deinFeld: 'Din plade',
    warteAndere: 'Venter på de andre …',
    nichtImFeld: 'Ikke på min plade – videre',
    bingoListe: 'Banko: {0}',
    bingoErste: 'Første banko: {0}',
    keinBingo: 'Ingen banko denne gang.',
    welchesWortSatz: 'Hvilket ord passer?',
    rundeVon: 'Runde {0} af {1}',
    rundeFertig: 'Runden er slut!',
    deinePunkte: 'Dine point: {0}',
    abgegebenWarte: 'Sendt – vent på de andre.',
    ueberspringenLoesung: 'Spring over (vis svaret)',
    gefunden: 'Fundet!',
    nichtGanzDoppel: 'Ikke helt:',
    richtigKlein: 'rigtigt!',
    wortVon: 'Ord {0} af {1}',
    satzVon: 'Sætning {0} af {1}',
    karteVon: 'Kort {0} af {1}',
    reiseVon: 'Rejse {0} af {1}',
    aussageVon: 'Udsagn {0} af {1}',
    faengtMit: 'Det begynder med „{0}".',
    passtNichtKlein: 'passer ikke.',
    wortPasst: '{0} passer!',
    kette: 'Kæde ({0} af {1})',
    neuesGlied: 'Nyt led!',
    ketteHaelt: 'Kæden holder alligevel – videre!',
    ketteErgebnis: 'Jeres kæde har {0} led.',
    paarGefunden: 'Par fundet!',
    keinPaar: 'Ikke et par.',
    memoryStand: 'Træk: {0} · Par: {1} af {2}',
    memoryDran: 'Din tur: vend to kort.',
    memoryErgebnis: 'Alle par fundet på {0} træk.',
    gemeinsamesRaetsel: 'Fælles krydsord',
    woerterGeloest: 'Dine ord er løst – hjælp hinanden!',
    kreuzErgebnis: 'Krydsordet løst med {0} forkerte forsøg.',
    wieRichtig: 'Hvad er den rigtige form af „{0}"?',
    fehlerGefunden: 'har fundet fejlen: „{0}".',
    istRichtigWort: '„{0}" er rigtigt.',
    fallGeloest: 'Sagen er løst!',
    hatUebersprungen: 'sprang over.',
    satzRot: 'Sætningen – det røde ord er forkert',
    deinSatz: 'Din sætning: hvilket ord er forkert? Tryk på det.',
    duVerbesserst: '{0} har fundet fejlen – du retter den:',
    verbessertDeinen: 'Fundet! Nu retter {0} din sætning.',
    nochFaelle: 'Endnu {0} sager i denne runde.',
    nochEinFall: 'Endnu 1 sag i denne runde.',
    faelleErgebnis: '{0} sager klaret, {1} forkerte tryk.',
    fehlerEntdeckt: 'har opdaget fejlen!',
    danebenPause: 'forbi – 3 sekunders pause.',
    niemandGefunden: 'Ingen fandt den.',
    verbesserungFalsch: 'Rettelsen er forkert.',
    uebersprungen: 'Sprunget over.',
    pause: 'Pause',
    tippeFalsches: 'Tryk på det forkerte ord!',
    verbessert: '{0} retter.',
    findeNicht: 'Kan ikke finde det – spring over',
    naechsterSatz: 'Videre til næste sætning.',
    deineRolle: 'Din rolle: {0}',
    bisherGespraech: 'Samtalen indtil nu',
    rolleFehlt: 'Rolle {0}: hvilket ord mangler?',
    rolleSpricht: 'Rolle {0} siger: {1}',
    dialogErgebnis: '{0} af {1} replikker spillet rigtigt.',
    richtigVerstanden: 'har forstået rigtigt!',
    diesmalNicht: 'Ikke denne gang.',
    warEsNicht: '– det var ikke det.',
    ketteGlieder: 'Kæde: {0} led',
    duHoerst: 'Du hører ordet. Sig det højt – de andre trykker på det.',
    sprichtVor: '{0} siger ordet til dig.',
    welchesGehoert: 'Hvilket ord hørte du?',
    hoerErgebnis: '{0} af {1} ord givet rigtigt videre.',
    eureReise: 'Det er jeres rejse!',
    reisePasstNicht: 'Denne rejse passer ikke til alle ledetråde.',
    deineHinweise: 'Dine ledetråde (kun du kan se dem)',
    welcheReise: 'Hvilken rejse er det? Tal sammen!',
    reiseErgebnis: '{0} rejser planlagt, {1} forkerte forsøg.',
    rpReiseN: 'Rejse {0}',
    rpTippen: 'Tryk på en rejse for at foreslå den.',
    rpVorschlag: '{0} foreslår rejse {1}.',
    rpZustimmen: 'Enig!',
    rpWarteZustimmung: 'Vent, til de andre er enige …',
    rpZustimmungen: 'Enige: {0} af {1}',
    rpPasstNichtWeil: 'Rejse {0} passer ikke: „{1}" ({2})',
    rpZeitAus: 'Tiden er gået – den rigtige rejse var rejse {0}.',
    rpZusammen: 'Kun alle ledetråde sammen passer til én rejse. Læs dem op for hinanden!',
    schnapp: 'Snuppet!',
    zuFrueh: 'snuppede for tidligt.',
    passteNicht: 'Rigtigt, det passede ikke.',
    schnappPasst: 'Snup! Det passer!',
    passtNichtKnopf: 'Passer ikke',
    wortGeschafft: 'har klaret et ord!',
    neuesWort: 'Nyt ord.',
    gesucht: 'Find ordet for: {0}',
    fehlerVonMax: 'Fejl: {0} af {1}',
    fuersTeam: '+{0} til holdet!',
    auchDaneben: 'også forbi.',
    buzzer: 'Tryk!',
    antwortet: '{0} svarer.',
    anderesTeamAntwortet: 'Det andet hold svarer.',
    aussageStimmte: 'Udsagnet var rigtigt.',
    aussageStimmteNicht: 'Udsagnet var forkert.',
    deineMuenzen: 'Dine mønter: {0}',
    gebotAb: 'Indsats lagt – vent på de andre.',
    aufStimmt: '{0} på „rigtigt"',
    aufStimmtNicht: '{0} på „forkert"',
    steinDoch: 'havde alligevel den rigtige brik.',
    steinPasstNicht: 'Den brik passer ikke.',
    legtAn: 'lægger en brik!',
    offen: 'Åben: {0}',
    dominoDran: 'Din tur: læg brikken med det rigtige ord – eller meld pas.',
    deineSteine: 'Dine brikker ({0})',
    passen: 'Pas',
    slfWort: 'Et ord fra dit forløb',
    slfLang: 'Et ord med mindst 5 bogstaver',
    slfNomen: 'Et navneord',
    slfVerb: 'Et udsagnsord',
    slfDeutsch: 'Den tyske betydning af et ord fra forløbet (ordet begynder med bogstavet)',
    zaehltNicht: '{0}: „{1}" tæller ikke',
    rundeAusgewertet: 'Runde {0} er tjekket.',
    rundeBuchstabe: 'Runde {0}: bogstav {1}',
    gemeinsamVon: 'Sammen: {0} af {1} {2}',
    geschafftEinheit: 'Klaret: {0} {1}!',
    vonEinheit: '{0} af {1} {2}.',
    welchesPasstDazu: 'Hvilket ord passer til?',
    welchesDasselbe: 'Hvilket ord betyder det samme?',
    bWortart: 'Ordklasse: {0}',
    bAnfang: 'Begynder med „{0}"',
    bEnde: 'Slutter på „{0}"',
    bLaenge: '{0} bogstaver',
    bLaengeWoerter: '{0} bogstaver i {1} ord',
    bGegenteil: 'Modsat: {0}',
    bErraten: 'har gættet det!',
    bNichtErraten: 'Ikke gættet denne gang.',
    bWarNicht: 'Det var ikke „{0}".',
    bDuErklaerst: 'Du forklarer: {0} ({1})',
    bWaehle: 'Vælg 2 eller 3 ledetråde og send dem',
    bAndereRaten: 'Nu gætter de andre.',
    bErklaert: '{0} forklarer.',
    bWarteHinweise: 'Venter på ledetrådene …',
    bHinweise: 'Ledetråde',
    bWelchesGemeint: 'Hvilket ord er det?',
    bErgebnis: '{0} af {1} ord gættet.',
    uiEinladungscode: 'Invitationskode',
    uiCodeHinweis: 'De andre skriver den på startsiden („Mit Code öffnen") eller i listen med spil.',
    uiDabei: 'Spillere ({0} af {1})',
    uiGetrennt: 'Forbindelsen er væk – pladsen holdes i 60 sekunder',
    uiHerausnehmen: 'Fjern {0}',
    uiSpiel: 'Spil',
    uiSchwierigkeit: 'Niveau',
    uiBerechnet: '{0} – ud fra hvad I alle kan.',
    uiGrammatik: 'Grammatik',
    uiStarten: 'Start spillet',
    uiWarteMit: 'Venter på spillere (mindst {0})',
    uiGleich: 'Snart går det løs – {0} vælger niveau og starter. Niveau: {1}',
    uiDerHost: 'værten',
    uiTeamZiel: 'Holdets mål er nået!',
    uiGutGespielt: 'Godt spillet!',
    uiGewonnen: 'Vinder: {0}',
    uiNurFuerDich: 'Kun til dig',
    uiRichtigN: '{0} rigtige',
    uiPlatz: 'Plads {0}',
    uiEinWortWieder: 'Du øver snart 1 ord igen.',
    uiWoerterWieder: 'Du øver snart {0} ord igen.',
    uiZurueck: 'Tilbage',
    uiNochmal: 'Igen',
    uiVerlassen: 'Forlad',
    uiKooperativ: 'Sammen',
    uiVersus: 'Mod hinanden',
    uiAntwortSchreiben: 'Skriv dit svar',
    uiKeineAntwort: 'Der er ikke noget svar på din skærm lige nu.',
    uiNochmalHoeren: 'Lyt igen',
    uiAbschicken: 'Send',
    uiAbschickenN: 'Send ({0})',
    sLeicht: 'Let',
    sMittel: 'Mellem',
    sSchwer: 'Svær',
    sUnmoeglich: 'Umulig',
    sLeichtText: 'Ord, som alle kan godt',
    sMittelText: 'Nogle gange gik det galt',
    sSchwerText: 'Tit forkert – godt at øve',
    sUnmoeglichText: 'Alles sværeste ord',
    ruf0: 'Godt gået!',
    ruf1: 'Hjælp?',
    ruf2: 'Det er min tur',
    ruf3: 'Super hold!',
    ruf4: 'Et øjeblik …',
    uiKoopText: 'Nå et mål sammen med andre fra dit forløb',
    uiVersusText: 'Mod hinanden – fair, med spørgsmål der passer til jer',
    uiZiffern: '6 cifre',
    uiBeitreten: 'Deltag',
    uiCodeSechs: 'Invitationskoden har seks cifre.',
    uiNachUebung: 'I kan spille sammen efter dagens øvelse.',
    uiWirdEroeffnet: 'Spillet åbnes …',
    uiStartenPersonen: 'Start · {0}–{1} spillere',
    uiCodeTitel: 'Spil sammen – invitationskode',
    uiCodeBeschreibung: 'Har nogen inviteret dig? Skriv koden og tryk Enter.',
    brauchtBeispielsatz: 'Kræver ord med en eksempelsætning.',
    brauchtVier: 'Kræver mindst fire ord.'
  },
  reise: lexikonAus(
    {
      ziel: [
        ['havet', 'Vi vil til havet.', 'Vi vil ikke til havet.', 'Tom hader sand og saltvand.', 'hav'],
        ['bjergene', 'Vi vil til bjergene.', 'Vi vil ikke til bjergene.', 'Mormor kan ikke gå op ad bakker.', 'bjerg'],
        ['en storby', 'Vi vil besøge en storby.', 'Vi vil ikke til en storby.', 'Mia hader larm og trafik.', 'by'],
        ['en sø', 'Vi vil til en sø.', 'Vi vil ikke til en sø.', 'Far synes, søer er kedelige.', 'sø'],
        ['en ø', 'Vi vil til en ø.', 'Vi vil ikke til en ø.', 'Ingen vil være på en lille ø en hel uge.', 'ø'],
        ['en bondegård', 'Vi vil bo på en bondegård.', 'Vi vil ikke bo på en bondegård.', 'Tom er bange for køer.', 'bondegård']
      ],
      verkehr: [
        ['tog', 'Vi vil køre med tog.', 'Vi vil ikke køre med tog.', 'Der er togstrejke i denne uge.', 'tog'],
        ['bus', 'Vi vil køre med bus.', 'Vi vil ikke køre med bus.', 'Mia bliver altid køresyg i bussen.', 'bus'],
        ['bil', 'Vi vil køre i bil.', 'Vi vil ikke køre i bil.', 'Vores bil er gået i stykker.', 'bil'],
        ['fly', 'Vi vil flyve.', 'Vi vil ikke flyve.', 'Far er bange for at flyve.', 'fly'],
        ['cykel', 'Vi vil cykle derhen.', 'Vi vil ikke cykle derhen.', 'Mormor kan ikke cykle.', 'cykel'],
        ['skib', 'Vi vil sejle med skib.', 'Vi vil ikke sejle med skib.', 'Mormor bliver søsyg på skibe.', 'skib']
      ],
      wetter: [
        ['sol', 'Vi vil have sol.', 'Vi vil ikke have sol.', 'Tom bliver meget hurtigt solskoldet.', 'sol', 'Hvis solen skinner,'],
        ['regn', null, 'Vi kan ikke lide regn.', 'Mia har glemt sin paraply.', 'regn', 'Hvis det regner,'],
        ['sne', 'Vi vil have sne.', 'Vi vil ikke have sne.', 'Vi har ikke varmt tøj med.', 'sne', 'Hvis det sner,'],
        ['blæst', 'Vi vil have lidt blæst.', 'Vi vil ikke have blæst.', 'Mias hat blæser altid væk.', 'vind', 'Hvis det blæser,']
      ],
      akt: [
        ['svømning', 'Vi vil svømme.', 'Mia kan ikke svømme.', 'Mia er bange for dybt vand.', 'svømme', 'vil vi svømme.'],
        ['vandring', 'Vi vil på vandretur.', 'Mormor kan ikke gå langt.', 'Mormor har ondt i knæet.', 'gå', 'vil vi på vandretur.'],
        ['ski', 'Vi vil stå på ski.', 'Tom kan ikke stå på ski.', 'Tom brækkede benet sidste vinter.', 'ski', 'vil vi stå på ski.'],
        ['museer', 'Vi vil på museum.', 'Vi vil ikke på museum.', 'Tom synes, museer er kedelige.', 'museum', 'vil vi på museum.'],
        ['shopping', 'Vi vil shoppe.', 'Vi vil ikke shoppe.', 'Vi har ingen penge til shopping.', 'butik', 'vil vi shoppe.'],
        ['sejlads', 'Vi vil sejle i sejlbåd.', 'Vi vil ikke sejle i sejlbåd.', 'Far bliver søsyg i små både.', 'sejl', 'vil vi sejle i sejlbåd.'],
        ['camping', 'Vi vil sove i telt.', 'Vi vil ikke sove i telt.', 'Mia er bange for insekter om natten.', 'telt', 'vil vi sove i telt.']
      ]
    },
    {
      preisKarte: '{0} €',
      tageKarte: '{0} dage',
      preis5: 'Vi har {0} euro.',
      preis7: 'Det skal koste mindre end {0} euro.',
      preis9: 'Vi kan højst bruge {0} euro.',
      tage5: 'Vi har kun {0} dage.',
      tage7: 'Vi vil blive mindst {0} dage.',
      tage9: 'Vi skal være hjemme igen senest efter {0} dage.'
    }
  )
}
