/** Nederlands – Spieltexte in einfacher Sprache (09.10.2026) */
import type { SprachPaket } from './typ'
import { lexikonAus } from './lexikonAus'

export const nl: SprachPaket = {
  beschreibung: {
    teammatch: 'Iedereen ziet de vraag. Het goede antwoord staat maar op één apparaat. Praat met elkaar!',
    satzbaustelle: 'Iedereen heeft een paar woorden van de zin. Zet ze samen in de goede volgorde.',
    fluchtraum: 'Antwoord samen. Na een paar goede antwoorden krijg je een letter van het geheime woord. Vind het woord en ontsnap!',
    beschreiben: 'Eén speler ziet het woord en kiest tips. De anderen raden. Dan wissel je.',
    tauziehen: 'Elk goed antwoord trekt het touw naar jouw kant. Moeilijke vragen trekken harder.',
    staffel: 'De teams antwoorden om de beurt. Wie het eerst tien vakjes vol heeft, wint.',
    bingo: 'De app roept woorden. Tik het goede vakje op je kaart aan. Een volle rij is bingo!',
    schiffe: 'Een paar goede antwoorden en je mag schieten. Vind als eerste alle schepen!',
    wortkette: 'Om de beurt een woord. Elk woord begint met de laatste letter van het vorige woord.',
    bildergeschichte: 'Het verhaal staat in woorden. Leg jullie plaatjes in de goede volgorde.',
    teammemory: 'Draai om de beurt twee kaarten om. Lukt het met weinig zetten?',
    kreuzwort: 'Iedereen heeft andere tips. Samen vullen jullie alle woorden in.',
    fehlerdetektive: 'Eén speler vindt de fout, de volgende verbetert hem.',
    uebersetzung: 'Bouw samen de vertaling – let op, niet elk stuk hoort erbij.',
    dialog: 'Twee rollen, één gesprek: vul in jouw zin het ontbrekende woord in.',
    woerterturm: 'Elk goed antwoord is een steen. Bouw de toren voordat hij wiebelt!',
    hoerkette: 'Eén speler hoort het woord en zegt het na. De anderen tikken het aan.',
    zeitstrahl: 'Leg de zinnen op de tijdlijn en noem de tijd.',
    reiseplaner: 'Iedereen ziet dezelfde reizen en heeft eigen tips. Alleen alle tips samen passen bij één reis.',
    schnapp: 'Passen woord en betekenis bij elkaar? Wie als eerste goed pakt, krijgt een punt.',
    galgen: 'Raad je woorden letter voor letter. Wie heeft er als eerste drie?',
    buzzer: 'Wie het eerst drukt, mag antwoorden. Fout? Dan is het andere team.',
    konjugation: 'De goede vorm van het werkwoord – wie heeft er als eerste acht?',
    umbau: 'Bouw de zin om – zo snel en goed mogelijk.',
    kollokation: 'Welk woord past bij de woorden ernaast?',
    auktion: 'Zet munten op „klopt" of „klopt niet".',
    domino: 'Leg de steen met het woord dat bij de open betekenis past.',
    stadtland: 'Woorden uit je cursus met de beginletter – de server controleert.',
    sniper: 'Tik als eerste de fout aan en verbeter hem. Mis? Drie seconden pauze.',
    synonyme: 'Woorden met dezelfde betekenis brengen je omhoog op de ladder.'
  },
  einzel: {
    'vok:memory': 'Vind het woord en de vertaling als paar.',
    'vok:zuordnen': 'Tik de paren zo snel mogelijk aan.',
    'vok:blitz': '60 seconden – zoveel mogelijk goede antwoorden.',
    'vok:satz': 'Zet de voorbeeldzinnen in de goede volgorde.',
    'vok:wortraten': 'Raad de letters voordat de bloem al haar blaadjes verliest.',
    'vok:kreuzwort': 'Jouw woorden in een kruiswoordpuzzel, met Duitse tips.',
    'vok:fallend': 'Typ de vertaling voordat het woord beneden is.',
    'vok:suchsel': 'Vind de woorden in het letterrooster.',
    'vok:bildwort': 'Vind het woord bij het plaatje.',
    'vok:hoeren': 'Luister en kies de goede schrijfwijze.',
    'vok:satzhoeren': 'Luister naar de zin en zet de woorden op volgorde.',
    'vok:diktat': 'Luister naar het woord en schrijf het goed.',
    'vok:satzluecke': 'Vul het goede woord in de voorbeeldzin in.',
    'vok:duell': 'Past het paar? 20 rondes tegen je beste tijd.',
    'vok:hoermemory': 'Vind bij elk geluid het goede woord.',
    'vok:richtiggehoert': '60 seconden: past het plaatje bij het woord dat je hoort?',
    'vok:buchstaben': 'Luister en leg het woord met letters.',
    'vok:hoerbingo': 'Tik de woorden aan die je hoort – een volle rij is bingo.',
    'vok:bildmemory': 'Vind plaatje en woord als paar.',
    'vok:wasfehlt': 'Onthoud de plaatjes – welk plaatje is weg?',
    'vok:aufdecken': 'Raad het woord voordat het hele plaatje te zien is.',
    'vok:wortbild': 'Tik het plaatje bij het woord aan.',
    'vok:verbtrio': 'Vind samen alle vormen van een werkwoord.',
    'vok:formenblitz': '60 seconden: welke vorm heb je gehoord?',
    'vok:bildverb': 'Noem de vormen van het werkwoord bij het plaatje.',
    'vok:muster': 'Sorteer de werkwoorden naar hun patroon.',
    'gram:fehlerjagd': 'Tik het foute woord aan en verbeter het.',
    'gram:satzbaupuzzle': 'Zet de woorden in de goede volgorde.',
    'gram:formenblitz': '60 seconden – kies de goede vorm.',
    'gram:regelzuordnen': 'Vind de regel bij de voorbeeldzin.',
    'gram:verbtrio': 'Vind samen alle vormen van een werkwoord.',
    'gram:verbblitz': '60 seconden: welke vorm heb je gehoord?',
    'gram:bildverb': 'Noem de vormen van het werkwoord bij het plaatje.',
    'gram:muster': 'Sorteer de werkwoorden naar hun patroon.',
    'gram:richtigfalsch': '60 seconden: is de zin goed?',
    'gram:formenmemory': 'Vind de grondvorm en de nieuwe vorm als paar.',
    'gram:tabellenpuzzle': 'Zet de vormen in de goede vakjes van de tabel.',
    'gram:signalwort': 'Welke tijd laat het signaalwoord zien?'
  },
  einheiten: {
    gelöst: 'opgelost',
    Fehler: 'fouten',
    s: 's',
    erraten: 'geraden',
    Punkte: 'punten',
    richtig: 'goed',
    Aufrufe: 'oproepen',
    Treffer: 'treffers',
    Glieder: 'schakels',
    Züge: 'zetten',
    Steine: 'stenen',
    Wörter: 'woorden',
    Sätze: 'zinnen',
    Münzen: 'munten',
    Sprossen: 'sporten'
  },
  texte: {
    wasBedeutet: 'Wat betekent het?',
    wieHeisst: 'Wat is het woord?',
    welchesFehlt: 'Welk woord ontbreekt?',
    richtigIst: 'Goed is: {0}',
    jemand: 'Iemand',
    duBistDran: 'Jij bent aan de beurt!',
    istDran: '{0} is aan de beurt.',
    daneben: 'mis.',
    richtig: 'Goed!',
    unentschieden: 'Gelijkspel!',
    gewonnenHat: 'Gewonnen: {0}',
    teilVon: 'Deel {0} van {1}',
    frageVon: 'Vraag {0} van {1}',
    herzen: 'samen hartjes',
    nurEinGeraet: 'Het goede antwoord staat maar op één apparaat. Wie heeft het?',
    passtNicht: '„{0}" klopt niet.',
    keineHerzen: 'Geen hartjes meer – we gaan verder.',
    tmGeschafft: 'Teamdoel gehaald: {0} van {1} opgelost!',
    tmLeer: '{0} van {1} opgelost – één keer waren de hartjes op.',
    satz: 'Zin',
    geschichte: 'Verhaal',
    zeitstrahl: 'Tijdlijn',
    vonN: '{0} {1} van {2}',
    gemeinsameReihe: 'Jullie rij',
    deineTeile: 'Jouw stukken – tik het volgende aan',
    keineTeile: 'Je hebt geen stukken meer – help de anderen.',
    nichtJedesTeil: 'Let op: niet elk stuk hoort erbij.',
    passtNochNicht: 'Dat past hier nog niet.',
    passt: 'Past!',
    fertig: 'Klaar!',
    baut: 'Bouw de zin.',
    frueherSpaeter: 'Leg de zinnen van vroeger naar later.',
    welcheZeitform: 'Welke tijd is het?',
    nenntZeitform: 'Nu noemt {0} de tijd van: „{1}"',
    richtigDoppel: 'Goed: {0}.',
    nichtGanz: 'Niet helemaal.',
    dieGeschichte: 'Het verhaal: {0}',
    uebersetzt: 'In het Duits: „{0}"',
    fehlerfreiGebaut: 'Zonder fouten gebouwd!',
    mitFehlern: 'Gelukt met {0} fouten.',
    mitEinemFehler: 'Gelukt met 1 fout.',
    codewort: 'Codewoord',
    codewortN: 'Codewoord – {0} letters',
    buchstabenGefunden: 'Gevonden letters (volgorde onbekend)',
    bisBuchstabe: 'Nog {0} goede antwoorden tot de volgende letter.',
    alleBuchstaben: 'Jullie hebben alle letters – typ het codewoord!',
    buchstabeFrei: 'heeft een letter vrijgespeeld!',
    richtigWeiter: 'goed! ({0} van {1} voor de volgende letter)',
    neueAufgabe: 'Niet helemaal – hier is een nieuwe opdracht.',
    falschesWort: 'Dat is niet het codewoord. Lees de tips nog eens!',
    entkommen: 'De deur is open! Het codewoord was „{0}" ({1}).',
    zeitAus: 'De tijd is om.',
    zeitAusWort: 'De tijd is om. Het codewoord was „{0}" ({1}).',
    gemeinsameZeit: 'Teamtijd',
    hinweise: 'Tips voor het codewoord',
    tuerOeffnen: 'Deur openen',
    wortEingeben: 'Typ het codewoord',
    fehlversuche: 'Foute pogingen: {0}',
    entkommenIn: 'Ontsnapt in {0} minuten!',
    nichtGereicht: 'Deze keer was er niet genoeg tijd.',
    hLaenge: 'Het woord heeft {0} letters.',
    hBild: 'Kijk naar het plaatje.',
    hNomen: 'Het is een zelfstandig naamwoord.',
    hVerb: 'Het is een werkwoord.',
    hAdj: 'Het is een bijvoeglijk naamwoord.',
    hAdv: 'Het is een bijwoord.',
    hLuecke: 'Het past in dit gat: {0}',
    hSynonym: 'Het betekent bijna hetzelfde als „{0}".',
    hDefinition: 'Definitie: {0} met {1} letters, lijkt op „{2}".',
    hGebrauch: 'Zo gebruik je het: {0}',
    hAufgabe: 'Het is het antwoord op deze opdracht: {0}',
    wortartNomen: 'een zelfstandig naamwoord',
    wortartVerb: 'een werkwoord',
    wortartAdj: 'een bijvoeglijk naamwoord',
    wortartAdv: 'een bijwoord',
    wortartWort: 'een woord',
    feldGefuellt: 'Vakje vol!',
    erstDieFrage: 'Jij bent aan de beurt – eerst de vraag!',
    schussLaden: 'Nog {0} goede antwoorden tot je mag schieten.',
    geladen: 'goed – nog {0} tot het schot.',
    darfSchiessen: 'mag schieten!',
    danebenAnderes: 'mis – het andere team is aan de beurt.',
    tippeFeld: 'Tik een vakje van het andere team aan.',
    treffer: 'Raak!',
    wasser: 'Water.',
    feldVon: 'Veld van {0} ({1} van {2} geraakt)',
    eureFlotte: 'Jullie vloot',
    ziehtMit: 'trekt met {0}!',
    teilRichtig: 'Deel {0} van {1} goed – ga door!',
    duZiehstLinks: 'Jij trekt naar links.',
    duZiehstRechts: 'Jij trekt naar rechts.',
    aufrufVon: 'Oproep {0} van {1}',
    nichtGerufen: 'Dat werd niet geroepen.',
    bingo: 'BINGO!',
    auchBingo: 'heeft ook bingo (plaats {0})!',
    bingoPlatz: 'Bingo – plaats {0}!',
    deinFeld: 'Jouw kaart',
    warteAndere: 'Wachten op de anderen …',
    nichtImFeld: 'Niet op mijn kaart – verder',
    bingoListe: 'Bingo: {0}',
    bingoErste: 'Eerste bingo: {0}',
    keinBingo: 'Deze keer geen bingo.',
    welchesWortSatz: 'Welk woord past?',
    rundeVon: 'Ronde {0} van {1}',
    rundeFertig: 'Ronde klaar!',
    deinePunkte: 'Jouw punten: {0}',
    abgegebenWarte: 'Verstuurd – wacht op de anderen.',
    ueberspringenLoesung: 'Overslaan (antwoord laten zien)',
    gefunden: 'Gevonden!',
    nichtGanzDoppel: 'Niet helemaal:',
    richtigKlein: 'goed!',
    wortVon: 'Woord {0} van {1}',
    satzVon: 'Zin {0} van {1}',
    karteVon: 'Kaart {0} van {1}',
    reiseVon: 'Reis {0} van {1}',
    aussageVon: 'Bewering {0} van {1}',
    faengtMit: 'Het begint met „{0}".',
    passtNichtKlein: 'past niet.',
    wortPasst: '{0} past!',
    kette: 'Ketting ({0} van {1})',
    neuesGlied: 'Nieuwe schakel!',
    ketteHaelt: 'De ketting houdt toch – ga door!',
    ketteErgebnis: 'Jullie ketting heeft {0} schakels.',
    paarGefunden: 'Paar gevonden!',
    keinPaar: 'Geen paar.',
    memoryStand: 'Zetten: {0} · Paren: {1} van {2}',
    memoryDran: 'Jij bent aan de beurt: draai twee kaarten om.',
    memoryErgebnis: 'Alle paren gevonden in {0} zetten.',
    gemeinsamesRaetsel: 'Samen puzzelen',
    woerterGeloest: 'Jouw woorden zijn opgelost – help elkaar!',
    kreuzErgebnis: 'Puzzel opgelost met {0} foute pogingen.',
    wieRichtig: 'Hoe is „{0}" goed?',
    fehlerGefunden: 'heeft de fout gevonden: „{0}".',
    istRichtigWort: '„{0}" is goed.',
    fallGeloest: 'Zaak opgelost!',
    hatUebersprungen: 'heeft overgeslagen.',
    satzRot: 'De zin – het rode woord is fout',
    deinSatz: 'Jouw zin: welk woord is fout? Tik het aan.',
    duVerbesserst: '{0} heeft de fout gevonden – jij verbetert hem:',
    verbessertDeinen: 'Gevonden! Nu verbetert {0} jouw zin.',
    nochFaelle: 'Nog {0} zaken in deze ronde.',
    nochEinFall: 'Nog 1 zaak in deze ronde.',
    faelleErgebnis: '{0} zaken gedaan, {1} foute tikken.',
    fehlerEntdeckt: 'heeft de fout ontdekt!',
    danebenPause: 'mis – 3 seconden pauze.',
    niemandGefunden: 'Niemand heeft hem gevonden.',
    verbesserungFalsch: 'De verbetering klopt niet.',
    uebersprungen: 'Overgeslagen.',
    pause: 'Pauze',
    tippeFalsches: 'Tik het foute woord aan!',
    verbessert: '{0} verbetert.',
    findeNicht: 'Ik vind het niet – overslaan',
    naechsterSatz: 'Door naar de volgende zin.',
    deineRolle: 'Jouw rol: {0}',
    bisherGespraech: 'Het gesprek tot nu toe',
    rolleFehlt: 'Rol {0}: welk woord ontbreekt?',
    rolleSpricht: 'Rol {0} zegt: {1}',
    dialogErgebnis: '{0} van {1} zinnen goed gespeeld.',
    richtigVerstanden: 'goed verstaan!',
    diesmalNicht: 'Deze keer niet.',
    warEsNicht: '– dat was het niet.',
    ketteGlieder: 'Ketting: {0} schakels',
    duHoerst: 'Jij hoort het woord. Zeg het hardop – de anderen tikken het aan.',
    sprichtVor: '{0} zegt het woord voor jou.',
    welchesGehoert: 'Welk woord heb je gehoord?',
    hoerErgebnis: '{0} van {1} woorden goed doorgegeven.',
    eureReise: 'Dat is jullie reis!',
    reisePasstNicht: 'Deze reis past niet bij alle tips.',
    deineHinweise: 'Jouw tips (alleen jij ziet ze)',
    welcheReise: 'Welke reis is het? Overleg!',
    reiseErgebnis: '{0} reizen gepland, {1} foute pogingen.',
    rpReiseN: 'Reis {0}',
    rpTippen: 'Tik een reis aan om hem voor te stellen.',
    rpVorschlag: '{0} stelt reis {1} voor.',
    rpZustimmen: 'Akkoord!',
    rpWarteZustimmung: 'Wacht tot de anderen akkoord zijn …',
    rpZustimmungen: 'Akkoord: {0} van {1}',
    rpPasstNichtWeil: 'Reis {0} past niet: „{1}" ({2})',
    rpZeitAus: 'De tijd is om – de goede reis was reis {0}.',
    rpZusammen: 'Alleen alle tips samen passen bij één reis. Lees ze aan elkaar voor!',
    schnapp: 'Hebbes!',
    zuFrueh: 'pakte te vroeg.',
    passteNicht: 'Goed, dat paste niet.',
    schnappPasst: 'Pak! Past!',
    passtNichtKnopf: 'Past niet',
    wortGeschafft: 'heeft een woord!',
    neuesWort: 'Nieuw woord.',
    gesucht: 'Zoek het woord voor: {0}',
    fehlerVonMax: 'Fouten: {0} van {1}',
    fuersTeam: '+{0} voor het team!',
    auchDaneben: 'ook mis.',
    buzzer: 'Druk!',
    antwortet: '{0} antwoordt.',
    anderesTeamAntwortet: 'Het andere team antwoordt.',
    aussageStimmte: 'De bewering klopte.',
    aussageStimmteNicht: 'De bewering klopte niet.',
    deineMuenzen: 'Jouw munten: {0}',
    gebotAb: 'Inzet gedaan – wacht op de anderen.',
    aufStimmt: '{0} op „klopt"',
    aufStimmtNicht: '{0} op „klopt niet"',
    steinDoch: 'had de goede steen toch.',
    steinPasstNicht: 'Die steen past niet.',
    legtAn: 'legt aan!',
    offen: 'Open: {0}',
    dominoDran: 'Jij bent aan de beurt: leg de steen met het goede woord – of pas.',
    deineSteine: 'Jouw stenen ({0})',
    passen: 'Passen',
    slfWort: 'Een woord uit je cursus',
    slfLang: 'Een woord met minstens 5 letters',
    slfNomen: 'Een zelfstandig naamwoord',
    slfVerb: 'Een werkwoord',
    slfDeutsch: 'De Duitse betekenis van een cursuswoord (het cursuswoord begint met de letter)',
    zaehltNicht: '{0}: „{1}" telt niet',
    rundeAusgewertet: 'Ronde {0} nagekeken.',
    rundeBuchstabe: 'Ronde {0}: letter {1}',
    gemeinsamVon: 'Samen: {0} van {1} {2}',
    geschafftEinheit: 'Gelukt: {0} {1}!',
    vonEinheit: '{0} van {1} {2}.',
    welchesPasstDazu: 'Welk woord past erbij?',
    welchesDasselbe: 'Welk woord betekent hetzelfde?',
    bWortart: 'Woordsoort: {0}',
    bAnfang: 'Begint met „{0}"',
    bEnde: 'Eindigt op „{0}"',
    bLaenge: '{0} letters',
    bLaengeWoerter: '{0} letters in {1} woorden',
    bGegenteil: 'Tegenovergestelde: {0}',
    bErraten: 'heeft het geraden!',
    bNichtErraten: 'Deze keer niet geraden.',
    bWarNicht: 'Het was niet „{0}".',
    bDuErklaerst: 'Jij legt uit: {0} ({1})',
    bWaehle: 'Kies 2 of 3 tips en stuur ze',
    bAndereRaten: 'Nu raden de anderen.',
    bErklaert: '{0} legt uit.',
    bWarteHinweise: 'Wachten op de tips …',
    bHinweise: 'Tips',
    bWelchesGemeint: 'Welk woord is het?',
    bErgebnis: '{0} van {1} woorden geraden.',
    uiEinladungscode: 'Uitnodigingscode',
    uiCodeHinweis: 'De anderen typen hem op de startpagina („Mit Code öffnen") of in de lijst met spellen.',
    uiDabei: 'Spelers ({0} van {1})',
    uiGetrennt: 'Verbinding weg – de plaats blijft 60 seconden vrij',
    uiHerausnehmen: '{0} verwijderen',
    uiSpiel: 'Spel',
    uiSchwierigkeit: 'Niveau',
    uiBerechnet: '{0} – berekend uit wat jullie allemaal weten.',
    uiGrammatik: 'Grammatica',
    uiStarten: 'Spel starten',
    uiWarteMit: 'Wachten op spelers (minstens {0})',
    uiGleich: 'Zo begint het – {0} kiest het niveau en start. Niveau: {1}',
    uiDerHost: 'de host',
    uiTeamZiel: 'Teamdoel gehaald!',
    uiGutGespielt: 'Goed gespeeld!',
    uiGewonnen: 'Gewonnen: {0}',
    uiNurFuerDich: 'Alleen voor jou',
    uiRichtigN: '{0} goed',
    uiPlatz: 'Plaats {0}',
    uiEinWortWieder: 'Je oefent binnenkort 1 woord opnieuw.',
    uiWoerterWieder: 'Je oefent binnenkort {0} woorden opnieuw.',
    uiZurueck: 'Terug',
    uiNochmal: 'Nog een keer',
    uiVerlassen: 'Verlaten',
    uiKooperativ: 'Samen',
    uiVersus: 'Tegen elkaar',
    uiAntwortSchreiben: 'Typ je antwoord',
    uiKeineAntwort: 'Op jouw apparaat staat nu geen antwoord.',
    uiNochmalHoeren: 'Nog eens luisteren',
    uiAbschicken: 'Versturen',
    uiAbschickenN: 'Versturen ({0})',
    sLeicht: 'Makkelijk',
    sMittel: 'Gemiddeld',
    sSchwer: 'Moeilijk',
    sUnmoeglich: 'Onmogelijk',
    sLeichtText: 'Woorden die iedereen goed kent',
    sMittelText: 'Soms ging er iets mis',
    sSchwerText: 'Vaak fout – goed om te oefenen',
    sUnmoeglichText: 'De moeilijkste woorden van iedereen',
    ruf0: 'Goed gedaan!',
    ruf1: 'Hulp?',
    ruf2: 'Ik ben aan de beurt',
    ruf3: 'Super team!',
    ruf4: 'Momentje …',
    uiKoopText: 'Samen met anderen uit je cursus een doel halen',
    uiVersusText: 'Tegen elkaar – eerlijk, met vragen die bij jullie passen',
    uiZiffern: '6 cijfers',
    uiBeitreten: 'Meedoen',
    uiCodeSechs: 'De uitnodigingscode heeft zes cijfers.',
    uiNachUebung: 'Samen spelen kan na de oefening van vandaag.',
    uiWirdEroeffnet: 'Spel wordt geopend …',
    uiStartenPersonen: 'Starten · {0}–{1} spelers',
    uiCodeTitel: 'Samen spelen – uitnodigingscode',
    uiCodeBeschreibung: 'Heeft iemand je uitgenodigd? Typ de code en druk op Enter.',
    brauchtBeispielsatz: 'Hiervoor zijn woorden met een voorbeeldzin nodig.',
    brauchtVier: 'Hiervoor zijn minstens vier woorden nodig.'
  },
  reise: lexikonAus(
    {
      ziel: [
        ['de zee', 'We willen naar de zee.', 'We willen niet naar de zee.', 'Tom haat zand en zout water.', 'zee'],
        ['de bergen', 'We willen naar de bergen.', 'We willen niet naar de bergen.', 'Oma kan geen steile heuvels op.', 'berg'],
        ['een grote stad', 'We willen een grote stad bezoeken.', 'We willen niet naar een grote stad.', 'Mia haat lawaai en verkeer.', 'stad'],
        ['een meer', 'We willen naar een meer.', 'We willen niet naar een meer.', 'Papa vindt meren saai.', 'meer'],
        ['een eiland', 'We willen naar een eiland.', 'We willen niet naar een eiland.', 'Niemand wil een week op een klein eiland zitten.', 'eiland'],
        ['een boerderij', 'We willen op een boerderij slapen.', 'We willen niet op een boerderij slapen.', 'Tom is bang voor koeien.', 'boerderij']
      ],
      verkehr: [
        ['de trein', 'We willen met de trein.', 'We willen niet met de trein.', 'Deze week staken de treinen.', 'trein'],
        ['de bus', 'We willen met de bus.', 'We willen niet met de bus.', 'Mia wordt altijd misselijk in de bus.', 'bus'],
        ['de auto', 'We willen met de auto.', 'We willen niet met de auto.', 'Onze auto is kapot.', 'auto'],
        ['het vliegtuig', 'We willen vliegen.', 'We willen niet vliegen.', 'Papa is bang om te vliegen.', 'vliegtuig'],
        ['de fiets', 'We willen met de fiets.', 'We willen niet met de fiets.', 'Oma kan niet fietsen.', 'fiets'],
        ['het schip', 'We willen met het schip.', 'We willen niet met het schip.', 'Oma wordt zeeziek op boten.', 'schip']
      ],
      wetter: [
        ['zon', 'We willen zon.', 'We willen geen zon.', 'Tom verbrandt heel snel.', 'zon', 'Als de zon schijnt,'],
        ['regen', null, 'We houden niet van regen.', 'Mia is haar paraplu vergeten.', 'regen', 'Als het regent,'],
        ['sneeuw', 'We willen sneeuw.', 'We willen geen sneeuw.', 'We hebben geen warme kleren bij ons.', 'sneeuw', 'Als het sneeuwt,'],
        ['wind', 'We willen een beetje wind.', 'We willen geen wind.', 'De hoed van Mia waait altijd weg.', 'wind', 'Als het waait,']
      ],
      akt: [
        ['zwemmen', 'We willen zwemmen.', 'Mia kan niet zwemmen.', 'Mia is bang voor diep water.', 'zwemmen', 'willen we zwemmen.'],
        ['wandelen', 'We willen wandelen.', 'Oma kan niet ver lopen.', 'Oma heeft pijn aan haar knie.', 'wandelen', 'willen we wandelen.'],
        ['skiën', 'We willen skiën.', 'Tom kan niet skiën.', 'Tom brak vorige winter zijn been.', 'ski', 'willen we skiën.'],
        ['musea', 'We willen een museum bezoeken.', 'We willen geen museum bezoeken.', 'Tom vindt musea saai.', 'museum', 'willen we een museum bezoeken.'],
        ['winkelen', 'We willen winkelen.', 'We willen niet winkelen.', 'We hebben geen geld om te winkelen.', 'winkel', 'willen we winkelen.'],
        ['zeilen', 'We willen zeilen.', 'We willen niet zeilen.', 'Papa wordt zeeziek op kleine boten.', 'zeil', 'willen we zeilen.'],
        ['kamperen', 'We willen in een tent slapen.', 'We willen niet in een tent slapen.', "Mia is 's nachts bang voor insecten.", 'tent', 'willen we in een tent slapen.']
      ]
    },
    {
      preisKarte: '€ {0}',
      tageKarte: '{0} dagen',
      preis5: 'We hebben {0} euro.',
      preis7: 'Het moet goedkoper zijn dan {0} euro.',
      preis9: 'We kunnen hoogstens {0} euro uitgeven.',
      tage5: 'We hebben maar {0} dagen.',
      tage7: 'We willen minstens {0} dagen blijven.',
      tage9: 'Na uiterlijk {0} dagen moeten we weer thuis zijn.'
    }
  )
}
