/** Polski – Spielnamen und Spieltexte in einfacher Sprache (09.10.2026) */
import type { SprachPaket } from './typ'
import { lexikonAus } from './lexikonAus'

export const pl: SprachPaket = {
  namen: {
    'mehr:teammatch': 'Mecz drużynowy',
    'mehr:satzbaustelle': 'Budowa zdań',
    'mehr:fluchtraum': 'Ucieczka',
    'mehr:beschreiben': 'Opisz i zgadnij',
    'mehr:tauziehen': 'Przeciąganie liny',
    'mehr:staffel': 'Sztafeta form',
    'mehr:bingo': 'Bingo słówek',
    'mehr:schiffe': 'Statki',
    'mehr:wortkette': 'Łańcuch słów',
    'mehr:bildergeschichte': 'Historia z obrazków',
    'mehr:teammemory': 'Memory drużynowe',
    'mehr:kreuzwort': 'Wspólna krzyżówka',
    'mehr:fehlerdetektive': 'Detektywi błędów',
    'mehr:uebersetzung': 'Puzzle tłumaczenia',
    'mehr:dialog': 'Teatr dialogów',
    'mehr:woerterturm': 'Wieża słów',
    'mehr:hoerkette': 'Łańcuch słuchu',
    'mehr:zeitstrahl': 'Oś czasu',
    'mehr:reiseplaner': 'Planer podróży',
    'mehr:schnapp': 'Łap!',
    'mehr:galgen': 'Pojedynek – wisielec',
    'mehr:buzzer': 'Drużynowy przycisk',
    'mehr:konjugation': 'Pojedynek odmiany',
    'mehr:umbau': 'Wyścig przekształceń',
    'mehr:kollokation': 'Pojedynek kolokacji',
    'mehr:auktion': 'Aukcja słów',
    'mehr:domino': 'Domino słówek',
    'mehr:stadtland': 'Państwa-miasta',
    'mehr:sniper': 'Snajper błędów',
    'mehr:synonyme': 'Drabina synonimów',
    'vok:memory': 'Memory',
    'vok:zuordnen': 'Dopasuj na czas',
    'vok:blitz': 'Runda błyskawiczna',
    'vok:satz': 'Puzzle zdań',
    'vok:wortraten': 'Zgadnij słowo',
    'vok:kreuzwort': 'Krzyżówka',
    'vok:fallend': 'Spadające słowa',
    'vok:suchsel': 'Wykreślanka',
    'vok:bildwort': 'Zagadka obrazkowa',
    'vok:hoeren': 'Quiz ze słuchu',
    'vok:satzhoeren': 'Dyktando zdań',
    'vok:diktat': 'Słuchaj i pisz',
    'vok:satzluecke': 'Uzupełnij lukę',
    'vok:duell': 'Pojedynek słów',
    'vok:hoermemory': 'Memory ze słuchu',
    'vok:richtiggehoert': 'Dobrze słyszysz?',
    'vok:buchstaben': 'Puzzle z liter',
    'vok:hoerbingo': 'Bingo ze słuchu',
    'vok:bildmemory': 'Memory obrazkowe',
    'vok:wasfehlt': 'Czego brakuje?',
    'vok:aufdecken': 'Odkryj obrazek',
    'vok:wortbild': 'Słowo → obrazek',
    'vok:verbtrio': 'Trio form',
    'vok:formenblitz': 'Błysk form',
    'vok:bildverb': 'Czasownik z obrazka',
    'vok:muster': 'Sortuj wzory',
    'gram:fehlerjagd': 'Znajdź błąd',
    'gram:satzbaupuzzle': 'Zbuduj zdanie',
    'gram:formenblitz': 'Błysk form',
    'gram:regelzuordnen': 'Dopasuj regułę',
    'gram:verbtrio': 'Trio form',
    'gram:verbblitz': 'Błysk form',
    'gram:bildverb': 'Czasownik z obrazka',
    'gram:muster': 'Sortuj wzory',
    'gram:richtigfalsch': 'Dobrze czy źle?',
    'gram:formenmemory': 'Memory form',
    'gram:tabellenpuzzle': 'Puzzle tabeli',
    'gram:signalwort': 'Słowa sygnałowe'
  },
  beschreibung: {
    teammatch: 'Wszyscy widzą pytanie. Dobra odpowiedź jest tylko na jednym urządzeniu. Rozmawiajcie!',
    satzbaustelle: 'Każdy ma kilka słów zdania. Ułóżcie je razem w dobrej kolejności.',
    fluchtraum: 'Odpowiadajcie razem. Za kilka dobrych odpowiedzi dostajecie literę tajnego słowa. Znajdźcie słowo i uciekajcie!',
    beschreiben: 'Jedna osoba widzi słowo i wybiera podpowiedzi. Inni zgadują. Potem zmiana.',
    tauziehen: 'Każda dobra odpowiedź ciągnie linę na twoją stronę. Trudne pytania ciągną mocniej.',
    staffel: 'Drużyny odpowiadają na zmianę. Kto pierwszy wypełni dziesięć pól, wygrywa.',
    bingo: 'Aplikacja podaje słowa. Dotknij dobrego pola na swojej karcie. Pełny rząd to bingo!',
    schiffe: 'Kilka dobrych odpowiedzi i możesz strzelać. Znajdź pierwszy wszystkie statki!',
    wortkette: 'Na zmianę jedno słowo. Każde słowo zaczyna się ostatnią literą poprzedniego.',
    bildergeschichte: 'Historia jest napisana słowami. Ułóżcie obrazki w dobrej kolejności.',
    teammemory: 'Na zmianę odkrywajcie dwie karty. Uda się w kilku ruchach?',
    kreuzwort: 'Każdy ma inne podpowiedzi. Razem wpiszecie wszystkie słowa.',
    fehlerdetektive: 'Jedna osoba znajduje błąd, następna go poprawia.',
    uebersetzung: 'Zbudujcie razem tłumaczenie – uwaga, nie każdy kawałek pasuje.',
    dialog: 'Dwie role, jedna rozmowa: wstaw w swoją kwestię brakujące słowo.',
    woerterturm: 'Każda dobra odpowiedź to klocek. Zbudujcie wieżę, zanim się zachwieje!',
    hoerkette: 'Jedna osoba słyszy słowo i je powtarza. Inni go dotykają.',
    zeitstrahl: 'Ułóżcie zdania na osi czasu i nazwijcie czas.',
    reiseplaner: 'Wszyscy widzą te same podróże, każdy ma swoje podpowiedzi. Tylko wszystkie podpowiedzi razem pasują do jednej podróży.',
    schnapp: 'Słowo i znaczenie pasują? Kto pierwszy dobrze złapie, dostaje punkt.',
    galgen: 'Zgaduj swoje słowa litera po literze. Kto pierwszy zgadnie trzy?',
    buzzer: 'Kto pierwszy naciśnie, odpowiada. Źle? Wtedy odpowiada druga drużyna.',
    konjugation: 'Dobra forma czasownika – kto pierwszy ma osiem?',
    umbau: 'Przekształć zdanie – szybko i dobrze.',
    kollokation: 'Które słowo pasuje do słów obok?',
    auktion: 'Stawiaj monety na „prawda" albo „fałsz".',
    domino: 'Połóż kamień ze słowem, które pasuje do otwartego znaczenia.',
    stadtland: 'Słowa z twojego kursu na daną literę – serwer sprawdza.',
    sniper: 'Pierwszy dotknij błędu i popraw go. Pudło? Trzy sekundy przerwy.',
    synonyme: 'Słowa o tym samym znaczeniu prowadzą cię w górę drabiny.'
  },
  einzel: {
    'vok:memory': 'Znajdź słowo i tłumaczenie jako parę.',
    'vok:zuordnen': 'Dotykaj par jak najszybciej.',
    'vok:blitz': '60 sekund – jak najwięcej dobrych odpowiedzi.',
    'vok:satz': 'Ułóż przykładowe zdania w dobrej kolejności.',
    'vok:wortraten': 'Zgadnij litery, zanim kwiatek straci wszystkie liście.',
    'vok:kreuzwort': 'Twoje słowa w krzyżówce, z niemieckimi podpowiedziami.',
    'vok:fallend': 'Wpisz tłumaczenie, zanim słowo spadnie na dół.',
    'vok:suchsel': 'Znajdź słowa w siatce liter.',
    'vok:bildwort': 'Znajdź słowo do obrazka.',
    'vok:hoeren': 'Słuchaj i wybierz dobrą pisownię.',
    'vok:satzhoeren': 'Posłuchaj zdania i ułóż słowa.',
    'vok:diktat': 'Posłuchaj słowa i napisz je dobrze.',
    'vok:satzluecke': 'Wstaw dobre słowo do przykładowego zdania.',
    'vok:duell': 'Para pasuje? 20 rund przeciw twojemu rekordowi.',
    'vok:hoermemory': 'Znajdź słowo do każdego dźwięku.',
    'vok:richtiggehoert': '60 sekund: obrazek pasuje do słowa, które słyszysz?',
    'vok:buchstaben': 'Słuchaj i ułóż słowo z liter.',
    'vok:hoerbingo': 'Dotykaj słów, które słyszysz – pełny rząd to bingo.',
    'vok:bildmemory': 'Znajdź obrazek i słowo jako parę.',
    'vok:wasfehlt': 'Zapamiętaj obrazki – którego brakuje?',
    'vok:aufdecken': 'Zgadnij słowo, zanim cały obrazek będzie widać.',
    'vok:wortbild': 'Dotknij obrazka do słowa.',
    'vok:verbtrio': 'Znajdź razem wszystkie formy czasownika.',
    'vok:formenblitz': '60 sekund: jaką formę słyszysz?',
    'vok:bildverb': 'Podaj formy czasownika do obrazka.',
    'vok:muster': 'Posortuj czasowniki według wzoru.',
    'gram:fehlerjagd': 'Dotknij złego słowa i popraw je.',
    'gram:satzbaupuzzle': 'Ułóż słowa w dobrej kolejności.',
    'gram:formenblitz': '60 sekund – wybierz dobrą formę.',
    'gram:regelzuordnen': 'Znajdź regułę do przykładu.',
    'gram:verbtrio': 'Znajdź razem wszystkie formy czasownika.',
    'gram:verbblitz': '60 sekund: jaką formę słyszysz?',
    'gram:bildverb': 'Podaj formy czasownika do obrazka.',
    'gram:muster': 'Posortuj czasowniki według wzoru.',
    'gram:richtigfalsch': '60 sekund: czy zdanie jest dobre?',
    'gram:formenmemory': 'Znajdź formę podstawową i nową jako parę.',
    'gram:tabellenpuzzle': 'Wstaw formy w dobre pola tabeli.',
    'gram:signalwort': 'Jaki czas pokazuje słowo sygnałowe?'
  },
  einheiten: {
    gelöst: 'rozwiązane',
    Fehler: 'błędy',
    s: 's',
    erraten: 'zgadnięte',
    Punkte: 'punkty',
    richtig: 'dobrze',
    Aufrufe: 'wywołania',
    Treffer: 'trafienia',
    Glieder: 'ogniwa',
    Züge: 'ruchy',
    Steine: 'klocki',
    Wörter: 'słowa',
    Sätze: 'zdania',
    Münzen: 'monety',
    Sprossen: 'szczeble'
  },
  texte: {
    wasBedeutet: 'Co to znaczy?',
    wieHeisst: 'Jakie to słowo?',
    welchesFehlt: 'Którego słowa brakuje?',
    richtigIst: 'Dobrze: {0}',
    jemand: 'Ktoś',
    duBistDran: 'Twoja kolej!',
    istDran: 'Kolej: {0}.',
    daneben: 'pudło.',
    richtig: 'Dobrze!',
    unentschieden: 'Remis!',
    gewonnenHat: 'Wygrywa: {0}',
    teilVon: 'Część {0} z {1}',
    frageVon: 'Pytanie {0} z {1}',
    herzen: 'wspólne serca',
    nurEinGeraet: 'Dobra odpowiedź jest tylko na jednym urządzeniu. Kto ją ma?',
    passtNicht: '„{0}" nie pasuje.',
    keineHerzen: 'Nie ma już serc – gramy dalej.',
    tmGeschafft: 'Cel drużyny osiągnięty: {0} z {1} rozwiązane!',
    tmLeer: '{0} z {1} rozwiązane – raz skończyły się serca.',
    satz: 'Zdanie',
    geschichte: 'Historia',
    zeitstrahl: 'Oś czasu',
    vonN: '{0} {1} z {2}',
    gemeinsameReihe: 'Wasz wspólny rząd',
    deineTeile: 'Twoje kawałki – dotknij następnego',
    keineTeile: 'Nie masz już kawałków – pomagaj innym.',
    nichtJedesTeil: 'Uwaga: nie każdy kawałek pasuje.',
    passtNochNicht: 'To jeszcze tu nie pasuje.',
    passt: 'Pasuje!',
    fertig: 'Gotowe!',
    baut: 'Zbudujcie zdanie.',
    frueherSpaeter: 'Ułóżcie zdania od wcześniej do później.',
    welcheZeitform: 'Jaki to czas?',
    nenntZeitform: 'Teraz {0} podaje czas zdania: „{1}"',
    richtigDoppel: 'Dobrze: {0}.',
    nichtGanz: 'Nie całkiem.',
    dieGeschichte: 'Historia: {0}',
    uebersetzt: 'Po niemiecku: „{0}"',
    fehlerfreiGebaut: 'Zbudowane bez błędu!',
    mitFehlern: 'Gotowe, błędy: {0}.',
    mitEinemFehler: 'Gotowe, 1 błąd.',
    codewort: 'Hasło',
    codewortN: 'Hasło – {0} liter',
    buchstabenGefunden: 'Znalezione litery (kolejność nieznana)',
    bisBuchstabe: 'Jeszcze {0} dobrych odpowiedzi do następnej litery.',
    alleBuchstaben: 'Macie wszystkie litery – wpiszcie hasło!',
    buchstabeFrei: 'odkrywa literę!',
    richtigWeiter: 'dobrze! ({0} z {1} do następnej litery)',
    neueAufgabe: 'Nie całkiem – oto nowe zadanie.',
    falschesWort: 'To nie jest hasło. Przeczytajcie jeszcze raz podpowiedzi!',
    entkommen: 'Drzwi są otwarte! Hasło to „{0}" ({1}).',
    zeitAus: 'Czas minął.',
    zeitAusWort: 'Czas minął. Hasło to „{0}" ({1}).',
    gemeinsameZeit: 'Wspólny czas',
    hinweise: 'Podpowiedzi do hasła',
    tuerOeffnen: 'Otwórz drzwi',
    wortEingeben: 'Wpisz hasło',
    fehlversuche: 'Złe próby: {0}',
    entkommenIn: 'Ucieczka w {0} minut!',
    nichtGereicht: 'Tym razem zabrakło czasu.',
    hLaenge: 'Słowo ma {0} liter.',
    hBild: 'Popatrzcie na obrazek.',
    hNomen: 'To rzeczownik.',
    hVerb: 'To czasownik.',
    hAdj: 'To przymiotnik.',
    hAdv: 'To przysłówek.',
    hLuecke: 'Pasuje do tej luki: {0}',
    hSynonym: 'Znaczy prawie to samo co „{0}".',
    hDefinition: 'Definicja: {0}, {1} liter, podobne do „{2}".',
    hGebrauch: 'Tak się go używa: {0}',
    hAufgabe: 'To odpowiedź na zadanie: {0}',
    wortartNomen: 'rzeczownik',
    wortartVerb: 'czasownik',
    wortartAdj: 'przymiotnik',
    wortartAdv: 'przysłówek',
    wortartWort: 'słowo',
    feldGefuellt: 'Pole wypełnione!',
    erstDieFrage: 'Twoja kolej – najpierw pytanie!',
    schussLaden: 'Jeszcze {0} dobrych odpowiedzi do strzału.',
    geladen: 'dobrze – jeszcze {0} do strzału.',
    darfSchiessen: 'może strzelać!',
    danebenAnderes: 'pudło – kolej drugiej drużyny.',
    tippeFeld: 'Dotknij pola drugiej drużyny.',
    treffer: 'Trafiony!',
    wasser: 'Pudło.',
    feldVon: 'Plansza: {0} ({1} z {2} trafione)',
    eureFlotte: 'Wasza flota',
    ziehtMit: 'ciągnie z siłą {0}!',
    teilRichtig: 'Część {0} z {1} dobrze – dalej!',
    duZiehstLinks: 'Ciągniesz w lewo.',
    duZiehstRechts: 'Ciągniesz w prawo.',
    aufrufVon: 'Wywołanie {0} z {1}',
    nichtGerufen: 'Tego nie wywołano.',
    bingo: 'BINGO!',
    auchBingo: 'też ma bingo (miejsce {0})!',
    bingoPlatz: 'Bingo – miejsce {0}!',
    deinFeld: 'Twoja karta',
    warteAndere: 'Czekamy na innych …',
    nichtImFeld: 'Nie ma na mojej karcie – dalej',
    bingoListe: 'Bingo: {0}',
    bingoErste: 'Pierwsze bingo: {0}',
    keinBingo: 'Tym razem bez bingo.',
    welchesWortSatz: 'Które słowo pasuje?',
    rundeVon: 'Runda {0} z {1}',
    rundeFertig: 'Runda skończona!',
    deinePunkte: 'Twoje punkty: {0}',
    abgegebenWarte: 'Wysłane – czekaj na innych.',
    ueberspringenLoesung: 'Pomiń (pokaż odpowiedź)',
    gefunden: 'Znalezione!',
    nichtGanzDoppel: 'Nie całkiem:',
    richtigKlein: 'dobrze!',
    wortVon: 'Słowo {0} z {1}',
    satzVon: 'Zdanie {0} z {1}',
    karteVon: 'Karta {0} z {1}',
    reiseVon: 'Podróż {0} z {1}',
    aussageVon: 'Zdanie {0} z {1}',
    faengtMit: 'Zaczyna się na „{0}".',
    passtNichtKlein: 'nie pasuje.',
    wortPasst: '{0} pasuje!',
    kette: 'Łańcuch ({0} z {1})',
    neuesGlied: 'Nowe ogniwo!',
    ketteHaelt: 'Łańcuch i tak się trzyma – dalej!',
    ketteErgebnis: 'Wasz łańcuch ma {0} ogniw.',
    paarGefunden: 'Para znaleziona!',
    keinPaar: 'To nie para.',
    memoryStand: 'Ruchy: {0} · Pary: {1} z {2}',
    memoryDran: 'Twoja kolej: odkryj dwie karty.',
    memoryErgebnis: 'Wszystkie pary w {0} ruchach.',
    gemeinsamesRaetsel: 'Wspólna krzyżówka',
    woerterGeloest: 'Twoje słowa są rozwiązane – pomagajcie sobie!',
    kreuzErgebnis: 'Krzyżówka rozwiązana, złe próby: {0}.',
    wieRichtig: 'Jak dobrze brzmi „{0}"?',
    fehlerGefunden: 'znajduje błąd: „{0}".',
    istRichtigWort: '„{0}" jest dobrze.',
    fallGeloest: 'Sprawa rozwiązana!',
    hatUebersprungen: 'pomija.',
    satzRot: 'Zdanie – czerwone słowo jest złe',
    deinSatz: 'Twoje zdanie: które słowo jest złe? Dotknij go.',
    duVerbesserst: '{0} znalazł(a) błąd – ty go poprawiasz:',
    verbessertDeinen: 'Znalezione! Teraz {0} poprawia twoje zdanie.',
    nochFaelle: 'Jeszcze {0} sprawy w tej rundzie.',
    nochEinFall: 'Jeszcze 1 sprawa w tej rundzie.',
    faelleErgebnis: 'Sprawy: {0}, złe dotknięcia: {1}.',
    fehlerEntdeckt: 'odkrywa błąd!',
    danebenPause: 'pudło – 3 sekundy przerwy.',
    niemandGefunden: 'Nikt go nie znalazł.',
    verbesserungFalsch: 'Poprawka jest zła.',
    uebersprungen: 'Pominięte.',
    pause: 'Przerwa',
    tippeFalsches: 'Dotknij złego słowa!',
    verbessert: '{0} poprawia.',
    findeNicht: 'Nie widzę – pomiń',
    naechsterSatz: 'Dalej do następnego zdania.',
    deineRolle: 'Twoja rola: {0}',
    bisherGespraech: 'Rozmowa do tej pory',
    rolleFehlt: 'Rola {0}: którego słowa brakuje?',
    rolleSpricht: 'Rola {0} mówi: {1}',
    dialogErgebnis: '{0} z {1} kwestii dobrze.',
    richtigVerstanden: 'dobrze zrozumiał(a)!',
    diesmalNicht: 'Tym razem nie.',
    warEsNicht: '– to nie to.',
    ketteGlieder: 'Łańcuch: {0} ogniw',
    duHoerst: 'Słyszysz słowo. Powiedz je głośno – inni go dotykają.',
    sprichtVor: '{0} mówi ci słowo.',
    welchesGehoert: 'Jakie słowo słyszysz?',
    hoerErgebnis: '{0} z {1} słów dobrze przekazanych.',
    eureReise: 'To wasza podróż!',
    reisePasstNicht: 'Ta podróż nie pasuje do wszystkich podpowiedzi.',
    deineHinweise: 'Twoje podpowiedzi (widzisz tylko ty)',
    welcheReise: 'Która to podróż? Rozmawiajcie!',
    reiseErgebnis: 'Podróże: {0}, złe próby: {1}.',
    rpReiseN: 'Podróż {0}',
    rpTippen: 'Dotknijcie podróży, żeby ją zaproponować.',
    rpVorschlag: '{0} proponuje podróż {1}.',
    rpZustimmen: 'Zgoda!',
    rpWarteZustimmung: 'Czekaj, aż inni się zgodzą …',
    rpZustimmungen: 'Zgoda: {0} z {1}',
    rpPasstNichtWeil: 'Podróż {0} nie pasuje: „{1}" ({2})',
    rpZeitAus: 'Czas minął – dobra podróż to {0}.',
    rpZusammen: 'Tylko wszystkie podpowiedzi razem pasują do jednej podróży. Przeczytajcie je sobie!',
    schnapp: 'Złapane!',
    zuFrueh: 'złapał(a) za wcześnie.',
    passteNicht: 'Dobrze, to nie pasowało.',
    schnappPasst: 'Łap! Pasuje!',
    passtNichtKnopf: 'Nie pasuje',
    wortGeschafft: 'zgaduje słowo!',
    neuesWort: 'Nowe słowo.',
    gesucht: 'Szukaj słowa: {0}',
    fehlerVonMax: 'Błędy: {0} z {1}',
    fuersTeam: '+{0} dla drużyny!',
    auchDaneben: 'też pudło.',
    buzzer: 'Naciśnij!',
    antwortet: '{0} odpowiada.',
    anderesTeamAntwortet: 'Odpowiada druga drużyna.',
    aussageStimmte: 'Zdanie było prawdziwe.',
    aussageStimmteNicht: 'Zdanie było fałszywe.',
    deineMuenzen: 'Twoje monety: {0}',
    gebotAb: 'Zakład zrobiony – czekaj na innych.',
    aufStimmt: '{0} na „prawda"',
    aufStimmtNicht: '{0} na „fałsz"',
    steinDoch: 'jednak miał(a) dobry kamień.',
    steinPasstNicht: 'Ten kamień nie pasuje.',
    legtAn: 'kładzie kamień!',
    offen: 'Otwarte: {0}',
    dominoDran: 'Twoja kolej: połóż kamień z pasującym słowem – albo pasuj.',
    deineSteine: 'Twoje kamienie ({0})',
    passen: 'Pasuję',
    slfWort: 'Słowo z twojego kursu',
    slfLang: 'Słowo z co najmniej 5 liter',
    slfNomen: 'Rzeczownik',
    slfVerb: 'Czasownik',
    slfDeutsch: 'Niemieckie znaczenie słowa z kursu (słowo zaczyna się na tę literę)',
    zaehltNicht: '{0}: „{1}" się nie liczy',
    rundeAusgewertet: 'Runda {0} sprawdzona.',
    rundeBuchstabe: 'Runda {0}: litera {1}',
    gemeinsamVon: 'Razem: {0} z {1} {2}',
    geschafftEinheit: 'Gotowe: {0} {1}!',
    vonEinheit: '{0} z {1} {2}.',
    welchesPasstDazu: 'Które słowo pasuje?',
    welchesDasselbe: 'Które słowo znaczy to samo?',
    bWortart: 'Część mowy: {0}',
    bAnfang: 'Zaczyna się na „{0}"',
    bEnde: 'Kończy się na „{0}"',
    bLaenge: '{0} liter',
    bLaengeWoerter: '{0} liter w {1} słowach',
    bGegenteil: 'Przeciwieństwo: {0}',
    bErraten: 'zgaduje!',
    bNichtErraten: 'Tym razem nie zgadnięte.',
    bWarNicht: 'To nie „{0}".',
    bDuErklaerst: 'Ty wyjaśniasz: {0} ({1})',
    bWaehle: 'Wybierz 2 lub 3 podpowiedzi i wyślij je',
    bAndereRaten: 'Teraz zgadują inni.',
    bErklaert: '{0} wyjaśnia.',
    bWarteHinweise: 'Czekamy na podpowiedzi …',
    bHinweise: 'Podpowiedzi',
    bWelchesGemeint: 'Jakie to słowo?',
    bErgebnis: 'Zgadnięte {0} z {1} słów.',
    uiEinladungscode: 'Kod zaproszenia',
    uiCodeHinweis: 'Inni wpisują go na stronie startowej („Mit Code öffnen") albo na liście gier.',
    uiDabei: 'Gracze ({0} z {1})',
    uiGetrennt: 'Brak połączenia – miejsce czeka 60 sekund',
    uiHerausnehmen: 'Usuń {0}',
    uiSpiel: 'Gra',
    uiSchwierigkeit: 'Poziom',
    uiBerechnet: '{0} – według tego, co wszyscy umiecie.',
    uiGrammatik: 'Gramatyka',
    uiStarten: 'Zacznij grę',
    uiWarteMit: 'Czekamy na graczy (co najmniej {0})',
    uiGleich: 'Zaraz zaczynamy – {0} wybiera poziom i startuje. Poziom: {1}',
    uiDerHost: 'gospodarz',
    uiTeamZiel: 'Cel drużyny osiągnięty!',
    uiGutGespielt: 'Dobra gra!',
    uiGewonnen: 'Wygrywa: {0}',
    uiNurFuerDich: 'Tylko dla ciebie',
    uiRichtigN: 'dobrze: {0}',
    uiPlatz: 'Miejsce {0}',
    uiEinWortWieder: 'Wkrótce powtórzysz 1 słowo.',
    uiWoerterWieder: 'Wkrótce powtórzysz {0} słów.',
    uiZurueck: 'Wróć',
    uiNochmal: 'Jeszcze raz',
    uiVerlassen: 'Wyjdź',
    uiKooperativ: 'Razem',
    uiVersus: 'Przeciw',
    uiAntwortSchreiben: 'Napisz odpowiedź',
    uiKeineAntwort: 'Teraz na twoim urządzeniu nie ma odpowiedzi.',
    uiNochmalHoeren: 'Posłuchaj jeszcze raz',
    uiAbschicken: 'Wyślij',
    uiAbschickenN: 'Wyślij ({0})',
    sLeicht: 'Łatwy',
    sMittel: 'Średni',
    sSchwer: 'Trudny',
    sUnmoeglich: 'Niemożliwy',
    sLeichtText: 'Słowa, które wszyscy dobrze znają',
    sMittelText: 'Czasem były błędy',
    sSchwerText: 'Często źle – dobre do ćwiczeń',
    sUnmoeglichText: 'Najtrudniejsze słowa wszystkich',
    ruf0: 'Brawo!',
    ruf1: 'Pomóc?',
    ruf2: 'Moja kolej',
    ruf3: 'Super drużyna!',
    ruf4: 'Chwileczkę …',
    uiKoopText: 'Osiągnąć cel razem z innymi z twojego kursu',
    uiVersusText: 'Przeciw sobie – uczciwie, z pytaniami na waszym poziomie',
    uiZiffern: '6 cyfr',
    uiBeitreten: 'Dołącz',
    uiCodeSechs: 'Kod zaproszenia ma sześć cyfr.',
    uiNachUebung: 'Wspólna gra jest po dzisiejszym ćwiczeniu.',
    uiWirdEroeffnet: 'Gra się otwiera …',
    uiStartenPersonen: 'Zacznij · {0}–{1} graczy',
    uiCodeTitel: 'Grajcie razem – kod zaproszenia',
    uiCodeBeschreibung: 'Ktoś cię zaprosił? Wpisz kod i naciśnij Enter.',
    brauchtBeispielsatz: 'Potrzebne są słowa z przykładowym zdaniem.',
    brauchtVier: 'Potrzebne są co najmniej cztery słowa.'
  },
  reise: lexikonAus(
    {
      ziel: [
        ['morze', 'Chcemy jechać nad morze.', 'Nie chcemy jechać nad morze.', 'Tom nie znosi piasku i słonej wody.', 'morze'],
        ['góry', 'Chcemy jechać w góry.', 'Nie chcemy jechać w góry.', 'Babcia nie może wchodzić na wzgórza.', 'góra'],
        ['duże miasto', 'Chcemy zwiedzić duże miasto.', 'Nie chcemy jechać do dużego miasta.', 'Mia nie znosi hałasu i ruchu.', 'miasto'],
        ['jezioro', 'Chcemy jechać nad jezioro.', 'Nie chcemy jechać nad jezioro.', 'Tata mówi, że jeziora są nudne.', 'jezioro'],
        ['wyspa', 'Chcemy jechać na wyspę.', 'Nie chcemy jechać na wyspę.', 'Nikt nie chce siedzieć tydzień na małej wyspie.', 'wyspa'],
        ['gospodarstwo', 'Chcemy spać w gospodarstwie.', 'Nie chcemy spać w gospodarstwie.', 'Tom boi się krów.', 'gospodarstwo']
      ],
      verkehr: [
        ['pociąg', 'Chcemy jechać pociągiem.', 'Nie chcemy jechać pociągiem.', 'W tym tygodniu jest strajk kolei.', 'pociąg'],
        ['autobus', 'Chcemy jechać autobusem.', 'Nie chcemy jechać autobusem.', 'Mii zawsze jest niedobrze w autobusie.', 'autobus'],
        ['samochód', 'Chcemy jechać samochodem.', 'Nie chcemy jechać samochodem.', 'Nasz samochód jest zepsuty.', 'samochód'],
        ['samolot', 'Chcemy lecieć samolotem.', 'Nie chcemy lecieć samolotem.', 'Tata boi się latać.', 'samolot'],
        ['rower', 'Chcemy jechać rowerem.', 'Nie chcemy jechać rowerem.', 'Babcia nie umie jeździć na rowerze.', 'rower'],
        ['statek', 'Chcemy płynąć statkiem.', 'Nie chcemy płynąć statkiem.', 'Babcia ma chorobę morską.', 'statek']
      ],
      wetter: [
        ['słońce', 'Chcemy słońca.', 'Nie chcemy słońca.', 'Tom bardzo szybko się opala na czerwono.', 'słońce', 'Jeśli świeci słońce,'],
        ['deszcz', null, 'Nie lubimy deszczu.', 'Mia zapomniała parasola.', 'deszcz', 'Jeśli pada deszcz,'],
        ['śnieg', 'Chcemy śniegu.', 'Nie chcemy śniegu.', 'Nie mamy ciepłych ubrań.', 'śnieg', 'Jeśli pada śnieg,'],
        ['wiatr', 'Chcemy trochę wiatru.', 'Nie chcemy wiatru.', 'Mii zawsze odlatuje kapelusz.', 'wiatr', 'Jeśli wieje wiatr,']
      ],
      akt: [
        ['pływanie', 'Chcemy pływać.', 'Mia nie umie pływać.', 'Mia boi się głębokiej wody.', 'pływać', 'chcemy pływać.'],
        ['wędrówki', 'Chcemy chodzić po górach.', 'Babcia nie może długo chodzić.', 'Babcię boli kolano.', 'chodzić', 'chcemy iść na wędrówkę.'],
        ['narty', 'Chcemy jeździć na nartach.', 'Tom nie umie jeździć na nartach.', 'Tom złamał nogę zeszłej zimy.', 'narty', 'chcemy jeździć na nartach.'],
        ['muzea', 'Chcemy iść do muzeum.', 'Nie chcemy iść do muzeum.', 'Tom uważa, że muzea są nudne.', 'muzeum', 'chcemy iść do muzeum.'],
        ['zakupy', 'Chcemy iść na zakupy.', 'Nie chcemy iść na zakupy.', 'Nie mamy pieniędzy na zakupy.', 'sklep', 'chcemy iść na zakupy.'],
        ['żagle', 'Chcemy pływać żaglówką.', 'Nie chcemy pływać żaglówką.', 'Tacie jest niedobrze na małych łódkach.', 'żagiel', 'chcemy pływać żaglówką.'],
        ['namiot', 'Chcemy spać w namiocie.', 'Nie chcemy spać w namiocie.', 'Mia boi się owadów w nocy.', 'namiot', 'chcemy spać w namiocie.']
      ]
    },
    {
      preisKarte: '{0} €',
      tageKarte: 'dni: {0}',
      preis5: 'Mamy {0} euro.',
      preis7: 'To musi kosztować mniej niż {0} euro.',
      preis9: 'Możemy wydać najwyżej {0} euro.',
      tage5: 'Mamy tylko {0} dni.',
      tage7: 'Chcemy zostać co najmniej {0} dni.',
      tage9: 'Najpóźniej po {0} dniach musimy być w domu.'
    }
  )
}
