/** Português – Spieltexte in einfacher Sprache (09.10.2026) */
import type { SprachPaket } from './typ'
import { lexikonAus } from './lexikonAus'

export const pt: SprachPaket = {
  beschreibung: {
    teammatch: 'Todos veem a pergunta. A resposta certa está só num aparelho. Falem uns com os outros!',
    satzbaustelle: 'Cada um tem algumas palavras da frase. Ponham-nas juntos na ordem certa.',
    fluchtraum: 'Respondam em equipa. Depois de algumas respostas certas recebem uma letra da palavra secreta. Encontrem a palavra e fujam!',
    beschreiben: 'Uma pessoa vê a palavra e escolhe pistas. Os outros adivinham. Depois trocam.',
    tauziehen: 'Cada resposta certa puxa a corda para o teu lado. Perguntas difíceis puxam com mais força.',
    staffel: 'As equipas respondem à vez. Ganha quem primeiro encher dez casas.',
    bingo: 'A app diz palavras. Toca na casa certa do teu cartão. Uma linha cheia é bingo!',
    schiffe: 'Algumas respostas certas e podes disparar. Encontra primeiro todos os navios!',
    wortkette: 'À vez, uma palavra. Cada palavra começa com a última letra da anterior.',
    bildergeschichte: 'A história está em palavras. Ponham as imagens na ordem certa.',
    teammemory: 'À vez, virem duas cartas. Conseguem com poucas jogadas?',
    kreuzwort: 'Cada um tem pistas diferentes. Juntos preenchem todas as palavras.',
    fehlerdetektive: 'Uma pessoa encontra o erro, a seguinte corrige-o.',
    uebersetzung: 'Construam juntos a tradução – cuidado, nem todas as peças servem.',
    dialog: 'Dois papéis, uma conversa: põe na tua fala a palavra que falta.',
    woerterturm: 'Cada resposta certa é uma pedra. Construam a torre antes que abane!',
    hoerkette: 'Uma pessoa ouve a palavra e repete-a. Os outros tocam nela.',
    zeitstrahl: 'Ponham as frases na linha do tempo e digam o tempo verbal.',
    reiseplaner: 'Todos veem as mesmas viagens e cada um tem pistas próprias. Só todas as pistas juntas servem a uma viagem.',
    schnapp: 'A palavra e o significado combinam? Quem apanhar primeiro e bem, ganha um ponto.',
    galgen: 'Adivinha as tuas palavras letra a letra. Quem consegue três primeiro?',
    buzzer: 'Quem carregar primeiro responde. Erraste? Então responde a outra equipa.',
    konjugation: 'A forma certa do verbo – quem tem oito primeiro?',
    umbau: 'Transforma a frase – o mais rápido e certo possível.',
    kollokation: 'Que palavra combina com as palavras ao lado?',
    auktion: 'Aposta moedas em «verdade» ou «mentira».',
    domino: 'Põe a peça cuja palavra combina com o significado aberto.',
    stadtland: 'Palavras do teu curso com a letra dada – o servidor verifica.',
    sniper: 'Toca primeiro no erro e corrige-o. Erraste? Três segundos de pausa.',
    synonyme: 'Palavras com o mesmo significado fazem-te subir a escada.'
  },
  einzel: {
    'vok:memory': 'Encontra a palavra e a tradução como par.',
    'vok:zuordnen': 'Toca nos pares o mais rápido possível.',
    'vok:blitz': '60 segundos – o maior número de respostas certas.',
    'vok:satz': 'Põe as frases de exemplo na ordem certa.',
    'vok:wortraten': 'Adivinha as letras antes de a flor perder todas as folhas.',
    'vok:kreuzwort': 'As tuas palavras em palavras cruzadas, com pistas em alemão.',
    'vok:fallend': 'Escreve a tradução antes de a palavra chegar ao fundo.',
    'vok:suchsel': 'Encontra as palavras na sopa de letras.',
    'vok:bildwort': 'Encontra a palavra para a imagem.',
    'vok:hoeren': 'Ouve e escolhe a escrita certa.',
    'vok:satzhoeren': 'Ouve a frase e põe as palavras por ordem.',
    'vok:diktat': 'Ouve a palavra e escreve-a bem.',
    'vok:satzluecke': 'Põe a palavra certa na frase de exemplo.',
    'vok:duell': 'O par combina? 20 rondas contra o teu melhor tempo.',
    'vok:hoermemory': 'Encontra a palavra para cada som.',
    'vok:richtiggehoert': '60 segundos: a imagem combina com a palavra que ouves?',
    'vok:buchstaben': 'Ouve e forma a palavra com letras.',
    'vok:hoerbingo': 'Toca nas palavras que ouves – uma linha cheia é bingo.',
    'vok:bildmemory': 'Encontra a imagem e a palavra como par.',
    'vok:wasfehlt': 'Memoriza as imagens – qual desapareceu?',
    'vok:aufdecken': 'Adivinha a palavra antes de a imagem estar toda à vista.',
    'vok:wortbild': 'Toca na imagem da palavra.',
    'vok:verbtrio': 'Encontra juntas todas as formas de um verbo.',
    'vok:formenblitz': '60 segundos: que forma ouviste?',
    'vok:bildverb': 'Diz as formas do verbo da imagem.',
    'vok:muster': 'Ordena os verbos pelo seu padrão.',
    'gram:fehlerjagd': 'Toca na palavra errada e corrige-a.',
    'gram:satzbaupuzzle': 'Põe as palavras na ordem certa.',
    'gram:formenblitz': '60 segundos – escolhe a forma certa.',
    'gram:regelzuordnen': 'Encontra a regra da frase de exemplo.',
    'gram:verbtrio': 'Encontra juntas todas as formas de um verbo.',
    'gram:verbblitz': '60 segundos: que forma ouviste?',
    'gram:bildverb': 'Diz as formas do verbo da imagem.',
    'gram:muster': 'Ordena os verbos pelo seu padrão.',
    'gram:richtigfalsch': '60 segundos: a frase está certa?',
    'gram:formenmemory': 'Encontra a forma base e a forma nova como par.',
    'gram:tabellenpuzzle': 'Põe as formas nas casas certas da tabela.',
    'gram:signalwort': 'Que tempo verbal mostra a palavra-sinal?'
  },
  einheiten: {
    gelöst: 'resolvidas',
    Fehler: 'erros',
    s: 's',
    erraten: 'adivinhadas',
    Punkte: 'pontos',
    richtig: 'certas',
    Aufrufe: 'chamadas',
    Treffer: 'acertos',
    Glieder: 'elos',
    Züge: 'jogadas',
    Steine: 'pedras',
    Wörter: 'palavras',
    Sätze: 'frases',
    Münzen: 'moedas',
    Sprossen: 'degraus'
  },
  texte: {
    wasBedeutet: 'O que significa?',
    wieHeisst: 'Qual é a palavra?',
    welchesFehlt: 'Que palavra falta?',
    richtigIst: 'Certo é: {0}',
    jemand: 'Alguém',
    duBistDran: 'É a tua vez!',
    istDran: 'É a vez de {0}.',
    daneben: 'errou.',
    richtig: 'Certo!',
    unentschieden: 'Empate!',
    gewonnenHat: 'Ganhou: {0}',
    teilVon: 'Parte {0} de {1}',
    frageVon: 'Pergunta {0} de {1}',
    herzen: 'corações da equipa',
    nurEinGeraet: 'A resposta certa está só num aparelho. Quem a tem?',
    passtNicht: '«{0}» não está certo.',
    keineHerzen: 'Acabaram os corações – vamos continuar.',
    tmGeschafft: 'Objetivo da equipa: {0} de {1} resolvidas!',
    tmLeer: '{0} de {1} resolvidas – uma vez acabaram os corações.',
    satz: 'Frase',
    geschichte: 'História',
    zeitstrahl: 'Linha do tempo',
    vonN: '{0} {1} de {2}',
    gemeinsameReihe: 'A vossa fila',
    deineTeile: 'As tuas peças – toca na próxima',
    keineTeile: 'Já não tens peças – ajuda os outros.',
    nichtJedesTeil: 'Cuidado: nem todas as peças servem.',
    passtNochNicht: 'Isso ainda não vai aqui.',
    passt: 'Serve!',
    fertig: 'Pronto!',
    baut: 'Construam a frase.',
    frueherSpaeter: 'Ponham as frases de antes para depois.',
    welcheZeitform: 'Que tempo verbal é?',
    nenntZeitform: 'Agora {0} diz o tempo verbal de: «{1}»',
    richtigDoppel: 'Certo: {0}.',
    nichtGanz: 'Não é bem isso.',
    dieGeschichte: 'A história: {0}',
    uebersetzt: 'Em alemão: «{0}»',
    fehlerfreiGebaut: 'Construído sem erros!',
    mitFehlern: 'Conseguido com {0} erros.',
    mitEinemFehler: 'Conseguido com 1 erro.',
    codewort: 'Palavra secreta',
    codewortN: 'Palavra secreta – {0} letras',
    buchstabenGefunden: 'Letras encontradas (ordem desconhecida)',
    bisBuchstabe: 'Faltam {0} respostas certas para a próxima letra.',
    alleBuchstaben: 'Têm todas as letras – escrevam a palavra secreta!',
    buchstabeFrei: 'desbloqueou uma letra!',
    richtigWeiter: 'certo! ({0} de {1} para a próxima letra)',
    neueAufgabe: 'Não é bem isso – aqui está uma nova tarefa.',
    falschesWort: 'Essa não é a palavra secreta. Leiam outra vez as pistas!',
    entkommen: 'A porta está aberta! A palavra secreta era «{0}» ({1}).',
    zeitAus: 'O tempo acabou.',
    zeitAusWort: 'O tempo acabou. A palavra secreta era «{0}» ({1}).',
    gemeinsameZeit: 'Tempo da equipa',
    hinweise: 'Pistas para a palavra secreta',
    tuerOeffnen: 'Abrir a porta',
    wortEingeben: 'Escreve a palavra secreta',
    fehlversuche: 'Tentativas erradas: {0}',
    entkommenIn: 'Fugiram em {0} minutos!',
    nichtGereicht: 'Desta vez o tempo não chegou.',
    hLaenge: 'A palavra tem {0} letras.',
    hBild: 'Olhem para a imagem.',
    hNomen: 'É um nome.',
    hVerb: 'É um verbo.',
    hAdj: 'É um adjetivo.',
    hAdv: 'É um advérbio.',
    hLuecke: 'Cabe neste espaço: {0}',
    hSynonym: 'Significa quase o mesmo que «{0}».',
    hDefinition: 'Definição: {0} com {1} letras, parecido com «{2}».',
    hGebrauch: 'Usa-se assim: {0}',
    hAufgabe: 'É a resposta desta tarefa: {0}',
    wortartNomen: 'um nome',
    wortartVerb: 'um verbo',
    wortartAdj: 'um adjetivo',
    wortartAdv: 'um advérbio',
    wortartWort: 'uma palavra',
    feldGefuellt: 'Casa cheia!',
    erstDieFrage: 'É a tua vez – primeiro a pergunta!',
    schussLaden: 'Faltam {0} respostas certas para disparar.',
    geladen: 'certo – faltam {0} para disparar.',
    darfSchiessen: 'pode disparar!',
    danebenAnderes: 'errou – é a vez da outra equipa.',
    tippeFeld: 'Toca numa casa da outra equipa.',
    treffer: 'Acertou!',
    wasser: 'Água.',
    feldVon: 'Campo de {0} ({1} de {2} acertados)',
    eureFlotte: 'A vossa frota',
    ziehtMit: 'puxa com {0}!',
    teilRichtig: 'Parte {0} de {1} certa – continua!',
    duZiehstLinks: 'Puxas para a esquerda.',
    duZiehstRechts: 'Puxas para a direita.',
    aufrufVon: 'Chamada {0} de {1}',
    nichtGerufen: 'Isso não foi chamado.',
    bingo: 'BINGO!',
    auchBingo: 'também tem bingo (lugar {0})!',
    bingoPlatz: 'Bingo – lugar {0}!',
    deinFeld: 'O teu cartão',
    warteAndere: 'À espera dos outros …',
    nichtImFeld: 'Não está no meu cartão – seguinte',
    bingoListe: 'Bingo: {0}',
    bingoErste: 'Primeiro bingo: {0}',
    keinBingo: 'Desta vez não houve bingo.',
    welchesWortSatz: 'Que palavra serve?',
    rundeVon: 'Ronda {0} de {1}',
    rundeFertig: 'Ronda acabada!',
    deinePunkte: 'Os teus pontos: {0}',
    abgegebenWarte: 'Enviado – espera pelos outros.',
    ueberspringenLoesung: 'Saltar (mostrar a resposta)',
    gefunden: 'Encontrado!',
    nichtGanzDoppel: 'Não é bem isso:',
    richtigKlein: 'certo!',
    wortVon: 'Palavra {0} de {1}',
    satzVon: 'Frase {0} de {1}',
    karteVon: 'Carta {0} de {1}',
    reiseVon: 'Viagem {0} de {1}',
    aussageVon: 'Afirmação {0} de {1}',
    faengtMit: 'Começa com «{0}».',
    passtNichtKlein: 'não serve.',
    wortPasst: '{0} serve!',
    kette: 'Cadeia ({0} de {1})',
    neuesGlied: 'Novo elo!',
    ketteHaelt: 'A cadeia aguenta – continuem!',
    ketteErgebnis: 'A vossa cadeia tem {0} elos.',
    paarGefunden: 'Par encontrado!',
    keinPaar: 'Não é par.',
    memoryStand: 'Jogadas: {0} · Pares: {1} de {2}',
    memoryDran: 'É a tua vez: vira duas cartas.',
    memoryErgebnis: 'Todos os pares em {0} jogadas.',
    gemeinsamesRaetsel: 'Palavras cruzadas da equipa',
    woerterGeloest: 'As tuas palavras estão resolvidas – ajudem-se!',
    kreuzErgebnis: 'Resolvido com {0} tentativas erradas.',
    wieRichtig: 'Como é «{0}» certo?',
    fehlerGefunden: 'encontrou o erro: «{0}».',
    istRichtigWort: '«{0}» está certo.',
    fallGeloest: 'Caso resolvido!',
    hatUebersprungen: 'saltou.',
    satzRot: 'A frase – a palavra vermelha está errada',
    deinSatz: 'A tua frase: que palavra está errada? Toca nela.',
    duVerbesserst: '{0} encontrou o erro – tu corriges:',
    verbessertDeinen: 'Encontrado! Agora {0} corrige a tua frase.',
    nochFaelle: 'Ainda {0} casos nesta ronda.',
    nochEinFall: 'Ainda 1 caso nesta ronda.',
    faelleErgebnis: '{0} casos feitos, {1} toques errados.',
    fehlerEntdeckt: 'descobriu o erro!',
    danebenPause: 'errou – 3 segundos de pausa.',
    niemandGefunden: 'Ninguém o encontrou.',
    verbesserungFalsch: 'A correção não está certa.',
    uebersprungen: 'Saltado.',
    pause: 'Pausa',
    tippeFalsches: 'Toca na palavra errada!',
    verbessert: '{0} está a corrigir.',
    findeNicht: 'Não encontro – saltar',
    naechsterSatz: 'Vamos para a próxima frase.',
    deineRolle: 'O teu papel: {0}',
    bisherGespraech: 'A conversa até agora',
    rolleFehlt: 'Papel {0}: que palavra falta?',
    rolleSpricht: 'Papel {0} diz: {1}',
    dialogErgebnis: '{0} de {1} falas certas.',
    richtigVerstanden: 'percebeu bem!',
    diesmalNicht: 'Desta vez não.',
    warEsNicht: '– não era essa.',
    ketteGlieder: 'Cadeia: {0} elos',
    duHoerst: 'Tu ouves a palavra. Di-la em voz alta – os outros tocam nela.',
    sprichtVor: '{0} diz-te a palavra.',
    welchesGehoert: 'Que palavra ouviste?',
    hoerErgebnis: '{0} de {1} palavras passadas bem.',
    eureReise: 'Esta é a vossa viagem!',
    reisePasstNicht: 'Esta viagem não combina com todas as pistas.',
    deineHinweise: 'As tuas pistas (só tu as vês)',
    welcheReise: 'Que viagem é? Falem!',
    reiseErgebnis: '{0} viagens planeadas, {1} tentativas erradas.',
    rpReiseN: 'Viagem {0}',
    rpTippen: 'Toquem numa viagem para a propor.',
    rpVorschlag: '{0} propõe a viagem {1}.',
    rpZustimmen: 'De acordo!',
    rpWarteZustimmung: 'Espera que os outros concordem …',
    rpZustimmungen: 'De acordo: {0} de {1}',
    rpPasstNichtWeil: 'A viagem {0} não serve: «{1}» ({2})',
    rpZeitAus: 'O tempo acabou – a viagem certa era a {0}.',
    rpZusammen: 'Só todas as pistas juntas servem a uma viagem. Leiam-nas uns aos outros!',
    schnapp: 'Apanhei!',
    zuFrueh: 'apanhou cedo demais.',
    passteNicht: 'Certo, não combinava.',
    schnappPasst: 'Apanha! Combina!',
    passtNichtKnopf: 'Não combina',
    wortGeschafft: 'acertou uma palavra!',
    neuesWort: 'Palavra nova.',
    gesucht: 'Procura a palavra para: {0}',
    fehlerVonMax: 'Erros: {0} de {1}',
    fuersTeam: '+{0} para a equipa!',
    auchDaneben: 'também errou.',
    buzzer: 'Carrega!',
    antwortet: '{0} responde.',
    anderesTeamAntwortet: 'A outra equipa responde.',
    aussageStimmte: 'A afirmação era verdade.',
    aussageStimmteNicht: 'A afirmação era mentira.',
    deineMuenzen: 'As tuas moedas: {0}',
    gebotAb: 'Aposta feita – espera pelos outros.',
    aufStimmt: '{0} em «verdade»',
    aufStimmtNicht: '{0} em «mentira»',
    steinDoch: 'afinal tinha a peça certa.',
    steinPasstNicht: 'Essa peça não serve.',
    legtAn: 'joga uma peça!',
    offen: 'Aberto: {0}',
    dominoDran: 'É a tua vez: põe a peça com a palavra certa – ou passa.',
    deineSteine: 'As tuas peças ({0})',
    passen: 'Passar',
    slfWort: 'Uma palavra do teu curso',
    slfLang: 'Uma palavra com pelo menos 5 letras',
    slfNomen: 'Um nome',
    slfVerb: 'Um verbo',
    slfDeutsch: 'O significado alemão de uma palavra do curso (a palavra começa com a letra)',
    zaehltNicht: '{0}: «{1}» não conta',
    rundeAusgewertet: 'Ronda {0} corrigida.',
    rundeBuchstabe: 'Ronda {0}: letra {1}',
    gemeinsamVon: 'Juntos: {0} de {1} {2}',
    geschafftEinheit: 'Conseguido: {0} {1}!',
    vonEinheit: '{0} de {1} {2}.',
    welchesPasstDazu: 'Que palavra combina?',
    welchesDasselbe: 'Que palavra significa o mesmo?',
    bWortart: 'Classe de palavra: {0}',
    bAnfang: 'Começa com «{0}»',
    bEnde: 'Acaba em «{0}»',
    bLaenge: '{0} letras',
    bLaengeWoerter: '{0} letras em {1} palavras',
    bGegenteil: 'Contrário: {0}',
    bErraten: 'adivinhou!',
    bNichtErraten: 'Desta vez não foi adivinhada.',
    bWarNicht: 'Não era «{0}».',
    bDuErklaerst: 'Tu explicas: {0} ({1})',
    bWaehle: 'Escolhe 2 ou 3 pistas e envia-as',
    bAndereRaten: 'Agora os outros adivinham.',
    bErklaert: '{0} explica.',
    bWarteHinweise: 'À espera das pistas …',
    bHinweise: 'Pistas',
    bWelchesGemeint: 'Que palavra é?',
    bErgebnis: '{0} de {1} palavras adivinhadas.',
    uiEinladungscode: 'Código de convite',
    uiCodeHinweis: 'Os outros escrevem-no na página inicial («Mit Code öffnen») ou na lista de jogos.',
    uiDabei: 'Jogadores ({0} de {1})',
    uiGetrennt: 'Ligação perdida – o lugar fica livre 60 segundos',
    uiHerausnehmen: 'Tirar {0}',
    uiSpiel: 'Jogo',
    uiSchwierigkeit: 'Nível',
    uiBerechnet: '{0} – conforme o que todos sabem.',
    uiGrammatik: 'Gramática',
    uiStarten: 'Começar o jogo',
    uiWarteMit: 'À espera de jogadores (pelo menos {0})',
    uiGleich: 'Já vai começar – {0} escolhe o nível e começa. Nível: {1}',
    uiDerHost: 'o anfitrião',
    uiTeamZiel: 'Objetivo da equipa alcançado!',
    uiGutGespielt: 'Bem jogado!',
    uiGewonnen: 'Ganhou: {0}',
    uiNurFuerDich: 'Só para ti',
    uiRichtigN: '{0} certas',
    uiPlatz: '{0}.º lugar',
    uiEinWortWieder: 'Em breve vais treinar 1 palavra outra vez.',
    uiWoerterWieder: 'Em breve vais treinar {0} palavras outra vez.',
    uiZurueck: 'Voltar',
    uiNochmal: 'Outra vez',
    uiVerlassen: 'Sair',
    uiKooperativ: 'Juntos',
    uiVersus: 'Contra',
    uiAntwortSchreiben: 'Escreve a tua resposta',
    uiKeineAntwort: 'Agora não há resposta no teu aparelho.',
    uiNochmalHoeren: 'Ouvir outra vez',
    uiAbschicken: 'Enviar',
    uiAbschickenN: 'Enviar ({0})',
    sLeicht: 'Fácil',
    sMittel: 'Médio',
    sSchwer: 'Difícil',
    sUnmoeglich: 'Impossível',
    sLeichtText: 'Palavras que todos sabem bem',
    sMittelText: 'Às vezes houve erros',
    sSchwerText: 'Muitas vezes erradas – bom para treinar',
    sUnmoeglichText: 'As palavras mais difíceis de todos',
    ruf0: 'Muito bem!',
    ruf1: 'Ajuda?',
    ruf2: 'É a minha vez',
    ruf3: 'Grande equipa!',
    ruf4: 'Um momento …',
    uiKoopText: 'Alcançar um objetivo com outros do teu curso',
    uiVersusText: 'Uns contra os outros – justo, com perguntas ao vosso nível',
    uiZiffern: '6 algarismos',
    uiBeitreten: 'Entrar',
    uiCodeSechs: 'O código de convite tem seis algarismos.',
    uiNachUebung: 'Jogar juntos é possível depois do treino de hoje.',
    uiWirdEroeffnet: 'A abrir o jogo …',
    uiStartenPersonen: 'Começar · {0}–{1} jogadores',
    uiCodeTitel: 'Jogar juntos – código de convite',
    uiCodeBeschreibung: 'Alguém te convidou? Escreve o código e carrega em Enter.',
    brauchtBeispielsatz: 'Precisa de palavras com frase de exemplo.',
    brauchtVier: 'Precisa de pelo menos quatro palavras.'
  },
  reise: lexikonAus(
    {
      ziel: [
        ['o mar', 'Queremos ir ao mar.', 'Não queremos ir ao mar.', 'O Tom odeia areia e água salgada.', 'mar'],
        ['a montanha', 'Queremos ir à montanha.', 'Não queremos ir à montanha.', 'A avó não consegue subir colinas.', 'montanha'],
        ['uma cidade grande', 'Queremos visitar uma cidade grande.', 'Não queremos ir a uma cidade grande.', 'A Mia odeia barulho e trânsito.', 'cidade'],
        ['um lago', 'Queremos ir a um lago.', 'Não queremos ir a um lago.', 'O pai diz que os lagos são aborrecidos.', 'lago'],
        ['uma ilha', 'Queremos ir a uma ilha.', 'Não queremos ir a uma ilha.', 'Ninguém quer ficar uma semana numa ilha pequena.', 'ilha'],
        ['uma quinta', 'Queremos dormir numa quinta.', 'Não queremos dormir numa quinta.', 'O Tom tem medo de vacas.', 'quinta']
      ],
      verkehr: [
        ['o comboio', 'Queremos ir de comboio.', 'Não queremos ir de comboio.', 'Esta semana há greve de comboios.', 'comboio'],
        ['o autocarro', 'Queremos ir de autocarro.', 'Não queremos ir de autocarro.', 'A Mia fica sempre enjoada no autocarro.', 'autocarro'],
        ['o carro', 'Queremos ir de carro.', 'Não queremos ir de carro.', 'O nosso carro está avariado.', 'carro'],
        ['o avião', 'Queremos ir de avião.', 'Não queremos ir de avião.', 'O pai tem medo de voar.', 'avião'],
        ['a bicicleta', 'Queremos ir de bicicleta.', 'Não queremos ir de bicicleta.', 'A avó não sabe andar de bicicleta.', 'bicicleta'],
        ['o navio', 'Queremos ir de navio.', 'Não queremos ir de navio.', 'A avó enjoa nos barcos.', 'navio']
      ],
      wetter: [
        ['sol', 'Queremos sol.', 'Não queremos sol.', 'O Tom queima-se muito depressa.', 'sol', 'Se estiver sol,'],
        ['chuva', null, 'Não gostamos de chuva.', 'A Mia esqueceu-se do guarda-chuva.', 'chuva', 'Se chover,'],
        ['neve', 'Queremos neve.', 'Não queremos neve.', 'Não temos roupa quente connosco.', 'neve', 'Se nevar,'],
        ['vento', 'Queremos um pouco de vento.', 'Não queremos vento.', 'O chapéu da Mia voa sempre.', 'vento', 'Se estiver vento,']
      ],
      akt: [
        ['nadar', 'Queremos nadar.', 'A Mia não sabe nadar.', 'A Mia tem medo de água funda.', 'nadar', 'queremos nadar.'],
        ['caminhadas', 'Queremos fazer caminhadas.', 'A avó não consegue andar muito.', 'A avó tem dores no joelho.', 'caminhar', 'queremos fazer uma caminhada.'],
        ['esqui', 'Queremos fazer esqui.', 'O Tom não sabe fazer esqui.', 'O Tom partiu a perna no inverno passado.', 'esqui', 'queremos fazer esqui.'],
        ['museus', 'Queremos visitar um museu.', 'Não queremos visitar museus.', 'O Tom acha os museus aborrecidos.', 'museu', 'queremos visitar um museu.'],
        ['compras', 'Queremos ir às compras.', 'Não queremos ir às compras.', 'Não temos dinheiro para compras.', 'loja', 'queremos ir às compras.'],
        ['vela', 'Queremos andar de barco à vela.', 'Não queremos andar de barco à vela.', 'O pai enjoa em barcos pequenos.', 'vela', 'queremos andar de barco à vela.'],
        ['campismo', 'Queremos dormir numa tenda.', 'Não queremos dormir numa tenda.', 'A Mia tem medo de insetos à noite.', 'tenda', 'queremos dormir numa tenda.']
      ]
    },
    {
      preisKarte: '{0} €',
      tageKarte: '{0} dias',
      preis5: 'Temos {0} euros.',
      preis7: 'Tem de custar menos de {0} euros.',
      preis9: 'Podemos gastar no máximo {0} euros.',
      tage5: 'Só temos {0} dias.',
      tage7: 'Queremos ficar pelo menos {0} dias.',
      tage9: 'Temos de estar em casa no máximo depois de {0} dias.'
    }
  )
}
