/** Türkçe – Spielnamen und Spieltexte in einfacher Sprache (09.10.2026) */
import type { SprachPaket } from './typ'
import { lexikonAus } from './lexikonAus'

export const tr: SprachPaket = {
  namen: {
    'mehr:teammatch': 'Takım Maçı',
    'mehr:satzbaustelle': 'Cümle İnşaatı',
    'mehr:fluchtraum': 'Kaçış Odası',
    'mehr:beschreiben': 'Anlat ve Tahmin Et',
    'mehr:tauziehen': 'Halat Çekme',
    'mehr:staffel': 'Biçim Bayrak Yarışı',
    'mehr:bingo': 'Kelime Tombalası',
    'mehr:schiffe': 'Amiral Battı',
    'mehr:wortkette': 'Kelime Zinciri',
    'mehr:bildergeschichte': 'Resimli Hikâye',
    'mehr:teammemory': 'Takım Hafıza Oyunu',
    'mehr:kreuzwort': 'Ortak Bulmaca',
    'mehr:fehlerdetektive': 'Hata Dedektifleri',
    'mehr:uebersetzung': 'Çeviri Yapbozu',
    'mehr:dialog': 'Diyalog Tiyatrosu',
    'mehr:woerterturm': 'Kelime Kulesi',
    'mehr:hoerkette': 'Dinleme Zinciri',
    'mehr:zeitstrahl': 'Zaman Çizelgesi',
    'mehr:reiseplaner': 'Gezi Planlayıcı',
    'mehr:schnapp': 'Yakala!',
    'mehr:galgen': 'Adam Asmaca Düellosu',
    'mehr:buzzer': 'Takım Zili',
    'mehr:konjugation': 'Çekim Düellosu',
    'mehr:umbau': 'Dönüştürme Yarışı',
    'mehr:kollokation': 'Eşdizim Düellosu',
    'mehr:auktion': 'Kelime Müzayedesi',
    'mehr:domino': 'Kelime Dominosu',
    'mehr:stadtland': 'İsim Şehir',
    'mehr:sniper': 'Hata Keskin Nişancısı',
    'mehr:synonyme': 'Eş Anlam Merdiveni',
    'vok:memory': 'Hafıza Oyunu',
    'vok:zuordnen': 'Zamana Karşı Eşleştir',
    'vok:blitz': 'Yıldırım Turu',
    'vok:satz': 'Cümle Yapbozu',
    'vok:wortraten': 'Kelimeyi Tahmin Et',
    'vok:kreuzwort': 'Bulmaca',
    'vok:fallend': 'Düşen Kelimeler',
    'vok:suchsel': 'Kelime Avı',
    'vok:bildwort': 'Resimli Bilmece',
    'vok:hoeren': 'Dinleme Yarışması',
    'vok:satzhoeren': 'Cümle Dikte',
    'vok:diktat': 'Dinle ve Yaz',
    'vok:satzluecke': 'Boşluğu Doldur',
    'vok:duell': 'Kelime Düellosu',
    'vok:hoermemory': 'Dinleme Hafıza Oyunu',
    'vok:richtiggehoert': 'Doğru mu duydun?',
    'vok:buchstaben': 'Harf Yapbozu',
    'vok:hoerbingo': 'Dinleme Tombalası',
    'vok:bildmemory': 'Resimli Hafıza Oyunu',
    'vok:wasfehlt': 'Ne eksik?',
    'vok:aufdecken': 'Resmi Aç',
    'vok:wortbild': 'Kelime → Resim',
    'vok:verbtrio': 'Biçim Üçlüsü',
    'vok:formenblitz': 'Biçim Şimşeği',
    'vok:bildverb': 'Resimli Fiil',
    'vok:muster': 'Kalıpları Sırala',
    'gram:fehlerjagd': 'Hatayı Bul',
    'gram:satzbaupuzzle': 'Cümleyi Kur',
    'gram:formenblitz': 'Biçim Şimşeği',
    'gram:regelzuordnen': 'Kuralı Eşleştir',
    'gram:verbtrio': 'Biçim Üçlüsü',
    'gram:verbblitz': 'Biçim Şimşeği',
    'gram:bildverb': 'Resimli Fiil',
    'gram:muster': 'Kalıpları Sırala',
    'gram:richtigfalsch': 'Doğru mu yanlış mı?',
    'gram:formenmemory': 'Biçim Hafıza Oyunu',
    'gram:tabellenpuzzle': 'Tablo Yapbozu',
    'gram:signalwort': 'İşaret Kelimeleri'
  },
  beschreibung: {
    teammatch: 'Herkes soruyu görür. Doğru cevap sadece bir cihazda. Birbirinizle konuşun!',
    satzbaustelle: 'Herkesin cümleden birkaç kelimesi var. Onları birlikte doğru sıraya koyun.',
    fluchtraum: 'Birlikte cevap verin. Birkaç doğru cevaptan sonra gizli kelimenin bir harfini alırsınız. Kelimeyi bulun ve kaçın!',
    beschreiben: 'Bir kişi kelimeyi görür ve ipuçları seçer. Diğerleri tahmin eder. Sonra değişirsiniz.',
    tauziehen: 'Her doğru cevap ipi senin tarafına çeker. Zor sorular daha güçlü çeker.',
    staffel: 'Takımlar sırayla cevap verir. Önce on kutuyu dolduran kazanır.',
    bingo: 'Uygulama kelimeler söyler. Kartındaki doğru kutuya dokun. Dolu bir sıra tombaladır!',
    schiffe: 'Birkaç doğru cevap ver, sonra ateş edebilirsin. Bütün gemileri ilk sen bul!',
    wortkette: 'Sırayla bir kelime. Her kelime bir öncekinin son harfiyle başlar.',
    bildergeschichte: 'Hikâye kelimelerle yazılı. Resimleri doğru sıraya koyun.',
    teammemory: 'Sırayla iki kart açın. Az hamleyle başarabilir misiniz?',
    kreuzwort: 'Herkesin başka ipuçları var. Birlikte bütün kelimeleri doldurursunuz.',
    fehlerdetektive: 'Bir kişi hatayı bulur, sonraki düzeltir.',
    uebersetzung: 'Çeviriyi birlikte kurun – dikkat, her parça ait değil.',
    dialog: 'İki rol, bir konuşma: kendi satırına eksik kelimeyi koy.',
    woerterturm: 'Her doğru cevap bir taştır. Kule sallanmadan önce onu kurun!',
    hoerkette: 'Bir kişi kelimeyi duyar ve tekrar eder. Diğerleri ona dokunur.',
    zeitstrahl: 'Cümleleri zaman çizelgesine koyun ve zamanı söyleyin.',
    reiseplaner: 'Herkes aynı gezileri görür ve kendi ipuçları vardır. Sadece bütün ipuçları birlikte tek bir geziye uyar.',
    schnapp: 'Kelime ve anlam uyuyor mu? İlk doğru yakalayan puan alır.',
    galgen: 'Kelimelerini harf harf tahmin et. Önce kim üç tane bulur?',
    buzzer: 'İlk basan cevap verir. Yanlış mı? O zaman diğer takım cevap verir.',
    konjugation: 'Fiilin doğru biçimi – önce kim sekiz tane bulur?',
    umbau: 'Cümleyi dönüştür – hızlı ve doğru.',
    kollokation: 'Hangi kelime yanındaki kelimelere uyar?',
    auktion: '„Doğru" ya da „yanlış" üzerine para koy.',
    domino: 'Kelimesi açık anlama uyan taşı koy.',
    stadtland: 'Verilen harfle kursundaki kelimeler – sunucu kontrol eder.',
    sniper: 'Hataya ilk sen dokun ve düzelt. Iskaladın mı? Üç saniye mola.',
    synonyme: 'Aynı anlamdaki kelimeler seni merdivende yukarı çıkarır.'
  },
  einzel: {
    'vok:memory': 'Kelimeyi ve çevirisini çift olarak bul.',
    'vok:zuordnen': 'Çiftlere olabildiğince hızlı dokun.',
    'vok:blitz': '60 saniye – olabildiğince çok doğru cevap.',
    'vok:satz': 'Örnek cümleleri doğru sıraya koy.',
    'vok:wortraten': 'Çiçek bütün yapraklarını kaybetmeden harfleri tahmin et.',
    'vok:kreuzwort': 'Kelimelerin bir bulmacada, Almanca ipuçlarıyla.',
    'vok:fallend': 'Kelime aşağı düşmeden çevirisini yaz.',
    'vok:suchsel': 'Harf tablosundaki kelimeleri bul.',
    'vok:bildwort': 'Resmin kelimesini bul.',
    'vok:hoeren': 'Dinle ve doğru yazılışı seç.',
    'vok:satzhoeren': 'Cümleyi dinle ve kelimeleri sırala.',
    'vok:diktat': 'Kelimeyi dinle ve doğru yaz.',
    'vok:satzluecke': 'Örnek cümleye doğru kelimeyi koy.',
    'vok:duell': 'Çift uyuyor mu? En iyi süreye karşı 20 tur.',
    'vok:hoermemory': 'Her sesin kelimesini bul.',
    'vok:richtiggehoert': '60 saniye: resim duyduğun kelimeye uyuyor mu?',
    'vok:buchstaben': 'Dinle ve kelimeyi harflerle kur.',
    'vok:hoerbingo': 'Duyduğun kelimelere dokun – dolu bir sıra tombaladır.',
    'vok:bildmemory': 'Resmi ve kelimeyi çift olarak bul.',
    'vok:wasfehlt': 'Resimleri aklında tut – hangisi kayboldu?',
    'vok:aufdecken': 'Resmin tamamı görünmeden kelimeyi tahmin et.',
    'vok:wortbild': 'Kelimenin resmine dokun.',
    'vok:verbtrio': 'Bir fiilin bütün biçimlerini birlikte bul.',
    'vok:formenblitz': '60 saniye: hangi biçimi duydun?',
    'vok:bildverb': 'Resimdeki fiilin biçimlerini söyle.',
    'vok:muster': 'Fiilleri kalıplarına göre sırala.',
    'gram:fehlerjagd': 'Yanlış kelimeye dokun ve düzelt.',
    'gram:satzbaupuzzle': 'Kelimeleri doğru sıraya koy.',
    'gram:formenblitz': '60 saniye – doğru biçimi seç.',
    'gram:regelzuordnen': 'Örnek cümlenin kuralını bul.',
    'gram:verbtrio': 'Bir fiilin bütün biçimlerini birlikte bul.',
    'gram:verbblitz': '60 saniye: hangi biçimi duydun?',
    'gram:bildverb': 'Resimdeki fiilin biçimlerini söyle.',
    'gram:muster': 'Fiilleri kalıplarına göre sırala.',
    'gram:richtigfalsch': '60 saniye: cümle doğru mu?',
    'gram:formenmemory': 'Temel biçimi ve yeni biçimi çift olarak bul.',
    'gram:tabellenpuzzle': 'Biçimleri tablonun doğru kutularına koy.',
    'gram:signalwort': 'İşaret kelimesi hangi zamanı gösteriyor?'
  },
  einheiten: {
    gelöst: 'çözüldü',
    Fehler: 'hata',
    s: 'sn',
    erraten: 'bilindi',
    Punkte: 'puan',
    richtig: 'doğru',
    Aufrufe: 'çağrı',
    Treffer: 'isabet',
    Glieder: 'halka',
    Züge: 'hamle',
    Steine: 'taş',
    Wörter: 'kelime',
    Sätze: 'cümle',
    Münzen: 'para',
    Sprossen: 'basamak'
  },
  texte: {
    wasBedeutet: 'Bu ne demek?',
    wieHeisst: 'Kelime ne?',
    welchesFehlt: 'Hangi kelime eksik?',
    richtigIst: 'Doğrusu: {0}',
    jemand: 'Biri',
    duBistDran: 'Sıra sende!',
    istDran: 'Sıra {0} adlı oyuncuda.',
    daneben: 'ıskaladı.',
    richtig: 'Doğru!',
    unentschieden: 'Berabere!',
    gewonnenHat: 'Kazanan: {0}',
    teilVon: 'Bölüm {0} / {1}',
    frageVon: 'Soru {0} / {1}',
    herzen: 'ortak kalp',
    nurEinGeraet: 'Doğru cevap sadece bir cihazda. Kimde?',
    passtNicht: '„{0}" doğru değil.',
    keineHerzen: 'Kalp kalmadı – devam ediyoruz.',
    tmGeschafft: 'Takım hedefi tamam: {0} / {1} çözüldü!',
    tmLeer: '{0} / {1} çözüldü – bir kez kalpler bitti.',
    satz: 'Cümle',
    geschichte: 'Hikâye',
    zeitstrahl: 'Zaman çizelgesi',
    vonN: '{0} {1} / {2}',
    gemeinsameReihe: 'Ortak sıranız',
    deineTeile: 'Senin parçaların – sonrakine dokun',
    keineTeile: 'Parçan kalmadı – diğerlerine yardım et.',
    nichtJedesTeil: 'Dikkat: her parça ait değil.',
    passtNochNicht: 'Bu henüz buraya uymuyor.',
    passt: 'Uyuyor!',
    fertig: 'Bitti!',
    baut: 'Cümleyi kurun.',
    frueherSpaeter: 'Cümleleri önceden sonraya sıralayın.',
    welcheZeitform: 'Bu hangi zaman?',
    nenntZeitform: 'Şimdi {0} şu cümlenin zamanını söylüyor: „{1}"',
    richtigDoppel: 'Doğru: {0}.',
    nichtGanz: 'Tam değil.',
    dieGeschichte: 'Hikâye: {0}',
    uebersetzt: 'Almancası: „{0}"',
    fehlerfreiGebaut: 'Hatasız kuruldu!',
    mitFehlern: '{0} hatayla bitti.',
    mitEinemFehler: '1 hatayla bitti.',
    codewort: 'Gizli kelime',
    codewortN: 'Gizli kelime – {0} harf',
    buchstabenGefunden: 'Bulunan harfler (sıra bilinmiyor)',
    bisBuchstabe: 'Sonraki harfe {0} doğru cevap daha.',
    alleBuchstaben: 'Bütün harfler sizde – gizli kelimeyi yazın!',
    buchstabeFrei: 'bir harf açtı!',
    richtigWeiter: 'doğru! (sonraki harf için {0} / {1})',
    neueAufgabe: 'Tam değil – işte yeni bir görev.',
    falschesWort: 'Bu gizli kelime değil. İpuçlarını tekrar okuyun!',
    entkommen: 'Kapı açık! Gizli kelime „{0}" ({1}) idi.',
    zeitAus: 'Süre doldu.',
    zeitAusWort: 'Süre doldu. Gizli kelime „{0}" ({1}) idi.',
    gemeinsameZeit: 'Takım süresi',
    hinweise: 'Gizli kelime için ipuçları',
    tuerOeffnen: 'Kapıyı aç',
    wortEingeben: 'Gizli kelimeyi yaz',
    fehlversuche: 'Yanlış denemeler: {0}',
    entkommenIn: '{0} dakikada kaçtınız!',
    nichtGereicht: 'Bu sefer süre yetmedi.',
    hLaenge: 'Kelimede {0} harf var.',
    hBild: 'Resme bakın.',
    hNomen: 'Bu bir isim.',
    hVerb: 'Bu bir fiil.',
    hAdj: 'Bu bir sıfat.',
    hAdv: 'Bu bir zarf.',
    hLuecke: 'Bu boşluğa uyar: {0}',
    hSynonym: 'Neredeyse „{0}" ile aynı anlamda.',
    hDefinition: 'Tanım: {0}, {1} harf, „{2}" kelimesine benzer.',
    hGebrauch: 'Şöyle kullanılır: {0}',
    hAufgabe: 'Bu görevin cevabı: {0}',
    wortartNomen: 'bir isim',
    wortartVerb: 'bir fiil',
    wortartAdj: 'bir sıfat',
    wortartAdv: 'bir zarf',
    wortartWort: 'bir kelime',
    feldGefuellt: 'Kutu doldu!',
    erstDieFrage: 'Sıra sende – önce soru!',
    schussLaden: 'Atışa {0} doğru cevap daha.',
    geladen: 'doğru – atışa {0} daha.',
    darfSchiessen: 'ateş edebilir!',
    danebenAnderes: 'ıskaladı – sıra diğer takımda.',
    tippeFeld: 'Diğer takımın bir kutusuna dokun.',
    treffer: 'İsabet!',
    wasser: 'Su.',
    feldVon: '{0} alanı ({1} / {2} vuruldu)',
    eureFlotte: 'Filonuz',
    ziehtMit: '{0} güçle çekiyor!',
    teilRichtig: 'Bölüm {0} / {1} doğru – devam!',
    duZiehstLinks: 'Sola çekiyorsun.',
    duZiehstRechts: 'Sağa çekiyorsun.',
    aufrufVon: 'Çağrı {0} / {1}',
    nichtGerufen: 'Bu söylenmedi.',
    bingo: 'TOMBALA!',
    auchBingo: 'de tombala yaptı ({0}. sıra)!',
    bingoPlatz: 'Tombala – {0}. sıra!',
    deinFeld: 'Kartın',
    warteAndere: 'Diğerleri bekleniyor …',
    nichtImFeld: 'Kartımda yok – devam',
    bingoListe: 'Tombala: {0}',
    bingoErste: 'İlk tombala: {0}',
    keinBingo: 'Bu sefer tombala yok.',
    welchesWortSatz: 'Hangi kelime uyuyor?',
    rundeVon: 'Tur {0} / {1}',
    rundeFertig: 'Tur bitti!',
    deinePunkte: 'Puanların: {0}',
    abgegebenWarte: 'Gönderildi – diğerlerini bekle.',
    ueberspringenLoesung: 'Geç (cevabı göster)',
    gefunden: 'Bulundu!',
    nichtGanzDoppel: 'Tam değil:',
    richtigKlein: 'doğru!',
    wortVon: 'Kelime {0} / {1}',
    satzVon: 'Cümle {0} / {1}',
    karteVon: 'Kart {0} / {1}',
    reiseVon: 'Gezi {0} / {1}',
    aussageVon: 'İfade {0} / {1}',
    faengtMit: '„{0}" ile başlıyor.',
    passtNichtKlein: 'uymuyor.',
    wortPasst: '{0} uyuyor!',
    kette: 'Zincir ({0} / {1})',
    neuesGlied: 'Yeni halka!',
    ketteHaelt: 'Zincir yine de sağlam – devam!',
    ketteErgebnis: 'Zincirinizde {0} halka var.',
    paarGefunden: 'Çift bulundu!',
    keinPaar: 'Çift değil.',
    memoryStand: 'Hamle: {0} · Çift: {1} / {2}',
    memoryDran: 'Sıra sende: iki kart aç.',
    memoryErgebnis: 'Bütün çiftler {0} hamlede bulundu.',
    gemeinsamesRaetsel: 'Ortak bulmaca',
    woerterGeloest: 'Kelimelerin çözüldü – birbirinize yardım edin!',
    kreuzErgebnis: 'Bulmaca {0} yanlış denemeyle çözüldü.',
    wieRichtig: '„{0}" doğrusu ne?',
    fehlerGefunden: 'hatayı buldu: „{0}".',
    istRichtigWort: '„{0}" doğru.',
    fallGeloest: 'Vaka çözüldü!',
    hatUebersprungen: 'geçti.',
    satzRot: 'Cümle – kırmızı kelime yanlış',
    deinSatz: 'Senin cümlen: hangi kelime yanlış? Ona dokun.',
    duVerbesserst: '{0} hatayı buldu – sen düzelt:',
    verbessertDeinen: 'Bulundu! Şimdi {0} cümleni düzeltiyor.',
    nochFaelle: 'Bu turda {0} vaka daha var.',
    nochEinFall: 'Bu turda 1 vaka daha var.',
    faelleErgebnis: '{0} vaka, {1} yanlış dokunuş.',
    fehlerEntdeckt: 'hatayı keşfetti!',
    danebenPause: 'ıskaladı – 3 saniye mola.',
    niemandGefunden: 'Kimse bulamadı.',
    verbesserungFalsch: 'Düzeltme yanlış.',
    uebersprungen: 'Geçildi.',
    pause: 'Mola',
    tippeFalsches: 'Yanlış kelimeye dokun!',
    verbessert: '{0} düzeltiyor.',
    findeNicht: 'Bulamıyorum – geç',
    naechsterSatz: 'Sonraki cümleye geçiyoruz.',
    deineRolle: 'Rolün: {0}',
    bisherGespraech: 'Şimdiye kadarki konuşma',
    rolleFehlt: 'Rol {0}: hangi kelime eksik?',
    rolleSpricht: 'Rol {0} diyor ki: {1}',
    dialogErgebnis: '{0} / {1} satır doğru oynandı.',
    richtigVerstanden: 'doğru anladı!',
    diesmalNicht: 'Bu sefer olmadı.',
    warEsNicht: '– o değildi.',
    ketteGlieder: 'Zincir: {0} halka',
    duHoerst: 'Kelimeyi sen duyuyorsun. Yüksek sesle söyle – diğerleri ona dokunur.',
    sprichtVor: '{0} sana kelimeyi söylüyor.',
    welchesGehoert: 'Hangi kelimeyi duydun?',
    hoerErgebnis: '{0} / {1} kelime doğru aktarıldı.',
    eureReise: 'İşte sizin geziniz!',
    reisePasstNicht: 'Bu gezi bütün ipuçlarına uymuyor.',
    deineHinweise: 'İpuçların (sadece sen görüyorsun)',
    welcheReise: 'Hangi gezi? Konuşun!',
    reiseErgebnis: '{0} gezi planlandı, {1} yanlış deneme.',
    rpReiseN: 'Gezi {0}',
    rpTippen: 'Önermek için bir geziye dokunun.',
    rpVorschlag: '{0} {1}. geziyi öneriyor.',
    rpZustimmen: 'Tamam!',
    rpWarteZustimmung: 'Diğerleri kabul edene kadar bekle …',
    rpZustimmungen: 'Kabul: {0} / {1}',
    rpPasstNichtWeil: 'Gezi {0} uymuyor: „{1}" ({2})',
    rpZeitAus: 'Süre doldu – doğru gezi {0} idi.',
    rpZusammen: 'Sadece bütün ipuçları birlikte tek bir geziye uyar. Birbirinize okuyun!',
    schnapp: 'Yakaladım!',
    zuFrueh: 'çok erken yakaladı.',
    passteNicht: 'Doğru, uymuyordu.',
    schnappPasst: 'Yakala! Uyuyor!',
    passtNichtKnopf: 'Uymuyor',
    wortGeschafft: 'bir kelime buldu!',
    neuesWort: 'Yeni kelime.',
    gesucht: 'Şunun kelimesini bul: {0}',
    fehlerVonMax: 'Hata: {0} / {1}',
    fuersTeam: 'Takıma +{0}!',
    auchDaneben: 'o da ıskaladı.',
    buzzer: 'Bas!',
    antwortet: '{0} cevap veriyor.',
    anderesTeamAntwortet: 'Diğer takım cevap veriyor.',
    aussageStimmte: 'İfade doğruydu.',
    aussageStimmteNicht: 'İfade yanlıştı.',
    deineMuenzen: 'Paraların: {0}',
    gebotAb: 'Bahis yapıldı – diğerlerini bekle.',
    aufStimmt: '„doğru" için {0}',
    aufStimmtNicht: '„yanlış" için {0}',
    steinDoch: 'doğru taş aslında vardı.',
    steinPasstNicht: 'Bu taş uymuyor.',
    legtAn: 'taş koyuyor!',
    offen: 'Açık: {0}',
    dominoDran: 'Sıra sende: uyan kelimeli taşı koy – ya da pas geç.',
    deineSteine: 'Taşların ({0})',
    passen: 'Pas',
    slfWort: 'Kursundan bir kelime',
    slfLang: 'En az 5 harfli bir kelime',
    slfNomen: 'Bir isim',
    slfVerb: 'Bir fiil',
    slfDeutsch: 'Kurs kelimesinin Almanca anlamı (kelime bu harfle başlar)',
    zaehltNicht: '{0}: „{1}" sayılmaz',
    rundeAusgewertet: 'Tur {0} değerlendirildi.',
    rundeBuchstabe: 'Tur {0}: harf {1}',
    gemeinsamVon: 'Birlikte: {0} / {1} {2}',
    geschafftEinheit: 'Tamam: {0} {1}!',
    vonEinheit: '{0} / {1} {2}.',
    welchesPasstDazu: 'Hangi kelime buna uyar?',
    welchesDasselbe: 'Hangi kelime aynı anlamda?',
    bWortart: 'Kelime türü: {0}',
    bAnfang: '„{0}" ile başlıyor',
    bEnde: '„{0}" ile bitiyor',
    bLaenge: '{0} harf',
    bLaengeWoerter: '{1} kelimede {0} harf',
    bGegenteil: 'Zıt anlamlısı: {0}',
    bErraten: 'bildi!',
    bNichtErraten: 'Bu sefer bilinemedi.',
    bWarNicht: '„{0}" değildi.',
    bDuErklaerst: 'Sen anlatıyorsun: {0} ({1})',
    bWaehle: '2 ya da 3 ipucu seç ve gönder',
    bAndereRaten: 'Şimdi diğerleri tahmin ediyor.',
    bErklaert: '{0} anlatıyor.',
    bWarteHinweise: 'İpuçları bekleniyor …',
    bHinweise: 'İpuçları',
    bWelchesGemeint: 'Hangi kelime?',
    bErgebnis: '{0} / {1} kelime bilindi.',
    uiEinladungscode: 'Davet kodu',
    uiCodeHinweis: 'Diğerleri onu başlangıç sayfasında („Mit Code öffnen") ya da oyun listesinde yazar.',
    uiDabei: 'Oyuncular ({0} / {1})',
    uiGetrennt: 'Bağlantı koptu – yer 60 saniye boş kalır',
    uiHerausnehmen: '{0} çıkar',
    uiSpiel: 'Oyun',
    uiSchwierigkeit: 'Seviye',
    uiBerechnet: '{0} – hepinizin bildiklerine göre.',
    uiGrammatik: 'Dil bilgisi',
    uiStarten: 'Oyunu başlat',
    uiWarteMit: 'Oyuncular bekleniyor (en az {0})',
    uiGleich: 'Birazdan başlıyoruz – {0} seviyeyi seçip başlatıyor. Seviye: {1}',
    uiDerHost: 'oyun kurucu',
    uiTeamZiel: 'Takım hedefi tamam!',
    uiGutGespielt: 'İyi oyundu!',
    uiGewonnen: 'Kazanan: {0}',
    uiNurFuerDich: 'Sadece senin için',
    uiRichtigN: '{0} doğru',
    uiPlatz: '{0}. sıra',
    uiEinWortWieder: 'Yakında 1 kelimeyi tekrar çalışacaksın.',
    uiWoerterWieder: 'Yakında {0} kelimeyi tekrar çalışacaksın.',
    uiZurueck: 'Geri',
    uiNochmal: 'Tekrar',
    uiVerlassen: 'Çık',
    uiKooperativ: 'Birlikte',
    uiVersus: 'Karşı karşıya',
    uiAntwortSchreiben: 'Cevabını yaz',
    uiKeineAntwort: 'Şu an cihazında cevap yok.',
    uiNochmalHoeren: 'Tekrar dinle',
    uiAbschicken: 'Gönder',
    uiAbschickenN: 'Gönder ({0})',
    sLeicht: 'Kolay',
    sMittel: 'Orta',
    sSchwer: 'Zor',
    sUnmoeglich: 'İmkânsız',
    sLeichtText: 'Herkesin iyi bildiği kelimeler',
    sMittelText: 'Bazen bir şey yanlış gitti',
    sSchwerText: 'Sık sık yanlış – alıştırma için iyi',
    sUnmoeglichText: 'Herkesin en zor kelimeleri',
    ruf0: 'Aferin!',
    ruf1: 'Yardım?',
    ruf2: 'Sıra bende',
    ruf3: 'Süper takım!',
    ruf4: 'Bir dakika …',
    uiKoopText: 'Kursundaki diğerleriyle birlikte bir hedefe ulaş',
    uiVersusText: 'Birbirinize karşı – adil, seviyenize uygun sorularla',
    uiZiffern: '6 rakam',
    uiBeitreten: 'Katıl',
    uiCodeSechs: 'Davet kodu altı rakamdır.',
    uiNachUebung: 'Birlikte oyun bugünkü alıştırmadan sonra.',
    uiWirdEroeffnet: 'Oyun açılıyor …',
    uiStartenPersonen: 'Başlat · {0}–{1} oyuncu',
    uiCodeTitel: 'Birlikte oyna – davet kodu',
    uiCodeBeschreibung: 'Biri seni davet mi etti? Kodu yaz ve Enter’a bas.',
    brauchtBeispielsatz: 'Örnek cümleli kelimeler gerekli.',
    brauchtVier: 'En az dört kelime gerekli.'
  },
  reise: lexikonAus(
    {
      ziel: [
        ['deniz', 'Denize gitmek istiyoruz.', 'Denize gitmek istemiyoruz.', 'Tom kumu ve tuzlu suyu hiç sevmez.', 'deniz'],
        ['dağlar', 'Dağlara gitmek istiyoruz.', 'Dağlara gitmek istemiyoruz.', 'Büyükanne yokuş çıkamaz.', 'dağ'],
        ['büyük şehir', 'Büyük bir şehri gezmek istiyoruz.', 'Büyük bir şehre gitmek istemiyoruz.', 'Mia gürültüyü ve trafiği sevmez.', 'şehir'],
        ['göl', 'Bir göle gitmek istiyoruz.', 'Bir göle gitmek istemiyoruz.', 'Babam gölleri sıkıcı buluyor.', 'göl'],
        ['ada', 'Bir adaya gitmek istiyoruz.', 'Bir adaya gitmek istemiyoruz.', 'Kimse bir hafta küçük bir adada kalmak istemiyor.', 'ada'],
        ['çiftlik', 'Bir çiftlikte kalmak istiyoruz.', 'Bir çiftlikte kalmak istemiyoruz.', 'Tom ineklerden korkar.', 'çiftlik']
      ],
      verkehr: [
        ['tren', 'Trenle gitmek istiyoruz.', 'Trenle gitmek istemiyoruz.', 'Bu hafta trenlerde grev var.', 'tren'],
        ['otobüs', 'Otobüsle gitmek istiyoruz.', 'Otobüsle gitmek istemiyoruz.', 'Mia otobüste hep midesi bulanır.', 'otobüs'],
        ['araba', 'Arabayla gitmek istiyoruz.', 'Arabayla gitmek istemiyoruz.', 'Arabamız bozuk.', 'araba'],
        ['uçak', 'Uçakla gitmek istiyoruz.', 'Uçakla gitmek istemiyoruz.', 'Babam uçmaktan korkar.', 'uçak'],
        ['bisiklet', 'Bisikletle gitmek istiyoruz.', 'Bisikletle gitmek istemiyoruz.', 'Büyükanne bisiklete binemez.', 'bisiklet'],
        ['gemi', 'Gemiyle gitmek istiyoruz.', 'Gemiyle gitmek istemiyoruz.', 'Büyükannenin gemide midesi bulanır.', 'gemi']
      ],
      wetter: [
        ['güneş', 'Güneşli hava istiyoruz.', 'Güneş istemiyoruz.', 'Tom çok çabuk güneşte yanar.', 'güneş', 'Güneş olursa'],
        ['yağmur', null, 'Yağmuru sevmeyiz.', 'Mia şemsiyesini unuttu.', 'yağmur', 'Yağmur yağarsa'],
        ['kar', 'Kar istiyoruz.', 'Kar istemiyoruz.', 'Yanımızda sıcak giysi yok.', 'kar', 'Kar yağarsa'],
        ['rüzgâr', 'Biraz rüzgâr istiyoruz.', 'Rüzgâr istemiyoruz.', 'Mia’nın şapkası hep uçar.', 'rüzgâr', 'Rüzgâr eserse']
      ],
      akt: [
        ['yüzme', 'Yüzmek istiyoruz.', 'Mia yüzme bilmez.', 'Mia derin sudan korkar.', 'yüzmek', 'yüzmek istiyoruz.'],
        ['yürüyüş', 'Yürüyüşe çıkmak istiyoruz.', 'Büyükanne uzun yürüyemez.', 'Büyükannenin dizi ağrıyor.', 'yürümek', 'yürüyüşe çıkmak istiyoruz.'],
        ['kayak', 'Kayak yapmak istiyoruz.', 'Tom kayak yapamaz.', 'Tom geçen kış bacağını kırdı.', 'kayak', 'kayak yapmak istiyoruz.'],
        ['müzeler', 'Bir müzeyi gezmek istiyoruz.', 'Müze gezmek istemiyoruz.', 'Tom müzeleri sıkıcı buluyor.', 'müze', 'bir müzeyi gezmek istiyoruz.'],
        ['alışveriş', 'Alışveriş yapmak istiyoruz.', 'Alışveriş yapmak istemiyoruz.', 'Alışveriş için paramız yok.', 'dükkân', 'alışveriş yapmak istiyoruz.'],
        ['yelken', 'Yelkenliyle gezmek istiyoruz.', 'Yelkenliyle gezmek istemiyoruz.', 'Babamın küçük teknelerde midesi bulanır.', 'yelken', 'yelkenliyle gezmek istiyoruz.'],
        ['kamp', 'Çadırda uyumak istiyoruz.', 'Çadırda uyumak istemiyoruz.', 'Mia geceleri böceklerden korkar.', 'çadır', 'çadırda uyumak istiyoruz.']
      ]
    },
    {
      preisKarte: '{0} €',
      tageKarte: '{0} gün',
      preis5: '{0} avromuz var.',
      preis7: '{0} avrodan ucuz olmalı.',
      preis9: 'En fazla {0} avro harcayabiliriz.',
      tage5: 'Sadece {0} günümüz var.',
      tage7: 'En az {0} gün kalmak istiyoruz.',
      tage9: 'En geç {0} gün sonra evde olmalıyız.'
    }
  )
}
