/** 中文（简体）– Spielnamen und Spieltexte in einfacher Sprache (09.10.2026) */
import type { SprachPaket } from './typ'
import { lexikonAus } from './lexikonAus'

export const zh: SprachPaket = {
  namen: {
    'mehr:teammatch': '团队对决',
    'mehr:satzbaustelle': '句子工地',
    'mehr:fluchtraum': '密室逃脱',
    'mehr:beschreiben': '描述猜词',
    'mehr:tauziehen': '拔河',
    'mehr:staffel': '形式接力',
    'mehr:bingo': '单词宾果',
    'mehr:schiffe': '海战棋',
    'mehr:wortkette': '词语接龙',
    'mehr:bildergeschichte': '看图讲故事',
    'mehr:teammemory': '团队记忆翻牌',
    'mehr:kreuzwort': '合作填字',
    'mehr:fehlerdetektive': '错误侦探',
    'mehr:uebersetzung': '翻译拼图',
    'mehr:dialog': '对话剧场',
    'mehr:woerterturm': '单词塔',
    'mehr:hoerkette': '听力接龙',
    'mehr:zeitstrahl': '时间轴',
    'mehr:reiseplaner': '旅行规划师',
    'mehr:schnapp': '抢！',
    'mehr:galgen': '猜字母对决',
    'mehr:buzzer': '团队抢答',
    'mehr:konjugation': '变位对决',
    'mehr:umbau': '改写竞赛',
    'mehr:kollokation': '搭配对决',
    'mehr:auktion': '单词拍卖',
    'mehr:domino': '单词多米诺',
    'mehr:stadtland': '城市国家河流',
    'mehr:sniper': '错误狙击手',
    'mehr:synonyme': '近义词阶梯',
    'vok:memory': '记忆翻牌',
    'vok:zuordnen': '限时配对',
    'vok:blitz': '闪电回合',
    'vok:satz': '句子拼图',
    'vok:wortraten': '猜单词',
    'vok:kreuzwort': '填字游戏',
    'vok:fallend': '下落的单词',
    'vok:suchsel': '找单词',
    'vok:bildwort': '看图猜词',
    'vok:hoeren': '听力测验',
    'vok:satzhoeren': '句子听写',
    'vok:diktat': '听和写',
    'vok:satzluecke': '填空',
    'vok:duell': '单词对决',
    'vok:hoermemory': '听力记忆翻牌',
    'vok:richtiggehoert': '听对了吗？',
    'vok:buchstaben': '字母拼图',
    'vok:hoerbingo': '听力宾果',
    'vok:bildmemory': '图片记忆翻牌',
    'vok:wasfehlt': '少了什么？',
    'vok:aufdecken': '揭开图片',
    'vok:wortbild': '单词 → 图片',
    'vok:verbtrio': '形式三连',
    'vok:formenblitz': '形式闪电',
    'vok:bildverb': '看图说动词',
    'vok:muster': '按规律分类',
    'gram:fehlerjagd': '找错误',
    'gram:satzbaupuzzle': '组句子',
    'gram:formenblitz': '形式闪电',
    'gram:regelzuordnen': '找规则',
    'gram:verbtrio': '形式三连',
    'gram:verbblitz': '形式闪电',
    'gram:bildverb': '看图说动词',
    'gram:muster': '按规律分类',
    'gram:richtigfalsch': '对还是错？',
    'gram:formenmemory': '形式记忆翻牌',
    'gram:tabellenpuzzle': '表格拼图',
    'gram:signalwort': '信号词'
  },
  beschreibung: {
    teammatch: '大家都看到问题。正确答案只在一台设备上。互相说一说！',
    satzbaustelle: '每人有句子的几个词。一起把它们排成正确的顺序。',
    fluchtraum: '一起回答。答对几次就得到秘密词的一个字。找到这个词，逃出去！',
    beschreiben: '一个人看到词并选择提示，其他人猜。然后交换。',
    tauziehen: '每答对一次，绳子就向你这边拉。难题拉得更多。',
    staffel: '两队轮流回答。先填满十个格子的队赢。',
    bingo: '应用说出单词。点你卡片上正确的格子。一整行就是宾果！',
    schiffe: '答对几题就可以开炮。先找到所有的船！',
    wortkette: '轮流说一个词。每个词用上一个词的最后一个字母开头。',
    bildergeschichte: '故事用词写出来。把图片排成正确的顺序。',
    teammemory: '轮流翻开两张牌。你们能用很少的步数完成吗？',
    kreuzwort: '每人有不同的提示。一起填出所有的词。',
    fehlerdetektive: '一个人找到错误，下一个人改正。',
    uebersetzung: '一起拼出翻译——小心，不是每块都有用。',
    dialog: '两个角色，一段对话：在你的台词里填上缺少的词。',
    woerterturm: '每个正确答案是一块砖。在塔摇晃之前把它建好！',
    hoerkette: '一个人听到词并说出来，其他人点它。',
    zeitstrahl: '把句子放到时间轴上，并说出时态。',
    reiseplaner: '大家看到同样的旅行，每人有自己的提示。只有所有提示合在一起才指向一个旅行。',
    schnapp: '词和意思配吗？谁先抢对谁得分。',
    galgen: '一个字母一个字母地猜你的词。谁先猜出三个？',
    buzzer: '谁先按谁回答。错了？那就由另一队回答。',
    konjugation: '正确的动词形式——谁先得到八个？',
    umbau: '改写句子——又快又对。',
    kollokation: '哪个词和旁边的词搭配？',
    auktion: '把硬币押在“对”或“不对”上。',
    domino: '放下词语和打开的意思相配的骨牌。',
    stadtland: '用给定的字母说出课程里的词——服务器来检查。',
    sniper: '先点到错误并改正。点错了？暂停三秒。',
    synonyme: '意思相同的词让你往梯子上爬。'
  },
  einzel: {
    'vok:memory': '把单词和翻译配成一对。',
    'vok:zuordnen': '尽快点出配对。',
    'vok:blitz': '60秒——答对得越多越好。',
    'vok:satz': '把例句排成正确的顺序。',
    'vok:wortraten': '在花掉光叶子之前猜出字母。',
    'vok:kreuzwort': '你的单词组成填字游戏，提示是德语。',
    'vok:fallend': '在单词落到底部之前写出翻译。',
    'vok:suchsel': '在字母格里找到单词。',
    'vok:bildwort': '为图片找到单词。',
    'vok:hoeren': '听一听，选出正确的写法。',
    'vok:satzhoeren': '听句子，把单词排好。',
    'vok:diktat': '听单词，把它写对。',
    'vok:satzluecke': '把正确的单词填进例句。',
    'vok:duell': '这一对配吗？和你的最好成绩比20轮。',
    'vok:hoermemory': '为每个声音找到单词。',
    'vok:richtiggehoert': '60秒：图片和你听到的词配吗？',
    'vok:buchstaben': '听一听，用字母拼出单词。',
    'vok:hoerbingo': '点你听到的单词——一整行就是宾果。',
    'vok:bildmemory': '把图片和单词配成一对。',
    'vok:wasfehlt': '记住图片——哪张不见了？',
    'vok:aufdecken': '在整张图片露出之前猜出单词。',
    'vok:wortbild': '点和单词相配的图片。',
    'vok:verbtrio': '一起找出一个动词的所有形式。',
    'vok:formenblitz': '60秒：你听到的是哪个形式？',
    'vok:bildverb': '说出图片上动词的各种形式。',
    'vok:muster': '按规律给动词分类。',
    'gram:fehlerjagd': '点出错误的词并改正。',
    'gram:satzbaupuzzle': '把单词排成正确的顺序。',
    'gram:formenblitz': '60秒——选出正确的形式。',
    'gram:regelzuordnen': '为例句找到规则。',
    'gram:verbtrio': '一起找出一个动词的所有形式。',
    'gram:verbblitz': '60秒：你听到的是哪个形式？',
    'gram:bildverb': '说出图片上动词的各种形式。',
    'gram:muster': '按规律给动词分类。',
    'gram:richtigfalsch': '60秒：这个句子对吗？',
    'gram:formenmemory': '把原形和新形式配成一对。',
    'gram:tabellenpuzzle': '把形式放进表格里正确的格子。',
    'gram:signalwort': '信号词表示哪个时态？'
  },
  einheiten: {
    gelöst: '已解决',
    Fehler: '个错误',
    s: '秒',
    erraten: '个猜中',
    Punkte: '分',
    richtig: '个正确',
    Aufrufe: '次叫号',
    Treffer: '次命中',
    Glieder: '环',
    Züge: '步',
    Steine: '块',
    Wörter: '个词',
    Sätze: '个句子',
    Münzen: '枚硬币',
    Sprossen: '级'
  },
  texte: {
    wasBedeutet: '这是什么意思？',
    wieHeisst: '这个词是什么？',
    welchesFehlt: '缺少哪个词？',
    richtigIst: '正确答案：{0}',
    jemand: '有人',
    duBistDran: '轮到你了！',
    istDran: '轮到{0}了。',
    daneben: '没答对。',
    richtig: '对了！',
    unentschieden: '平局！',
    gewonnenHat: '获胜：{0}',
    teilVon: '第{0}部分，共{1}部分',
    frageVon: '第{0}题，共{1}题',
    herzen: '共同的心',
    nurEinGeraet: '正确答案只在一台设备上。谁有？',
    passtNicht: '“{0}”不对。',
    keineHerzen: '没有心了——继续。',
    tmGeschafft: '团队目标完成：答对{0}题，共{1}题！',
    tmLeer: '答对{0}题，共{1}题——有一次心用完了。',
    satz: '句子',
    geschichte: '故事',
    zeitstrahl: '时间轴',
    vonN: '{0} {1}/{2}',
    gemeinsameReihe: '你们的共同一行',
    deineTeile: '你的部分——点下一个',
    keineTeile: '你没有部分了——帮助别人吧。',
    nichtJedesTeil: '小心：不是每块都有用。',
    passtNochNicht: '这个现在还不能放这里。',
    passt: '对了！',
    fertig: '完成！',
    baut: '组成句子。',
    frueherSpaeter: '把句子从早到晚排列。',
    welcheZeitform: '这是什么时态？',
    nenntZeitform: '现在{0}说出这个句子的时态：“{1}”',
    richtigDoppel: '对：{0}。',
    nichtGanz: '不完全对。',
    dieGeschichte: '故事：{0}',
    uebersetzt: '德语：“{0}”',
    fehlerfreiGebaut: '零错误完成！',
    mitFehlern: '完成，有{0}个错误。',
    mitEinemFehler: '完成，有1个错误。',
    codewort: '密码词',
    codewortN: '密码词——{0}个字',
    buchstabenGefunden: '找到的字（顺序未知）',
    bisBuchstabe: '再答对{0}次就得到下一个字。',
    alleBuchstaben: '所有的字都有了——输入密码词！',
    buchstabeFrei: '解开了一个字！',
    richtigWeiter: '对了！（下一个字：{0}/{1}）',
    neueAufgabe: '不完全对——这是新任务。',
    falschesWort: '这不是密码词。再读一读提示！',
    entkommen: '门开了！密码词是“{0}”（{1}）。',
    zeitAus: '时间到了。',
    zeitAusWort: '时间到了。密码词是“{0}”（{1}）。',
    gemeinsameZeit: '团队时间',
    hinweise: '密码词的提示',
    tuerOeffnen: '开门',
    wortEingeben: '输入密码词',
    fehlversuche: '错误尝试：{0}',
    entkommenIn: '{0}分钟逃出！',
    nichtGereicht: '这次时间不够。',
    hLaenge: '这个词有{0}个字。',
    hBild: '看看图片。',
    hNomen: '这是一个名词。',
    hVerb: '这是一个动词。',
    hAdj: '这是一个形容词。',
    hAdv: '这是一个副词。',
    hLuecke: '它可以填进这个空：{0}',
    hSynonym: '它的意思和“{0}”差不多。',
    hDefinition: '定义：{0}，{1}个字，意思接近“{2}”。',
    hGebrauch: '用法：{0}',
    hAufgabe: '它是这个任务的答案：{0}',
    wortartNomen: '名词',
    wortartVerb: '动词',
    wortartAdj: '形容词',
    wortartAdv: '副词',
    wortartWort: '词',
    feldGefuellt: '格子填满了！',
    erstDieFrage: '轮到你了——先回答问题！',
    schussLaden: '再答对{0}次就可以开炮。',
    geladen: '对了——还差{0}次开炮。',
    darfSchiessen: '可以开炮！',
    danebenAnderes: '没答对——轮到另一队。',
    tippeFeld: '点另一队的一个格子。',
    treffer: '命中！',
    wasser: '落水了。',
    feldVon: '{0}的海域（命中{1}/{2}）',
    eureFlotte: '你们的舰队',
    ziehtMit: '用{0}的力气拉！',
    teilRichtig: '第{0}部分（共{1}）对了——继续！',
    duZiehstLinks: '你往左拉。',
    duZiehstRechts: '你往右拉。',
    aufrufVon: '第{0}次叫号，共{1}次',
    nichtGerufen: '这个没有被叫到。',
    bingo: '宾果！',
    auchBingo: '也宾果了（第{0}名）！',
    bingoPlatz: '宾果——第{0}名！',
    deinFeld: '你的卡片',
    warteAndere: '等其他人……',
    nichtImFeld: '不在我的卡片上——下一个',
    bingoListe: '宾果：{0}',
    bingoErste: '第一个宾果：{0}',
    keinBingo: '这次没有宾果。',
    welchesWortSatz: '哪个词合适？',
    rundeVon: '第{0}轮，共{1}轮',
    rundeFertig: '这一轮结束了！',
    deinePunkte: '你的分数：{0}',
    abgegebenWarte: '已发送——等其他人。',
    ueberspringenLoesung: '跳过（显示答案）',
    gefunden: '找到了！',
    nichtGanzDoppel: '不完全对：',
    richtigKlein: '对了！',
    wortVon: '第{0}个词，共{1}个',
    satzVon: '第{0}句，共{1}句',
    karteVon: '第{0}张牌，共{1}张',
    reiseVon: '第{0}次旅行，共{1}次',
    aussageVon: '第{0}句话，共{1}句',
    faengtMit: '以“{0}”开头。',
    passtNichtKlein: '不对。',
    wortPasst: '{0}对了！',
    kette: '链（{0}/{1}）',
    neuesGlied: '新的一环！',
    ketteHaelt: '链还连着——继续！',
    ketteErgebnis: '你们的链有{0}环。',
    paarGefunden: '找到一对！',
    keinPaar: '不是一对。',
    memoryStand: '步数：{0} · 对数：{1}/{2}',
    memoryDran: '轮到你了：翻开两张牌。',
    memoryErgebnis: '用{0}步找到所有的对。',
    gemeinsamesRaetsel: '合作填字',
    woerterGeloest: '你的词都填好了——互相帮助吧！',
    kreuzErgebnis: '填字完成，错误尝试{0}次。',
    wieRichtig: '“{0}”正确的形式是什么？',
    fehlerGefunden: '找到了错误：“{0}”。',
    istRichtigWort: '“{0}”是对的。',
    fallGeloest: '案子破了！',
    hatUebersprungen: '跳过了。',
    satzRot: '句子——红色的词是错的',
    deinSatz: '你的句子：哪个词错了？点它。',
    duVerbesserst: '{0}找到了错误——你来改正：',
    verbessertDeinen: '找到了！现在{0}改正你的句子。',
    nochFaelle: '这一轮还有{0}个案子。',
    nochEinFall: '这一轮还有1个案子。',
    faelleErgebnis: '{0}个案子，{1}次点错。',
    fehlerEntdeckt: '发现了错误！',
    danebenPause: '点错了——暂停3秒。',
    niemandGefunden: '没有人找到。',
    verbesserungFalsch: '改正不对。',
    uebersprungen: '已跳过。',
    pause: '暂停',
    tippeFalsches: '点错误的词！',
    verbessert: '{0}正在改正。',
    findeNicht: '找不到——跳过',
    naechsterSatz: '下一句。',
    deineRolle: '你的角色：{0}',
    bisherGespraech: '到现在为止的对话',
    rolleFehlt: '角色{0}：缺少哪个词？',
    rolleSpricht: '角色{0}说：{1}',
    dialogErgebnis: '{1}句台词中说对了{0}句。',
    richtigVerstanden: '听懂了！',
    diesmalNicht: '这次没有。',
    warEsNicht: '——不是这个。',
    ketteGlieder: '链：{0}环',
    duHoerst: '你听到这个词。大声说出来——其他人点它。',
    sprichtVor: '{0}给你说这个词。',
    welchesGehoert: '你听到的是哪个词？',
    hoerErgebnis: '{1}个词中正确传了{0}个。',
    eureReise: '这就是你们的旅行！',
    reisePasstNicht: '这个旅行不符合所有提示。',
    deineHinweise: '你的提示（只有你能看到）',
    welcheReise: '是哪个旅行？商量一下！',
    reiseErgebnis: '规划了{0}次旅行，错误尝试{1}次。',
    rpReiseN: '旅行{0}',
    rpTippen: '点一个旅行来提议。',
    rpVorschlag: '{0}提议旅行{1}。',
    rpZustimmen: '同意！',
    rpWarteZustimmung: '等其他人同意……',
    rpZustimmungen: '同意：{0}/{1}',
    rpPasstNichtWeil: '旅行{0}不合适：“{1}”（{2}）',
    rpZeitAus: '时间到了——正确的是旅行{0}。',
    rpZusammen: '只有所有提示合在一起才指向一个旅行。互相读一读！',
    schnapp: '抢到了！',
    zuFrueh: '抢得太早了。',
    passteNicht: '对，这不配。',
    schnappPasst: '抢！配！',
    passtNichtKnopf: '不配',
    wortGeschafft: '猜出了一个词！',
    neuesWort: '新词。',
    gesucht: '找这个意思的词：{0}',
    fehlerVonMax: '错误：{0}/{1}',
    fuersTeam: '团队+{0}！',
    auchDaneben: '也没答对。',
    buzzer: '按！',
    antwortet: '{0}在回答。',
    anderesTeamAntwortet: '另一队在回答。',
    aussageStimmte: '这句话是对的。',
    aussageStimmteNicht: '这句话是错的。',
    deineMuenzen: '你的硬币：{0}',
    gebotAb: '已下注——等其他人。',
    aufStimmt: '{0}押“对”',
    aufStimmtNicht: '{0}押“不对”',
    steinDoch: '其实有合适的牌。',
    steinPasstNicht: '这张牌不合适。',
    legtAn: '出了一张牌！',
    offen: '打开的：{0}',
    dominoDran: '轮到你了：放下有正确词的牌——或者跳过。',
    deineSteine: '你的牌（{0}）',
    passen: '跳过',
    slfWort: '课程里的一个词',
    slfLang: '至少5个字母的词',
    slfNomen: '一个名词',
    slfVerb: '一个动词',
    slfDeutsch: '课程词的德语意思（这个词用这个字母开头）',
    zaehltNicht: '{0}：“{1}”不算',
    rundeAusgewertet: '第{0}轮已检查。',
    rundeBuchstabe: '第{0}轮：字母{1}',
    gemeinsamVon: '一起：{0}/{1} {2}',
    geschafftEinheit: '完成：{0} {1}！',
    vonEinheit: '{0}/{1} {2}。',
    welchesPasstDazu: '哪个词搭配？',
    welchesDasselbe: '哪个词意思一样？',
    bWortart: '词性：{0}',
    bAnfang: '以“{0}”开头',
    bEnde: '以“{0}”结尾',
    bLaenge: '{0}个字',
    bLaengeWoerter: '{1}个词，共{0}个字',
    bGegenteil: '反义词：{0}',
    bErraten: '猜对了！',
    bNichtErraten: '这次没猜出来。',
    bWarNicht: '不是“{0}”。',
    bDuErklaerst: '你来描述：{0}（{1}）',
    bWaehle: '选2到3个提示并发送',
    bAndereRaten: '现在其他人来猜。',
    bErklaert: '{0}在描述。',
    bWarteHinweise: '等提示……',
    bHinweise: '提示',
    bWelchesGemeint: '是哪个词？',
    bErgebnis: '{1}个词中猜对{0}个。',
    uiEinladungscode: '邀请码',
    uiCodeHinweis: '其他人在首页（“Mit Code öffnen”）或游戏列表中输入它。',
    uiDabei: '玩家（{0}/{1}）',
    uiGetrennt: '连接断开——位置保留60秒',
    uiHerausnehmen: '移出{0}',
    uiSpiel: '游戏',
    uiSchwierigkeit: '难度',
    uiBerechnet: '{0}——根据你们大家的学习情况。',
    uiGrammatik: '语法',
    uiStarten: '开始游戏',
    uiWarteMit: '等待玩家（至少{0}人）',
    uiGleich: '马上开始——{0}选择难度并开始。难度：{1}',
    uiDerHost: '主持人',
    uiTeamZiel: '团队目标完成！',
    uiGutGespielt: '玩得好！',
    uiGewonnen: '获胜：{0}',
    uiNurFuerDich: '只给你看',
    uiRichtigN: '答对{0}个',
    uiPlatz: '第{0}名',
    uiEinWortWieder: '你很快会再练习1个词。',
    uiWoerterWieder: '你很快会再练习{0}个词。',
    uiZurueck: '返回',
    uiNochmal: '再来一次',
    uiVerlassen: '离开',
    uiKooperativ: '合作',
    uiVersus: '对战',
    uiAntwortSchreiben: '写下你的答案',
    uiKeineAntwort: '现在你的设备上没有答案。',
    uiNochmalHoeren: '再听一次',
    uiAbschicken: '发送',
    uiAbschickenN: '发送（{0}）',
    sLeicht: '简单',
    sMittel: '中等',
    sSchwer: '困难',
    sUnmoeglich: '不可能',
    sLeichtText: '大家都很熟的词',
    sMittelText: '有时会出错',
    sSchwerText: '经常错——适合练习',
    sUnmoeglichText: '大家最难的词',
    ruf0: '真棒！',
    ruf1: '要帮忙吗？',
    ruf2: '轮到我了',
    ruf3: '超级团队！',
    ruf4: '等一下……',
    uiKoopText: '和课程里的其他同学一起完成目标',
    uiVersusText: '互相对战——公平，题目符合你们的水平',
    uiZiffern: '6位数字',
    uiBeitreten: '加入',
    uiCodeSechs: '邀请码有六位数字。',
    uiNachUebung: '完成今天的练习后可以一起玩。',
    uiWirdEroeffnet: '正在开启游戏……',
    uiStartenPersonen: '开始 · {0}–{1}人',
    uiCodeTitel: '一起玩——邀请码',
    uiCodeBeschreibung: '有人邀请你了吗？输入邀请码并按回车。',
    brauchtBeispielsatz: '需要有例句的词。',
    brauchtVier: '至少需要四个词。'
  },
  reise: lexikonAus(
    {
      ziel: [
        ['海边', '我们想去海边。', '我们不想去海边。', '汤姆讨厌沙子和咸水。', '海'],
        ['山区', '我们想去山里。', '我们不想去山里。', '奶奶爬不了山坡。', '山'],
        ['大城市', '我们想去大城市。', '我们不想去大城市。', '米娅讨厌噪音和车多。', '城市'],
        ['湖边', '我们想去湖边。', '我们不想去湖边。', '爸爸觉得湖很无聊。', '湖'],
        ['小岛', '我们想去一个岛上。', '我们不想去岛上。', '没有人想在小岛上待一个星期。', '岛'],
        ['农场', '我们想住在农场。', '我们不想住在农场。', '汤姆怕牛。', '农场']
      ],
      verkehr: [
        ['火车', '我们想坐火车去。', '我们不想坐火车去。', '这个星期火车罢工。', '火车'],
        ['公共汽车', '我们想坐公共汽车去。', '我们不想坐公共汽车去。', '米娅坐公共汽车总是晕车。', '公共汽车'],
        ['汽车', '我们想开车去。', '我们不想开车去。', '我们的车坏了。', '汽车'],
        ['飞机', '我们想坐飞机去。', '我们不想坐飞机去。', '爸爸怕坐飞机。', '飞机'],
        ['自行车', '我们想骑自行车去。', '我们不想骑自行车去。', '奶奶不会骑自行车。', '自行车'],
        ['轮船', '我们想坐船去。', '我们不想坐船去。', '奶奶坐船会晕船。', '船']
      ],
      wetter: [
        ['晴天', '我们想要晴天。', '我们不想要太阳。', '汤姆很快就会晒伤。', '太阳', '如果是晴天，'],
        ['下雨', null, '我们不喜欢下雨。', '米娅忘了带伞。', '雨', '如果下雨，'],
        ['下雪', '我们想要雪。', '我们不想要雪。', '我们没有带厚衣服。', '雪', '如果下雪，'],
        ['刮风', '我们想要一点风。', '我们不想要风。', '米娅的帽子总是被吹走。', '风', '如果刮风，']
      ],
      akt: [
        ['游泳', '我们想游泳。', '米娅不会游泳。', '米娅怕深水。', '游泳', '我们想去游泳。'],
        ['徒步', '我们想去徒步。', '奶奶走不了很远。', '奶奶膝盖疼。', '走', '我们想去徒步。'],
        ['滑雪', '我们想滑雪。', '汤姆不会滑雪。', '汤姆去年冬天摔断了腿。', '滑雪', '我们想去滑雪。'],
        ['博物馆', '我们想参观博物馆。', '我们不想去博物馆。', '汤姆觉得博物馆很无聊。', '博物馆', '我们想去博物馆。'],
        ['购物', '我们想去购物。', '我们不想去购物。', '我们没有钱购物。', '商店', '我们想去购物。'],
        ['帆船', '我们想坐帆船。', '我们不想坐帆船。', '爸爸坐小船会晕船。', '帆', '我们想去坐帆船。'],
        ['露营', '我们想在帐篷里睡觉。', '我们不想在帐篷里睡觉。', '米娅晚上怕虫子。', '帐篷', '我们想在帐篷里睡觉。']
      ]
    },
    {
      preisKarte: '{0}欧元',
      tageKarte: '{0}天',
      preis5: '我们有{0}欧元。',
      preis7: '必须比{0}欧元便宜。',
      preis9: '我们最多能花{0}欧元。',
      tage5: '我们只有{0}天。',
      tage7: '我们想至少住{0}天。',
      tage9: '最晚{0}天后我们必须回家。'
    }
  )
}
