/**
 * Grammatikthemen der neuen Schulfremdsprachen (30.09.2026, Audit Länder/Schulformen/Fächer):
 * Niederländisch, Polnisch, Tschechisch, Portugiesisch, Türkisch, Chinesisch.
 *
 * Datenformat wie `grammarTopicsErgaenzung.ts`; die Liste hängt dort an. Stufen auf der Skala der
 * 2. Fremdsprache (Lernjahr 1 ≙ A1, 2 ≙ A1+/A2, 3 ≙ A2/A2+, 4 ≙ A2+/B1, 5–6 ≙ B1/B1+); als
 * 3. Fremdsprache rechnet die App selbst um (`topicStart`).
 *
 * QUELLENLAGE – ehrlich: Für diese Sprachen führen die Länder keine sprachspezifischen
 * Grammatiklisten. Der Rahmenlehrplan Berlin/Brandenburg 1–10 (Teil C Moderne Fremdsprachen,
 * 2015/2025, recherche/lehrplaene/BE) gilt für alle modernen Fremdsprachen gemeinsam und nennt
 * sprachliche Mittel nur nach Niveaustufe, nicht nach Struktur. Die Einordnung je Thema ist daher
 * eine FAUSTREGEL nach üblicher Anfängerprogression und den GER-Referenzbeschreibungen der
 * Sprachen (genannt in `source`, nicht Seite für Seite abgeglichen). Eine Netzrecherche war in
 * dieser Sitzung nicht mehr möglich (Suchkontingent erschöpft). Beispiele sind nicht
 * muttersprachlich geprüft – siehe recherche/sprachtexte-2026-09-30.md.
 *
 * Portugiesisch: Wo sich europäisches und brasilianisches Portugiesisch unterscheiden, stehen
 * beide Formen mit (PT)/(BR). Chinesisch: Kurzzeichen mit Pinyin (Tonzeichen) in Klammern.
 */
import type { GrammarScale, GrammarTopic } from './grammarTopics'

type Eingabe = Omit<GrammarTopic, 'subject' | 'scale' | 'stage' | 'formatsText' | 'source'> & {
  scale?: GrammarScale
  source?: string
}

const stufe = (from: number, to: number): string => (from === to ? `${from}` : `${from}–${to}`)

/** Jedes Thema trägt den Beleg der Sprache; ein eigener Beleg am Thema geht vor. */
function fach(subject: string, quelle: string, liste: Eingabe[]): GrammarTopic[] {
  return liste.map((e) => ({
    ...e,
    subject,
    scale: e.scale ?? 'lernjahr',
    stage: stufe(e.from, e.to),
    formatsText: e.description ?? '',
    source: e.source ?? quelle
  }))
}

// ---------------------------------------------------------------- Niederländisch

const NIEDERLAENDISCH = fach(
  'niederlaendisch',
  'Faustregel (übliche Anfängerprogression Niederländisch als Fremdsprache; GER-Einordnung angelehnt an die Niveaubeschreibungen des CNaVT/der Taalunie, nicht einzeln abgeglichen)',
  [
    {
      id: 'nl.nom.lidwoord',
      label: 'Artikel und Plural',
      term: 'lidwoord de/het, een; meervoud -en/-s',
      area: 'Nomen',
      from: 1,
      to: 2,
      level: 'A1',
      errors: 'de/het nach deutschem Genus (*de huis*); Plural *-s* statt -en',
      formats: ['zuordnen', 'luecke', 'tabelle'],
      description: 'Bestimmter Artikel de (m./f., alle Plurale) oder het (n.); Plural meist auf -en, nach unbetonter Endsilbe oft -s.',
      examples: ['de tafel – de tafels', 'het huis – de huizen', 'een boek – twee boeken']
    },
    {
      id: 'nl.verb.presens',
      label: 'Präsens, zijn und hebben',
      term: 'tegenwoordige tijd (stam + t); zijn, hebben',
      area: 'Verb',
      from: 1,
      to: 1,
      level: 'A1',
      errors: '-t bei Inversion behalten (*Werkt jij?*); zijn/hebben nach Deutsch konjugiert',
      formats: ['tabelle', 'luecke', 'formenbestimmen'],
      description: 'Stamm + t in der 2./3. Person Singular; in der Frage mit jij/je fällt das -t weg.',
      examples: ['Ik werk, jij werkt, hij werkt.', 'Werk jij morgen?', 'Wij hebben een hond.']
    },
    {
      id: 'nl.syn.woordvolgorde',
      label: 'Wortstellung im Hauptsatz und Fragen',
      term: 'woordvolgorde: persoonsvorm op plaats 2, inversie, vraagzinnen',
      area: 'Satzbau',
      from: 1,
      to: 2,
      level: 'A1',
      errors: 'Verb nicht an zweiter Stelle nach Zeitangabe (*Morgen ik ga*)',
      formats: ['sortieren', 'umformen', 'satzbildung'],
      description: 'Das finite Verb steht an zweiter Stelle; beginnt der Satz mit einer Angabe, folgt das Subjekt dem Verb.',
      examples: ['Morgen ga ik naar school.', 'Waar woon je?']
    },
    {
      id: 'nl.syn.ontkenning',
      label: 'Verneinung mit niet und geen',
      term: 'ontkenning: niet / geen',
      area: 'Satzbau',
      from: 1,
      to: 1,
      level: 'A1',
      errors: '*niet een* statt geen; niet an falscher Stelle',
      formats: ['multiplechoice', 'umformen', 'luecke'],
      description: 'geen verneint ein Nomen mit een oder ohne Artikel, niet alles andere.',
      examples: ['Ik heb geen fiets.', 'Ik kom vandaag niet.']
    },
    {
      id: 'nl.pron.persoonlijk',
      label: 'Personal- und Possessivpronomen',
      term: 'persoonlijke en bezittelijke voornaamwoorden (jij/je, mijn/m’n)',
      area: 'Pronomen',
      from: 1,
      to: 2,
      level: 'A1',
      errors: 'betonte und unbetonte Formen vertauscht; *hem* und *haar* nach Deutsch',
      formats: ['luecke', 'zuordnen', 'tabelle'],
      description: 'Betonte (jij, mij) und unbetonte Formen (je, me); Possessiva mijn, jouw, zijn, haar, ons/onze, jullie, hun.',
      examples: ['Dat is mijn broer.', 'Zie je hem morgen?', 'Dat is ons huis, en dat is onze tuin.']
    },
    {
      id: 'nl.adj.buiging',
      label: 'Adjektivendung -e',
      term: 'buiging van het bijvoeglijk naamwoord',
      area: 'Adjektiv',
      from: 1,
      to: 2,
      level: 'A1/A2',
      errors: '*een grote huis* (bei het-Wort nach een ohne -e)',
      formats: ['luecke', 'fehlerkorrektur', 'multiplechoice'],
      description: 'Vor dem Nomen bekommt das Adjektiv -e – außer bei het-Wörtern im Singular nach een, geen oder ohne Artikel.',
      examples: ['de oude fiets', 'een oud huis', 'het oude huis']
    },
    {
      id: 'nl.nom.verkleinwoord',
      label: 'Verkleinerungsformen',
      term: 'verkleinwoord -je, -tje, -pje, -etje',
      area: 'Nomen/Wortbildung',
      from: 1,
      to: 2,
      level: 'A1/A2',
      errors: 'falsche Endung (*boomje*); Artikel nicht auf het umgestellt',
      formats: ['tabelle', 'luecke', 'zuordnen'],
      description: 'Verkleinerungen sind immer het-Wörter; die Endung richtet sich nach dem Wortende.',
      examples: ['het huisje', 'een kopje koffie', 'het boompje']
    },
    {
      id: 'nl.verb.modaal',
      label: 'Modalverben',
      term: 'modale werkwoorden kunnen, willen, moeten, mogen',
      area: 'Verb',
      from: 1,
      to: 2,
      level: 'A1',
      errors: 'Infinitiv nicht ans Satzende; mogen und moeten vertauscht (nicht mogen ≠ nicht müssen)',
      formats: ['luecke', 'satzbildung', 'multiplechoice'],
      description: 'Modalverb an zweiter Stelle, Infinitiv am Satzende.',
      examples: ['Ik wil een ijsje.', 'Mag ik naar buiten?', 'Je hoeft niet te komen.']
    },
    {
      id: 'nl.verb.toekomst',
      label: 'Zukunft mit gaan und zullen',
      term: 'toekomst: gaan + infinitief, zullen',
      area: 'Verb/Zeit',
      from: 2,
      to: 3,
      level: 'A2',
      errors: '*Ik werde* nach Deutsch; zullen für einfache Pläne überdehnt',
      formats: ['luecke', 'umformen', 'satzbildung'],
      description: 'Pläne und Vorhaben mit gaan + Infinitiv; zullen für Vermutung und Versprechen.',
      examples: ['Ik ga morgen voetballen.', 'Het zal wel lukken.']
    },
    {
      id: 'nl.verb.perfectum',
      label: 'Perfekt',
      term: 'voltooid tegenwoordige tijd (hebben/zijn + voltooid deelwoord, ’t kofschip)',
      area: 'Verb/Zeit',
      from: 2,
      to: 3,
      level: 'A2',
      errors: 'Hilfsverb nach Deutsch; -t/-d am Partizip (*gewoont*)',
      formats: ['luecke', 'tabelle', 'fehlerkorrektur'],
      description: 'hebben oder zijn + Partizip mit ge-; Endung -t nach den Lauten aus „’t kofschip", sonst -d.',
      examples: ['Ik heb gisteren gewerkt.', 'Wij zijn naar Utrecht gefietst.', 'Ze heeft in Gent gewoond.']
    },
    {
      id: 'nl.verb.imperfectum',
      label: 'Imperfekt',
      term: 'onvoltooid verleden tijd (-te/-de; sterke werkwoorden)',
      area: 'Verb/Zeit',
      from: 2,
      to: 4,
      level: 'A2',
      contested: true,
      errors: '-te/-de vertauscht; starke Formen nach Deutsch (*ik gang*)',
      formats: ['tabelle', 'luecke', 'umformen'],
      description: 'Erzählzeit; regelmäßig Stamm + -te(n)/-de(n) nach „’t kofschip", unregelmäßige Verben mit Vokalwechsel.',
      examples: ['Hij werkte in een winkel.', 'Wij woonden in Delft.', 'Ik ging naar huis.']
    },
    {
      id: 'nl.adj.vergelijking',
      label: 'Steigerung und Vergleich',
      term: 'trappen van vergelijking (-er, -st; dan)',
      area: 'Adjektiv',
      from: 2,
      to: 2,
      level: 'A2',
      errors: '*groter als* statt groter dan (Standardsprache); *goeder*',
      formats: ['tabelle', 'luecke', 'satzbildung'],
      description: 'Komparativ auf -er (nach r: -der), Superlativ auf -st; Vergleich mit dan bzw. even … als.',
      examples: ['Hij is groter dan ik.', 'goed – beter – best', 'Zij is even oud als ik.']
    },
    {
      id: 'nl.verb.scheidbaar',
      label: 'Trennbare Verben',
      term: 'scheidbare werkwoorden',
      area: 'Verb',
      from: 2,
      to: 2,
      level: 'A2',
      errors: 'Partikel nicht abgetrennt; Partizip *geopbeld* statt opgebeld',
      formats: ['luecke', 'sortieren', 'umformen'],
      description: 'Die Partikel steht im Hauptsatz am Satzende; im Partizip steht ge- zwischen Partikel und Stamm.',
      examples: ['Ik bel je morgen op.', 'Hij staat om zeven uur op.', 'Ik heb hem opgebeld.']
    },
    {
      id: 'nl.verb.wederkerend',
      label: 'Reflexive Verben',
      term: 'wederkerende werkwoorden (zich)',
      area: 'Verb',
      from: 2,
      to: 3,
      level: 'A2',
      errors: 'Reflexivpronomen nach Deutsch gesetzt oder weggelassen; *hij verveelt hem*',
      formats: ['luecke', 'tabelle', 'uebersetzen'],
      description: 'Reflexivpronomen me, je, zich, ons, je, zich; nicht jedes deutsche reflexive Verb ist im Niederländischen reflexiv.',
      examples: ['Ik was me.', 'Hij verveelt zich.', 'Wij vergissen ons.']
    },
    {
      id: 'nl.syn.bijzin',
      label: 'Nebensätze und Verbstellung',
      term: 'bijzinnen met omdat, dat, als, toen; werkwoordsvolgorde',
      area: 'Satzbau',
      from: 3,
      to: 4,
      level: 'A2/B1',
      errors: 'Verb nicht ans Ende (*omdat ik ben ziek*); als/toen vertauscht',
      formats: ['umformen', 'luecke', 'satzbildung'],
      description: 'Im Nebensatz stehen die Verben am Ende; im Verbcluster steht das Modalverb meist vor dem Infinitiv.',
      examples: ['Ik blijf thuis, omdat ik ziek ben.', 'Ik weet dat hij morgen komt.', 'Ik denk dat hij niet kan komen.']
    },
    {
      id: 'nl.syn.te_infinitief',
      label: 'Infinitiv mit (om …) te',
      term: '(om) … te + infinitief',
      area: 'Satzbau',
      from: 3,
      to: 4,
      level: 'A2/B1',
      errors: 'te vergessen; om an falscher Stelle',
      formats: ['luecke', 'umformen', 'satzbildung'],
      description: 'Infinitivgruppen mit te, nach Adjektiven und bei Zweck oft mit om … te.',
      examples: ['Het is leuk om te zwemmen.', 'Ik probeer op tijd te komen.']
    },
    {
      id: 'nl.pron.betrekkelijk',
      label: 'Relativpronomen',
      term: 'betrekkelijke voornaamwoorden die, dat, wat, waar + voorzetsel',
      area: 'Pronomen',
      from: 3,
      to: 4,
      level: 'A2/B1',
      errors: '*het boek die*; Präposition + die statt waar- (*het huis in die*)',
      formats: ['luecke', 'multiplechoice', 'umformen'],
      description: 'die bei de-Wörtern und im Plural, dat bei het-Wörtern; mit Präposition waar- + Präposition.',
      examples: ['de man die daar staat', 'het boek dat ik lees', 'het huis waarin ik woon']
    },
    {
      id: 'nl.syn.er',
      label: 'Der Gebrauch von er',
      term: 'er (plaats, hoeveelheid, er + voorzetsel, er in existentiële zinnen)',
      area: 'Satzbau',
      from: 3,
      to: 5,
      level: 'A2/B1',
      contested: true,
      errors: 'er weggelassen (*Ik heb drie.*); *over het denken* statt erover denken',
      formats: ['luecke', 'markieren', 'uebersetzen'],
      description: 'er steht für einen Ort, eine Menge mit Zahlwort, ein Präpositionalobjekt (erover, ermee) und als Platzhalter.',
      examples: ['Er staat een man bij de deur.', 'Ik heb er drie.', 'Ik denk erover na.']
    },
    {
      id: 'nl.verb.plusquam_conditionalis',
      label: 'Plusquamperfekt und Konditional',
      term: 'voltooid verleden tijd; zou(den) + infinitief',
      area: 'Verb/Zeit',
      from: 4,
      to: 5,
      level: 'B1',
      errors: '*würde* nach Deutsch; zou in beiden Satzhälften des Bedingungssatzes',
      formats: ['umformen', 'luecke', 'satzbildung'],
      description: 'Vorzeitigkeit mit had/was + Partizip; Unwirkliches und Höflichkeit mit zou(den).',
      examples: ['Ik had het al gezien.', 'Als ik tijd had, zou ik komen.']
    },
    {
      id: 'nl.verb.passief',
      label: 'Passiv',
      term: 'lijdende vorm: worden/zijn + voltooid deelwoord (door)',
      area: 'Verb',
      from: 4,
      to: 5,
      level: 'B1',
      errors: 'worden (Vorgang) und zijn (Ergebnis) vertauscht; *van* statt door',
      formats: ['umformen', 'luecke', 'markieren'],
      description: 'Vorgangspassiv mit worden, Perfekt des Passivs mit zijn; der Handelnde mit door.',
      examples: ['Het huis wordt verkocht.', 'Het huis is verkocht.', 'De brief wordt door mijn zus geschreven.']
    },
    {
      id: 'nl.syn.indirecte_rede',
      label: 'Indirekte Rede und indirekte Frage',
      term: 'indirecte rede (dat), indirecte vraag (of, vraagwoord)',
      area: 'Satzbau',
      from: 4,
      to: 5,
      level: 'B1',
      errors: '*als* statt of in der indirekten Frage; Verbstellung wie im Hauptsatz',
      formats: ['umformen', 'luecke'],
      description: 'Wiedergabe mit dat bzw. of oder Fragewort; Verb am Ende; Pronomen und Zeit angepasst.',
      examples: ['Ze zegt dat ze moe is.', 'Hij vraagt of ik meega.', 'Weet jij waar hij woont?']
    }
  ]
)

// ---------------------------------------------------------------- Polnisch

const POLNISCH = fach(
  'polnisch',
  'Faustregel (übliche Anfängerprogression Polnisch als Fremdsprache; GER-Einordnung angelehnt an die Prüfungsstandards der staatlichen Polnisch-Zertifikate A1–C2, nicht einzeln abgeglichen)',
  [
    {
      id: 'pl.nom.rodzaj',
      label: 'Genus am Wortende erkennen',
      term: 'rodzaj gramatyczny: męski, żeński, nijaki (ten, ta, to)',
      area: 'Nomen',
      from: 1,
      to: 1,
      level: 'A1',
      errors: 'Genus nach Deutsch (*ta dom*)',
      formats: ['zuordnen', 'tabelle', 'luecke'],
      description: 'Maskulinum meist auf Konsonant, Femininum auf -a, Neutrum auf -o, -e, -ę.',
      examples: ['ten dom, ta szkoła, to okno']
    },
    {
      id: 'pl.verb.koniugacja',
      label: 'Präsens: Konjugationsmuster, być und mieć',
      term: 'czas teraźniejszy (-m/-sz; -ę/-esz; -ę/-isz), być, mieć',
      area: 'Verb',
      from: 1,
      to: 1,
      level: 'A1',
      errors: 'Muster vertauscht (*czytę*); być nicht konjugiert',
      formats: ['tabelle', 'luecke', 'formenbestimmen'],
      description: 'Drei Grundmuster nach der 1. und 2. Person Singular; być und mieć unregelmäßig.',
      examples: ['czytam, czytasz', 'robię, robisz', 'jestem, jesteś', 'mam, masz']
    },
    {
      id: 'pl.syn.pytania',
      label: 'Fragesätze',
      term: 'pytania z czy i zaimkami pytającymi',
      area: 'Satzbau',
      from: 1,
      to: 1,
      level: 'A1',
      errors: 'czy vergessen bzw. Umstellung nach Deutsch',
      formats: ['umformen', 'zuordnen', 'satzbildung'],
      description: 'Entscheidungsfragen beginnen mit czy, die Wortstellung bleibt; Ergänzungsfragen mit Fragewort.',
      examples: ['Czy masz psa?', 'Gdzie mieszkasz?']
    },
    {
      id: 'pl.adj.odmiana',
      label: 'Adjektive: Übereinstimmung',
      term: 'przymiotnik: zgoda w rodzaju, liczbie i przypadku',
      area: 'Adjektiv',
      from: 1,
      to: 2,
      level: 'A1',
      errors: 'Endung nicht angeglichen (*nowy szkoła*)',
      formats: ['luecke', 'tabelle', 'fehlerkorrektur'],
      description: 'Das Adjektiv richtet sich in Genus, Zahl und Kasus nach dem Nomen.',
      examples: ['nowy dom, nowa szkoła, nowe okno', 'Mam nowy telefon.']
    },
    {
      id: 'pl.nom.biernik',
      label: 'Akkusativ',
      term: 'biernik',
      area: 'Nomen/Kasus',
      from: 1,
      to: 2,
      level: 'A1',
      errors: 'Objekt im Nominativ (*mam siostra*); Belebtheit beim Maskulinum übersehen',
      formats: ['luecke', 'tabelle', 'umformen'],
      description: 'Direktes Objekt; Femininum -ę, belebtes Maskulinum wie der Genitiv.',
      examples: ['Mam siostrę.', 'Widzę kota.', 'Lubię kawę.']
    },
    {
      id: 'pl.nom.miejscownik',
      label: 'Lokativ',
      term: 'miejscownik (w, na, o)',
      area: 'Nomen/Kasus',
      from: 1,
      to: 2,
      level: 'A1',
      errors: '*w Kraków*; w und na vertauscht; Konsonantenwechsel vergessen',
      formats: ['luecke', 'zuordnen'],
      description: 'Ort auf die Frage gdzie? und Thema mit o; oft mit Konsonantenwechsel (Kraków → w Krakowie).',
      examples: ['Mieszkam w Krakowie.', 'Jestem na dworcu.', 'Mówimy o filmie.']
    },
    {
      id: 'pl.num.liczebniki',
      label: 'Zahlwörter und Kasus',
      term: 'liczebniki: 2–4 + mianownik lm., od 5 + dopełniacz lm.',
      area: 'Zahlwort',
      from: 1,
      to: 3,
      level: 'A1/A2',
      contested: true,
      errors: '*pięć koty*; *dwa książki*',
      formats: ['luecke', 'tabelle', 'multiplechoice'],
      description: 'Nach 2, 3, 4 steht der Nominativ Plural, ab 5 der Genitiv Plural.',
      examples: ['dwa koty – pięć kotów', 'trzy książki – pięć książek']
    },
    {
      id: 'pl.pron.osobowe',
      label: 'Personal- und Possessivpronomen',
      term: 'zaimki osobowe (formy krótkie: mi, go, mu) i dzierżawcze',
      area: 'Pronomen',
      from: 1,
      to: 3,
      level: 'A1/A2',
      errors: 'Langform statt Kurzform (*Znasz jego?*); Possessivum nicht angeglichen',
      formats: ['luecke', 'tabelle', 'umformen'],
      description: 'Unbetonte Kurzformen der Personalpronomen; Possessiva mój, twój, jego, jej … richten sich nach dem Nomen.',
      examples: ['Znasz go?', 'Daj mi to.', 'mój brat, moja siostra']
    },
    {
      id: 'pl.nom.dopelniacz',
      label: 'Genitiv',
      term: 'dopełniacz (przeczenie, ilość, przynależność)',
      area: 'Nomen/Kasus',
      from: 1,
      to: 3,
      level: 'A1/A2',
      errors: 'nach Verneinung Akkusativ (*Nie mam czas*); Mengenangabe im Nominativ',
      formats: ['luecke', 'umformen', 'fehlerkorrektur'],
      description: 'Nach verneinten Verben mit Akkusativobjekt, nach Mengenangaben, für Besitz und nach vielen Präpositionen (do, z, bez, od).',
      examples: ['Nie mam czasu.', 'butelka wody', 'dom brata', 'Idę do sklepu.']
    },
    {
      id: 'pl.nom.narzednik',
      label: 'Instrumental',
      term: 'narzędnik (być + zawód, z + narzędnik, środek lokomocji)',
      area: 'Nomen/Kasus',
      from: 2,
      to: 3,
      level: 'A1/A2',
      errors: 'Beruf im Nominativ (*Jestem nauczyciel*); *z mama*',
      formats: ['luecke', 'umformen', 'zuordnen'],
      description: 'Nach być bei Beruf und Eigenschaft (Nomen), nach z (mit), für Verkehrsmittel.',
      examples: ['Jestem nauczycielem.', 'Idę z mamą.', 'Jadę autobusem.']
    },
    {
      id: 'pl.nom.liczba_mnoga',
      label: 'Plural (mit Personalform)',
      term: 'liczba mnoga: rodzaj męskoosobowy i niemęskoosobowy',
      area: 'Nomen',
      from: 2,
      to: 3,
      level: 'A1/A2',
      errors: 'Personalform bei Personen vergessen (*studenty*); Adjektiv/Verb nicht angepasst',
      formats: ['tabelle', 'luecke', 'formenbestimmen'],
      description: 'Männliche Personen haben eigene Pluralformen (-i/-y mit Konsonantenwechsel, -owie); auch Adjektiv und Verb (byli/były) folgen.',
      examples: ['student – studenci', 'pan – panowie', 'kot – koty', 'książka – książki']
    },
    {
      id: 'pl.verb.czas_przeszly',
      label: 'Präteritum',
      term: 'czas przeszły (formy rodzajowe: byłem/byłam)',
      area: 'Verb/Zeit',
      from: 2,
      to: 2,
      level: 'A2',
      errors: 'Genusform der Sprecherin/des Sprechers vertauscht; Personalendung fehlt',
      formats: ['tabelle', 'luecke', 'umformen'],
      description: 'l-Form mit Genus und Personalendung; im Plural männliche Personen (-li) gegenüber allen anderen (-ły).',
      examples: ['Wczoraj byłem w kinie.', 'Ona czytała książkę.', 'Byliśmy w domu.']
    },
    {
      id: 'pl.verb.aspekt',
      label: 'Verbalaspekt',
      term: 'aspekt dokonany i niedokonany',
      area: 'Verb',
      from: 2,
      to: 4,
      level: 'A2',
      contested: true,
      errors: 'Aspekt nach Tempus gewählt; vollendetes Verb in der Gegenwart gemeint',
      formats: ['multiplechoice', 'luecke', 'zuordnen'],
      description: 'Aspektpaare: unvollendet für Verlauf und Wiederholung, vollendet für den abgeschlossenen Einzelvorgang.',
      examples: ['robić – zrobić', 'pisać – napisać', 'Czytałem książkę. – Przeczytałem książkę.']
    },
    {
      id: 'pl.verb.czas_przyszly',
      label: 'Futur',
      term: 'czas przyszły złożony (będę + bezokolicznik) i prosty (dokonany)',
      area: 'Verb/Zeit',
      from: 2,
      to: 3,
      level: 'A2',
      errors: '*będę zrobić* (vollendetes Verb mit będę)',
      formats: ['luecke', 'umformen', 'multiplechoice'],
      description: 'Unvollendete Verben bilden das Futur mit będę, vollendete mit ihrer Präsensform.',
      examples: ['Jutro będę pracować.', 'Zrobię to jutro.']
    },
    {
      id: 'pl.verb.ruch',
      label: 'Verben der Bewegung',
      term: 'czasowniki ruchu: iść/chodzić, jechać/jeździć',
      area: 'Verb',
      from: 2,
      to: 3,
      level: 'A2',
      errors: 'iść für Fahrten; gerichtete und ungerichtete Form vertauscht',
      formats: ['multiplechoice', 'luecke'],
      description: 'Zu Fuß (iść/chodzić) oder mit Fahrzeug (jechać/jeździć); jeweils einmalig-gerichtet oder wiederholt.',
      examples: ['Idę do szkoły.', 'Codziennie chodzę do parku.', 'Jadę do Warszawy.']
    },
    {
      id: 'pl.nom.celownik',
      label: 'Dativ',
      term: 'celownik',
      area: 'Nomen/Kasus',
      from: 2,
      to: 3,
      level: 'A2',
      errors: 'indirektes Objekt im Akkusativ; *podobam się* für Gefallen',
      formats: ['luecke', 'tabelle', 'umformen'],
      description: 'Empfänger, Verben wie pomagać, dziękować und die Konstruktion podobać się.',
      examples: ['Daję prezent mamie.', 'Pomagam bratu.', 'Ten film mi się podoba.']
    },
    {
      id: 'pl.verb.tryb_rozkazujacy',
      label: 'Imperativ',
      term: 'tryb rozkazujący',
      area: 'Verb',
      from: 2,
      to: 3,
      level: 'A2',
      errors: 'vollendetes Verb im verneinten Imperativ (*Nie zrób tego!*)',
      formats: ['umformen', 'luecke'],
      description: 'Aufforderung aus dem Präsensstamm; verneint in der Regel mit unvollendetem Verb.',
      examples: ['Czytaj!', 'Otwórz okno!', 'Nie rób tego!']
    },
    {
      id: 'pl.adj.stopniowanie',
      label: 'Steigerung',
      term: 'stopniowanie przymiotników (-szy, -ejszy, naj-; niż)',
      area: 'Adjektiv',
      from: 3,
      to: 3,
      level: 'A2',
      errors: '*dobrzejszy*; Vergleich mit *jak* statt niż/od',
      formats: ['tabelle', 'luecke', 'satzbildung'],
      description: 'Komparativ auf -szy/-ejszy, Superlativ mit naj-; unregelmäßig dobry, zły, duży, mały.',
      examples: ['ładny – ładniejszy – najładniejszy', 'dobry – lepszy – najlepszy', 'Ona jest wyższa niż ja.']
    },
    {
      id: 'pl.verb.tryb_przypuszczajacy',
      label: 'Konditional',
      term: 'tryb przypuszczający (-by; gdyby)',
      area: 'Verb',
      from: 3,
      to: 4,
      level: 'A2/B1',
      errors: '-by am falschen Wort; gdyby-Satz im Präsens',
      formats: ['umformen', 'luecke', 'satzbildung'],
      description: 'l-Form + -by + Personalendung; Höflichkeit (chciałbym) und unwirkliche Bedingung mit gdyby.',
      examples: ['Chciałbym kawę.', 'Gdybym miał czas, pojechałbym nad morze.']
    },
    {
      id: 'pl.syn.zdania_wzgledne',
      label: 'Relativsätze',
      term: 'zdania względne z który, która, które',
      area: 'Satzbau',
      from: 3,
      to: 4,
      level: 'A2/B1',
      errors: 'który nicht nach Genus und Kasus angeglichen',
      formats: ['luecke', 'umformen'],
      description: 'który richtet sich im Genus nach dem Bezugswort, im Kasus nach seiner Rolle im Relativsatz.',
      examples: ['To jest chłopak, który mieszka obok.', 'Książka, którą czytam, jest ciekawa.']
    },
    {
      id: 'pl.verb.strona_bierna',
      label: 'Passiv und unpersönliche Formen',
      term: 'strona bierna (zostać/być + imiesłów), formy -no/-to, się',
      area: 'Verb',
      from: 4,
      to: 5,
      level: 'B1',
      errors: 'Passiv nach Deutsch mit *być* für Vorgänge; unpersönliches się vergessen',
      formats: ['umformen', 'markieren', 'uebersetzen'],
      description: 'Vorgangspassiv mit zostać, Zustandspassiv mit być; unpersönlich mit się oder den Formen auf -no/-to.',
      examples: ['Dom został zbudowany w 1990 roku.', 'Tutaj mówi się po polsku.', 'Sklep otwarto o ósmej.']
    },
    {
      id: 'pl.verb.imieslowy',
      label: 'Partizipien und Adverbialpartizip',
      term: 'imiesłowy przymiotnikowe i przysłówkowe (-ący, -ny/-ty, -ąc)',
      area: 'Verb',
      from: 5,
      to: 6,
      level: 'B1',
      receptive: true,
      errors: 'Adverbialpartizip mit anderem Subjekt als im Hauptsatz',
      formats: ['markieren', 'umformen', 'uebersetzen'],
      description: 'Partizipien der Schriftsprache verstehen und in Nebensätze auflösen.',
      examples: ['czytając gazetę', 'zamknięte drzwi', 'śpiące dziecko']
    }
  ]
)

// ---------------------------------------------------------------- Tschechisch

const TSCHECHISCH = fach(
  'tschechisch',
  'Faustregel (übliche Anfängerprogression Tschechisch als Fremdsprache; GER-Einordnung angelehnt an die Referenzbeschreibungen des Tschechischen für A1/A2/B1, nicht einzeln abgeglichen)',
  [
    {
      id: 'cs.nom.rod',
      label: 'Genus und Belebtheit',
      term: 'rod: mužský životný/neživotný, ženský, střední (ten, ta, to)',
      area: 'Nomen',
      from: 1,
      to: 1,
      level: 'A1',
      errors: 'Genus nach Deutsch (*ta stůl*); Belebtheit übersehen',
      formats: ['zuordnen', 'tabelle', 'luecke'],
      description: 'Maskulinum meist auf Konsonant (belebt/unbelebt), Femininum auf -a/-e, Neutrum auf -o/-e/-í.',
      examples: ['ten stůl, ta kniha, to okno', 'ten pán, ta žena, to město']
    },
    {
      id: 'cs.verb.prezens',
      label: 'Präsens: Konjugationstypen, být und mít',
      term: 'přítomný čas (typ -á-, -í-, -e-), být, mít',
      area: 'Verb',
      from: 1,
      to: 1,
      level: 'A1',
      errors: 'Typen vertauscht (*mluvám*); být nicht konjugiert',
      formats: ['tabelle', 'luecke', 'formenbestimmen'],
      description: 'Drei Grundtypen nach der 1. Person Singular (dělám, mluvím, jdu); být und mít unregelmäßig.',
      examples: ['dělám, děláš', 'mluvím, mluvíš', 'jsem, jsi', 'mám, máš']
    },
    {
      id: 'cs.syn.negace',
      label: 'Verneinung',
      term: 'zápor ne- (psaný dohromady), dvojí zápor',
      area: 'Satzbau',
      from: 1,
      to: 1,
      level: 'A1',
      errors: 'ne getrennt geschrieben (*ne mám*); einfache Verneinung nach Deutsch (*Nikdo nic ví*)',
      formats: ['umformen', 'fehlerkorrektur', 'luecke'],
      description: 'ne- wird ans Verb geschrieben; mit nikdo, nic, nikdy bleibt auch das Verb verneint.',
      examples: ['Nemám čas.', 'Nikdo nic neví.']
    },
    {
      id: 'cs.adj.shoda',
      label: 'Adjektive: harte und weiche Endungen',
      term: 'přídavná jména tvrdá (-ý, -á, -é) a měkká (-í)',
      area: 'Adjektiv',
      from: 1,
      to: 2,
      level: 'A1',
      errors: 'Endung nicht angeglichen (*nový kniha*)',
      formats: ['luecke', 'tabelle', 'fehlerkorrektur'],
      description: 'Harte Adjektive ändern die Endung nach Genus, weiche (-í) bleiben im Nominativ gleich.',
      examples: ['nový dům, nová škola, nové auto', 'moderní dům, moderní škola']
    },
    {
      id: 'cs.nom.akuzativ',
      label: 'Akkusativ',
      term: '4. pád (akuzativ)',
      area: 'Nomen/Kasus',
      from: 1,
      to: 2,
      level: 'A1',
      errors: 'Objekt im Nominativ (*Mám sestra*); belebtes Maskulinum ohne -a',
      formats: ['luecke', 'tabelle', 'umformen'],
      description: 'Direktes Objekt; Femininum -u, belebtes Maskulinum -a/-e.',
      examples: ['Mám bratra.', 'Vidím kočku.', 'Piju kávu.']
    },
    {
      id: 'cs.nom.lokal',
      label: 'Lokativ',
      term: '6. pád (lokál) s v, na, o',
      area: 'Nomen/Kasus',
      from: 1,
      to: 2,
      level: 'A1/A2',
      errors: '*v Praha*; v und na vertauscht; Konsonantenwechsel vergessen (*v Prahe*)',
      formats: ['luecke', 'zuordnen'],
      description: 'Ort auf die Frage kde? und Thema mit o; oft mit Konsonantenwechsel (Praha → v Praze).',
      examples: ['Bydlím v Praze.', 'Jsem na nádraží.', 'Mluvíme o filmu.']
    },
    {
      id: 'cs.num.cislovky',
      label: 'Zahlwörter und Kasus',
      term: 'číslovky: 2–4 + 1. pád mn. č., od 5 + 2. pád mn. č.',
      area: 'Zahlwort',
      from: 1,
      to: 3,
      level: 'A1/A2',
      contested: true,
      errors: '*pět knihy*; dva/dvě nach Genus vertauscht',
      formats: ['luecke', 'tabelle', 'multiplechoice'],
      description: 'Nach 2, 3, 4 der Nominativ Plural, ab 5 der Genitiv Plural; dva (m.) und dvě (f., n.).',
      examples: ['dva psi – pět psů', 'tři knihy – pět knih', 'dvě auta']
    },
    {
      id: 'cs.pron.osobni',
      label: 'Personal- und Possessivpronomen, Stellung',
      term: 'osobní a přivlastňovací zájmena; příklonky na druhém místě',
      area: 'Pronomen',
      from: 1,
      to: 3,
      level: 'A1/A2',
      errors: 'Kurzformen nicht an zweiter Stelle; *jeho* statt ho als unbetontes Objekt',
      formats: ['luecke', 'sortieren', 'umformen'],
      description: 'Unbetonte Formen (mi, ho, se, jsem) stehen an zweiter Satzstelle; Possessiva můj, tvůj, jeho, její … richten sich nach dem Nomen.',
      examples: ['Znáš ho?', 'Dej mi to.', 'můj bratr, moje sestra']
    },
    {
      id: 'cs.nom.genitiv',
      label: 'Genitiv',
      term: '2. pád (genitiv) s do, z, u, bez; množství',
      area: 'Nomen/Kasus',
      from: 2,
      to: 3,
      level: 'A2',
      errors: 'Richtung mit Akkusativ (*Jdu do škola*); Mengenangabe im Nominativ',
      formats: ['luecke', 'umformen', 'zuordnen'],
      description: 'Nach do, z, u, bez, od und nach Mengenangaben; für Besitz nachgestellt.',
      examples: ['Jdu do školy.', 'Jsem z Německa.', 'láhev vody']
    },
    {
      id: 'cs.nom.instrumental',
      label: 'Instrumental',
      term: '7. pád (instrumentál) s s, před, za; jet čím',
      area: 'Nomen/Kasus',
      from: 2,
      to: 3,
      level: 'A2',
      errors: '*jedu s autobusem*; *s kamarád*',
      formats: ['luecke', 'umformen'],
      description: 'Begleitung mit s, Verkehrsmittel ohne Präposition, Ort mit před, za, nad, pod.',
      examples: ['Jedu autobusem.', 'Jdu s kamarádem.', 'Čekám před školou.']
    },
    {
      id: 'cs.nom.dativ',
      label: 'Dativ',
      term: '3. pád (dativ)',
      area: 'Nomen/Kasus',
      from: 2,
      to: 3,
      level: 'A2',
      errors: 'Empfänger im Akkusativ; *líbím se* für Gefallen',
      formats: ['luecke', 'tabelle', 'umformen'],
      description: 'Empfänger, Verben wie pomáhat, děkovat und die Konstruktion líbit se.',
      examples: ['Dám to mamince.', 'Pomáhám bratrovi.', 'Ten film se mi líbí.']
    },
    {
      id: 'cs.nom.plural',
      label: 'Plural',
      term: 'množné číslo (životné: -i, -ové)',
      area: 'Nomen',
      from: 2,
      to: 3,
      level: 'A1/A2',
      errors: 'belebte Maskulina ohne -i/-ové; Konsonantenwechsel (*studenty*)',
      formats: ['tabelle', 'luecke', 'formenbestimmen'],
      description: 'Belebte Maskulina auf -i (mit Konsonantenwechsel) oder -ové; auch Adjektiv und Verb (byli/byly) folgen.',
      examples: ['student – studenti', 'pán – pánové', 'žena – ženy', 'město – města']
    },
    {
      id: 'cs.verb.minuly_cas',
      label: 'Präteritum',
      term: 'minulý čas (-l + jsem, jsi …)',
      area: 'Verb/Zeit',
      from: 2,
      to: 2,
      level: 'A2',
      errors: 'Hilfsverb in der 3. Person (*on je byl*); jsem nicht an zweiter Stelle',
      formats: ['tabelle', 'luecke', 'umformen'],
      description: 'l-Form mit Genus; in der 1. und 2. Person mit jsem, jsi …, in der 3. Person ohne Hilfsverb.',
      examples: ['Včera jsem byl v kině.', 'Byla jsem doma.', 'Četli jsme knihu.']
    },
    {
      id: 'cs.verb.vid',
      label: 'Verbalaspekt',
      term: 'vid dokonavý a nedokonavý',
      area: 'Verb',
      from: 2,
      to: 4,
      level: 'A2',
      contested: true,
      errors: 'Aspekt nach Tempus gewählt; vollendetes Verb für Gegenwart gemeint',
      formats: ['multiplechoice', 'luecke', 'zuordnen'],
      description: 'Aspektpaare: unvollendet für Verlauf und Wiederholung, vollendet für den abgeschlossenen Einzelvorgang.',
      examples: ['dělat – udělat', 'psát – napsat', 'Celý den jsem psal dopis. – Napsal jsem dopis.']
    },
    {
      id: 'cs.verb.budouci',
      label: 'Futur',
      term: 'budoucí čas (budu + infinitiv; dokonavé sloveso)',
      area: 'Verb/Zeit',
      from: 2,
      to: 3,
      level: 'A2',
      errors: '*budu udělat*; půjdu/pojedu nicht als Futur erkannt',
      formats: ['luecke', 'umformen', 'multiplechoice'],
      description: 'Unvollendete Verben mit budu, vollendete mit ihrer Präsensform; Bewegungsverben mit pů-/po-.',
      examples: ['Zítra budu pracovat.', 'Udělám to zítra.', 'Půjdu do kina.']
    },
    {
      id: 'cs.verb.pohyb',
      label: 'Verben der Bewegung',
      term: 'slovesa pohybu: jít/chodit, jet/jezdit',
      area: 'Verb',
      from: 2,
      to: 3,
      level: 'A2',
      errors: 'jít für Fahrten; gerichtete und wiederholte Form vertauscht',
      formats: ['multiplechoice', 'luecke'],
      description: 'Zu Fuß (jít/chodit) oder mit Fahrzeug (jet/jezdit); jeweils einmalig-gerichtet oder wiederholt.',
      examples: ['Jdu do školy.', 'Každý den chodím do parku.', 'Jedu do Brna.']
    },
    {
      id: 'cs.pron.reflexivni',
      label: 'Reflexivpronomen se, si und svůj',
      term: 'zvratná zájmena se/si; přivlastňovací svůj',
      area: 'Pronomen',
      from: 2,
      to: 3,
      level: 'A2',
      errors: 'se und si vertauscht; *jeho* statt svůj bei Bezug auf das Subjekt',
      formats: ['luecke', 'multiplechoice', 'fehlerkorrektur'],
      description: 'se (Akkusativ) und si (Dativ) an zweiter Stelle; svůj, wenn der Besitzer das Subjekt ist.',
      examples: ['Myju se.', 'Koupím si kávu.', 'Vzal svou tašku.']
    },
    {
      id: 'cs.verb.imperativ',
      label: 'Imperativ',
      term: 'rozkazovací způsob',
      area: 'Verb',
      from: 2,
      to: 3,
      level: 'A2',
      errors: 'vollendetes Verb im verneinten Imperativ (*Neudělej to!* als Verbot)',
      formats: ['umformen', 'luecke'],
      description: 'Aufforderung aus dem Präsensstamm; Verbote in der Regel mit unvollendetem Verb.',
      examples: ['Pojď sem!', 'Otevři okno!', 'Nedělej to!']
    },
    {
      id: 'cs.adj.stupnovani',
      label: 'Steigerung',
      term: 'stupňování přídavných jmen (-ší, -ejší, nej-; než)',
      area: 'Adjektiv',
      from: 3,
      to: 3,
      level: 'A2',
      errors: '*dobřejší*; Vergleich mit *jako* statt než',
      formats: ['tabelle', 'luecke', 'satzbildung'],
      description: 'Komparativ auf -ší/-ejší, Superlativ mit nej-; unregelmäßig dobrý, špatný, velký, malý.',
      examples: ['mladý – mladší – nejmladší', 'dobrý – lepší – nejlepší', 'Je starší než já.']
    },
    {
      id: 'cs.verb.kondicional',
      label: 'Konditional',
      term: 'podmiňovací způsob (bych, bys, by …; kdyby)',
      area: 'Verb',
      from: 3,
      to: 4,
      level: 'A2/B1',
      errors: 'bych nicht nach Person gebildet (*já by*); kdyby-Satz im Präsens',
      formats: ['umformen', 'luecke', 'satzbildung'],
      description: 'l-Form + bych, bys, by, bychom, byste, by; Höflichkeit und unwirkliche Bedingung mit kdyby.',
      examples: ['Chtěl bych kávu.', 'Kdybych měl čas, jel bych k moři.']
    },
    {
      id: 'cs.syn.vztazne_vety',
      label: 'Relativsätze',
      term: 'vztažné věty s který, která, které',
      area: 'Satzbau',
      from: 3,
      to: 4,
      level: 'A2/B1',
      errors: 'který nicht nach Genus und Kasus angeglichen',
      formats: ['luecke', 'umformen'],
      description: 'který richtet sich im Genus nach dem Bezugswort, im Kasus nach seiner Rolle im Relativsatz.',
      examples: ['To je kluk, který bydlí vedle.', 'Kniha, kterou čtu, je zajímavá.']
    },
    {
      id: 'cs.verb.pasivum',
      label: 'Passiv',
      term: 'trpný rod (být + příčestí trpné; zvratné pasivum se)',
      area: 'Verb',
      from: 4,
      to: 5,
      level: 'B1',
      errors: 'Passiv nach Deutsch mit *být* für jeden Vorgang; se-Passiv nicht erkannt',
      formats: ['umformen', 'markieren', 'uebersetzen'],
      description: 'Passiv mit být + Partizip (postaven, napsán) oder reflexiv mit se.',
      examples: ['Dům byl postaven v roce 1990.', 'Tady se mluví česky.']
    }
  ]
)

// ---------------------------------------------------------------- Portugiesisch

const PORTUGIESISCH = fach(
  'portugiesisch',
  'Faustregel (übliche Anfängerprogression Portugiesisch als Fremdsprache; GER-Einordnung angelehnt an das Referenzprogramm des Camões-Instituts für Portugiesisch als Fremdsprache, nicht einzeln abgeglichen)',
  [
    {
      id: 'pt.nom.genero',
      label: 'Artikel, Genus und Plural',
      term: 'artigo definido/indefinido; género; plural (-s, -ões, -ais)',
      area: 'Nomen',
      from: 1,
      to: 1,
      level: 'A1',
      errors: 'Genus nach Deutsch (*o casa*); Plural auf -l/-ão (*animals*)',
      formats: ['zuordnen', 'tabelle', 'luecke'],
      description: 'o/a, os/as, um/uma; Plural meist auf -s, besondere Formen bei -l, -ão, -m.',
      examples: ['o livro – os livros', 'a casa – as casas', 'o animal – os animais']
    },
    {
      id: 'pt.verb.presente_reg',
      label: 'Präsens der regelmäßigen Verben',
      term: 'presente do indicativo (-ar, -er, -ir)',
      area: 'Verb',
      from: 1,
      to: 1,
      level: 'A1',
      errors: 'Endungen der Konjugationen vertauscht; tu/você nach Varietät nicht beachtet',
      formats: ['tabelle', 'luecke', 'formenbestimmen'],
      description: 'Drei Konjugationen; in Portugal ist tu üblich, in Brasilien meist você (3. Person).',
      examples: ['Eu falo português.', 'Nós comemos às oito.', 'Eles partem amanhã.']
    },
    {
      id: 'pt.verb.presente_irreg',
      label: 'Unregelmäßige Verben im Präsens',
      term: 'verbos irregulares: ter, ir, fazer, poder, querer',
      area: 'Verb',
      from: 1,
      to: 1,
      level: 'A1',
      errors: 'regelmäßig gebildet (*fazo*, *io*)',
      formats: ['tabelle', 'luecke'],
      description: 'Häufige unregelmäßige Verben mit eigenen Formen in der 1. Person.',
      examples: ['Tenho dois irmãos.', 'Vou à escola.', 'Faço os trabalhos de casa.']
    },
    {
      id: 'pt.verb.ser_estar',
      label: 'ser, estar und ficar',
      term: 'ser / estar / ficar',
      area: 'Verb',
      from: 1,
      to: 2,
      level: 'A1',
      contested: true,
      errors: 'ser für Zustände (*Ela é cansada*); ficar für Lage nicht genutzt',
      formats: ['multiplechoice', 'luecke', 'fehlerkorrektur'],
      description: 'ser für Wesen und Merkmal, estar für Zustand und Befinden, ficar für feste Lage.',
      examples: ['Ela é alta.', 'Ela está cansada.', 'Lisboa fica em Portugal.']
    },
    {
      id: 'pt.nom.contracoes',
      label: 'Präposition und Artikel verschmolzen',
      term: 'contrações: no, na, do, da, ao, à, pelo',
      area: 'Präposition',
      from: 1,
      to: 2,
      level: 'A1',
      errors: '*em o*, *de a*; *a a* statt à',
      formats: ['luecke', 'tabelle', 'fehlerkorrektur'],
      description: 'em, de, a, por verschmelzen mit dem bestimmten Artikel.',
      examples: ['Moro no Porto.', 'Venho da escola.', 'Vou ao cinema.']
    },
    {
      id: 'pt.adj.concordancia',
      label: 'Adjektive: Übereinstimmung und Stellung',
      term: 'concordância do adjetivo',
      area: 'Adjektiv',
      from: 1,
      to: 1,
      level: 'A1',
      errors: 'Adjektiv vorangestellt nach Deutsch; Endung nicht angeglichen',
      formats: ['luecke', 'fehlerkorrektur', 'umformen'],
      description: 'Das Adjektiv steht meist nach dem Nomen und richtet sich nach Genus und Zahl.',
      examples: ['um carro novo', 'uma casa bonita', 'os livros interessantes']
    },
    {
      id: 'pt.pron.possessivos',
      label: 'Possessivbegleiter',
      term: 'possessivos (o meu, a minha; dele, dela)',
      area: 'Pronomen',
      from: 1,
      to: 2,
      level: 'A1',
      errors: 'Artikel weggelassen (PT); seu mehrdeutig statt dele/dela',
      formats: ['luecke', 'tabelle', 'multiplechoice'],
      description: 'In Portugal meist mit Artikel (o meu); dele/dela machen den Besitzer eindeutig.',
      examples: ['o meu irmão', 'a minha casa', 'o carro dele']
    },
    {
      id: 'pt.verb.progressivo',
      label: 'Verlaufsform',
      term: 'estar a + infinitivo (PT) / estar + gerúndio (BR)',
      area: 'Verb/Zeit',
      from: 1,
      to: 2,
      level: 'A1/A2',
      errors: 'Formen der Varietäten gemischt; Präsens statt Verlaufsform',
      formats: ['umformen', 'luecke'],
      description: 'Handlung im Verlauf: europäisch estar a + Infinitiv, brasilianisch estar + Gerúndio.',
      examples: ['Estou a estudar. (PT)', 'Estou estudando. (BR)']
    },
    {
      id: 'pt.verb.ir_futuro',
      label: 'Nahe Zukunft mit ir',
      term: 'ir + infinitivo',
      area: 'Verb/Zeit',
      from: 1,
      to: 2,
      level: 'A1',
      errors: 'ir nicht konjugiert; *vou a visitar*',
      formats: ['luecke', 'satzbildung'],
      description: 'Pläne und Vorhaben mit ir im Präsens + Infinitiv.',
      examples: ['Amanhã vou visitar a minha avó.', 'Vamos jogar à bola.']
    },
    {
      id: 'pt.verb.preterito_perfeito',
      label: 'Pretérito perfeito simples',
      term: 'pretérito perfeito simples',
      area: 'Verb/Zeit',
      from: 2,
      to: 3,
      level: 'A2',
      errors: 'unregelmäßige Formen (*fazi*); ir und ser (fui) nicht unterschieden aus dem Zusammenhang',
      formats: ['tabelle', 'luecke', 'umformen'],
      description: 'Abgeschlossene Handlung in der Vergangenheit; ir und ser haben dieselben Formen.',
      examples: ['Ontem comi peixe.', 'Fomos à praia.', 'Ela falou com o professor.']
    },
    {
      id: 'pt.verb.imperfeito',
      label: 'Imperfeito und Abgrenzung zum Perfeito',
      term: 'pretérito imperfeito vs. perfeito',
      area: 'Verb/Zeit',
      from: 2,
      to: 4,
      level: 'A2',
      contested: true,
      errors: 'Zeitwahl nach deutschem Perfekt/Präteritum',
      formats: ['multiplechoice', 'luecke', 'satzanalyse'],
      description: 'Imperfeito für Hintergrund, Gewohnheit und Beschreibung; Perfeito für abgeschlossene Ereignisse.',
      examples: ['Quando era pequeno, morava em Faro.', 'Estava a ler quando ele chegou.']
    },
    {
      id: 'pt.adj.comparacao',
      label: 'Steigerung und Vergleich',
      term: 'comparativos e superlativos (mais … do que, tão … como/quanto)',
      area: 'Adjektiv',
      from: 2,
      to: 2,
      level: 'A2',
      errors: '*mais bom*; Vergleich mit *como* bei Ungleichheit',
      formats: ['tabelle', 'luecke', 'satzbildung'],
      description: 'mais/menos … (do) que; tão … como (PT) bzw. quanto (BR); melhor, pior, maior, menor.',
      examples: ['Ele é mais alto do que eu.', 'É o melhor aluno da turma.', 'Ela é tão simpática como a irmã.']
    },
    {
      id: 'pt.pron.objeto',
      label: 'Objektpronomen und ihre Stellung',
      term: 'pronomes átonos: ênclise (PT) / próclise (BR)',
      area: 'Pronomen',
      from: 2,
      to: 4,
      level: 'A2',
      contested: true,
      errors: 'Stellung nach Deutsch; nach Verneinung trotzdem Bindestrich (*Não vejo-o*)',
      formats: ['umformen', 'luecke', 'fehlerkorrektur'],
      description: 'In Portugal steht das Pronomen im Aussagesatz hinter dem Verb, nach Verneinung davor; in Brasilien meist davor.',
      examples: ['Vejo-o amanhã. (PT)', 'Eu o vejo amanhã. (BR)', 'Não o vejo.']
    },
    {
      id: 'pt.verb.imperativo',
      label: 'Imperativ',
      term: 'imperativo (tu, você, vocês)',
      area: 'Verb',
      from: 2,
      to: 3,
      level: 'A2',
      errors: 'verneinter Imperativ mit Indikativform (*Não falas!*)',
      formats: ['umformen', 'luecke'],
      description: 'Bejaht für tu aus dem Präsens, für você/vocês und verneint mit den Formen des Konjunktivs.',
      examples: ['Fala mais devagar!', 'Abra a janela, por favor.', 'Não fales tão alto!']
    },
    {
      id: 'pt.verb.reflexivos',
      label: 'Reflexive Verben',
      term: 'verbos pronominais (levantar-se)',
      area: 'Verb',
      from: 2,
      to: 2,
      level: 'A2',
      errors: 'Pronomen weggelassen; Stellung der Varietäten gemischt',
      formats: ['luecke', 'tabelle'],
      description: 'Reflexivpronomen me, te, se, nos, se; Stellung wie die Objektpronomen.',
      examples: ['Levanto-me às sete. (PT)', 'Eu me levanto às sete. (BR)']
    },
    {
      id: 'pt.verb.futuro_condicional',
      label: 'Futur I und Konditional',
      term: 'futuro do presente, condicional (futuro do pretérito)',
      area: 'Verb/Zeit',
      from: 3,
      to: 4,
      level: 'A2/B1',
      errors: 'unregelmäßige Stämme (*fazerei*); Konditional nach Deutsch umschrieben',
      formats: ['tabelle', 'luecke', 'umformen'],
      description: 'Endungen am Infinitiv; unregelmäßig fazer, dizer, trazer. Konditional für Höflichkeit und Hypothesen.',
      examples: ['Amanhã choverá.', 'Gostaria de um café.', 'Eu compraria uma casa.']
    },
    {
      id: 'pt.syn.relativos',
      label: 'Relativpronomen',
      term: 'pronomes relativos: que, quem, onde, o qual',
      area: 'Satzbau',
      from: 3,
      to: 4,
      level: 'A2/B1',
      errors: 'quem ohne Präposition; *o livro quem*',
      formats: ['luecke', 'umformen'],
      description: 'que als Standard, quem nach Präposition für Personen, onde für Orte.',
      examples: ['O livro que li é bom.', 'A cidade onde moro é pequena.', 'A professora com quem falei é nova.']
    },
    {
      id: 'pt.verb.conjuntivo_presente',
      label: 'Konjunktiv Präsens',
      term: 'presente do conjuntivo (PT) / subjuntivo (BR)',
      area: 'Verb',
      from: 4,
      to: 5,
      level: 'B1',
      errors: 'Indikativ nach Wunsch und Zweifel; Stamm nicht aus der 1. Person gebildet',
      formats: ['luecke', 'multiplechoice', 'umformen'],
      description: 'Nach Ausdrücken des Wunsches, Gefühls, Zweifels und nach talvez.',
      examples: ['Espero que venhas.', 'É importante que estudes.', 'Talvez ele chegue tarde.']
    },
    {
      id: 'pt.verb.perfeito_composto',
      label: 'Pretérito perfeito composto',
      term: 'pretérito perfeito composto (ter + particípio)',
      area: 'Verb/Zeit',
      from: 4,
      to: 5,
      level: 'B1',
      errors: 'wie das deutsche Perfekt für einmalige Ereignisse verwendet',
      formats: ['multiplechoice', 'luecke', 'satzanalyse'],
      description: 'Wiederholte oder andauernde Handlung bis jetzt – nicht für ein einzelnes abgeschlossenes Ereignis.',
      examples: ['Tenho estudado muito ultimamente.', 'Ontem estudei muito.']
    },
    {
      id: 'pt.verb.infinitivo_pessoal',
      label: 'Persönlicher Infinitiv',
      term: 'infinitivo pessoal (flexionado)',
      area: 'Verb',
      from: 4,
      to: 5,
      level: 'B1',
      errors: 'Personalendung am Infinitiv vergessen; Nebensatz statt Infinitiv erzwungen',
      formats: ['luecke', 'umformen', 'markieren'],
      description: 'Infinitiv mit Personalendung, wenn er ein eigenes Subjekt hat.',
      examples: ['É melhor irmos agora.', 'Antes de saíres, fecha a janela.']
    },
    {
      id: 'pt.verb.passiva',
      label: 'Passiv',
      term: 'voz passiva (ser + particípio; passiva com se)',
      area: 'Verb',
      from: 4,
      to: 5,
      level: 'B1',
      errors: 'Partizip nicht angeglichen; se-Passiv nicht im Plural (*Vende-se casas*)',
      formats: ['umformen', 'markieren', 'uebersetzen'],
      description: 'ser + angeglichenes Partizip; unpersönlich mit se, das Verb richtet sich nach dem Nomen.',
      examples: ['O museu foi construído em 1900.', 'Vendem-se casas.']
    },
    {
      id: 'pt.verb.conjuntivo_imperfeito_futuro',
      label: 'Konjunktiv Imperfekt und Futur',
      term: 'imperfeito e futuro do conjuntivo (se, quando)',
      area: 'Verb',
      from: 5,
      to: 6,
      level: 'B1',
      errors: 'Indikativ nach se/quando mit Zukunftsbezug; Konditional im se-Satz',
      formats: ['luecke', 'umformen', 'satzbildung'],
      description: 'Unwirkliche Bedingung mit se + Konjunktiv Imperfekt; Zukünftiges nach se, quando mit dem Konjunktiv Futur.',
      examples: ['Se eu tivesse tempo, viajaria.', 'Quando chegares, liga-me.', 'Se puderes, vem cedo.']
    }
  ]
)

// ---------------------------------------------------------------- Türkisch

const TUERKISCH = fach(
  'tuerkisch',
  'Faustregel (übliche Anfängerprogression Türkisch als Fremdsprache; GER-Einordnung angelehnt an die Lehrprogramme des Yunus-Emre-Instituts A1–C1, nicht einzeln abgeglichen)',
  [
    {
      id: 'tr.laut.vokalharmonie',
      label: 'Vokalharmonie und Konsonantenwechsel',
      term: 'büyük ve küçük ünlü uyumu; ünsüz yumuşaması/benzeşmesi',
      area: 'Laut/Schrift',
      from: 1,
      to: 1,
      level: 'A1',
      errors: 'Suffix nicht an den letzten Vokal angepasst (*evlar*); k/ğ, p/b nicht gewechselt (*kitapı*)',
      formats: ['zuordnen', 'tabelle', 'luecke'],
      description: 'Suffixvokale richten sich nach dem letzten Vokal (e/a bzw. i/ı/ü/u); vor Vokal wird p, ç, t, k oft zu b, c, d, ğ.',
      examples: ['evler – kitaplar', 'evde – okulda', 'kitap – kitabı']
    },
    {
      id: 'tr.nom.cogul',
      label: 'Plural',
      term: 'çoğul eki -ler/-lar',
      area: 'Nomen',
      from: 1,
      to: 1,
      level: 'A1',
      errors: 'Plural nach Zahlwort (*iki kitaplar*)',
      formats: ['tabelle', 'luecke', 'fehlerkorrektur'],
      description: 'Plural mit -ler/-lar; nach Zahlwörtern bleibt das Nomen im Singular.',
      examples: ['ev – evler', 'araba – arabalar', 'iki kitap']
    },
    {
      id: 'tr.syn.ek_fiil',
      label: 'Personalendungen beim Nomen („sein") und değil',
      term: 'ek-fiil / kişi ekleri (-(y)Im, -sIn …), değil',
      area: 'Satzbau',
      from: 1,
      to: 1,
      level: 'A1',
      errors: 'eigenes Wort für „sein" gesucht; Endung nicht harmonisiert (*öğrenciyım*)',
      formats: ['luecke', 'tabelle', 'umformen'],
      description: 'Das Prädikatsnomen bekommt die Personalendung; verneint mit değil + Endung.',
      examples: ['Öğrenciyim.', 'Yorgun değilim.', 'Doktor musun?']
    },
    {
      id: 'tr.syn.soru',
      label: 'Fragepartikel mi',
      term: 'soru eki mi/mı/mu/mü',
      area: 'Satzbau',
      from: 1,
      to: 1,
      level: 'A1',
      errors: 'mi zusammengeschrieben (*geliyormusun*); Vokal nicht harmonisiert',
      formats: ['umformen', 'fehlerkorrektur', 'luecke'],
      description: 'Die Fragepartikel steht getrennt hinter dem erfragten Wort und folgt der Vokalharmonie.',
      examples: ['Bu senin kitabın mı?', 'Geliyor musun?']
    },
    {
      id: 'tr.syn.var_yok',
      label: 'var und yok',
      term: 'var / yok',
      area: 'Satzbau',
      from: 1,
      to: 1,
      level: 'A1',
      errors: '*değil* statt yok; „haben" als Verb gesucht',
      formats: ['luecke', 'satzbildung', 'uebersetzen'],
      description: 'Vorhandensein und „haben" (mit Possessivendung) mit var bzw. yok.',
      examples: ['Evde kedi var.', 'Param yok.']
    },
    {
      id: 'tr.verb.simdiki',
      label: 'Präsens auf -iyor',
      term: 'şimdiki zaman -(I)yor',
      area: 'Verb/Zeit',
      from: 1,
      to: 1,
      level: 'A1',
      errors: 'Endvokal des Stamms nicht getilgt (*okuiyor*); Personalendung fehlt',
      formats: ['tabelle', 'luecke', 'formenbestimmen'],
      description: 'Verbstamm + -(I)yor + Personalendung; ein Endvokal -a/-e des Stamms wird zu ı/i/u/ü.',
      examples: ['Ben geliyorum.', 'Ne yapıyorsun?', 'Kitap okuyorlar.']
    },
    {
      id: 'tr.verb.olumsuz',
      label: 'Verneinung am Verb',
      term: 'olumsuzluk eki -mA-',
      area: 'Verb',
      from: 1,
      to: 2,
      level: 'A1',
      errors: '*değil* beim Verb; -me- an falscher Stelle',
      formats: ['umformen', 'luecke'],
      description: 'Das Verb wird mit -ma/-me direkt nach dem Stamm verneint.',
      examples: ['Gelmiyorum.', 'Gitmedim.', 'Anlamıyorum.']
    },
    {
      id: 'tr.nom.yer_hal',
      label: 'Lokativ, Dativ und Ablativ',
      term: 'bulunma, yönelme, ayrılma hâli (-DA, -(y)A, -DAn)',
      area: 'Nomen/Kasus',
      from: 1,
      to: 2,
      level: 'A1',
      errors: 'd/t nach stimmlosem Laut (*kitapda*); Richtung mit Lokativ (*okulda gidiyorum*)',
      formats: ['luecke', 'tabelle', 'zuordnen'],
      description: 'Wo? -de/-da, wohin? -(y)e/-(y)a, woher? -den/-dan; Eigennamen mit Apostroph.',
      examples: ['Okuldayım.', 'Eve gidiyorum.', "İstanbul'dan geliyorum."]
    },
    {
      id: 'tr.nom.iyelik',
      label: 'Possessivendungen',
      term: 'iyelik ekleri (evim, evin, evi …)',
      area: 'Nomen',
      from: 1,
      to: 2,
      level: 'A1/A2',
      errors: 'Bindekonsonant vergessen (*arabaım*); Endung nicht harmonisiert',
      formats: ['tabelle', 'luecke', 'formenbestimmen'],
      description: 'Besitz wird am Nomen angezeigt; nach Vokal ohne Bindevokal, in der 3. Person mit -s-.',
      examples: ['evim, evin, evi', 'benim annem', 'arabası']
    },
    {
      id: 'tr.nom.belirtme',
      label: 'Akkusativ des bestimmten Objekts',
      term: 'belirtme hâli -(y)I',
      area: 'Nomen/Kasus',
      from: 2,
      to: 2,
      level: 'A1/A2',
      errors: 'Akkusativ bei unbestimmtem Objekt bzw. vergessen beim bestimmten',
      formats: ['multiplechoice', 'luecke', 'fehlerkorrektur'],
      description: 'Bestimmte Objekte stehen im Akkusativ, unbestimmte ohne Endung.',
      examples: ['Kitabı okudum.', 'Kitap okudum.', "Ali'yi gördüm."]
    },
    {
      id: 'tr.verb.gecmis_di',
      label: 'Vergangenheit auf -di',
      term: 'görülen geçmiş zaman -DI',
      area: 'Verb/Zeit',
      from: 2,
      to: 2,
      level: 'A1/A2',
      errors: 'd/t nicht angeglichen (*gitdim*); Personalendungen der -iyor-Zeit übernommen',
      formats: ['tabelle', 'luecke', 'umformen'],
      description: 'Erlebte, abgeschlossene Vergangenheit; eigene Personalendungen (-m, -n, –, -k, -nIz, -lAr).',
      examples: ['Dün sinemaya gittim.', 'Ne yaptın?', 'Evde değildik.']
    },
    {
      id: 'tr.verb.gelecek',
      label: 'Futur',
      term: 'gelecek zaman -(y)AcAk',
      area: 'Verb/Zeit',
      from: 2,
      to: 2,
      level: 'A2',
      errors: 'k/ğ vor Vokal nicht gewechselt (*gelecekim*)',
      formats: ['tabelle', 'luecke'],
      description: 'Stamm + -ecek/-acak + Personalendung; vor vokalischer Endung wird k zu ğ.',
      examples: ['Yarın geleceğim.', 'Ne yapacaksın?']
    },
    {
      id: 'tr.syn.tamlama',
      label: 'Genitivverbindung',
      term: 'isim tamlaması (belirtili / belirtisiz)',
      area: 'Nomen',
      from: 2,
      to: 3,
      level: 'A2',
      errors: 'Possessivendung am zweiten Nomen vergessen (*okulun bahçe*)',
      formats: ['luecke', 'umformen', 'uebersetzen'],
      description: 'Besitzer im Genitiv, Besitz mit Possessivendung; ohne Genitiv als fester Begriff.',
      examples: ['okulun bahçesi', 'Türkçe öğretmeni', "Ali'nin annesi"]
    },
    {
      id: 'tr.verb.genis_zaman',
      label: 'Aorist (Gewohnheit)',
      term: 'geniş zaman -(A/I)r, olumsuz -mAz',
      area: 'Verb/Zeit',
      from: 2,
      to: 3,
      level: 'A2',
      contested: true,
      errors: '-ar/-er/-ir falsch gewählt; Verneinung 1. Person (*içmezim*)',
      formats: ['tabelle', 'luecke', 'multiplechoice'],
      description: 'Gewohnheit, allgemeine Aussagen und höfliche Fragen; verneint mit -maz/-mez (1. Person -mam/-mem).',
      examples: ['Her sabah kahve içerim.', 'Türkçe konuşur musun?', 'Çay içmem.']
    },
    {
      id: 'tr.verb.emir_istek',
      label: 'Imperativ und Aufforderung',
      term: 'emir kipi, istek kipi (-(y)AlIm)',
      area: 'Verb',
      from: 2,
      to: 2,
      level: 'A2',
      errors: 'Höflichkeitsform -(y)In vergessen',
      formats: ['umformen', 'luecke'],
      description: 'Imperativ = Stamm, höflich/Plural -(y)in; gemeinsame Aufforderung mit -(y)elim/-(y)alım.',
      examples: ['Gel!', 'Kapıyı açın, lütfen.', 'Gidelim!']
    },
    {
      id: 'tr.verb.yeterlik',
      label: 'können und nicht können',
      term: 'yeterlik fiili -(y)Abil-, olumsuz -(y)AmA-',
      area: 'Verb',
      from: 2,
      to: 3,
      level: 'A2',
      errors: 'Verneinung *gelebilmem* statt gelemem',
      formats: ['umformen', 'luecke'],
      description: 'Fähigkeit und Möglichkeit mit -(y)ebil-/-(y)abil-; verneint mit -(y)eme-/-(y)ama-.',
      examples: ['Yüzebilirim.', 'Gelemem.', 'Türkçe konuşabiliyor musun?']
    },
    {
      id: 'tr.adj.karsilastirma',
      label: 'Vergleich',
      term: 'karşılaştırma: daha, en, -DAn',
      area: 'Adjektiv',
      from: 2,
      to: 3,
      level: 'A2',
      errors: 'Vergleichsobjekt nicht im Ablativ (*Ali ben daha uzun*)',
      formats: ['luecke', 'satzbildung'],
      description: 'Das Verglichene steht im Ablativ, dazu daha; Superlativ mit en.',
      examples: ['Ali benden daha uzun.', 'En güzel şehir hangisi?']
    },
    {
      id: 'tr.verb.gereklilik',
      label: 'Notwendigkeit',
      term: 'gereklilik: -mAlI, lazım, gerek',
      area: 'Verb',
      from: 3,
      to: 3,
      level: 'A2',
      errors: 'lazım ohne Possessivendung am Verbalnomen (*Erken kalkmak lazımım*)',
      formats: ['luecke', 'umformen'],
      description: 'Pflicht mit -meli/-malı + Personalendung oder mit Verbalnomen + Possessiv + lazım/gerek.',
      examples: ['Ödevimi yapmalıyım.', 'Erken kalkmam lazım.']
    },
    {
      id: 'tr.verb.mis',
      label: 'Vergangenheit auf -miş',
      term: 'öğrenilen geçmiş zaman -mIş',
      area: 'Verb/Zeit',
      from: 3,
      to: 4,
      level: 'A2/B1',
      errors: '-miş und -di ohne Bedeutungsunterschied verwendet',
      formats: ['multiplechoice', 'satzanalyse', 'umformen'],
      description: 'Nicht selbst Erlebtes, Gehörtes oder überraschend Festgestelltes.',
      examples: ['Ali gelmiş.', 'Hava çok güzelmiş.']
    },
    {
      id: 'tr.syn.kosul',
      label: 'Bedingungssätze',
      term: 'şart kipi -(y)sA',
      area: 'Satzbau',
      from: 3,
      to: 5,
      level: 'A2/B1',
      contested: true,
      errors: '*eğer* als Pflicht verstanden; Zeit im Nebensatz nach Deutsch',
      formats: ['umformen', 'luecke', 'satzbildung'],
      description: 'Bedingung mit -se/-sa am Verb; wirklich (-ırsa) oder unwirklich (-sa … -ırdı).',
      examples: ['Zamanım olursa gelirim.', 'Param olsa bir araba alırdım.']
    },
    {
      id: 'tr.syn.ortac',
      label: 'Partizipien statt Relativsatz',
      term: 'sıfat-fiiller -(y)An, -DIK',
      area: 'Satzbau',
      from: 4,
      to: 5,
      level: 'B1',
      errors: 'deutschen Relativsatz nachgebaut; -en und -dik vertauscht',
      formats: ['umformen', 'uebersetzen', 'markieren'],
      description: 'Relativsätze werden als vorangestellte Partizipien gebildet: -en/-an für das Subjekt, -dik + Possessiv für andere Rollen.',
      examples: ['kitap okuyan çocuk', 'Okuduğum kitap çok güzel.']
    },
    {
      id: 'tr.syn.zarf_fiil',
      label: 'Temporale Verbformen (Konverben)',
      term: 'zarf-fiiller -ken, -(y)IncA, -DIğIndA',
      area: 'Satzbau',
      from: 4,
      to: 5,
      level: 'B1',
      errors: 'deutschen Nebensatz mit Konjunktion nachgebaut',
      formats: ['umformen', 'luecke', 'uebersetzen'],
      description: 'Gleichzeitigkeit mit -ken, „sobald/als" mit -ince/-ınca bzw. -diğinde.',
      examples: ['Eve gelince seni ararım.', 'Yemek yerken televizyon izlemem.']
    },
    {
      id: 'tr.verb.edilgen',
      label: 'Passiv',
      term: 'edilgen çatı -Il-/-In-',
      area: 'Verb',
      from: 5,
      to: 6,
      level: 'B1',
      errors: '-il- und -in- vertauscht (nach l-Stamm -in-)',
      formats: ['umformen', 'markieren'],
      description: 'Passiv mit -il-/-ıl- (nach Vokal und l: -n-/-in-).',
      examples: ['Kapı açıldı.', "Bu ev 1990'da yapıldı."]
    }
  ]
)

// ---------------------------------------------------------------- Chinesisch

const CHINESISCH = fach(
  'chinesisch',
  'Faustregel (übliche Anfängerprogression Chinesisch als Fremdsprache; GER-Einordnung angelehnt an die Grammatikstufen 1–3 des chinesischen Niveaustandards HSK 3.0, nicht einzeln abgeglichen)',
  [
    {
      id: 'zh.syn.shi_hen',
      label: 'Sätze mit 是 und Adjektivprädikat',
      term: '是 shì; 很 hěn + Adjektiv',
      area: 'Satzbau',
      from: 1,
      to: 1,
      level: 'A1',
      errors: '是 vor Adjektiven (*我是很高*)',
      formats: ['multiplechoice', 'fehlerkorrektur', 'satzbildung'],
      description: '是 verbindet zwei Nomen; Adjektive sind selbst Prädikat, meist mit 很.',
      examples: ['我是学生。(Wǒ shì xuésheng.)', '她很高。(Tā hěn gāo.)']
    },
    {
      id: 'zh.syn.fragen',
      label: 'Fragen mit 吗, 呢 und Fragewörtern',
      term: '吗 ma, 呢 ne, 什么 shénme, 谁 shéi, 哪儿 nǎr',
      area: 'Satzbau',
      from: 1,
      to: 1,
      level: 'A1',
      errors: 'Fragewort an den Satzanfang (*什么你叫名字*); 吗 zusätzlich zum Fragewort',
      formats: ['umformen', 'zuordnen', 'sortieren'],
      description: 'Entscheidungsfrage mit 吗 am Satzende; Fragewörter stehen an der Stelle der Antwort.',
      examples: ['你是老师吗？(Nǐ shì lǎoshī ma?)', '你叫什么名字？(Nǐ jiào shénme míngzi?)', '我很好，你呢？(Wǒ hěn hǎo, nǐ ne?)']
    },
    {
      id: 'zh.syn.bu_mei',
      label: 'Verneinung mit 不 und 没(有)',
      term: '不 bù / 没(有) méi(yǒu)',
      area: 'Satzbau',
      from: 1,
      to: 2,
      level: 'A1',
      errors: '*不有*; 不 für Vergangenes (*他昨天不来*)',
      formats: ['multiplechoice', 'umformen', 'fehlerkorrektur'],
      description: '不 für Gegenwart, Gewohnheit und Wille; 没 für 有 und für nicht Geschehenes.',
      examples: ['我不喝咖啡。(Wǒ bù hē kāfēi.)', '我没有哥哥。(Wǒ méiyǒu gēge.)', '他昨天没来。(Tā zuótiān méi lái.)']
    },
    {
      id: 'zh.nom.liangci',
      label: 'Zählwörter',
      term: '量词 liàngcí: 个, 本, 张, 只',
      area: 'Nomen',
      from: 1,
      to: 2,
      level: 'A1',
      errors: 'Zählwort fehlt (*三书*); *二个* statt 两个',
      formats: ['zuordnen', 'luecke', 'multiplechoice'],
      description: 'Zwischen Zahl bzw. 这/那 und Nomen steht ein Zählwort; vor Zählwörtern 两 statt 二.',
      examples: ['一个人 (yí ge rén)', '三本书 (sān běn shū)', '两张桌子 (liǎng zhāng zhuōzi)']
    },
    {
      id: 'zh.syn.de_attribut',
      label: 'Attribut mit 的',
      term: '的 de (Besitz und Attribut)',
      area: 'Satzbau',
      from: 1,
      to: 1,
      level: 'A1',
      errors: 'Reihenfolge nach Deutsch umgedreht; 的 bei enger Beziehung erzwungen',
      formats: ['sortieren', 'luecke', 'uebersetzen'],
      description: 'Das Bestimmende steht mit 的 vor dem Nomen; bei enger Beziehung (Familie) kann 的 wegfallen.',
      examples: ['我的书 (wǒ de shū)', '妈妈的朋友 (māma de péngyou)', '我朋友 (wǒ péngyou)']
    },
    {
      id: 'zh.syn.you_zai',
      label: '有 und 在: haben, es gibt, sich befinden',
      term: '有 yǒu; 在 zài',
      area: 'Satzbau',
      from: 1,
      to: 1,
      level: 'A1',
      errors: '*我是在家* ; 有 und 在 bei Ortsangaben vertauscht',
      formats: ['multiplechoice', 'luecke', 'satzbildung'],
      description: '有 für Besitz und „es gibt" (Ort am Satzanfang); 在 für den Aufenthaltsort.',
      examples: ['我有一个妹妹。(Wǒ yǒu yí ge mèimei.)', '桌子上有一本书。(Zhuōzi shang yǒu yì běn shū.)', '我在家。(Wǒ zài jiā.)']
    },
    {
      id: 'zh.syn.wortstellung',
      label: 'Satzstellung: Zeit und Ort vor dem Verb',
      term: '主语 + 时间 + 地点 + 动词',
      area: 'Satzbau',
      from: 1,
      to: 2,
      level: 'A1',
      errors: 'Orts- und Zeitangabe nach dem Verb (*我学习在学校*)',
      formats: ['sortieren', 'fehlerkorrektur', 'satzbildung'],
      description: 'Zeitangabe vor oder nach dem Subjekt, Ortsangabe mit 在 vor dem Verb.',
      examples: ['我明天在学校学习。(Wǒ míngtiān zài xuéxiào xuéxí.)', '他八点去学校。(Tā bā diǎn qù xuéxiào.)']
    },
    {
      id: 'zh.verb.modal',
      label: 'Modalverben',
      term: '想 xiǎng, 要 yào, 会 huì, 能 néng, 可以 kěyǐ',
      area: 'Verb',
      from: 1,
      to: 2,
      level: 'A1/A2',
      contested: true,
      errors: '会, 能 und 可以 vertauscht; Verneinung *不要* als „nicht wollen" missverstanden',
      formats: ['multiplechoice', 'luecke', 'zuordnen'],
      description: '会 für Gelerntes, 能 für Möglichkeit, 可以 für Erlaubnis; 想/要 für Wunsch und Absicht.',
      examples: ['我想喝茶。(Wǒ xiǎng hē chá.)', '我会说汉语。(Wǒ huì shuō Hànyǔ.)', '这里可以拍照吗？(Zhèlǐ kěyǐ pāizhào ma?)']
    },
    {
      id: 'zh.asp.le',
      label: 'Die Partikel 了',
      term: '了 le (Abschluss; Veränderung am Satzende)',
      area: 'Verb/Aspekt',
      from: 2,
      to: 3,
      level: 'A2',
      contested: true,
      errors: '了 als Vergangenheitszeichen bei jedem Verb; *没去了*',
      formats: ['luecke', 'multiplechoice', 'fehlerkorrektur'],
      description: '了 nach dem Verb zeigt den Abschluss, am Satzende eine neue Lage; verneint mit 没 ohne 了.',
      examples: ['我买了两本书。(Wǒ mǎile liǎng běn shū.)', '下雨了。(Xià yǔ le.)']
    },
    {
      id: 'zh.asp.guo',
      label: 'Erfahrung mit 过',
      term: '过 guo',
      area: 'Verb/Aspekt',
      from: 2,
      to: 3,
      level: 'A2',
      errors: '*不去过*; 了 und 过 vertauscht',
      formats: ['luecke', 'umformen', 'multiplechoice'],
      description: '过 nach dem Verb: etwas schon einmal erlebt haben; verneint mit 没.',
      examples: ['我去过中国。(Wǒ qùguo Zhōngguó.)', '你吃过饺子吗？(Nǐ chīguo jiǎozi ma?)', '我没去过上海。(Wǒ méi qùguo Shànghǎi.)']
    },
    {
      id: 'zh.asp.zai_zhe',
      label: 'Verlauf mit 在 und Zustand mit 着',
      term: '(正)在 (zhèng)zài; 着 zhe',
      area: 'Verb/Aspekt',
      from: 2,
      to: 3,
      level: 'A2',
      errors: '在 und 着 vertauscht; 着 bei Handlungen ohne andauernden Zustand',
      formats: ['multiplechoice', 'luecke'],
      description: '在/正在 vor dem Verb für eine laufende Handlung, 着 nach dem Verb für einen andauernden Zustand.',
      examples: ['他在看书。(Tā zài kàn shū.)', '她正在打电话。(Tā zhèngzài dǎ diànhuà.)', '门开着。(Mén kāizhe.)']
    },
    {
      id: 'zh.syn.bi',
      label: 'Vergleich mit 比',
      term: '比 bǐ; 没有 … 那么',
      area: 'Satzbau',
      from: 2,
      to: 3,
      level: 'A2',
      errors: '很 im Vergleich (*我比他很高*); *我不比他高* für „kleiner"',
      formats: ['satzbildung', 'fehlerkorrektur', 'umformen'],
      description: 'A 比 B + Adjektiv (ohne 很); Unterschied mit 一点儿/多了; verneint mit 没有 … 那么.',
      examples: ['我比他高。(Wǒ bǐ tā gāo.)', '今天比昨天冷一点儿。(Jīntiān bǐ zuótiān lěng yìdiǎnr.)', '我没有他那么高。(Wǒ méiyǒu tā nàme gāo.)']
    },
    {
      id: 'zh.syn.de_grad',
      label: 'Gradkomplement mit 得',
      term: '得 de (Verb + 得 + Bewertung)',
      area: 'Satzbau',
      from: 2,
      to: 3,
      level: 'A2',
      errors: '得 fehlt (*他说很快*); Objekt zwischen Verb und 得',
      formats: ['umformen', 'fehlerkorrektur', 'luecke'],
      description: 'Bewertung einer Handlung: Verb + 得 + Adjektiv; mit Objekt wird das Verb wiederholt oder das Objekt vorangestellt.',
      examples: ['他说得很快。(Tā shuō de hěn kuài.)', '她汉语说得很好。(Tā Hànyǔ shuō de hěn hǎo.)']
    },
    {
      id: 'zh.syn.konnektoren',
      label: 'Satzverbindungen in Paaren',
      term: '因为 … 所以, 虽然 … 但是, 如果 … 就',
      area: 'Satzbau',
      from: 2,
      to: 4,
      level: 'A2',
      errors: 'nur einen Teil des Paares gesetzt; Reihenfolge nach Deutsch',
      formats: ['zuordnen', 'luecke', 'satzbildung'],
      description: 'Begründung, Einräumung und Bedingung mit paarigen Konnektoren; der Nebensatz steht vorn.',
      examples: ['因为下雨，所以我没去。(Yīnwèi xià yǔ, suǒyǐ wǒ méi qù.)', '虽然很累，但是我很高兴。(Suīrán hěn lèi, dànshì wǒ hěn gāoxìng.)']
    },
    {
      id: 'zh.syn.ergebnis',
      label: 'Resultativkomplement',
      term: '结果补语 (看懂, 做完, 听见)',
      area: 'Satzbau',
      from: 3,
      to: 4,
      level: 'A2',
      errors: 'Ergebnis weggelassen (*我看了* für „verstanden"); verneint mit 不 statt 没',
      formats: ['luecke', 'zuordnen', 'uebersetzen'],
      description: 'Ein zweites Verb oder Adjektiv nennt das Ergebnis der Handlung; verneint mit 没.',
      examples: ['我看懂了。(Wǒ kàndǒng le.)', '作业做完了吗？(Zuòyè zuòwán le ma?)', '我没听见。(Wǒ méi tīngjiàn.)']
    },
    {
      id: 'zh.syn.richtung',
      label: 'Richtungskomplement',
      term: '趋向补语 (来/去; 进来, 出去, 过来)',
      area: 'Satzbau',
      from: 3,
      to: 4,
      level: 'A2/B1',
      errors: '来 und 去 nach der Sprecherposition vertauscht',
      formats: ['multiplechoice', 'luecke'],
      description: 'Richtung der Bewegung nach dem Verb; 来 zum Sprecher hin, 去 vom Sprecher weg.',
      examples: ['他走进来了。(Tā zǒu jìnlai le.)', '她跑出去了。(Tā pǎo chuqu le.)']
    },
    {
      id: 'zh.syn.shi_de',
      label: 'Hervorhebung mit 是 … 的',
      term: '是 … 的 (Zeit, Ort, Art eines vergangenen Geschehens)',
      area: 'Satzbau',
      from: 3,
      to: 4,
      level: 'A2/B1',
      errors: '了 statt 是 … 的 bei Nachfrage nach Umständen',
      formats: ['umformen', 'luecke'],
      description: 'Nach den Umständen eines bekannten vergangenen Geschehens fragen und sie betonen.',
      examples: ['你是什么时候来的？(Nǐ shì shénme shíhou lái de?)', '我是坐飞机来的。(Wǒ shì zuò fēijī lái de.)']
    },
    {
      id: 'zh.syn.yue',
      label: '越来越 und 越 … 越',
      term: '越来越 yuè lái yuè; 越 … 越',
      area: 'Satzbau',
      from: 3,
      to: 4,
      level: 'A2/B1',
      errors: '很 zusätzlich (*越来越很冷*)',
      formats: ['luecke', 'satzbildung'],
      description: 'Zunehmende Veränderung bzw. Abhängigkeit zweier Größen.',
      examples: ['天气越来越冷了。(Tiānqì yuè lái yuè lěng le.)', '他越说越快。(Tā yuè shuō yuè kuài.)']
    },
    {
      id: 'zh.syn.temporal',
      label: 'Zeitliche Abfolge',
      term: '一 … 就, 先 … 然后, … 以后/以前',
      area: 'Satzbau',
      from: 3,
      to: 4,
      level: 'A2/B1',
      errors: '以后/以前 vor den Satz gestellt wie „nachdem"',
      formats: ['sortieren', 'luecke', 'satzbildung'],
      description: 'Abfolge von Handlungen; 以前/以后 stehen hinter dem Zeitsatz.',
      examples: ['我一到家就给你打电话。(Wǒ yí dào jiā jiù gěi nǐ dǎ diànhuà.)', '先吃饭，然后写作业。(Xiān chīfàn, ránhòu xiě zuòyè.)']
    },
    {
      id: 'zh.syn.ba',
      label: 'Der 把-Satz',
      term: '把 bǎ',
      area: 'Satzbau',
      from: 3,
      to: 5,
      level: 'A2/B1',
      contested: true,
      errors: 'Verb ohne Ergänzung (*我把书看*); 把 mit unbestimmtem Objekt',
      formats: ['umformen', 'fehlerkorrektur', 'satzbildung'],
      description: 'Das bestimmte Objekt tritt mit 把 vor das Verb; das Verb braucht eine Ergänzung (Ergebnis, Richtung, 了).',
      examples: ['我把作业做完了。(Wǒ bǎ zuòyè zuòwán le.)', '请把门关上。(Qǐng bǎ mén guānshang.)', '请把书拿过来。(Qǐng bǎ shū ná guolai.)']
    },
    {
      id: 'zh.syn.moeglichkeit',
      label: 'Potentialkomplement',
      term: '可能补语 (看得懂 / 听不懂)',
      area: 'Satzbau',
      from: 4,
      to: 5,
      level: 'B1',
      errors: '*不能听懂* statt 听不懂',
      formats: ['umformen', 'multiplechoice', 'luecke'],
      description: '得/不 zwischen Verb und Ergebnis: ob etwas gelingen kann.',
      examples: ['我听不懂。(Wǒ tīng bu dǒng.)', '这么多菜，你吃得完吗？(Zhème duō cài, nǐ chī de wán ma?)']
    },
    {
      id: 'zh.syn.bei',
      label: 'Passiv mit 被',
      term: '被 bèi',
      area: 'Satzbau',
      from: 4,
      to: 5,
      level: 'B1',
      errors: '被 für neutrale Vorgänge nach deutschem Passiv; Verb ohne Ergänzung',
      formats: ['umformen', 'markieren'],
      description: '被-Sätze vor allem für unerwünschte Ereignisse; das Verb braucht eine Ergänzung.',
      examples: ['我的自行车被偷了。(Wǒ de zìxíngchē bèi tōu le.)', '蛋糕被弟弟吃了。(Dàngāo bèi dìdi chī le.)']
    }
  ]
)

export const NEUE_SPRACHEN_GRAMMATIK: GrammarTopic[] = [...NIEDERLAENDISCH, ...POLNISCH, ...TSCHECHISCH, ...PORTUGIESISCH, ...TUERKISCH, ...CHINESISCH]
