/**
 * Zuordnung der Lehrwerks-Grammatik Latein (Pontes, Campus A, prima., prima.nova – Synopsen zum KC Niedersachsen,
 * Recherche 07.10.2026) zu den Katalogthemen `la.*`. Erste passende Zeile gewinnt; gesucht wird im normierten
 * Wortlaut (klein, ä → ae, ohne Hinweise wie „(KC NI: erst Jg. 10)"). Was keine Zeile trifft, schlägt die Suche nur vor.
 */
export interface ZuordnungLa {
  muster: RegExp
  ids: string[]
  /** Teilformen (Kennung) – gilt bei genau einem Thema */
  teile?: string[]
  unsicher?: boolean
}

export const ZUORDNUNG_LA: ZuordnungLa[] = [
  // ---------- Substantive
  { muster: /a-\/o-dekl.*nominativ|substantive: (nom(inativ|\. sg|\. pl)|nominativ)/, ids: ['la.form.subst_ao'], teile: ['a-dekl', 'o-dekl-us'] },
  { muster: /nom\. und akk\. (sg|pl)\. der o-\/a-\/kons/, ids: ['la.form.subst_ao', 'la.form.subst_3'] },
  { muster: /a-\/o-dekl.*(akkusativ|dativ|genitiv|ablativ)/, ids: ['la.form.subst_ao'], teile: ['a-dekl', 'o-dekl-us'] },
  { muster: /a-\/o-dekl.*vokativ|vok\. sg\. der o-dekl|substantive: vokativ/, ids: ['la.form.subst_ao'], teile: ['vokativ'] },
  { muster: /o-dekl.*-?\(?e\)?r|o-dekl\. auf -er/, ids: ['la.form.subst_ao'], teile: ['o-dekl-er'] },
  { muster: /neutr(a|um) der o-dekl|o-deklination \(neutra/, ids: ['la.form.subst_ao'], teile: ['o-dekl-um'] },
  { muster: /^substantive: (akkusativ|dativ|genitiv|ablativ)$|^formen des genitivs/, ids: ['la.form.subst_ao', 'la.form.subst_3'] },
  { muster: /neutra der kons\. dekl|3\. dekl.*neutra|3\. deklination: erweiterung \(neutra\)/, ids: ['la.form.subst_3'], teile: ['kons-n'] },
  { muster: /i-stamme|i-staemme|subst\. der i-dekl/, ids: ['la.form.subst_3'], teile: ['i-staemme', 'mischklasse'] },
  { muster: /^3\. dekl|^substantive der 3\. dekl|^substantive: 3\. dekl|^substantive der 3\. deklination|wortstamm/, ids: ['la.form.subst_3'] },
  { muster: /u-dekl/, ids: ['la.form.subst_eu'], teile: ['u-dekl'] },
  { muster: /e-dekl/, ids: ['la.form.subst_eu'], teile: ['e-dekl'] },
  { muster: /pluralwoerter/, ids: ['la.form.subst_besonderheiten'], teile: ['pluralia-tantum'] },
  { muster: /uebersicht: substantive/, ids: ['la.form.subst_ao', 'la.form.subst_3', 'la.form.subst_eu'] },
  { muster: /^genus \(geschlecht\)/, ids: ['la.form.subst_3'], teile: ['genusregeln'] },
  // ---------- Adjektive, Adverbien, Steigerung
  { muster: /verschiedenen deklinationsklassen/, ids: ['la.form.adj_ao', 'la.form.adj_3'] },
  { muster: /kng-kongruenz|^ng-kongruenz/, ids: ['la.syn.kongruenz'], teile: ['kng'] },
  { muster: /adjektive: a-\/o-dekl\. \(auf -\(e\)r\)/, ids: ['la.form.adj_ao'], teile: ['er-a-um'] },
  { muster: /adj(ektive|\.)?:? (der )?(a-|a- und o-|a-\/o-)/, ids: ['la.form.adj_ao'] },
  { muster: /adj(ektive|\.)?:? (der )?(3\.|i-dekl)/, ids: ['la.form.adj_3'] },
  { muster: /adj(ektiv|\.)? als attribut/, ids: ['la.form.adj_ao'], teile: ['kng-attribut'] },
  { muster: /adj(ektiv|\.)? als praedikatsnomen/, ids: ['la.form.adj_ao'], teile: ['praedikatsnomen'] },
  { muster: /adverbien: (die )?steigerung/, ids: ['la.adv.bildung'], teile: ['steigerung'] },
  { muster: /komparation|steigerung/, ids: ['la.form.komparation'] },
  { muster: /^adv\. zu|^adverbbildung|^adverb$/, ids: ['la.adv.bildung'] },
  { muster: /^substantivierung/, ids: ['la.syn.substantivierung'] },
  // ---------- Pronomen
  { muster: /personalpron.*gen/, ids: ['la.form.pron_pers'], teile: ['gen-obiectivus-pers'] },
  { muster: /personalpronomen/, ids: ['la.form.pron_pers'], teile: ['ego-tu'] },
  { muster: /possessivpronomen: 3\. person/, ids: ['la.form.pron_refl'], teile: ['suus-eius'] },
  { muster: /possessivpronomen/, ids: ['la.form.pron_pers'], teile: ['possessiv'] },
  { muster: /reflexivpronomen|^se, sibi/, ids: ['la.form.pron_refl'] },
  { muster: /reflexivitaet im aci|pronom(en|ina) im aci/, ids: ['la.syn.aci', 'la.form.pron_refl'] },
  { muster: /pronomen is|^is$/, ids: ['la.form.pron_dem'], teile: ['is-ea-id', 'is-funktionen'] },
  { muster: /hic(,| und) ille/, ids: ['la.form.pron_dem'], teile: ['hic-ille'] },
  { muster: /iste/, ids: ['la.form.pron_dem'], teile: ['iste'] },
  { muster: /idem/, ids: ['la.form.pron_dem'], teile: ['idem'] },
  { muster: /ipse/, ids: ['la.form.pron_dem'], teile: ['ipse'] },
  { muster: /interrogativpronomen|^fragewoerter/, ids: ['la.form.pron_interrog'] },
  { muster: /indefinitpronomen/, ids: ['la.pron.indefinit'] },
  { muster: /relativpronomen|relativsaetze und/, ids: ['la.form.pron_rel'] },
  { muster: /korrelativa/, ids: ['la.pron.verallgemeinernd'], teile: ['korrelativa'] },
  // ---------- Verben: Formen
  { muster: /verben: (3\.|1\. und 2\.)|kons\. konjugation: 3\. pers|verben: infinitiv praesens/, ids: ['la.form.konj_praes', 'la.form.verbmorphologie'] },
  { muster: /^a-konjugation/, ids: ['la.form.konj_praes'], teile: ['a-konj'] },
  { muster: /^e-konjugation \/ esse \(imperativ\)|imperativ/, ids: ['la.form.imperativ'] },
  { muster: /^e-konjugation/, ids: ['la.form.konj_praes'], teile: ['e-konj', 'esse-praesens'] },
  { muster: /i-konjugation/, ids: ['la.form.konj_praes'], teile: ['i-konj'] },
  { muster: /(i-erweiterung|gem\. konj)/, ids: ['la.form.konj_praes'], teile: ['kons-i'] },
  { muster: /konsonantische konjugation|kons\. konjug/, ids: ['la.form.konj_praes'], teile: ['kons-konj'] },
  { muster: /komposita von esse/, ids: ['la.verb.unregelmaessig'], teile: ['esse-komposita'] },
  { muster: /^(verben: )?esse/, ids: ['la.verb.unregelmaessig'], teile: ['esse'] },
  { muster: /^(verben: )?posse/, ids: ['la.verb.unregelmaessig'], teile: ['posse'] },
  { muster: /^(verben: )?ire/, ids: ['la.verb.unregelmaessig'], teile: ['ire'] },
  { muster: /^(verben: )?ferre/, ids: ['la.verb.unregelmaessig'], teile: ['ferre'] },
  { muster: /^(verben: )?fieri/, ids: ['la.verb.unregelmaessig'], teile: ['fieri'] },
  { muster: /velle|nolle/, ids: ['la.verb.unregelmaessig'], teile: ['velle-nolle-malle'] },
  { muster: /^komposita$/, ids: ['la.verb.unregelmaessig'], teile: ['esse-komposita'], unsicher: true },
  { muster: /^stammformen|uebersicht: konjugation/, ids: ['la.form.verbmorphologie'] },
  // Passiv vor den Tempora (sonst trifft „Passiv (Imperfekt)" das Imperfekt)
  { muster: /^verwendung des passivs/, ids: ['la.form.passiv'], teile: ['wiedergabe'] },
  { muster: /passiv \((ind\. )?perf|passiv \(plusquamperfekt|verben: passiv \(perfekt/, ids: ['la.form.passiv'], teile: ['perfektstamm'] },
  { muster: /passiv/, ids: ['la.form.passiv'], teile: ['endungen', 'praesensstamm'] },
  { muster: /konj(unktiv|\.)? (praes|impf|imperfekt|perf|plu)|uebersicht: konjunktiv|^verben: konjunktiv/, ids: ['la.form.konjunktiv'] },
  { muster: /konj(unktiv|\.)? (als|im hs|im hauptsatz)|irrealis/, ids: ['la.syn.konj_hs', 'la.syn.konditional'] },
  { muster: /hortativ|jussiv|optativ|prohibitiv|deliberativ|potentialis/, ids: ['la.syn.konj_hs'] },
  { muster: /konj(unktiv|\.)? (in|im) (gliedsaetzen|nebensaetzen|rs)|cum-saetze im konj/, ids: ['la.syn.nebensatz_konj'] },
  { muster: /verwendung des imperfekts|^impf\. und perf\. in texten|tempora in erzaehlenden/, ids: ['la.syn.tempusfunktionen'], teile: ['tempusrelief'] },
  { muster: /imperfekt|impf\. akt/, ids: ['la.form.imperfekt'] },
  { muster: /fut(ur)?\.? ii/, ids: ['la.form.futur'], teile: ['futur-2'] },
  { muster: /verwendung des futurs/, ids: ['la.form.futur'], teile: ['zeitverhaeltnis'] },
  { muster: /futur i \(a-\/e-/, ids: ['la.form.futur'], teile: ['bo-bi-bu', 'ero'] },
  { muster: /futur i \(i-\/kons/, ids: ['la.form.futur'], teile: ['am-es'] },
  { muster: /^(verben: )?futur$|fut\. i akt/, ids: ['la.form.futur'] },
  { muster: /zustandsperfekt|verwendung des perfekts/, ids: ['la.syn.tempusfunktionen'], teile: ['perfekt-praeteritum', 'resultativ'] },
  { muster: /perfekt(bildung)?:? ?\(?(-?v|-?u|u-|v-)/, ids: ['la.form.perfekt'], teile: ['v-perfekt', 'u-perfekt'] },
  { muster: /perf(ekt(bildung)?)?\.?:? .*(reduplikation|dehnung|-s-|s-|stamm)/, ids: ['la.form.perfekt'] },
  { muster: /^(verben: )?perfekt$|ind\. perf\. akt/, ids: ['la.form.perfekt'] },
  { muster: /plusquamperfekt|plqu/, ids: ['la.form.plusquamperfekt'] },
  { muster: /uebersicht: tempora/, ids: ['la.form.imperfekt', 'la.form.perfekt', 'la.form.futur', 'la.form.plusquamperfekt'] },
  { muster: /inf(initiv|\.) (perf|fut)|infinitiv futur aktiv/, ids: ['la.form.infinitive'] },
  // ---------- Partizipien, nd-Formen, satzwertige Konstruktionen
  { muster: /(abl\. abs|ablativus absolutus)/, ids: ['la.syn.abl_abs'] },
  { muster: /ppa als pc|ppp als pc|^pc:|partizip als adverbiale|das partizip als adverbiale/, ids: ['la.syn.pc'] },
  { muster: /ppa und ppp als attribut/, ids: ['la.form.ppa', 'la.form.ppp'] },
  { muster: /ppp der deponentien/, ids: ['la.form.deponens'], teile: ['partizip'] },
  { muster: /\bppa\b|partizip praesens aktiv/, ids: ['la.form.ppa'] },
  { muster: /\bppp\b|partizip perfekt passiv/, ids: ['la.form.ppp'] },
  { muster: /\bpfa\b|partizip futur aktiv|partizips futur aktiv/, ids: ['la.form.pfa'] },
  { muster: /deponentien/, ids: ['la.form.deponens'] },
  { muster: /gerundivum: pn|gerundiv.*praedikativ|nd \+ esse/, ids: ['la.syn.gerundiv_esse'] },
  { muster: /gerundium|gerundiv|nd-formen/, ids: ['la.form.nd'] },
  { muster: /aci|akkusativ mit infinitiv|zeitverhaeltnisse im aci/, ids: ['la.syn.aci'] },
  { muster: /satzgliedfunktion von aci und inf/, ids: ['la.syn.aci', 'la.syn.infinitiv_funktionen'] },
  { muster: /praedikativum/, ids: ['la.syn.praedikativum'] },
  { muster: /satzwertige konstruktionen/, ids: ['la.syn.aci', 'la.syn.pc', 'la.syn.abl_abs'] },
  // ---------- Kasusfunktionen
  { muster: /abl\. loc\., sep\., soc\., instr\., temp/, ids: ['la.syn.kasus'], teile: ['abl-loci-temporis', 'abl-separativus', 'abl-sociativus', 'abl-instrumentalis'] },
  { muster: /ablativ der zeit, des grundes, der trennung/, ids: ['la.syn.kasus'], teile: ['abl-loci-temporis', 'abl-causae', 'abl-separativus'] },
  { muster: /ablativ (als adverbiale: )?(der zeit|ablativ der zeit)/, ids: ['la.syn.kasus'], teile: ['abl-loci-temporis'] },
  { muster: /ablativ (als adverbiale: ablativ )?des mittels/, ids: ['la.syn.kasus'], teile: ['abl-instrumentalis'] },
  { muster: /ablativ (als adverbiale \(causae\)|des grundes)|^des grundes/, ids: ['la.syn.kasus'], teile: ['abl-causae'] },
  { muster: /abl(ativ|\.) (des vergleichs|comp)|vergleich mit quam/, ids: ['la.syn.kasus_erweitert'], teile: ['abl-comparationis'] },
  { muster: /(abl(ativ|\.)|genitiv und ablativ) (der beschaffenheit|qual)/, ids: ['la.syn.kasus_erweitert'], teile: ['abl-qualitatis', 'gen-qualitatis'] },
  { muster: /gen(itiv|\.) (der beschaffenheit|qual)/, ids: ['la.syn.kasus_erweitert'], teile: ['gen-qualitatis'] },
  { muster: /gen(\.|itiv(us)?) (subi|obi|subiectivus)|genitivus obiectivus/, ids: ['la.syn.kasus_erweitert'], teile: ['gen-subj-obj'] },
  { muster: /gen(\.|itivus) part|genitiv als attribut: genitivus partitivus/, ids: ['la.syn.kasus_erweitert'], teile: ['gen-partitivus'] },
  { muster: /gen(itiv|\.) (als n|als praedikatsnomen)/, ids: ['la.syn.kasus_erweitert'], teile: ['gen-praedikativ'] },
  { muster: /genitiv(attribut| als attribut| der zugehoerigkeit)|gen\. poss/, ids: ['la.syn.kasus'], teile: ['gen-possessivus'] },
  { muster: /dat(iv|\.)? (des besitzers|poss)|dativfunktionen: dat\. poss/, ids: ['la.syn.kasus'], teile: ['dat-possessivus'] },
  { muster: /dativ des zwecks und des vorteils/, ids: ['la.syn.kasus_erweitert'], teile: ['dat-finalis', 'dat-commodi'] },
  { muster: /dat(iv|\.)? (des zwecks|fin)|dativ als praedikatsnomen: dativ des zwecks/, ids: ['la.syn.kasus_erweitert'], teile: ['dat-finalis'] },
  { muster: /dat(iv|\.)? (des vorteils|comm)|dativ als adverbiale/, ids: ['la.syn.kasus_erweitert'], teile: ['dat-commodi'] },
  { muster: /dat(ivus|\.) auct/, ids: ['la.syn.gerundiv_esse'], teile: ['dat-auctoris'] },
  { muster: /dopp(elter|\.) dat/, ids: ['la.syn.doppelter_kasus'], teile: ['doppelter-dativ'] },
  { muster: /dativ(objekt| als objekt)/, ids: ['la.syn.kasus'], teile: ['dat-objekt'] },
  { muster: /dativ als praedikatsnomen$/, ids: ['la.syn.kasus'], teile: ['dat-possessivus'] },
  { muster: /akk(\.|usativ) (der ausdehnung|als adverbiale)/, ids: ['la.syn.kasus'], teile: ['akk-ausdehnung'] },
  { muster: /doppelte?r? akkusativ/, ids: ['la.syn.doppelter_kasus'], teile: ['doppelter-akk-objekt', 'praedikatsakkusativ'] },
  { muster: /akkusativ(objekt| als objekt)/, ids: ['la.syn.kasus'], teile: ['akk-objekt-richtung'] },
  { muster: /ab der richtung|praepositionalausdruck|verwendung der praepositionen/, ids: ['la.syn.praepositionen'] },
  { muster: /herkunfts-, orts- und richtungsangaben/, ids: ['la.syn.ortsangaben'] },
  { muster: /abweichender und unterschiedlicher kasusrektion/, ids: ['la.syn.kasusrektion'] },
  // ---------- Satzlehre
  { muster: /kongruenz: subjekt und praedikat/, ids: ['la.syn.kongruenz'], teile: ['sp-kongruenz'] },
  { muster: /subjekt (und|im) praedikat|verstecktes|ohne artikel|satzglied|subst\.?:? (als attribut|praedikatsnomen)|substantiv als praedikatsnomen|uebersicht: satzglieder/, ids: ['la.syn.satzglieder'] },
  { muster: /rel(ativer|\.) satzanschluss/, ids: ['la.syn.rel_satzanschluss'] },
  { muster: /relativsatz/, ids: ['la.syn.nebensatz_ind'], teile: ['relativsatz'] },
  { muster: /indir(ekte|\.) fragesaetze|gliedsaetze als objekt/, ids: ['la.syn.indirekter_fragesatz'] },
  { muster: /cum-saetze/, ids: ['la.syn.cum_saetze'] },
  { muster: /ut-saetze/, ids: ['la.syn.ut_ne_saetze'] },
  { muster: /begehrsaetze/, ids: ['la.syn.nebensatz_konj'], teile: ['begehrsatz'] },
  { muster: /consecutio temporum|zeitenfolge|tempusgebrauch in konjunktivischen/, ids: ['la.syn.consecutio'] },
  { muster: /^dum$|^postquam$|tempora nach subjunktionen/, ids: ['la.syn.nebensatz_ind'], teile: ['temporal'] },
  { muster: /gliedsaetze|nebensaetze als adverbiale|sinnrichtung|satzgefuege/, ids: ['la.syn.nebensatz_ind', 'la.syn.nebensatz_konj'], unsicher: true },
  { muster: /fragesaetze|fragen/, ids: ['la.syn.frage_verneinung'] },
  { muster: /aufforderungssaetze/, ids: ['la.form.imperativ', 'la.syn.konj_hs'] },
  { muster: /grundzahlen/, ids: ['la.num.zahlwoerter'] },
  { muster: /summo in monte/, ids: ['la.form.pronominaladjektive'], unsicher: true },
  { muster: /konnektoren/, ids: ['la.syn.satzperiode'], unsicher: true }
]

/** Hinweise der Synopsen („(KC NI: erst Jg. 10)", „(fakultativ)", „(1)") aus dem Wortlaut für den Vergleich entfernen */
export const ohneHinweis = (s: string): string =>
  s
    .replace(/\((kc ni:[^)]*|fakultativ|\d)\)/gi, '')
    .replace(/\s+/g, ' ')
    .trim()
