/**
 * Grundwortschatz Latein nach Lernjahren (07.10.2026, für Grammatiktraining und Grammatiktest – abgestimmt mit der
 * Lehrkraft: Wortschatz aus Lehrwerk, Grundwortschatz oder eigener Liste). Häufige Lernwörter, wie sie in allen
 * gängigen Lehrwerken früh vorkommen, mit Nennform (Genitiv und Genus, Stammformen) und Längenzeichen – keine
 * Übernahme aus einem bestimmten Lehrwerk. Ein Lernjahr umfasst auch alle Wörter der früheren.
 */
export interface GrundWort {
  /** Nennform mit Längenzeichen, z. B. „rosa, -ae f." oder „vocāre, vocō, vocāvī, vocātum" */
  nennform: string
  deutsch: string
  lernjahr: 1 | 2 | 3
}

const W = (lernjahr: 1 | 2 | 3, liste: [string, string][]): GrundWort[] => liste.map(([nennform, deutsch]) => ({ nennform, deutsch, lernjahr }))

export const LATEIN_GRUNDWORTSCHATZ: GrundWort[] = [
  // ---------- 1. Lernjahr: a-, o-, 3. Deklination; a-/e-/i-/kons. Konjugation; esse, posse, īre; Adjektive a/o
  ...W(1, [
    ['puella, -ae f.', 'Mädchen'],
    ['amīca, -ae f.', 'Freundin'],
    ['fīlia, -ae f.', 'Tochter'],
    ['domina, -ae f.', 'Herrin'],
    ['via, -ae f.', 'Weg, Straße'],
    ['vīlla, -ae f.', 'Landhaus'],
    ['silva, -ae f.', 'Wald'],
    ['aqua, -ae f.', 'Wasser'],
    ['terra, -ae f.', 'Land, Erde'],
    ['pecūnia, -ae f.', 'Geld'],
    ['turba, -ae f.', 'Menschenmenge'],
    ['familia, -ae f.', 'Familie'],
    ['agricola, -ae m.', 'Bauer'],
    ['nauta, -ae m.', 'Seemann'],
    ['servus, -ī m.', 'Sklave'],
    ['amīcus, -ī m.', 'Freund'],
    ['fīlius, -ī m.', 'Sohn'],
    ['dominus, -ī m.', 'Herr'],
    ['equus, -ī m.', 'Pferd'],
    ['deus, -ī m.', 'Gott'],
    ['populus, -ī m.', 'Volk'],
    ['animus, -ī m.', 'Geist, Mut'],
    ['ager, agrī m.', 'Feld, Acker'],
    ['puer, puerī m.', 'Junge'],
    ['magister, magistrī m.', 'Lehrer'],
    ['templum, -ī n.', 'Tempel'],
    ['forum, -ī n.', 'Marktplatz'],
    ['dōnum, -ī n.', 'Geschenk'],
    ['verbum, -ī n.', 'Wort'],
    ['perīculum, -ī n.', 'Gefahr'],
    ['oppidum, -ī n.', 'Stadt'],
    ['bellum, -ī n.', 'Krieg'],
    ['cōnsilium, -ī n.', 'Rat, Plan'],
    ['rēx, rēgis m.', 'König'],
    ['senātor, -ōris m.', 'Senator'],
    ['mercātor, -ōris m.', 'Kaufmann'],
    ['pater, patris m.', 'Vater'],
    ['māter, mātris f.', 'Mutter'],
    ['frāter, frātris m.', 'Bruder'],
    ['soror, -ōris f.', 'Schwester'],
    ['homō, hominis m.', 'Mensch'],
    ['vōx, vōcis f.', 'Stimme'],
    ['lūx, lūcis f.', 'Licht'],
    ['clāmor, -ōris m.', 'Geschrei'],
    ['labor, -ōris m.', 'Arbeit, Mühe'],
    ['tempus, -oris n.', 'Zeit'],
    ['corpus, -oris n.', 'Körper'],
    ['nōmen, -inis n.', 'Name'],
    ['iter, itineris n.', 'Weg, Reise'],
    ['bonus, -a, -um', 'gut'],
    ['magnus, -a, -um', 'groß'],
    ['parvus, -a, -um', 'klein'],
    ['multus, -a, -um', 'viel'],
    ['laetus, -a, -um', 'froh'],
    ['malus, -a, -um', 'schlecht'],
    ['novus, -a, -um', 'neu'],
    ['longus, -a, -um', 'lang'],
    ['līber, lībera, līberum', 'frei'],
    ['pulcher, pulchra, pulchrum', 'schön'],
    ['miser, misera, miserum', 'elend, unglücklich'],
    ['esse, sum, fuī', 'sein'],
    ['posse, possum, potuī', 'können'],
    ['īre, eō, iī, itum', 'gehen'],
    ['vocāre, vocō, vocāvī, vocātum', 'rufen'],
    ['amāre, amō, amāvī, amātum', 'lieben'],
    ['labōrāre, labōrō, labōrāvī', 'arbeiten'],
    ['clāmāre, clāmō, clāmāvī', 'schreien'],
    ['spectāre, spectō, spectāvī, spectātum', 'betrachten'],
    ['exspectāre, exspectō, exspectāvī', 'erwarten, warten'],
    ['intrāre, intrō, intrāvī', 'betreten'],
    ['parāre, parō, parāvī, parātum', 'vorbereiten'],
    ['dare, dō, dedī, datum', 'geben'],
    ['stāre, stō, stetī', 'stehen'],
    ['monēre, moneō, monuī, monitum', 'mahnen'],
    ['tenēre, teneō, tenuī', 'halten'],
    ['vidēre, videō, vīdī, vīsum', 'sehen'],
    ['habēre, habeō, habuī, habitum', 'haben'],
    ['timēre, timeō, timuī', 'fürchten'],
    ['respondēre, respondeō, respondī, respōnsum', 'antworten'],
    ['audīre, audiō, audīvī, audītum', 'hören'],
    ['venīre, veniō, vēnī, ventum', 'kommen'],
    ['dormīre, dormiō, dormīvī', 'schlafen'],
    ['agere, agō, ēgī, āctum', 'tun, handeln'],
    ['dīcere, dīcō, dīxī, dictum', 'sagen'],
    ['dūcere, dūcō, dūxī, ductum', 'führen'],
    ['mittere, mittō, mīsī, missum', 'schicken'],
    ['petere, petō, petīvī, petītum', 'erstreben, bitten'],
    ['scrībere, scrībō, scrīpsī, scrīptum', 'schreiben'],
    ['legere, legō, lēgī, lēctum', 'lesen'],
    ['currere, currō, cucurrī', 'laufen'],
    ['capere, capiō, cēpī, captum', 'fassen, nehmen'],
    ['facere, faciō, fēcī, factum', 'machen, tun'],
    ['cupere, cupiō, cupīvī', 'wünschen'],
    ['in (mit Akk.)', 'in, nach (wohin?)'],
    ['in (mit Abl.)', 'in, auf (wo?)'],
    ['ad (mit Akk.)', 'zu, bei, an'],
    ['cum (mit Abl.)', 'mit'],
    ['ex/ē (mit Abl.)', 'aus'],
    ['ā/ab (mit Abl.)', 'von'],
    ['dē (mit Abl.)', 'von, über'],
    ['per (mit Akk.)', 'durch'],
    ['ego, meī', 'ich'],
    ['tū, tuī', 'du'],
    ['meus, -a, -um', 'mein'],
    ['tuus, -a, -um', 'dein'],
    ['is, ea, id', 'dieser, er, sie, es'],
    ['et', 'und'],
    ['sed', 'aber'],
    ['nōn', 'nicht'],
    ['quod', 'weil']
  ]),
  // ---------- 2. Lernjahr: Imperfekt, Futur, Plusquamperfekt, Passiv; hic/ille/ipse/quī; 3. Deklination der Adjektive; e-Deklination
  ...W(2, [
    ['rēs, reī f.', 'Sache, Ding'],
    ['diēs, diēī m.', 'Tag'],
    ['spēs, speī f.', 'Hoffnung'],
    ['fidēs, fideī f.', 'Treue, Vertrauen'],
    ['urbs, urbis f.', 'Stadt (Rom)'],
    ['nāvis, nāvis f.', 'Schiff'],
    ['cīvis, cīvis m.', 'Bürger'],
    ['hostis, hostis m.', 'Feind'],
    ['mare, maris n.', 'Meer'],
    ['animal, -ālis n.', 'Lebewesen, Tier'],
    ['mōns, montis m.', 'Berg'],
    ['pars, partis f.', 'Teil'],
    ['mors, mortis f.', 'Tod'],
    ['virtūs, -ūtis f.', 'Tapferkeit, Tugend'],
    ['lēx, lēgis f.', 'Gesetz'],
    ['pāx, pācis f.', 'Frieden'],
    ['dux, ducis m.', 'Anführer'],
    ['mīles, mīlitis m.', 'Soldat'],
    ['caput, capitis n.', 'Kopf, Hauptstadt'],
    ['flūmen, -inis n.', 'Fluss'],
    ['gēns, gentis f.', 'Stamm, Volk'],
    ['fortis, -e', 'tapfer, stark'],
    ['omnis, -e', 'jeder, ganz; Pl. alle'],
    ['facilis, -e', 'leicht'],
    ['difficilis, -e', 'schwierig'],
    ['brevis, -e', 'kurz'],
    ['trīstis, -e', 'traurig'],
    ['ācer, ācris, ācre', 'scharf, heftig'],
    ['celer, celeris, celere', 'schnell'],
    ['ingēns, ingentis', 'gewaltig'],
    ['fēlīx, fēlīcis', 'glücklich'],
    ['potēns, potentis', 'mächtig'],
    ['altus, -a, -um', 'hoch, tief'],
    ['clārus, -a, -um', 'berühmt, hell'],
    ['hic, haec, hoc', 'dieser (hier)'],
    ['ille, illa, illud', 'jener'],
    ['ipse, ipsa, ipsum', 'selbst'],
    ['quī, quae, quod', 'welcher, der'],
    ['suus, -a, -um', 'sein, ihr (reflexiv)'],
    ['noster, nostra, nostrum', 'unser'],
    ['vester, vestra, vestrum', 'euer'],
    ['nōs, nostrī', 'wir'],
    ['vōs, vestrī', 'ihr'],
    ['sē', 'sich'],
    ['vincere, vincō, vīcī, victum', 'siegen, besiegen'],
    ['relinquere, relinquō, relīquī, relictum', 'verlassen, zurücklassen'],
    ['quaerere, quaerō, quaesīvī, quaesītum', 'suchen, fragen'],
    ['cognōscere, cognōscō, cognōvī, cognitum', 'erkennen, kennenlernen'],
    ['cōnstituere, cōnstituō, cōnstituī, cōnstitūtum', 'beschließen'],
    ['trādere, trādō, trādidī, trāditum', 'übergeben, überliefern'],
    ['accipere, accipiō, accēpī, acceptum', 'annehmen, empfangen'],
    ['fugere, fugiō, fūgī', 'fliehen'],
    ['interficere, interficiō, interfēcī, interfectum', 'töten'],
    ['putāre, putō, putāvī, putātum', 'glauben, halten für'],
    ['superāre, superō, superāvī, superātum', 'besiegen, übertreffen'],
    ['servāre, servō, servāvī, servātum', 'retten, bewahren'],
    ['nūntiāre, nūntiō, nūntiāvī, nūntiātum', 'melden'],
    ['iubēre, iubeō, iussī, iussum', 'befehlen'],
    ['manēre, maneō, mānsī', 'bleiben'],
    ['movēre, moveō, mōvī, mōtum', 'bewegen'],
    ['dēlēre, dēleō, dēlēvī, dēlētum', 'zerstören'],
    ['scīre, sciō, scīvī, scītum', 'wissen'],
    ['invenīre, inveniō, invēnī, inventum', 'finden'],
    ['ferre, ferō, tulī, lātum', 'tragen, bringen'],
    ['velle, volō, voluī', 'wollen'],
    ['ante (mit Akk.)', 'vor'],
    ['post (mit Akk.)', 'nach, hinter'],
    ['contrā (mit Akk.)', 'gegen'],
    ['propter (mit Akk.)', 'wegen'],
    ['prō (mit Abl.)', 'vor, für'],
    ['sine (mit Abl.)', 'ohne'],
    ['sub (mit Abl./Akk.)', 'unter'],
    ['cum (Subjunktion)', 'als, wenn'],
    ['dum', 'während, solange'],
    ['postquam', 'nachdem'],
    ['autem', 'aber'],
    ['enim', 'denn, nämlich'],
    ['tamen', 'dennoch']
  ]),
  // ---------- 3. Lernjahr: Konjunktiv, u-Deklination, Deponentien, Komparation
  ...W(3, [
    ['manus, -ūs f.', 'Hand, Schar'],
    ['exercitus, -ūs m.', 'Heer'],
    ['senātus, -ūs m.', 'Senat'],
    ['metus, -ūs m.', 'Furcht'],
    ['cursus, -ūs m.', 'Lauf'],
    ['domus, -ūs f.', 'Haus'],
    ['cornū, -ūs n.', 'Horn, Flügel (des Heeres)'],
    ['rēs pūblica, reī pūblicae f.', 'Staat'],
    ['cōnsul, -is m.', 'Konsul'],
    ['imperium, -ī n.', 'Befehl, Herrschaft'],
    ['potestās, -ātis f.', 'Macht'],
    ['honor, -ōris m.', 'Ehre, Ehrenamt'],
    ['ōrātiō, -ōnis f.', 'Rede'],
    ['multitūdō, -inis f.', 'Menge'],
    ['sapiēns, sapientis', 'weise'],
    ['similis, -e', 'ähnlich'],
    ['melior, melius', 'besser'],
    ['maximus, -a, -um', 'der größte'],
    ['plūrimī, -ae, -a', 'die meisten'],
    ['īdem, eadem, idem', 'derselbe'],
    ['iste, ista, istud', 'dieser (da)'],
    ['quis, quid', 'wer, was'],
    ['aliquis, aliquid', 'irgendjemand, irgendetwas'],
    ['nēmō', 'niemand'],
    ['nihil', 'nichts'],
    ['arbitrārī, arbitror, arbitrātus sum', 'meinen, glauben'],
    ['hortārī, hortor, hortātus sum', 'ermahnen, auffordern'],
    ['loquī, loquor, locūtus sum', 'sprechen'],
    ['sequī, sequor, secūtus sum', 'folgen'],
    ['proficīscī, proficīscor, profectus sum', 'aufbrechen'],
    ['patī, patior, passus sum', 'erleiden, zulassen'],
    ['morī, morior, mortuus sum', 'sterben'],
    ['ūtī, ūtor, ūsus sum (mit Abl.)', 'benutzen'],
    ['fierī, fīō, factus sum', 'werden, geschehen'],
    ['nōlle, nōlō, nōluī', 'nicht wollen'],
    ['mālle, mālō, māluī', 'lieber wollen'],
    ['cōnsulere, cōnsulō, cōnsuluī, cōnsultum', 'befragen, sorgen für'],
    ['crēdere, crēdō, crēdidī, crēditum', 'glauben, anvertrauen'],
    ['dēfendere, dēfendō, dēfendī, dēfēnsum', 'verteidigen'],
    ['regere, regō, rēxī, rēctum', 'lenken, beherrschen'],
    ['ut (mit Konj.)', 'dass, damit, sodass'],
    ['nē (mit Konj.)', 'dass nicht, damit nicht'],
    ['sī', 'wenn, falls'],
    ['nisi', 'wenn nicht'],
    ['quamquam', 'obwohl'],
    ['propter (mit Akk.)', 'wegen'],
    ['ob (mit Akk.)', 'wegen'],
    ['causā (nachgestellt, mit Gen.)', 'wegen']
  ])
]

/** Wörter bis einschließlich dieses Lernjahres – als Liste für den KI-Auftrag („Nennform – deutsch") */
export function grundwortschatzBis(lernjahr: number): string[] {
  return LATEIN_GRUNDWORTSCHATZ.filter((w) => w.lernjahr <= Math.max(1, lernjahr)).map((w) => `${w.nennform} – ${w.deutsch}`)
}
