/**
 * Weitere Spieltexte in der Zielsprache (09.10.2026, Entscheidung der Lehrkraft „Nur Fremdsprache"): Meldungen der
 * Spiele der Welle 2, Beschreib-Raten, Lobby und Ergebnis, Bausteine der Oberfläche, Kurzrufe, Schwierigkeiten,
 * Einheiten und die Beschreibungen der Einzelspiele. Fassung: ein Text oder [einfach (Klasse 5–6), normal].
 * Deutsch (`de`) gilt für DaZ-Kurse; fehlt eine Sprache, gilt Englisch (spielSprache.ts).
 */

type F = string | [string, string]
type T = { de: F; en: F; fr?: F; es?: F; it?: F; la?: F }
const t = (de: F, en: F, fr: F, es: F, it: F, la: F): T => ({ de, en, fr, es, it, la })

export const TEXTE2 = {
  // ---------------------------------------------------------------- allgemein
  rundeVon: t('Runde {0} von {1}', 'Round {0} of {1}', 'Manche {0} sur {1}', 'Ronda {0} de {1}', 'Turno {0} di {1}', 'Circuitus {0} ex {1}'),
  rundeFertig: t('Runde fertig!', 'Round complete!', 'Manche terminée !', '¡Ronda terminada!', 'Turno finito!', 'Circuitus perfectus!'),
  deinePunkte: t('Deine Punkte: {0}', 'Your points: {0}', 'Tes points : {0}', 'Tus puntos: {0}', 'I tuoi punti: {0}', 'Puncta tua: {0}'),
  abgegebenWarte: t('Abgegeben – warte auf die anderen.', 'Sent – wait for the others.', 'Envoyé – attends les autres.', 'Enviado – espera a los demás.', 'Inviato – aspetta gli altri.', 'Missum – ceteros exspecta.'),
  ueberspringenLoesung: t('Überspringen (Lösung zeigen)', 'Skip (show the answer)', 'Passer (montrer la réponse)', 'Saltar (mostrar la respuesta)', 'Salta (mostra la risposta)', 'Praetermitte (responsum monstra)'),
  gefunden: t('Gefunden!', 'Found!', 'Trouvé !', '¡Encontrado!', 'Trovato!', 'Inventum!'),
  nichtGanzDoppel: t('Nicht ganz:', 'Not quite:', 'Pas tout à fait :', 'No del todo:', 'Non proprio:', 'Non omnino:'),
  richtigKlein: t('richtig!', 'right!', 'juste !', '¡correcto!', 'giusto!', 'recte!'),
  wortVon: t('Wort {0} von {1}', 'Word {0} of {1}', 'Mot {0} sur {1}', 'Palabra {0} de {1}', 'Parola {0} di {1}', 'Verbum {0} ex {1}'),
  satzVon: t('Satz {0} von {1}', 'Sentence {0} of {1}', 'Phrase {0} sur {1}', 'Frase {0} de {1}', 'Frase {0} di {1}', 'Sententia {0} ex {1}'),
  karteVon: t('Karte {0} von {1}', 'Card {0} of {1}', 'Carte {0} sur {1}', 'Carta {0} de {1}', 'Carta {0} di {1}', 'Charta {0} ex {1}'),
  reiseVon: t('Reise {0} von {1}', 'Trip {0} of {1}', 'Voyage {0} sur {1}', 'Viaje {0} de {1}', 'Viaggio {0} di {1}', 'Iter {0} ex {1}'),
  aussageVon: t('Aussage {0} von {1}', 'Statement {0} of {1}', 'Phrase {0} sur {1}', 'Afirmación {0} de {1}', 'Affermazione {0} di {1}', 'Sententia {0} ex {1}'),
  faengtMit: t('Fängt mit „{0}“ an.', 'It starts with “{0}”.', 'Ça commence par « {0} ».', 'Empieza por «{0}».', 'Comincia con «{0}».', 'A littera “{0}” incipit.'),
  passtNichtKlein: t('passt nicht.', "doesn't fit.", 'ne va pas.', 'no encaja.', 'non va.', 'non convenit.'),
  wortPasst: t('{0} passt!', '{0} fits!', '{0} va !', '¡{0} encaja!', '{0} va bene!', '{0} convenit!'),
  // ---------------------------------------------------------------- Wortkette
  kette: t('Kette ({0} von {1})', 'Chain ({0} of {1})', 'Chaîne ({0} sur {1})', 'Cadena ({0} de {1})', 'Catena ({0} di {1})', 'Catena ({0} ex {1})'),
  neuesGlied: t('Neues Glied!', 'New link!', 'Nouveau maillon !', '¡Nuevo eslabón!', 'Nuovo anello!', 'Novus anulus!'),
  ketteHaelt: t('Die Kette hält trotzdem – weiter!', 'The chain still holds – go on!', 'La chaîne tient quand même – continuez !', 'La cadena aguanta – ¡seguid!', 'La catena tiene lo stesso – avanti!', 'Catena tamen tenet – pergite!'),
  ketteErgebnis: t('Eure Kette hat {0} Glieder.', 'Your chain has {0} links.', 'Votre chaîne a {0} maillons.', 'Vuestra cadena tiene {0} eslabones.', 'La vostra catena ha {0} anelli.', 'Catena vestra {0} anulos habet.'),
  // ---------------------------------------------------------------- Team-Memory
  paarGefunden: t('Paar gefunden!', 'Pair found!', 'Paire trouvée !', '¡Pareja encontrada!', 'Coppia trovata!', 'Par inventum!'),
  keinPaar: t('Kein Paar.', 'No pair.', 'Pas de paire.', 'No es pareja.', 'Nessuna coppia.', 'Non par.'),
  memoryStand: t('Züge: {0} · Paare: {1} von {2}', 'Moves: {0} · Pairs: {1} of {2}', 'Coups : {0} · Paires : {1} sur {2}', 'Jugadas: {0} · Parejas: {1} de {2}', 'Mosse: {0} · Coppie: {1} di {2}', 'Motus: {0} · Paria: {1} ex {2}'),
  memoryDran: t('Du bist dran: zwei Karten aufdecken.', 'Your turn: turn over two cards.', "C'est ton tour : retourne deux cartes.", 'Te toca: da la vuelta a dos cartas.', 'Tocca a te: gira due carte.', 'Tuae partes: duas chartas verte.'),
  memoryErgebnis: t('Alle Paare in {0} Zügen gefunden.', 'All pairs found in {0} moves.', 'Toutes les paires trouvées en {0} coups.', 'Todas las parejas en {0} jugadas.', 'Tutte le coppie trovate in {0} mosse.', 'Omnia paria {0} motibus inventa.'),
  // ---------------------------------------------------------------- Kreuzwort
  gemeinsamesRaetsel: t('Gemeinsames Rätsel', 'Shared puzzle', 'Grille commune', 'Crucigrama común', 'Cruciverba comune', 'Aenigma commune'),
  woerterGeloest: t('Deine Wörter sind gelöst – helft euch gegenseitig!', 'Your words are solved – help each other!', 'Tes mots sont trouvés – aidez-vous !', 'Tus palabras están resueltas – ¡ayudaos!', 'Le tue parole sono risolte – aiutatevi!', 'Verba tua soluta sunt – vos invicem adiuvate!'),
  kreuzErgebnis: t('Rätsel gelöst mit {0} Fehlversuchen.', 'Puzzle solved with {0} wrong tries.', 'Grille résolue avec {0} essais ratés.', 'Crucigrama resuelto con {0} intentos fallidos.', 'Cruciverba risolto con {0} tentativi sbagliati.', 'Aenigma solutum cum {0} conatibus irritis.'),
  // ---------------------------------------------------------------- Fehlerdetektive / Sniper
  wieRichtig: t('Wie heißt „{0}“ richtig?', 'What is the correct form of “{0}”?', 'Quelle est la bonne forme de « {0} » ?', '¿Cuál es la forma correcta de «{0}»?', 'Qual è la forma giusta di «{0}»?', 'Quae est forma recta verbi “{0}”?'),
  fehlerGefunden: t('hat den Fehler gefunden: „{0}“.', 'found the mistake: “{0}”.', 'a trouvé la faute : « {0} ».', 'ha encontrado el error: «{0}».', "ha trovato l'errore: «{0}».", 'errorem invenit: “{0}”.'),
  istRichtigWort: t('„{0}“ ist richtig.', '“{0}” is correct.', '« {0} » est juste.', '«{0}» es correcto.', '«{0}» è giusto.', '“{0}” rectum est.'),
  fallGeloest: t('Fall gelöst!', 'Case solved!', 'Affaire résolue !', '¡Caso resuelto!', 'Caso risolto!', 'Causa soluta!'),
  hatUebersprungen: t('hat übersprungen.', 'skipped.', 'a passé.', 'ha saltado.', 'ha saltato.', 'praetermisit.'),
  satzRot: t('Der Satz – das rote Wort ist falsch', 'The sentence – the red word is wrong', 'La phrase – le mot rouge est faux', 'La frase – la palabra roja es incorrecta', 'La frase – la parola rossa è sbagliata', 'Sententia – verbum rubrum falsum est'),
  deinSatz: t('Dein Satz: Welches Wort ist falsch? Tippe es an.', 'Your sentence: which word is wrong? Tap it.', 'Ta phrase : quel mot est faux ? Touche-le.', 'Tu frase: ¿qué palabra está mal? Tócala.', 'La tua frase: quale parola è sbagliata? Toccala.', 'Sententia tua: quod verbum falsum est? Tange id.'),
  duVerbesserst: t('{0} hat den Fehler gefunden – du verbesserst ihn:', '{0} found the mistake – you correct it:', '{0} a trouvé la faute – tu la corriges :', '{0} ha encontrado el error – tú lo corriges:', "{0} ha trovato l'errore – tu lo correggi:", '{0} errorem invenit – tu eum corrige:'),
  verbessertDeinen: t('Gefunden! Jetzt verbessert {0} deinen Satz.', 'Found! Now {0} corrects your sentence.', 'Trouvé ! Maintenant, {0} corrige ta phrase.', '¡Encontrado! Ahora {0} corrige tu frase.', 'Trovato! Ora {0} corregge la tua frase.', 'Inventum! Nunc {0} sententiam tuam corrigit.'),
  nochFaelle: t('Noch {0} Fälle in dieser Runde.', '{0} cases left in this round.', 'Encore {0} affaires dans cette manche.', 'Quedan {0} casos en esta ronda.', 'Ancora {0} casi in questo turno.', 'Adhuc {0} causae in hoc circuitu.'),
  nochEinFall: t('Noch 1 Fall in dieser Runde.', '1 case left in this round.', 'Encore 1 affaire dans cette manche.', 'Queda 1 caso en esta ronda.', 'Ancora 1 caso in questo turno.', 'Adhuc una causa in hoc circuitu.'),
  faelleErgebnis: t('{0} Fälle bearbeitet, {1} Fehltipps.', '{0} cases done, {1} wrong taps.', '{0} affaires traitées, {1} erreurs.', '{0} casos resueltos, {1} fallos.', '{0} casi svolti, {1} errori.', '{0} causae tractatae, {1} errores.'),
  fehlerEntdeckt: t('hat den Fehler entdeckt!', 'spotted the mistake!', 'a repéré la faute !', '¡ha descubierto el error!', "ha scoperto l'errore!", 'errorem detexit!'),
  danebenPause: t('daneben – 3 Sekunden Pause.', 'missed – 3 seconds break.', 'raté – 3 secondes de pause.', 'fallo – 3 segundos de pausa.', 'sbagliato – 3 secondi di pausa.', 'erravit – tria secunda quies.'),
  niemandGefunden: t('Niemand hat ihn gefunden.', 'Nobody found it.', "Personne ne l'a trouvée.", 'Nadie lo ha encontrado.', "Nessuno l'ha trovato.", 'Nemo eum invenit.'),
  verbesserungFalsch: t('Verbesserung stimmt nicht.', 'The correction is wrong.', "La correction n'est pas juste.", 'La corrección no es correcta.', 'La correzione è sbagliata.', 'Correctio falsa est.'),
  uebersprungen: t('Übersprungen.', 'Skipped.', 'Passé.', 'Saltado.', 'Saltato.', 'Praetermissum.'),
  pause: t('Pause', 'Break', 'Pause', 'Pausa', 'Pausa', 'Quies'),
  tippeFalsches: t('Tippe das falsche Wort an!', 'Tap the wrong word!', 'Touche le mot faux !', '¡Toca la palabra incorrecta!', 'Tocca la parola sbagliata!', 'Verbum falsum tange!'),
  verbessert: t('{0} verbessert.', '{0} is correcting.', '{0} corrige.', '{0} corrige.', '{0} corregge.', '{0} corrigit.'),
  findeNicht: t('Finde ich nicht – überspringen', "Can't find it – skip", 'Je ne trouve pas – passer', 'No lo encuentro – saltar', 'Non lo trovo – salta', 'Non invenio – praetermitte'),
  naechsterSatz: t('Weiter zum nächsten Satz.', 'On to the next sentence.', 'On passe à la phrase suivante.', 'Pasamos a la siguiente frase.', 'Avanti con la prossima frase.', 'Ad sententiam proximam.'),
  // ---------------------------------------------------------------- Dialog-Theater
  deineRolle: t('Deine Rolle: {0}', 'Your role: {0}', 'Ton rôle : {0}', 'Tu papel: {0}', 'Il tuo ruolo: {0}', 'Partes tuae: {0}'),
  bisherGespraech: t('Bisher im Gespräch', 'The conversation so far', 'La conversation jusqu’ici', 'La conversación hasta ahora', 'La conversazione finora', 'Sermo adhuc'),
  rolleFehlt: t('Rolle {0}: Welches Wort fehlt?', 'Role {0}: which word is missing?', 'Rôle {0} : quel mot manque ?', 'Papel {0}: ¿qué palabra falta?', 'Ruolo {0}: quale parola manca?', 'Persona {0}: quod verbum deest?'),
  rolleSpricht: t('Rolle {0} spricht: {1}', 'Role {0} says: {1}', 'Rôle {0} dit : {1}', 'Papel {0} dice: {1}', 'Ruolo {0} dice: {1}', 'Persona {0} dicit: {1}'),
  dialogErgebnis: t('{0} von {1} Zeilen richtig gespielt.', '{0} of {1} lines played correctly.', '{0} répliques sur {1} jouées correctement.', '{0} de {1} frases bien dichas.', '{0} battute su {1} recitate bene.', '{0} ex {1} versibus recte acti.'),
  // ---------------------------------------------------------------- Hör-Kette
  richtigVerstanden: t('richtig verstanden!', 'understood it right!', 'a bien compris !', '¡lo ha entendido bien!', 'ha capito bene!', 'recte intellexit!'),
  diesmalNicht: t('Diesmal nicht.', 'Not this time.', 'Pas cette fois.', 'Esta vez no.', 'Questa volta no.', 'Hoc tempore non.'),
  warEsNicht: t('war es nicht.', "– that wasn't it.", "– ce n'était pas ça.", '– no era eso.', '– non era quella.', '– non erat.'),
  ketteGlieder: t('Kette: {0} Glieder', 'Chain: {0} links', 'Chaîne : {0} maillons', 'Cadena: {0} eslabones', 'Catena: {0} anelli', 'Catena: {0} anuli'),
  duHoerst: t(
    'Du hörst das Wort. Sprich es laut nach – die anderen tippen es an.',
    ['You hear the word. Say it out loud. The others tap it.', 'You hear the word. Say it out loud – the others tap it.'],
    'Tu entends le mot. Répète-le à voix haute – les autres le touchent.',
    'Oyes la palabra. Dila en voz alta – los demás la tocan.',
    'Senti la parola. Ripetila ad alta voce – gli altri la toccano.',
    'Verbum audis. Clara voce dic – ceteri id tangunt.'
  ),
  sprichtVor: t('{0} spricht dir das Wort vor.', '{0} says the word for you.', '{0} te dit le mot.', '{0} te dice la palabra.', '{0} ti dice la parola.', '{0} tibi verbum dicit.'),
  welchesGehoert: t('Welches Wort hast du gehört?', 'Which word did you hear?', 'Quel mot as-tu entendu ?', '¿Qué palabra has oído?', 'Quale parola hai sentito?', 'Quod verbum audivisti?'),
  hoerErgebnis: t('{0} von {1} Wörtern richtig weitergegeben.', '{0} of {1} words passed on correctly.', '{0} mots sur {1} bien transmis.', '{0} de {1} palabras bien transmitidas.', '{0} parole su {1} passate bene.', '{0} ex {1} verbis recte tradita.'),
  // ---------------------------------------------------------------- Reiseplaner
  eureReise: t('Das ist eure Reise!', "That's your trip!", "C'est votre voyage !", '¡Ese es vuestro viaje!', 'È il vostro viaggio!', 'Hoc est iter vestrum!'),
  reisePasstNicht: t('Diese Reise passt nicht zu allen Hinweisen.', "This trip doesn't match all the clues.", 'Ce voyage ne correspond pas à tous les indices.', 'Este viaje no encaja con todas las pistas.', 'Questo viaggio non va con tutti gli indizi.', 'Hoc iter omnibus indiciis non convenit.'),
  deineHinweise: t('Deine Hinweise (nur du siehst sie)', 'Your clues (only you can see them)', 'Tes indices (toi seul les vois)', 'Tus pistas (solo tú las ves)', 'I tuoi indizi (li vedi solo tu)', 'Indicia tua (tu sola/solus vides)'),
  welcheReise: t('Welche Reise ist es? Besprecht euch!', 'Which trip is it? Talk it over!', 'Quel voyage est-ce ? Discutez !', '¿Qué viaje es? ¡Hablad!', 'Quale viaggio è? Parlatene!', 'Quod iter est? Colloquimini!'),
  reiseErgebnis: t('{0} Reisen geplant, {1} Fehlversuche.', '{0} trips planned, {1} wrong tries.', '{0} voyages planifiés, {1} essais ratés.', '{0} viajes planeados, {1} intentos fallidos.', '{0} viaggi pianificati, {1} tentativi sbagliati.', '{0} itinera parata, {1} conatus irriti.'),
  rpReiseN: t('Reise {0}', 'Trip {0}', 'Voyage {0}', 'Viaje {0}', 'Viaggio {0}', 'Iter {0}'),
  rpTippen: t('Tippt eine Reise an, um sie vorzuschlagen.', 'Tap a trip to suggest it.', 'Touchez un voyage pour le proposer.', 'Tocad un viaje para proponerlo.', 'Toccate un viaggio per proporlo.', 'Iter tangite, ut id proponatis.'),
  rpVorschlag: t('{0} schlägt Reise {1} vor.', '{0} suggests trip {1}.', '{0} propose le voyage {1}.', '{0} propone el viaje {1}.', '{0} propone il viaggio {1}.', '{0} iter {1} proponit.'),
  rpZustimmen: t('Einverstanden!', 'Agreed!', "D'accord !", '¡De acuerdo!', "D'accordo!", 'Consentio!'),
  rpWarteZustimmung: t('Warte, bis die anderen zustimmen …', 'Wait until the others agree …', "Attends que les autres soient d'accord …", 'Espera a que los demás estén de acuerdo …', "Aspetta che gli altri siano d'accordo …", 'Exspecta, dum ceteri consentiunt …'),
  rpZustimmungen: t('Einverstanden: {0} von {1}', 'Agreed: {0} of {1}', "D'accord : {0} sur {1}", 'De acuerdo: {0} de {1}', "D'accordo: {0} di {1}", 'Consentiunt: {0} ex {1}'),
  rpPasstNichtWeil: t('Reise {0} passt nicht: „{1}“ ({2})', 'Trip {0} does not fit: “{1}” ({2})', 'Le voyage {0} ne va pas : « {1} » ({2})', 'El viaje {0} no encaja: «{1}» ({2})', 'Il viaggio {0} non va: «{1}» ({2})', 'Iter {0} non convenit: “{1}” ({2})'),
  rpZeitAus: t('Die Zeit ist um – richtig war Reise {0}.', 'Time is up – the right trip was trip {0}.', "Le temps est écoulé – c'était le voyage {0}.", 'Se acabó el tiempo – era el viaje {0}.', 'Il tempo è scaduto – era il viaggio {0}.', 'Tempus exiit – iter {0} rectum erat.'),
  rpZusammen: t('Nur alle Hinweise zusammen passen zu genau einer Reise. Lest sie einander vor!', ['Only all your clues together fit one trip. Read them to each other!', 'Only all clues together fit exactly one trip. Read them out to each other!'], 'Seuls tous les indices ensemble vont avec un seul voyage. Lisez-les à voix haute !', 'Solo todas las pistas juntas encajan con un único viaje. ¡Leédselas!', 'Solo tutti gli indizi insieme vanno con un solo viaggio. Leggeteli ad alta voce!', 'Omnia indicia una uni tantum itineri conveniunt. Ea inter vos recitate!'),
  // ---------------------------------------------------------------- Schnapp!
  schnapp: t('Schnapp!', 'Snap!', 'Attrapé !', '¡Atrapado!', 'Preso!', 'Captum!'),
  zuFrueh: t('hat zu früh geschnappt.', 'snapped too early.', 'a attrapé trop tôt.', 'ha atrapado demasiado pronto.', 'ha preso troppo presto.', 'nimis cito cepit.'),
  passteNicht: t('Richtig, das passte nicht.', "Right, that didn't match.", "Juste, ça n'allait pas ensemble.", 'Correcto, no iba junto.', 'Giusto, non andava insieme.', 'Recte, non congruebat.'),
  schnappPasst: t('Schnapp! Passt!', 'Snap! It matches!', 'Attrape ! Ça va !', '¡Atrapa! ¡Va junto!', 'Prendi! Va insieme!', 'Cape! Congruit!'),
  passtNichtKnopf: t('Passt nicht', "Doesn't match", 'Ça ne va pas', 'No va junto', 'Non va insieme', 'Non congruit'),
  // ---------------------------------------------------------------- Galgen-Duell
  wortGeschafft: t('hat ein Wort geschafft!', 'got a word!', 'a trouvé un mot !', '¡ha acertado una palabra!', 'ha indovinato una parola!', 'verbum invenit!'),
  neuesWort: t('Neues Wort.', 'New word.', 'Nouveau mot.', 'Palabra nueva.', 'Nuova parola.', 'Novum verbum.'),
  gesucht: t('Gesucht: {0}', 'Find the word for: {0}', 'Trouve le mot pour : {0}', 'Busca la palabra para: {0}', 'Trova la parola per: {0}', 'Quaere verbum: {0}'),
  fehlerVonMax: t('Fehler {0} von {1}', 'Mistakes: {0} of {1}', 'Erreurs : {0} sur {1}', 'Errores: {0} de {1}', 'Errori: {0} di {1}', 'Errores: {0} ex {1}'),
  // ---------------------------------------------------------------- Team-Buzzer
  fuersTeam: t('+{0} für das Team!', '+{0} for the team!', "+{0} pour l'équipe !", '¡+{0} para el equipo!', '+{0} per la squadra!', '+{0} turmae!'),
  auchDaneben: t('auch daneben.', 'also missed.', 'raté aussi.', 'también ha fallado.', 'sbagliato anche.', 'quoque erravit.'),
  buzzer: t('Buzzer!', 'Buzz!', 'Buzzer !', '¡Pulsa!', 'Premi!', 'Preme!'),
  antwortet: t('{0} antwortet.', '{0} is answering.', '{0} répond.', '{0} responde.', '{0} risponde.', '{0} respondet.'),
  anderesTeamAntwortet: t('Das andere Team antwortet.', 'The other team is answering.', "L'autre équipe répond.", 'El otro equipo responde.', "L'altra squadra risponde.", 'Altera turma respondet.'),
  // ---------------------------------------------------------------- Wort-Auktion
  aussageStimmte: t('Die Aussage stimmte.', 'The statement was true.', 'La phrase était vraie.', 'La afirmación era verdadera.', "L'affermazione era vera.", 'Sententia vera erat.'),
  aussageStimmteNicht: t('Die Aussage stimmte nicht.', 'The statement was false.', 'La phrase était fausse.', 'La afirmación era falsa.', "L'affermazione era falsa.", 'Sententia falsa erat.'),
  deineMuenzen: t('Deine Münzen: {0}', 'Your coins: {0}', 'Tes pièces : {0}', 'Tus monedas: {0}', 'Le tue monete: {0}', 'Nummi tui: {0}'),
  gebotAb: t('Gebot abgegeben – warte auf die anderen.', 'Bet placed – wait for the others.', 'Mise faite – attends les autres.', 'Apuesta hecha – espera a los demás.', 'Puntata fatta – aspetta gli altri.', 'Pignus positum – ceteros exspecta.'),
  aufStimmt: t('{0} auf „stimmt“', '{0} on “true”', '{0} sur « vrai »', '{0} a «verdadero»', '{0} su «vero»', '{0} in “verum”'),
  aufStimmtNicht: t('{0} auf „stimmt nicht“', '{0} on “false”', '{0} sur « faux »', '{0} a «falso»', '{0} su «falso»', '{0} in “falsum”'),
  // ---------------------------------------------------------------- Wort-Domino
  steinDoch: t('hatte den passenden Stein doch.', 'had the right tile after all.', 'avait quand même le bon domino.', 'sí tenía la ficha correcta.', 'aveva la tessera giusta.', 'tesseram rectam tamen habuit.'),
  steinPasstNicht: t('Der Stein passt nicht.', "That tile doesn't fit.", 'Ce domino ne va pas.', 'Esa ficha no encaja.', 'Questa tessera non va.', 'Haec tessera non convenit.'),
  legtAn: t('legt an!', 'plays a tile!', 'pose un domino !', '¡coloca una ficha!', 'mette una tessera!', 'tesseram ponit!'),
  offen: t('Offen: {0}', 'Open: {0}', 'Ouvert : {0}', 'Abierto: {0}', 'Aperto: {0}', 'Apertum: {0}'),
  dominoDran: t(
    'Du bist dran: lege den Stein mit dem passenden Wort – oder passe.',
    ['Your turn: play the tile with the right word – or pass.', 'Your turn: play the tile with the matching word – or pass.'],
    "C'est ton tour : pose le domino avec le bon mot – ou passe.",
    'Te toca: coloca la ficha con la palabra correcta – o pasa.',
    'Tocca a te: metti la tessera con la parola giusta – o passa.',
    'Tuae partes: tesseram cum verbo recto pone – aut transi.'
  ),
  deineSteine: t('Deine Steine ({0})', 'Your tiles ({0})', 'Tes dominos ({0})', 'Tus fichas ({0})', 'Le tue tessere ({0})', 'Tesserae tuae ({0})'),
  passen: t('Passen', 'Pass', 'Passer', 'Pasar', 'Passa', 'Transi'),
  // ---------------------------------------------------------------- Stadt-Land-Fluss
  slfWort: t('Ein Wort aus dem Kurs', 'A word from your course', 'Un mot de ton cours', 'Una palabra de tu curso', 'Una parola del tuo corso', 'Verbum ex cursu tuo'),
  slfLang: t('Ein Wort mit mindestens 5 Buchstaben', 'A word with at least 5 letters', 'Un mot d’au moins 5 lettres', 'Una palabra de al menos 5 letras', 'Una parola di almeno 5 lettere', 'Verbum quinque litterarum saltem'),
  slfNomen: t('Ein Nomen', 'A noun', 'Un nom', 'Un sustantivo', 'Un nome', 'Nomen'),
  slfVerb: t('Ein Verb', 'A verb', 'Un verbe', 'Un verbo', 'Un verbo', 'Verbum (actionis)'),
  slfDeutsch: t(
    'Die deutsche Bedeutung eines Kursworts (das Kurswort beginnt mit dem Buchstaben)',
    'The German meaning of a course word (the course word starts with the letter)',
    "Le sens allemand d'un mot du cours (le mot commence par la lettre)",
    'El significado alemán de una palabra del curso (la palabra empieza por la letra)',
    'Il significato tedesco di una parola del corso (la parola comincia con la lettera)',
    'Significatio Germanica verbi cursus (verbum a littera incipit)'
  ),
  zaehltNicht: t('{0}: „{1}“ zählt nicht', '{0}: “{1}” does not count', '{0} : « {1} » ne compte pas', '{0}: «{1}» no cuenta', '{0}: «{1}» non conta', '{0}: “{1}” non valet'),
  rundeAusgewertet: t('Runde {0} ausgewertet.', 'Round {0} checked.', 'Manche {0} corrigée.', 'Ronda {0} corregida.', 'Turno {0} corretto.', 'Circuitus {0} probatus.'),
  rundeBuchstabe: t('Runde {0}: Buchstabe {1}', 'Round {0}: letter {1}', 'Manche {0} : lettre {1}', 'Ronda {0}: letra {1}', 'Turno {0}: lettera {1}', 'Circuitus {0}: littera {1}'),
  // ---------------------------------------------------------------- Rennen (Wörterturm, Konjugation, Umbau, Kollokation, Synonyme)
  gemeinsamVon: t('Gemeinsam: {0} von {1} {2}', 'Together: {0} of {1} {2}', 'Ensemble : {0} sur {1} {2}', 'Juntos: {0} de {1} {2}', 'Insieme: {0} di {1} {2}', 'Una: {0} ex {1} {2}'),
  geschafftEinheit: t('Geschafft: {0} {1}!', 'Done: {0} {1}!', 'Réussi : {0} {1} !', '¡Logrado: {0} {1}!', 'Fatto: {0} {1}!', 'Perfectum: {0} {1}!'),
  vonEinheit: t('{0} von {1} {2}.', '{0} of {1} {2}.', '{0} sur {1} {2}.', '{0} de {1} {2}.', '{0} di {1} {2}.', '{0} ex {1} {2}.'),
  welchesPasstDazu: t('Welches Wort passt dazu?', 'Which word goes with it?', 'Quel mot va avec ?', '¿Qué palabra va con esto?', 'Quale parola ci va?', 'Quod verbum convenit?'),
  welchesDasselbe: t('Welches Wort bedeutet dasselbe?', 'Which word means the same?', 'Quel mot veut dire la même chose ?', '¿Qué palabra significa lo mismo?', 'Quale parola significa lo stesso?', 'Quod verbum idem significat?'),
  // ---------------------------------------------------------------- Beschreib-Raten
  bWortart: t('Wortart: {0}', 'Part of speech: {0}', 'Nature du mot : {0}', 'Tipo de palabra: {0}', 'Parte del discorso: {0}', 'Pars orationis: {0}'),
  bAnfang: t('Fängt mit „{0}“ an', 'Starts with “{0}”', 'Commence par « {0} »', 'Empieza por «{0}»', 'Comincia con «{0}»', 'A “{0}” incipit'),
  bEnde: t('Endet auf „{0}“', 'Ends with “{0}”', 'Finit par « {0} »', 'Termina en «{0}»', 'Finisce con «{0}»', 'In “{0}” desinit'),
  bLaenge: t('{0} Buchstaben', '{0} letters', '{0} lettres', '{0} letras', '{0} lettere', '{0} litterae'),
  bLaengeWoerter: t('{0} Buchstaben in {1} Wörtern', '{0} letters in {1} words', '{0} lettres en {1} mots', '{0} letras en {1} palabras', '{0} lettere in {1} parole', '{0} litterae in {1} verbis'),
  bGegenteil: t('Gegenteil: {0}', 'Opposite: {0}', 'Contraire : {0}', 'Contrario: {0}', 'Contrario: {0}', 'Contrarium: {0}'),
  bErraten: t('hat es erraten!', 'guessed it!', "l'a deviné !", '¡lo ha adivinado!', "l'ha indovinata!", 'divinavit!'),
  bNichtErraten: t('Diesmal nicht erraten.', 'Not guessed this time.', 'Pas deviné cette fois.', 'Esta vez no se ha adivinado.', 'Questa volta non indovinata.', 'Hoc tempore non divinatum.'),
  bWarNicht: t('„{0}“ war es nicht.', "It wasn't “{0}”.", "Ce n'était pas « {0} ».", 'No era «{0}».', 'Non era «{0}».', 'Non erat “{0}”.'),
  bDuErklaerst: t('Du erklärst: {0} ({1})', 'You explain: {0} ({1})', 'Tu expliques : {0} ({1})', 'Tú explicas: {0} ({1})', 'Tu spieghi: {0} ({1})', 'Tu explicas: {0} ({1})'),
  bWaehle: t('Wähle 2 bis 3 Hinweise und schicke sie ab', 'Choose 2 or 3 clues and send them', 'Choisis 2 ou 3 indices et envoie-les', 'Elige 2 o 3 pistas y envíalas', 'Scegli 2 o 3 indizi e inviali', 'Elige duo aut tria indicia et mitte'),
  bAndereRaten: t('Die anderen raten jetzt.', 'The others are guessing now.', 'Les autres devinent maintenant.', 'Ahora adivinan los demás.', 'Ora indovinano gli altri.', 'Nunc ceteri divinant.'),
  bErklaert: t('{0} erklärt.', '{0} is explaining.', '{0} explique.', '{0} explica.', '{0} spiega.', '{0} explicat.'),
  bWarteHinweise: t('Warte auf die Hinweise …', 'Waiting for the clues …', 'On attend les indices …', 'Esperando las pistas …', 'Aspetta gli indizi …', 'Indicia exspecta …'),
  bHinweise: t('Hinweise', 'Clues', 'Indices', 'Pistas', 'Indizi', 'Indicia'),
  bWelchesGemeint: t('Welches Wort ist gemeint?', 'Which word is it?', 'Quel est le mot ?', '¿Qué palabra es?', 'Qual è la parola?', 'Quod verbum est?'),
  bErgebnis: t('{0} von {1} Wörtern erraten.', '{0} of {1} words guessed.', '{0} mots sur {1} devinés.', '{0} de {1} palabras adivinadas.', '{0} parole su {1} indovinate.', '{0} ex {1} verbis divinata.'),
  // ---------------------------------------------------------------- Lobby und Ergebnis (MehrspielerSeite)
  uiEinladungscode: t('Einladungscode', 'Invitation code', "Code d'invitation", 'Código de invitación', 'Codice di invito', 'Signum invitationis'),
  uiCodeHinweis: t(
    'Die anderen geben ihn auf der Startseite bei „Mit Code öffnen“ oder in der Spielauswahl ein.',
    ['The others type it in on the start page (“Mit Code öffnen”) or in the game list.', 'The others enter it on the start page (“Mit Code öffnen”) or in the list of games.'],
    'Les autres le tapent sur la page d’accueil (« Mit Code öffnen ») ou dans la liste des jeux.',
    'Los demás lo escriben en la página de inicio («Mit Code öffnen») o en la lista de juegos.',
    'Gli altri lo scrivono nella pagina iniziale («Mit Code öffnen») o nella lista dei giochi.',
    'Ceteri id in pagina prima (“Mit Code öffnen”) aut in indice ludorum inscribunt.'
  ),
  uiDabei: t('Dabei ({0} von {1})', 'Players ({0} of {1})', 'Joueurs ({0} sur {1})', 'Jugadores ({0} de {1})', 'Giocatori ({0} di {1})', 'Lusores ({0} ex {1})'),
  uiGetrennt: t(
    'Verbindung unterbrochen – der Platz bleibt 60 Sekunden frei',
    'Connection lost – the place is kept for 60 seconds',
    'Connexion perdue – la place reste libre 60 secondes',
    'Conexión perdida – el sitio se guarda 60 segundos',
    'Connessione persa – il posto resta libero 60 secondi',
    'Conexio interrupta – locus 60 secunda servatur'
  ),
  uiHerausnehmen: t('{0} herausnehmen', 'Remove {0}', 'Retirer {0}', 'Quitar a {0}', 'Togli {0}', '{0} remove'),
  uiSpiel: t('Spiel', 'Game', 'Jeu', 'Juego', 'Gioco', 'Ludus'),
  uiSchwierigkeit: t('Schwierigkeit', 'Level', 'Niveau', 'Nivel', 'Livello', 'Gradus'),
  uiBerechnet: t('{0} – berechnet aus dem Lernstand von allen.', '{0} – based on what all of you know.', '{0} – calculé avec ce que vous savez tous.', '{0} – según lo que sabéis todos.', '{0} – in base a quello che sapete tutti.', '{0} – ex eo quod omnes scitis.'),
  uiGrammatik: t('Grammatik', 'Grammar', 'Grammaire', 'Gramática', 'Grammatica', 'Grammatica'),
  uiStarten: t('Spiel starten', 'Start the game', 'Commencer le jeu', 'Empezar el juego', 'Inizia il gioco', 'Ludum incipe'),
  uiWarteMit: t('Warte auf Mitspielende (mindestens {0})', 'Waiting for players (at least {0})', 'On attend des joueurs (au moins {0})', 'Esperando jugadores (al menos {0})', 'Aspetta i giocatori (almeno {0})', 'Lusores exspecta (saltem {0})'),
  uiGleich: t(
    'Gleich geht’s los – {0} wählt die Schwierigkeit und startet. Schwierigkeit: {1}',
    ['Get ready! {0} chooses the level and starts. Level: {1}', 'Get ready – {0} chooses the level and starts the game. Level: {1}'],
    'Ça commence bientôt – {0} choisit le niveau et lance le jeu. Niveau : {1}',
    'Empieza enseguida – {0} elige el nivel y empieza. Nivel: {1}',
    'Si comincia subito – {0} sceglie il livello e inizia. Livello: {1}',
    'Mox incipimus – {0} gradum eligit et incipit. Gradus: {1}'
  ),
  uiDerHost: t('der Host', 'the host', "l'hôte", 'el anfitrión', "l'organizzatore", 'hospes'),
  uiTeamZiel: t('Team-Ziel geschafft!', 'Team goal reached!', 'Objectif atteint !', '¡Objetivo logrado!', 'Obiettivo raggiunto!', 'Propositum effectum!'),
  uiGutGespielt: t('Gut gespielt!', 'Well played!', 'Bien joué !', '¡Bien jugado!', 'Ben giocato!', 'Bene lusum!'),
  uiGewonnen: t('Gewonnen: {0}', 'Winner: {0}', 'Gagnant : {0}', 'Ganador: {0}', 'Vincitore: {0}', 'Victor: {0}'),
  uiNurFuerDich: t('Nur für dich', 'Only for you', 'Rien que pour toi', 'Solo para ti', 'Solo per te', 'Tibi soli'),
  uiRichtigN: t('{0} richtig', '{0} correct', '{0} justes', '{0} correctas', '{0} giuste', '{0} recta'),
  uiPlatz: t('Platz {0}', 'Place {0}', '{0}e place', 'Puesto {0}', '{0}° posto', 'Locus {0}'),
  uiEinWortWieder: t('1 Wort kommt im Kasten bald wieder dran.', 'You will practise 1 word again soon.', 'Tu vas revoir 1 mot bientôt.', 'Pronto repasarás 1 palabra.', 'Presto ripasserai 1 parola.', 'Mox unum verbum iterum exercebis.'),
  uiWoerterWieder: t('{0} Wörter kommen im Kasten bald wieder dran.', 'You will practise {0} words again soon.', 'Tu vas revoir {0} mots bientôt.', 'Pronto repasarás {0} palabras.', 'Presto ripasserai {0} parole.', 'Mox {0} verba iterum exercebis.'),
  uiZurueck: t('Zurück', 'Back', 'Retour', 'Volver', 'Indietro', 'Redi'),
  uiNochmal: t('Nochmal', 'Play again', 'Rejouer', 'Otra vez', 'Ancora', 'Iterum'),
  uiVerlassen: t('Verlassen', 'Leave', 'Quitter', 'Salir', 'Esci', 'Exi'),
  uiKooperativ: t('Kooperativ', 'Co-op', 'Coopératif', 'Cooperativo', 'Cooperativo', 'Communiter'),
  uiVersus: t('Versus', 'Versus', 'Duel', 'Duelo', 'Sfida', 'Certamen'),
  uiKoopText: t('Gemeinsam mit anderen aus deinem Kurs ein Ziel schaffen', 'Reach a goal together with others from your course', 'Atteindre un but avec d\'autres de ton cours', 'Lograr un objetivo junto con otros de tu curso', 'Raggiungere un obiettivo insieme ad altri del tuo corso', 'Cum aliis cursus tui propositum una efficere'),
  uiVersusText: t('Gegeneinander – fair, mit Fragen passend zu eurem Können', 'Against each other – fair, with questions that match what you know', 'Les uns contre les autres – juste, avec des questions à votre niveau', 'Unos contra otros – justo, con preguntas a vuestro nivel', 'Uno contro l\'altro – giusto, con domande adatte al vostro livello', 'Alii contra alios – aequo modo, quaestionibus ad vestram scientiam aptis'),
  uiZiffern: t('6 Ziffern', '6 digits', '6 chiffres', '6 cifras', '6 cifre', 'sex numeri'),
  uiBeitreten: t('Beitreten', 'Join', 'Rejoindre', 'Unirse', 'Entra', 'Intra'),
  uiCodeSechs: t('Der Einladungscode hat sechs Ziffern.', 'The invitation code has six digits.', 'Le code d\'invitation a six chiffres.', 'El código de invitación tiene seis cifras.', 'Il codice di invito ha sei cifre.', 'Signum invitationis sex numeros habet.'),
  uiNachUebung: t('Zusammen spielen gibt es nach der Übung für heute.', 'You can play together after today\'s practice.', 'On joue ensemble après l\'exercice du jour.', 'Se juega juntos después de la práctica de hoy.', 'Si gioca insieme dopo l\'esercizio di oggi.', 'Post exercitationem hodiernam una ludere licet.'),
  uiWirdEroeffnet: t('Runde wird eröffnet …', 'Opening the game …', 'La partie s’ouvre …', 'Abriendo la partida …', 'Apertura della partita …', 'Ludus aperitur …'),
  uiStartenPersonen: t('Spiel starten · {0}–{1} Personen', 'Start · {0}–{1} players', 'Commencer · {0} à {1} joueurs', 'Empezar · {0}–{1} jugadores', 'Inizia · {0}–{1} giocatori', 'Incipe · {0}–{1} lusores'),
  uiCodeTitel: t('Zusammen spielen – Einladungscode', 'Play together – invitation code', 'Jouer ensemble – code d\'invitation', 'Jugar juntos – código de invitación', 'Giocare insieme – codice di invito', 'Una ludere – signum invitationis'),
  uiCodeBeschreibung: t('Hat dich jemand eingeladen? Code eingeben und Enter drücken.', 'Did someone invite you? Type the code and press Enter.', 'Quelqu\'un t\'a invité ? Tape le code et appuie sur Entrée.', '¿Alguien te ha invitado? Escribe el código y pulsa Intro.', 'Qualcuno ti ha invitato? Scrivi il codice e premi Invio.', 'Num quis te invitavit? Signum inscribe et Enter preme.'),
  // ---------------------------------------------------------------- Bausteine (Bloecke)
  uiAntwortSchreiben: t('Antwort schreiben', 'Type your answer', 'Écris ta réponse', 'Escribe tu respuesta', 'Scrivi la risposta', 'Responsum scribe'),
  uiKeineAntwort: t('Auf deinem Gerät ist gerade keine Antwort.', 'There is no answer on your device right now.', "Il n'y a pas de réponse sur ton appareil maintenant.", 'Ahora no hay ninguna respuesta en tu aparato.', 'Ora non c’è nessuna risposta sul tuo dispositivo.', 'Nunc nullum responsum in instrumento tuo est.'),
  uiNochmalHoeren: t('Nochmal hören', 'Listen again', 'Réécouter', 'Escuchar otra vez', 'Ascolta di nuovo', 'Iterum audi'),
  uiAbschicken: t('Abschicken', 'Send', 'Envoyer', 'Enviar', 'Invia', 'Mitte'),
  uiAbschickenN: t('Abschicken ({0})', 'Send ({0})', 'Envoyer ({0})', 'Enviar ({0})', 'Invia ({0})', 'Mitte ({0})'),
  // ---------------------------------------------------------------- Schwierigkeiten und Kurzrufe
  sLeicht: t('Leicht', 'Easy', 'Facile', 'Fácil', 'Facile', 'Facilis'),
  sMittel: t('Mittel', 'Medium', 'Moyen', 'Medio', 'Medio', 'Medius'),
  sSchwer: t('Schwer', 'Hard', 'Difficile', 'Difícil', 'Difficile', 'Difficilis'),
  sUnmoeglich: t('Unmöglich', 'Impossible', 'Impossible', 'Imposible', 'Impossibile', 'Impossibilis'),
  sLeichtText: t('Wörter, die alle sicher können', 'Words everyone knows well', 'Des mots que tout le monde connaît bien', 'Palabras que todos sabéis bien', 'Parole che tutti sanno bene', 'Verba quae omnes bene sciunt'),
  sMittelText: t('Ab und zu ging etwas daneben', 'Sometimes something went wrong', 'Parfois, il y avait une erreur', 'A veces algo salió mal', 'A volte qualcosa è andato storto', 'Interdum aliquid erratum est'),
  sSchwerText: t('Öfter falsch – gut zum Üben', 'Often wrong – good for practice', 'Souvent faux – bien pour s’entraîner', 'A menudo mal – bueno para practicar', 'Spesso sbagliate – buone per esercitarsi', 'Saepe falsa – apta ad exercendum'),
  sUnmoeglichText: t('Die Stolpersteine von allen', "Everyone's trickiest words", 'Les pièges de tout le monde', 'Las trampas de todos', 'Le trappole di tutti', 'Verba omnibus difficillima'),
  ruf0: t('Gut gemacht!', 'Well done!', 'Bravo !', '¡Bien hecho!', 'Brava/o!', 'Bene factum!'),
  ruf1: t('Hilfe?', 'Help?', "De l'aide ?", '¿Ayuda?', 'Aiuto?', 'Auxilium?'),
  ruf2: t('Ich bin dran', "It's my turn", "C'est mon tour", 'Me toca a mí', 'Tocca a me', 'Meae partes sunt'),
  ruf3: t('Super Team!', 'Great team!', 'Super équipe !', '¡Gran equipo!', 'Grande squadra!', 'Optima turma!'),
  ruf4: t('Moment …', 'Wait …', 'Attends …', 'Un momento …', 'Un momento …', 'Mane …'),
  // ---------------------------------------------------------------- Karten der Einzelspiele (Hinweis, wenn gesperrt)
  brauchtBeispielsatz: t('Braucht Wörter mit Beispielsatz.', 'Needs words with an example sentence.', 'Il faut des mots avec une phrase d’exemple.', 'Necesita palabras con frase de ejemplo.', 'Servono parole con una frase d’esempio.', 'Verba cum exemplo requirit.'),
  brauchtVier: t('Braucht mindestens vier Wörter.', 'Needs at least four words.', 'Il faut au moins quatre mots.', 'Necesita al menos cuatro palabras.', 'Servono almeno quattro parole.', 'Saltem quattuor verba requirit.')
} satisfies Record<string, T>

/** Einheiten (Rekord, Ergebnis) – Schlüssel ist die deutsche Einheit aus MEHRSPIELE/SPIELE */
export const EINHEITEN: Record<string, Omit<T, 'de'>> = {
  gelöst: { en: 'solved', fr: 'résolues', es: 'resueltas', it: 'risolte', la: 'soluta' },
  Fehler: { en: 'mistakes', fr: 'fautes', es: 'errores', it: 'errori', la: 'errores' },
  s: { en: 's', fr: 's', es: 's', it: 's', la: 's' },
  erraten: { en: 'guessed', fr: 'devinés', es: 'adivinadas', it: 'indovinate', la: 'divinata' },
  Punkte: { en: 'points', fr: 'points', es: 'puntos', it: 'punti', la: 'puncta' },
  richtig: { en: 'correct', fr: 'justes', es: 'correctas', it: 'giuste', la: 'recta' },
  Aufrufe: { en: 'calls', fr: 'appels', es: 'llamadas', it: 'chiamate', la: 'vocationes' },
  Treffer: { en: 'hits', fr: 'touchés', es: 'tocados', it: 'colpi', la: 'ictus' },
  Glieder: { en: 'links', fr: 'maillons', es: 'eslabones', it: 'anelli', la: 'anuli' },
  Züge: { en: 'moves', fr: 'coups', es: 'jugadas', it: 'mosse', la: 'motus' },
  Steine: { en: 'pieces', fr: 'pierres', es: 'piezas', it: 'pezzi', la: 'lapides' },
  Wörter: { en: 'words', fr: 'mots', es: 'palabras', it: 'parole', la: 'verba' },
  Sätze: { en: 'sentences', fr: 'phrases', es: 'frases', it: 'frasi', la: 'sententiae' },
  Münzen: { en: 'coins', fr: 'pièces', es: 'monedas', it: 'monete', la: 'nummi' },
  Sprossen: { en: 'rungs', fr: 'barreaux', es: 'peldaños', it: 'pioli', la: 'gradus' }
}

/** Beschreibungen der Einzelspiele (Karten) – Deutsch steht in vokabelSpiele.ts bzw. grammatiktrainer.ts */
export const EINZEL_BESCHREIBUNG: Record<string, Omit<T, 'de'>> = {
  'vok:memory': { en: 'Find the word and its translation as a pair.', fr: 'Trouve le mot et sa traduction en paire.', es: 'Encuentra la palabra y su traducción como pareja.', it: 'Trova la parola e la sua traduzione come coppia.', la: 'Verbum et translationem eius ut par inveni.' },
  'vok:zuordnen': { en: 'Tap the pairs as fast as you can.', fr: 'Touche les paires le plus vite possible.', es: 'Toca las parejas lo más rápido posible.', it: 'Tocca le coppie il più velocemente possibile.', la: 'Paria quam celerrime tange.' },
  'vok:blitz': { en: '60 seconds – as many right answers as you can.', fr: '60 secondes – le plus de bonnes réponses possible.', es: '60 segundos – todas las respuestas correctas que puedas.', it: '60 secondi – più risposte giuste possibili.', la: 'Sexaginta secunda – quam plurima responsa recta.' },
  'vok:satz': { en: 'Put the example sentences in the right order.', fr: "Remets les phrases d'exemple dans le bon ordre.", es: 'Ordena las frases de ejemplo.', it: "Metti in ordine le frasi d'esempio.", la: 'Exempla recto ordine pone.' },
  'vok:wortraten': { en: 'Guess the letters before the flower loses all its leaves.', fr: 'Devine les lettres avant que la fleur perde toutes ses feuilles.', es: 'Adivina las letras antes de que la flor pierda todas sus hojas.', it: 'Indovina le lettere prima che il fiore perda tutte le foglie.', la: 'Litteras divina, antequam flos omnia folia amittit.' },
  'vok:kreuzwort': { en: 'Your words in a crossword, with German clues.', fr: 'Tes mots en mots croisés, avec des indices en allemand.', es: 'Tus palabras en un crucigrama, con pistas en alemán.', it: 'Le tue parole in un cruciverba, con indizi in tedesco.', la: 'Verba tua decussata, cum indiciis Germanicis.' },
  'vok:fallend': { en: 'Type the translation before the word reaches the bottom.', fr: 'Tape la traduction avant que le mot arrive en bas.', es: 'Escribe la traducción antes de que la palabra llegue abajo.', it: 'Scrivi la traduzione prima che la parola arrivi in fondo.', la: 'Translationem scribe, antequam verbum ad imum pervenit.' },
  'vok:suchsel': { en: 'Find the words in the letter grid.', fr: 'Trouve les mots dans la grille de lettres.', es: 'Encuentra las palabras en la sopa de letras.', it: 'Trova le parole nella griglia di lettere.', la: 'Verba in tabula litterarum inveni.' },
  'vok:bildwort': { en: 'Find the word for the picture.', fr: "Trouve le mot pour l'image.", es: 'Encuentra la palabra para la imagen.', it: "Trova la parola per l'immagine.", la: 'Verbum picturae inveni.' },
  'vok:hoeren': { en: 'Listen and choose the right spelling.', fr: "Écoute et choisis la bonne orthographe.", es: 'Escucha y elige la escritura correcta.', it: 'Ascolta e scegli la scrittura giusta.', la: 'Audi et rectam scripturam elige.' },
  'vok:satzhoeren': { en: 'Listen to the sentence and put the words in order.', fr: 'Écoute la phrase et mets les mots dans l’ordre.', es: 'Escucha la frase y ordena las palabras.', it: 'Ascolta la frase e metti in ordine le parole.', la: 'Sententiam audi et verba ordina.' },
  'vok:diktat': { en: 'Listen to the word and write it correctly.', fr: 'Écoute le mot et écris-le correctement.', es: 'Escucha la palabra y escríbela bien.', it: 'Ascolta la parola e scrivila bene.', la: 'Verbum audi et recte scribe.' },
  'vok:satzluecke': { en: 'Put the right word into the example sentence.', fr: "Mets le bon mot dans la phrase d'exemple.", es: 'Pon la palabra correcta en la frase de ejemplo.', it: "Metti la parola giusta nella frase d'esempio.", la: 'Verbum rectum in exemplum insere.' },
  'vok:duell': { en: 'Does the pair match? 20 rounds against your best time.', fr: 'La paire va-t-elle ensemble ? 20 manches contre ton record.', es: '¿La pareja va junta? 20 rondas contra tu mejor tiempo.', it: 'La coppia va bene? 20 turni contro il tuo record.', la: 'Congruitne par? Viginti circuitus contra tempus tuum optimum.' },
  'vok:hoermemory': { en: 'Find the word that goes with each sound.', fr: 'Trouve le mot qui va avec chaque son.', es: 'Encuentra la palabra de cada sonido.', it: 'Trova la parola per ogni suono.', la: 'Verbum cuique sono inveni.' },
  'vok:richtiggehoert': { en: '60 seconds: does the picture match the word you hear?', fr: "60 secondes : l'image va-t-elle avec le mot entendu ?", es: '60 segundos: ¿la imagen va con la palabra que oyes?', it: "60 secondi: l'immagine va con la parola che senti?", la: 'Sexaginta secunda: congruitne pictura verbo audito?' },
  'vok:buchstaben': { en: 'Listen and build the word from letters.', fr: 'Écoute et forme le mot avec des lettres.', es: 'Escucha y forma la palabra con letras.', it: 'Ascolta e forma la parola con le lettere.', la: 'Audi et verbum ex litteris compone.' },
  'vok:hoerbingo': { en: 'Tap the words you hear – a full line is Bingo.', fr: 'Touche les mots entendus – une ligne pleine, c’est Bingo.', es: 'Toca las palabras que oyes – una línea completa es Bingo.', it: 'Tocca le parole che senti – una riga piena è Bingo.', la: 'Verba audita tange – linea plena est Bingo.' },
  'vok:bildmemory': { en: 'Find the picture and the word as a pair.', fr: "Trouve l'image et le mot en paire.", es: 'Encuentra la imagen y la palabra como pareja.', it: "Trova l'immagine e la parola come coppia.", la: 'Picturam et verbum ut par inveni.' },
  'vok:wasfehlt': { en: 'Remember the pictures – which one has gone?', fr: 'Retiens les images – laquelle a disparu ?', es: 'Recuerda las imágenes – ¿cuál ha desaparecido?', it: 'Ricorda le immagini – quale è sparita?', la: 'Picturas memento – quae evanuit?' },
  'vok:aufdecken': { en: 'Guess the word before the whole picture is shown.', fr: "Devine le mot avant que toute l'image soit visible.", es: 'Adivina la palabra antes de ver toda la imagen.', it: "Indovina la parola prima di vedere tutta l'immagine.", la: 'Verbum divina, antequam tota pictura apparet.' },
  'vok:wortbild': { en: 'Tap the picture that goes with the word.', fr: "Touche l'image qui va avec le mot.", es: 'Toca la imagen que va con la palabra.', it: "Tocca l'immagine che va con la parola.", la: 'Picturam quae verbo convenit tange.' },
  'vok:verbtrio': { en: 'Find all the forms of a verb together.', fr: "Trouve ensemble toutes les formes d'un verbe.", es: 'Encuentra juntas todas las formas de un verbo.', it: 'Trova insieme tutte le forme di un verbo.', la: 'Omnes formas verbi una inveni.' },
  'vok:formenblitz': { en: '60 seconds: which form did you hear?', fr: '60 secondes : quelle forme as-tu entendue ?', es: '60 segundos: ¿qué forma has oído?', it: '60 secondi: quale forma hai sentito?', la: 'Sexaginta secunda: quam formam audivisti?' },
  'vok:bildverb': { en: 'Give the forms of the verb for the picture.', fr: "Donne les formes du verbe pour l'image.", es: 'Di las formas del verbo de la imagen.', it: "Scrivi le forme del verbo dell'immagine.", la: 'Formas verbi picturae dic.' },
  'vok:muster': { en: 'Sort the verbs by their pattern.', fr: 'Trie les verbes selon leur modèle.', es: 'Ordena los verbos según su patrón.', it: 'Ordina i verbi secondo il loro modello.', la: 'Verba secundum exemplum ordina.' },
  'gram:fehlerjagd': { en: 'Tap the wrong word and correct it.', fr: 'Touche le mot faux et corrige-le.', es: 'Toca la palabra incorrecta y corrígela.', it: 'Tocca la parola sbagliata e correggila.', la: 'Verbum falsum tange et corrige.' },
  'gram:satzbaupuzzle': { en: 'Put the words in the right order.', fr: 'Mets les mots dans le bon ordre.', es: 'Pon las palabras en el orden correcto.', it: "Metti le parole nell'ordine giusto.", la: 'Verba recto ordine pone.' },
  'gram:formenblitz': { en: '60 seconds – choose the right form.', fr: '60 secondes – choisis la bonne forme.', es: '60 segundos – elige la forma correcta.', it: '60 secondi – scegli la forma giusta.', la: 'Sexaginta secunda – formam rectam elige.' },
  'gram:regelzuordnen': { en: 'Find the rule that goes with the example sentence.', fr: "Trouve la règle qui va avec la phrase d'exemple.", es: 'Encuentra la regla de la frase de ejemplo.', it: "Trova la regola della frase d'esempio.", la: 'Regulam exemplo convenientem inveni.' },
  'gram:verbtrio': { en: 'Find all the forms of a verb together.', fr: "Trouve ensemble toutes les formes d'un verbe.", es: 'Encuentra juntas todas las formas de un verbo.', it: 'Trova insieme tutte le forme di un verbo.', la: 'Omnes formas verbi una inveni.' },
  'gram:verbblitz': { en: '60 seconds: which form did you hear?', fr: '60 secondes : quelle forme as-tu entendue ?', es: '60 segundos: ¿qué forma has oído?', it: '60 secondi: quale forma hai sentito?', la: 'Sexaginta secunda: quam formam audivisti?' },
  'gram:bildverb': { en: 'Give the forms of the verb for the picture.', fr: "Donne les formes du verbe pour l'image.", es: 'Di las formas del verbo de la imagen.', it: "Scrivi le forme del verbo dell'immagine.", la: 'Formas verbi picturae dic.' },
  'gram:muster': { en: 'Sort the verbs by their pattern.', fr: 'Trie les verbes selon leur modèle.', es: 'Ordena los verbos según su patrón.', it: 'Ordina i verbi secondo il loro modello.', la: 'Verba secundum exemplum ordina.' },
  'gram:richtigfalsch': { en: '60 seconds: is the sentence correct?', fr: '60 secondes : la phrase est-elle correcte ?', es: '60 segundos: ¿la frase es correcta?', it: '60 secondi: la frase è corretta?', la: 'Sexaginta secunda: rectane est sententia?' },
  'gram:formenmemory': { en: 'Find the base form and the new form as a pair.', fr: 'Trouve la forme de base et la forme nouvelle en paire.', es: 'Encuentra la forma base y la forma nueva como pareja.', it: 'Trova la forma base e la forma nuova come coppia.', la: 'Formam primam et formam novam ut par inveni.' },
  'gram:tabellenpuzzle': { en: 'Put the forms into the right boxes of the table.', fr: 'Mets les formes dans les bonnes cases du tableau.', es: 'Pon las formas en las casillas correctas de la tabla.', it: 'Metti le forme nelle caselle giuste della tabella.', la: 'Formas in campos rectos tabulae pone.' },
  'gram:signalwort': { en: 'Which tense does the signal word show?', fr: 'Quel temps le mot indicateur montre-t-il ?', es: '¿Qué tiempo verbal indica la palabra señal?', it: 'Quale tempo indica la parola segnale?', la: 'Quod tempus verbum signi ostendit?' }
}
